### ISSUE TITLE
Lerna packages installed as private git urls

### ISSUE THREAD

**Issue by jamiehill** [lerna/lerna#1003]
Forgive me for filling a bug for this, but I can find no information on the subject elsewhere.

We've migrated to a Lerna Monorepo, but I fail to understand how this might support installing lerna packages as private git repos.

my-mono-repo
```
root
- packages
  - @scope/package-a
  - @scope/package-b
```
some-other-project
```
"devDependencies": {
    "@scope/package-a": "git+ssh://git@gitrepo.com/my-mono-repo.git#v0.0.0",
}
```

Scoped modules possibly confuses the issue, but how do I get access to a package, that has not been published to `npm` using this syntax?

**Comment by evocateur** [comment]
Git dependencies are one of the most complicated and error-prone features in all of npm, in my experience. Lerna isn't really meant to be consumed this way, it's meant to publish packages (but not always _public_ packages).

If you're using lerna to develop packages, you can always publish them to an internal private registry, or as private (scoped) packages on the public registry. I would really recommend avoiding git dependencies altogether.

**Comment by ramasilveyra** [comment]
I'm facing the same issue, on my end we use [gitpkg](https://github.com/ramasilveyra/gitpkg) to publish the packages from the monorepo. But I didn't create the issue because I though that was a very strange use case.

@evocateur I saw your opinions about git deps on other issues, would you consider merging a pr fixing this issue? I started some time ago a fix for this (unfinished) https://github.com/lerna/lerna/compare/master...ramasilveyra:git-deps?expand=1 If this could cause more problems enabled by default, at least we can try to enable the `git deps semver resolving` with a flag like `--resolve-git-deps-semver`?

**Comment by evocateur** [comment]
@ramasilveyra Perhaps as a Lerna plugin (API tbd, but it would be dependent on #174 at the very least), but I don't see that ever getting into core. Lerna facilitates the operation of npm/yarn over many packages in a single repository that are published to a registry in a coordinated fashion. It does not support consumption by non-package means (i.e., a git url).

**Comment by ramasilveyra** [comment]
Hey @jamiehill it seems that our use case got covered on https://github.com/lerna/lerna/pull/1033 🎉
