### ISSUE TITLE
bootstrap --since links not-included modules

### ISSUE THREAD

**Issue by viliusl** [lerna/lerna#1005]
Given a project:
```
.
 ├── a
 ├── b (depends on a)
 └── c (depends on b)
```

then I have a branch where only `b` has changes and I run `lerna bootstrap --since master`, then it bootstraps `b, c` - which is correct, but for `b` links-in it's dependency `a` which was not bootstrap. I run tests and they obviously fail because `a` does not have it's dependencies bootstrapped.

## Expected Behavior
 - for given scenario dependency `a` for module `b` should be npm installed and not linked-in.
 - if I want dependency `a` for module `b` to be linked/bootstraped, then I can do it with '--include-filtered-dependencies'

## Current Behavior
described in scenario

## Possible Solution
 - I would say it's a bug and it should be fixed, as current behavior does not yield correct repo state.

## Context
I want to build/test only changed sub-tree of my modules in PullRequest ci where subtree starts from modules with actual changes and goes into their dependees (as they can be impacted by change).

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.1.2 |
| `npm --version`  | 3.10.10 |
| `node --version` | 6.11.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

**Comment by viliusl** [comment]
@evocateur would like your input on this one. Thanks

**Comment by evocateur** [comment]
The bootstrap algorithm is so complicated, I really don't see adding more conditional complexity across the entire command as worthwhile. There _are_ certainly many opportunities for improving the bootstrap command, generally speaking. I don't think the changes you're requesting are one of them.

Lerna's current "contract" is that it always symlinks local dependencies, runs their lifecycle scripts, and streamlines the flow of concurrent, inter-related package development. Leaving aside the gigantic refactoring necessary to accomplish what you desire, I would consider it a fundamentally breaking change as well.

Making `lerna bootstrap --since` implicitly enable `--include-filtered-dependencies`, in my opinion, does a better job of fulfilling that contract. It is far easier to implement, document, and maintain in the long run.

**Comment by viliusl** [comment]
Well `--include-filtered-dependencies` changes the behaviour (includes untouched modules) and `--since` without it does not yield valid result.

It would be a breaking change though, so if you don't agree on changing it I will not attempt that. Though it's painful for me as I do work on a project with ~ 90 modules and if I touch one, I can get a PR build with say 5 modules to build/test, but if I will add `--include-filtered-dependencies` then it will be 75 instead:/
