### ISSUE TITLE
root changelog for fixed-mode --conventional-commits

### ISSUE THREAD

**Issue by rsouthgate** [lerna/lerna#1015]
Our monorepo is typically distributed as a whole, though each package can live separately. We operate lerna in fixed mode and the recent changes in 2.1.0 that fix #922 are great. One thing that would help us though is the ability to combine the changelog messaging into a root changelog in addition to the package changelogs currently generated in that mode.

**Comment by ZauberNerd** [comment]
I dug into this and there are a couple of complications:

* The main problem is that [conventional-changelog-core](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-core) needs to know the `version` that is being / has been published.
* It does so by reading the `package.json` file in the current working directory (and if not found, searching upwards for a `package.json` file - see [conventional-changelog-core/merge-config](https://github.com/conventional-changelog/conventional-changelog/blob/431598a3b12a404aee63f8ab3e51263121cde485/packages/conventional-changelog-core/lib/merge-config.js#L97) and [conventional-changelog-cli/cli](https://github.com/conventional-changelog/conventional-changelog/blob/1fc561217d79978b9d0248612b75e87c4b4a2d0b/packages/conventional-changelog-cli/cli.js#L90)).
* The [conventional-changelog-cli](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli) can be configured to the location of the `package.json` with the `--pkg` options (which is [done by lerna](https://github.com/lerna/lerna/blob/d721b2a7579b702477e00c551eb684f25dd06305/src/ConventionalCommitUtilities.js#L66)).

Right now I can see two ways to make this work:
1. Let lerna update the `version` field in the root `package.json` file if it is configured to run in `fixed-mode`.
2. [Overwrite the `version`](https://github.com/conventional-changelog/conventional-changelog/blob/431598a3b12a404aee63f8ab3e51263121cde485/packages/conventional-changelog-core/lib/merge-config.js#L158) through a [context](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-core#context) that can be passed to the [conventional-changelog-cli as `--context`](https://github.com/conventional-changelog/conventional-changelog/blob/1fc561217d79978b9d0248612b75e87c4b4a2d0b/packages/conventional-changelog-cli/cli.js#L110)

If choosing option 2 there are two ways to make this work:
* 2.a. use [conventional-changelog-core](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-core) directly instead of [conventional-changelog-cli](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli) - That means that we would have to implement parts of the code from [this file (conventional-changelog-cli/cli.js)](https://github.com/conventional-changelog/conventional-changelog/blob/1fc561217d79978b9d0248612b75e87c4b4a2d0b/packages/conventional-changelog-cli/cli.js).
* 2.b. Add a default conventional-changelog context file to lerna with content similar to: `module.exports = { version: repository.version };`

The actual changes in lerna are quite simple:
* in `src/commands/PublishCommand.js` move the `ConventionalCommitUtilities.updateFixedChangelog()` invocation out of the the `forEach` loop.
* In `src/ConventionalCommitUtilities.js` change the arguments for the changelog cli in `updateFixedChangelog` to remove `--pkg`, `--commit-path` and add `--context`.

I think 2-2.b. (overwrite `version` through custom context inside lerna) would be the best way to go, because option 1 would change the behaviour of lerna quite a lot and option 2.a. would duplicate some code from the `conventional-changelog-cli` - but would in my opinion also be a viable alternative.

I could create a PR for any of these changes, but would like some feedback on the proposed solution / other options first.

What are your thoughts on this @rsouthgate & @evocateur ?

**Comment by rsouthgate** [comment]
I'm no expert, but it would seem sensible to remain with the cli conventional changelog tool since it's actively maintained. That would lead to 2-2-b being the only sensible option, and as far as I understand - a good one for my use case.

**Comment by ZauberNerd** [comment]
Another question: When in fixed mode - do we want to have just one single changelog.md in the root or do we want to have a changelog.md for each package **and** a root changelog.md?

**Comment by rsouthgate** [comment]
Seems like it could be configurable. For my use case i’d only want the root changelog. And duplicating the same changes in each package would just create more noise, but I can imagine other use cases where packages are bundled and also published individually where both would be required.

**Comment by ZauberNerd** [comment]
@rsouthgate I created this PR: #1078 and I decided to keep the behaviour the same as before and generate one changelog per package and one consolidated changelog in the root.
I didn't want to complicate the surface of lerna by introducing more options to configure and in your case you could simply put the package changelogs in your `.gitignore` file.
