### ISSUE TITLE
Recursive local packages don't install correctly

### ISSUE THREAD

**Issue by ds82** [lerna/lerna#1016]
Let's assume 3 packages: ``a``, ``b`` & ``c``. Say ``a`` depends on ``b``, ``b`` depends on ``c``.
When bootstraping this layout with lerna und using local (``"file:./../b"``) dependencies, lerna does not install all deps correctly.

## Expected Behavior
lerna should link dependency ``b`` in ``a`` and dependency ``c`` in ``b``.

## Current Behavior
lerna just links ``c`` in ``b`` and skips the installation of ``b`` in ``a``.
This happens with ``npm@5`` and ``yarn@1`` (yarn cannot even bootstrap this layout at all and fails with a ``version not found`` error, but the result is similar)

## Steps to Reproduce
I made a repo to reproduce the bug.
See https://github.com/ds82/lerna-test-recusrive-packages

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.1.2",
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.1.2 |
| `npm --version`  | 5.4.1 |
| `yarn --version` | 1.0.2 |
| `node --version` | 6.10.2 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by evocateur** [comment]
Thanks for the example repo! This is something I've had on my mind recently; lerna does not currently consider a relative file path to be a valid indicator of "sibling"-ness (that is, a package it also manages and should symlink).

This is something I would like to support, especially since npm5 should _theoretically_ support bootstrapping in this manner without heinous `package.json` mangling like we do today. We'll have to play it by ear, though.

**Comment by jiverson** [comment]
What does it consider then to be a valid indicator of "sibling"-ness then, I am confused? Because according to the docs it should link them.

**Comment by evocateur** [comment]
Incredibly enough, I just commented on another issue not five minutes ago that our docs in this area are in need of improvement.

At a high level, there are two "simple" tests that a given package dependency must pass to be considered a sibling:
1. It must match the `name` field of one of the `package.json` files collected from the `packages` glob[s] in `lerna.json`.
   * The directory name of a given package has no bearing on this calculation, only the `pkg.name` field.
2. The version range specified in the dependency must be satisfied (`semver.satisfy()`) by the `version` field in the local sibling's `package.json`.
   * In practice, this usually boils down to "same major version => is local package".

**Comment by jiverson** [comment]
I am working on a PR that implements a flag `ignore-semver` I am not sure that would be a feature contributors would be interested in. 

The specific case I am working on is, locally we have a monster symlink shell script, that links all our  packages for `dev` work. But in `prod` we want dependancies linked via github or npm. All our package.json files are set up for prod obviously. 

I started investigating moving to a mono repo setup, but this would take some time because our repos have thousands of commits and I am running across issues with bootstrap. I was able to get around that through using `git subtree`.

Now I am not completely sold I am not going down a rabbit hole, but it is a "lerna"ing experience either way.
