### ISSUE TITLE
Publishing single packages

### ISSUE THREAD

**Issue by morpheus-87** [lerna/lerna#1055]
Imagine the following scenario:

* I manage package A and package B with independent versions
* Both have changed since their latest release
* I want to publish package A, but not package B

When running `lerna publish`, both packages would be published. Is it somehow possible to run `lerna publish <name of package A>`?

**Comment by zxqfox** [comment]
Actually, you can run any npm script inside specific packages using scope param: `lerna publish --scope="name-of-package-A"`

**Comment by morpheus-87** [comment]
@Socia1Circus if I do it like that way, the whole git process with creating tags would not be done.

Thanks for this information, @zxqfox, I haven't seen this flag in the docs. I will try it out the next time.

**Comment by evocateur** [comment]
Actually, you can't scope `lerna publish`. It's all or nothing, due to the manner in which git tags are used to detect changes since the last release (which is tagged).

There's not really a way around this, given how lerna works. Sorry.

**Comment by ivosabev** [comment]
Any plans on adding this feature in the future?

**Comment by evocateur** [comment]
As I noted above, this is impossible due to the manner in which lerna coordinates versions with git tags (and the diff since the last one is what indicates which packages should be published).

If they are both independent, and you don’t want to publish them at the same time, then don’t use lerna, it’s clearly not necessary for your use case.
