### ISSUE TITLE
lerna to publish packages with their current version

### ISSUE THREAD

**Issue by RinatMullayanov** [lerna/lerna#1056]
How do I tell `lerna` to publish packages with **their current version**?
Now `lerna` is always trying to increase the version of packages ...

I need this because I want to divide the publication process into 2 stages:
1. First I want to manually raise the package version only in git in dialog mode:
`lerna publish --skip-npm`
2. Only then with the help of CI I want to publish in npm:
`lerna publish --skip-git`

I do not need to raise the version twice.

## My Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.2.0|
| `npm --version`  | 5.4.2|
| `node --version` | v6.11.2|

| OS | Version |
| --- | --- |
| Windows 10 Pro | 1703 |

**Comment by yairkukielka** [comment]
I want lerna to use the package.json version number to publish without having to bump it since it was already bumped manually by the developer.

In my case, CI doesn't know if it's a breaking change or not, so I expect the developer to do this. When the branch is merged to master, that's when I expect lerna to just use the version in package.json to publish without new commits.

**Comment by evocateur** [comment]
If your CI has ways of indicating when a tag has been created, `lerna exec -- npm publish` (after bootstrap) would accomplish this. Instead of making `lerna publish` more complicated, I'd rather focus on making `--conventional-commits` more useful/robust for the automated publishing in CI use-case.

**Comment by KingScooty** [comment]
`lerna exec -- npm publish` wouldn't work when one or more of the packages are private. `lerna publish` respects private packages, however `npm publish` does not and results in an exit 1 error.

Ideally, CI would run a `lerna publish` with some args that would just push to an npm registry _without_ altering version numbers or affecting change logs. 

I've scoured the issues section of Lerna, but have really struggled to find a proper answer for cleanly setting up Lerna with a monorepo in CI.

Because Lerna insists on bumping the package.json regardless of what args are passed, it results in a messy CI integration. If you push changes back to git (package.json, changelogs etc), it then triggers a subsequent build. 

Ideally Lerna would have a `--ci` mode or something that just disabled altering any files within the git repo. So it would just push to npm, and push tags back to git?

Anything more triggers further unnecessary builds. The developer can run the changelog part of lerna `lerna publish --skip-npm --skip-git` before pushing to github.

Thoughts?

**Comment by azu** [comment]
> lerna exec -- npm publish wouldn't work when one or more of the packages are private. lerna publish respects private packages

I've created [can-npm-publish](https://github.com/azu/can-npm-publish "can-npm-publish") CLI.
It will help `lerna exec npm publish` pattern.

```
lerna exec --bail=fase can-npm-publish && npm publish
```

**Comment by unregistered** [comment]
@evocateur Is there interest in a PR for this? Conventional commits seems kind of awkward when using lerna in Independent mode.

**Comment by evocateur** [comment]
@unregistered I was thinking of implementing a `from-git` value of the `--cd-version` option, similar to [`npm version`](https://docs.npmjs.com/cli/version)'s positional value of the same name. It would throw if the current commit wasn't tagged, of course. Pull out the paths to publish from `git show HEAD --name-only --pretty=format:%D -- packages/*/package.json` (adding appropriate package location globs as necessary), and jumping straight to the publish loop.

```
lerna publish --cd-version from-git
```

btw, `--no-private` was added in [v3.0.0-beta.1](https://github.com/lerna/lerna/releases/tag/v3.0.0-beta.1), so now `lerna exec -- npm publish` could skip packages with `"private": true` set in their package.json.

**Comment by unregistered** [comment]
@evocateur can you clarify what the tag should be for an independently versioned repo? Wouldn't it have to contain the name of the package that's being published?

I think that feature you mentioned might work, just trying to wrap my head around it.

To clarify we publish on every commit we squash to master, but when a commit changes only one package it's wasteful to publish the other 80 packages (and dishonest too, since the patch-level gets bumped but there are no changes).

**Comment by evocateur** [comment]
You would also need to pass `--yes` to the command in CI, of course, otherwise it would break due to hanging prompt. Here's some sketches of output and expected response:

```sh
# independent mode with valid tags
$ git show HEAD --name-only --pretty=format:%D -- packages/*/package.json
tag: @scope/package-1@2.9.1, tag: package-2@1.1.0
packages/package-1/package.json
packages/package-2/package.json
```
In independent mode, the tags themselves are valid arguments to `npm-package-arg`, and we can map the names back to our internal Package objects. Pretty straightforward.

```sh
# fixed mode with valid tag
$ git show HEAD --name-only --pretty=format:%D -- packages/*/package.json
tag: v1.8.0
packages/package-1/package.json
packages/package-2/package.json
```
Fixed mode is a bit more wrinkly, requiring reverse lookups by `pkg.manifestLocation` of the list of modified package.json files. Not too terribly difficult, really (except maybe windows because windows sucks).

```sh
# no tags found, return no-op with appropriate logging
$ git show HEAD --name-only --pretty=format:%D -- packages/*/package.json
# empty string
```
I figure throwing is not what we want, it should just behave the same as the "no changes found" case, which is just to exit.

**Comment by evocateur** [comment]
To be clear, this would also pretty much require #961, using `lerna version` instead of the wonky-looking `lerna publish --skip-npm`.

If it's desired to be _completely_ automated, you'll need to use `--conventional-commits`. What exactly is "awkward" about that option in a CI context? The changelog generation?

**Comment by unregistered** [comment]
@evocateur It's a bit of a pain to get the auto-generated commit sent back to the master branch, since we have branch protection on, commits only enter master through PRs. Not sure what the recommended pattern for that is, I may just be doing something unusual.

**Comment by evocateur** [comment]
Sounds like you want `semantic-release`, but with monorepo-awareness. Unfortunately, there isn't great support for that scenario right now. It's something I would definitely like to get to, though.

**Comment by penx** [comment]
> `lerna exec -- npm publish`

If some packages have been updated but others haven't, this will fail as `npm publish` will be run on all packages, even those that haven't changed, and throw an error:

```
You cannot publish over the previously published versions
```

**Comment by morgs32** [comment]
@penx what about the package from @azu.
Could that help you?
https://github.com/lerna/lerna/issues/1056#issuecomment-360095023
