### ISSUE TITLE
feature: no hoisting, no symlinking bootstrap

### ISSUE THREAD

**Issue by cdaringe** [lerna/lerna#1061]
## Expected Behavior

- for all package deps to be local to the package, postbootstrap, _conditionally_

## Current Behavior

- symlinks get created on bootstrap

## Possible Solution

- `lerna bootstap --ci` or something to install all deps local to each package, such that each package is isolated and can function on its own.  this package production shipable/tarball-able/etc

for instance, i want to build containers for some `packages/<x,y,z>`. however, symlinks and hoisting prevent this.

some may say "just npm install in the container".  this works for all but my private packages i'm linking in my project.  i _could_ `COPY` those other packages at build time from their respective packages dir, but they also may have links, and suddenly the build gets wonky.

thoughts?

**Comment by evocateur** [comment]
If you're publishing the packages that you want to consume in the containers, I would think `rm -rf node_modules && npm install` in the container root directories would be sufficient.

At a higher level, `lerna` is expressly designed to be a development tool for maintaining several packages in the same repo. It's not meant to be a build tool in the sense you've described, and will likely never support direct application bundling and whatnot. It's just too far afield of "arranging repository filesystems to resemble node-resolved installations of npm packages, and then sometimes maybe running `npm publish`".

I generate a variety of webpack bundles daily from a handful of lerna-based repos that manage a few dozen packages each without any avoidance of hoisting and symlinks. It all boils down to the bundling configuration, which is way outside the scope of a tool like `lerna`.

**Comment by evocateur** [comment]
If you're never publishing packages to a registry (public or private), I
don't recommend using lerna. There is no shame in relative path imports.

I would definitely separate the bundling and packaging of the "shippable"
artifact and the relationship of the code. I don't see any reason to use
lerna in your case.

**Comment by cdaringe** [comment]
> There is no shame in relative path imports.

sure. agreed.

> I don't see any reason to use lerna in your case.

i could `link` all of the things manually (youch--i have ~10 pkgs), but dep reduction (hoisting+workspaces) & auto linking are still very much value add.  it a definite "why not?" situation at development time.

> I would definitely separate the bundling 

just to be clear, i'm not talking about bundling.  you've mentioned it twice now, but i'm not sure why.  perhaps we have different interpretations on what "bundling" means?  when in hear it, i assume it implies something like rollup/webpack with target ~= node.  is that your intent w/ it too?

**Comment by evocateur** [comment]
> for instance, i want to build containers for some packages/<x,y,z>

> this package production shipable/tarball-able/etc

Those are both descriptions of bundling, whether that means running webpack/rollup first or not, it ultimately ends up in a tarball for deployment.

You don’t need more than one package.json (in the root) to gain the benefit of “hoisting” for an entire tree. It’s easy to prune dev dependencies before packing into the container if you’re worried about download size.

You don’t need to link packages you never publish, just require modules with relative paths. Like literally everybody did before lerna was a thing.

**Comment by trxcllnt** [comment]
@cdaringe we have a similar setup at Graphistry, a mono-repo with private/proprietary library and application modules. We're migrating off publishing them to npm so we don't have to do silly things like inject npm creds into our dockerfile-build containers.

We've come up with a strategy of copying only the relevant private modules into our docker containers conditionally, then executing `lerna bootstrap` (or using yarn workspaces) inside the container.

For example, to make containers for each `app-1` and `app-2` (`package.json` summary printed next to each path):
```
mono-repo/packages/lib-a  - { "name": "lib-a" }
mono-repo/packages/lib-b  - { "name": "lib-b", "dependencies": [ "lib-a" ] }
mono-repo/packages/app-1  - { "name": "app-1", "dependencies": [ "lib-a" ] }
mono-repo/packages/app-2  - { "name": "app-2", "dependencies": [ "lib-b" ] }
```

We can run this command to get the paths to the module we want to make a container for, and also all its private dependencies:
 ```sh
$ lerna exec --loglevel=error --scope app-1 --include-filtered-dependencies -- echo \${PWD##*/mono-repo/}
> packages/lib-a
> packages/app-1

$ lerna exec --loglevel=error --scope app-2 --include-filtered-dependencies -- echo \${PWD##*/mono-repo/}
> packages/lib-a
> packages/lib-b
> packages/app-2
```

Notes:
- `--scope` is the module name in `package.json` whose private deps we want to list
- `--loglevel=error` is critical, otherwise lerna prints other stuff that's not your module paths
- the `${PWD##*/mono-repo/}` ensures we echo the path to the module under `mono-repo/`, not the absolute path. This is also handy if you have modules in sub-folders, like `packages/legacy/an-old-module`).

Then inside the dockerfile-build we synthesize the mono-repo structure, but only `COPY` in the paths of the relevant dependencies:

```sh
# in reality we also execute this command in its own lerna container, but this is shorter
packages=$(lerna exec --loglevel=error --scope app-1 --include-filtered-dependencies -- echo \${PWD##*/mono-repo/})

docker build \
     -f Dockerfile-build \
    --build-arg PACKAGES=${packages}
    -t graphistry/app-1:dev .
```

```dockerfile
# the Dockerfile-build
FROM node:alpine
WORKDIR /app
ARG PACKAGES
# get lerna in here and populate (or copy in) lerna.json
RUN npm i lerna && echo '{"packages": ["packages/**/*"]}' >> ./lerna.json
# copy in relevant package source dirs
# don't forget to add packages/**/node_modules to your .dockerignore
COPY ${PACKAGES} packages/
# aka `lerna go wild`
RUN  npx lerna bootstrap
# etc
```

This is from memory, apologies if I messed up the syntax for the `COPY` command. Hope this helps, @ me if you have any questions.

**Comment by cdaringe** [comment]
@trxcllnt, that's a nice play.  i ended up doing a similar, but much simpler/less-robust strategy that meets the same intent.

i see maybe a package coming out of this exercise.  `lerna-delink`/`lerna-debootstrap`/`lerna-isolate`/etc.

thx @evocateur @trxcllnt.

**Comment by tombburnell** [comment]
I've also hit this issue - we have a project that was migrated to lerna to ease local development but is now making deployment much harder. It contains a number of applications and dependant modules. The apps need to be built from their respective directories and are end up with a set of stale symlinks rather than the actual files of dependent modules.

I tried using the following to copy the actual dirs over the symlinks, but it causes problems with npm prune --production. In fact npm prune --production actually just deleted the symlinks which seems a bit strange.

find . -type l -depth 1 -exec bash -c 'echo "copying {}"; cp -RL $(readlink {}) __tmp && rm {} && mv __tmp {}' \;

**Comment by evocateur** [comment]
Lerna is not a deployment tool.

**Comment by trxcllnt** [comment]
@tombburnell we've since switched to using yarn inside our build containers. Paired with docker's new ONBUILD directives and multi-stage builds, we can define a base container with a yarn global cache of all the dependencies, then only copy in the packages of the mono-repo that are relevant to the package the container is intended to run.

**Comment by evocateur** [comment]
@ajhool Have fun forking.

> Serverless monorepo projects will far outnumber the number of projects that need to publish a group of npm modules **(I think)**

LOL, sorry for giving away stuff for free that isn't EXACTLY what you demand?!? Get a grip, dude.

**Comment by ajhool** [comment]
This is an issues tool that Github provides for people to post issues, which I tried to do.

I didn't mean for the explanation to be rude or demanding, nor do I think that it was. Just an attempt to explain where people are coming from when they are confused about how to deploy serverless code in a hoisted monorepo. I'm also happy to provide a PR with an update for the README

**Comment by evocateur** [comment]
Intent is irrelevant, impact is what matters.

People doing "serverless" stuff shouldn't use Lerna. I don't know how to explain that multiple npm packages in the same repository is different than a single package in a repository, and maybe you shouldn't assume everything will be the same?

I've made myself clear, I hope.
