### ISSUE TITLE
Proposal: Document and expose official Node.js API

### ISSUE THREAD

**Issue by marionebl** [lerna/lerna#1071]
## Expected Behavior
As a developer, I want ...
* ... to build specialized project tooling on top of lerna repos
* ... to use an API exposed by Lerna for dealing with lerna specific things to avoid additional effort
* ... to benefit from semantic versioning to keep my API usage safe

## Current Behaviour
* There is no official Node.js API
* Building on the undocumented, internal API is hazardous
* Breaking changes can happen with every update. E.g. removal of `.packages` from `Repository` with `2.4`

## Possible Solution
* Expose a carefully selected official API
* Add tests for said API surface
* Publish documentation for Node.js API

## Context
* There is potential for the eco system in officially enabling other tooling use cases, e.g.: [@commitlin/config-lerna-scopes](https://github.com/marionebl/commitlint/blob/master/%40commitlint/config-lerna-scopes/index.js#L18)
* The current solution is prone to break with internal changes of `Repository` and/or `PackageUtilities`
* Potentially useful API surface (derived from my use cases, incomplete)
   * Repository.constructor
   * Repository.packageConfigs
   * Repository.packageGraph
   * PackageUtilities.getPackages
   * PackageUtilities.addDependencies
   * RunCommand

**Comment by evocateur** [comment]
This is related to #174, where I'd ultimately like to expose these sorts of things, as modularly as possible. So it's kind of a big refactor, which I've been delaying due to time constraints and the potential for causing conflicts in every open PR.

I recently worked through (or closed) almost all open PRs, so that's not such a big concern now. Just gotta find the time.

**Comment by marionebl** [comment]
Closing this as duplicate of #174
