### ISSUE TITLE
Parallel package development

### ISSUE THREAD

**Issue by Gurkenschreck** [lerna/lerna#1084]
Hello there,

I have questions regarding the simultaneous development of two packages. Let's assume we have package `a` and `b`, where `b` is a dependency of `a`. Inside `a` I am installing `b` using `npm i --save ../b`, which creates a new dependency. When changing code in `b`, `a` does not automatically get note of it because `b` is already put in the node_modules folder of `a`. 

My question here is how would I go about reimporting the dependency `b` after I did a small change in there? Is there a command for that or do I have to `lerna clean && lerna bootrstrap` every time I did some change in `b`?
This is pretty slow. What is the fastest way to develop multiple packages in parallel? 

It may be a naive question or there may be an obvious answer which I am not aware of. This somewhat has to do with #1073. But I am not asking for some kind of file-watcher specifically.

Thank you for your time! Regards

**Comment by alampros** [comment]
I had the same difficulty understanding this process. In short, instead of linking the dependencies with `npm i -S ../my-module-b`, you will need to do two things:
1. Make sure each of your modules has a valid version in their `package.json` (even if it's `0.0.1`)
2. Manually add `my-module-b` to module `my-module-a`'s `package.json/dependencies`:
```json
{
  "name": "my-module-a",
  "version": "0.0.1",
  "dependencies": {
     "my-module-b": "^0.0.1"
  }
}
```

Then, when you run `lerna bootstrap`, lerna will see the dependency and symlink `my-module-b` into `my-module-a/node_modules` (similar to using `npm link`).

My biggest problem with this is that it is super cumbersome to work with until your modules to npm. If you try to run `yarn` or `yarn add` in a package that requires an unpublished sibling package, yarn craps its pants because it can't find it.

Did that help at all?

**Comment by evocateur** [comment]
@Gurkenschreck @alampros's explanation is accurate.

I'll also chime in that unless you're using yarn workspaces, one doesn't tend to run yarn/npm commands in the package directories directly, but from the root (`npm test`, various lerna commands, etc). This means most dependency manipulation is done by hand. There is at least one PR open right now (i need more hours in the day) to make this situation less manual, and suggestions/PRs for improvement are always welcome.

**Comment by Gurkenschreck** [comment]
@alampros @evocateur thank you both for your responses! This is it, it finally works like charm. Nice explanation. I also found that I cannot install a local dependency which is set to private in the `package.json`.

How would I have learned it, if i did not ask the question here? Is there some documentation on this I have overread? (Maybe this is something that needs to be better documented?)

**Comment by Gurkenschreck** [comment]
I would like to close this. Are my questions about to be left unanswered?

**Comment by evocateur** [comment]
We have an “add” subcommand now, as of 2.5.0, which should streamline this situation. Our documentation no doubt needs clarification, and perhaps example projects are in order. Any contribution on either topic would be very welcome.

**Comment by Gurkenschreck** [comment]
Thanks for your answer. I'll see if I can help with that.
