### ISSUE TITLE
lerna init is not initialising a new project

### ISSUE THREAD

**Issue by shawnthye** [lerna/lerna#1097]
`lerna init` on a new folder should generate `package.json`/`lerna.json`/`packages` ?

```
$ mkdir lerna-repo && cd lerna-repo
$ lerna init
lerna info version 2.4.0
lerna info Updating package.json
lerna info Updating lerna.json
lerna info Creating packages directory
lerna success Initialized Lerna files
```

## Expected Behavior
```
lerna-repo/
  packages/
  package.json
  lerna.json
```

## Current Behavior
```
lerna-repo/
```
`lerna-repo` folder is still empty

---------------------------------------------------------------------------

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.4.0 |
| `npm --version`  | 5.5.1 |
| `node --version` | 8.9.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.6 |

**Comment by shawnthye** [comment]
Ok, I found the problem, if I have a `lerna.json`/`package.json`/`packages` in the `$username` root directory, it will forever updating the `$username` directory, is it the expected Behavior??

**Comment by evocateur** [comment]
Oh, yeah, apparently if you have a `lerna.json` in your `$HOME` directory, this situation will arise.
https://github.com/lerna/lerna/blob/d9e0ec58e2b4f57a57439e1540b7834076d9d226/src/Repository.js#L18

I think we need to make `lerna init` force the evaluation somehow to limit the lerna.json search to "the directory I am currently in" instead of recursive.

**Comment by LeoAJ** [comment]
@evocateur I tested if I made code like this it will work

```js
const lernaJsonLocation = (
      // path.resolve(".", ...) starts from process.cwd()
      path.resolve((cwd || "."), "lerna.json")
);
```

just remove this line

```js
findUp.sync("lerna.json", { cwd })
```

and `find-up` dependency.

But I wonder what is the initial intention to do like that at first place, since this is the only place to use `find-up` module in the entire project.

if this solution looks fine, I am ready to submit PR to fix this anytime, thanks.

**Comment by evocateur** [comment]
No, find-up (or something like it) is necessary, we just need to find a way to limit how much it recurses.

**Comment by marionebl** [comment]
could we limit the search from `cwd` to git root? cosmiconfig has the stopDir config for this: https://github.com/davidtheclark/cosmiconfig/blob/master/README.md#stopdir

**Comment by evocateur** [comment]
Yeah, I was looking into cosmiconfig just yesterday, that sounds ideal.

Cosmic might even be useful for the overall “durable” configuration defaulting via `yargs.config()`. Still noodling about that, though.

**Comment by ken-harris** [comment]
Was there a resolution for this issue? I'd love to try to convert my private repo to a monorepo but I can't initialize a project right now using this tool.
