### ISSUE TITLE
No info on typo in command

### ISSUE THREAD

**Issue by hon2a** [lerna/lerna#1098]
_Some context: I've just upgraded NodeJS, Npm, and Lerna, so I was expecting all sorts of trouble._

I've just spent the last 20 minutes the silliest way. I tried to do a clean `lerna bootstrap --scope package-name` in my repo and when I ran the command, nothing happened. (Nothing whatsoever, it just immediately returned.) After looking at various things and some googling, I discovered that I just made a typo in the command and wrote `lerna boostrap --scope package-name`.

## Expected Behavior

I'd be nice to be told that no valid command was passed to `lerna` when that happens.

## Current Behavior

Immediate return with no output.

## Possible Solution

It'd be helpful for `lerna` to emit some sort of basic command list (like other apps) when no valid command is passed to it.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.4.0 |
| `npm --version`  | 5.5.1 |
| `yarn --version` | N/A |
| `node --version` | v8.9.0 |

| OS | Version |
| --- | --- |
| Windows 7 | SP1 |

**Comment by evocateur** [comment]
Indeed, we tried to enable the [`strict`](https://github.com/yargs/yargs/blob/master/docs/api.md#strictenabledtrue) yargs config, which would throw errors in this situation, but we ran into other problems when that was enabled (mostly due to how we allow unrecognized parameters to pass through to the wrapped command for `lerna exec` and `lerna run`).

I appreciate the well-written issue, and support any PR to improve this experience. A "did you mean?" error output would be super cool, but even a "default" command that indicates you done goofed and outputs the existing help would be an improvement.
