### ISSUE TITLE
Independently versioned + fixed release/publish

### ISSUE THREAD

**Issue by hzoo** [lerna/lerna#1121]
This might only be a use-case for Babel, but I suppose this could be the case for any project that has "experimental/unstable" packages. (blocker for v7 release)

Any TC39 syntax proposal is subject to change until it reaches Stage 4, and the way these implemented in Babel is with separate npm packages.

Currently Babel still uses the "fixed" versioning mode described in the lerna readme, but we'd need to move to "independent" mode in order to make a major bump in 1 package without it affecting the others. Although I don't think we intend to make the other packages independently versioned but only specific ones. (For Babel 7 this would be `@babel/proposal-x` and `@babel/preset-stage-x`, and I guess `@babel/preset-env` since it may include Stage 3 plugins that are included in the browser)

## Goals
- Make it possible to publish all packages at once + that experimental packages can have a major version bump while the others update in the same way as before
- Don't create unnecessary multiple git tags (this could be considered a separate issue for independent mode, or just use the no tags option)

Thoughts:

- no: Don't use 1 monorepo and have a separate repo for "experimental proposals".
  - Means there is a separate publish process and everything works.
  - However it means we have to transfer the repo into the main repo later, have to setup a separate build process, issues/prs, and separate CI/REPL build so don't really want to do this.
- no: Allow lerna to specify certain folders/globs that are independently versioned while in fixed mode (we made an `experimental` folder for this)
  - Thought this would be good at first but now I wonder why even make another folder, it should be able to work in `packages` fine because we have to deal with changing the config for all the git/npm/babel/eslint configs to handle a different folder and then later move the folder back into `packages`.
- Add a config to each package that will be independently versioned and prompt for it when publishing? `package.json`: `{ "lerna" : { "independent": true } }`
- Allow ignoring the experimental packages when publishing only, and then have a separate command for the independent publish (ideally that would work together as 1 command)
- Combine something from https://github.com/lerna/lerna/issues/389?
  - Also suggested in there, publish whatever the updated package.json is and skip git tag

So.. I think ideally `lerna publish` would just work then same, but prompt for the other versions after (or signal that via cli flag, or package.json config per repo, or config in lerna.json)

Other ideas, there are probably a lot of possibilities we could do?

**Comment by nicolo-ribaudo** [comment]
> no: Allow lerna to specify certain folders/globs that are independently versioned while in fixed mode (we made an experimental folder for this)

Wouldn't something like this work?

(Disclaimer: I have never looked at a `lerna.json` file)
```json
{ 
  "mode": "fixed",
  "overriddes": {
    "packages/babel-plugin-proposal-*": {
      "mode": "independent"
    }
  }
}
```

**Comment by evocateur** [comment]
I am partial to the `lerna` field in package.json (in managed packages as well as the root), as it would open up opportunities to customize other lerna behaviors on a fine-grained basis (using [cosmiconfig](https://github.com/davidtheclark/cosmiconfig#cosmiconfig) instead of a hand-rolled solution).

As for tagging, if you're in a mixed mode (fixed + independent), I'd say we stick to the fixed mode "single" vX.Y.Z tag pattern. Simplifies a lot, really.

**Comment by JamesHenry** [comment]
Hi Folks 👋

In light of its age, and in order to allow our small team to focus on what matters most to Lerna v6 users in late 2022, I'm going to close this one. If you have any requests that could enhance your usage of Lerna 6, then please do let us know by opening a new discussion (for a feature) or issue (for a bug report) with as much context as possible.

You can also check out our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

Many thanks 🙏
