### ISSUE TITLE
Ambiguous --ignore params in publish command vs other commands

### ISSUE THREAD

**Issue by donaldpipowitch** [lerna/lerna#1132]
Hi!

I'm quite new to Lerna so this is maybe a dumb question. I try to publish a package in independent mode and want to ignore some packages. (I want to ignore packages which are `private: true`. I thought they would be ignored anyway, but why isn't that the case?) So I used `--ignore` like it is used in other commands to ignore some packages based on the _package names_. But I now found out  that `--ignore` in `$ lerna publish` refers to files globs which are used to filter for non-relevant file diffs.

I know this would be a breaking change, but for the next major Lerna version I'd like to see:

1. Rename `commands.publish.ignore` to `commands.publish.ignoreFiles`.
2. Rename the old `$ lerna publish --ignore` to `$ lerna publish --ignore-files` _and_ introduce `$ lerna publish --ignore` with the same behavior as in other commands (ignore packages based on package names, so they are _never_ published).
3. Maybe I don't the use case behind it, but it would be nice to ignore `private: true` packages by default in `$ lerna publish`.

**Update**

I just noticed that while it doesn't seem to be documented `--scope` actually works as expected in `$ lerna publish`.

**Comment by evocateur** [comment]
`"private": true` actually does avoid publishing a given package, but it _does_ still version it, if there are changes. The logging is a bit confusing on this fact.

I agree with the `command.publish.ignore` -> `ignoreFiles` change, it was an unfortunate oversight.

`--scope` and `--ignore` were only ever applicable to a subset of commands, `(Only for 'run', 'exec', 'clean', 'ls', and 'bootstrap' commands)` as the help text attempts to clarify. They aren't _truly_ "global" options, and should be refactored into a shared yargs builder. The only intentional mechanism to ignore packages when publishing is `"private": true` in the package.json, and `--scope` application is a bug.

**Comment by donaldpipowitch** [comment]
> --scope application is a bug.

I don't know if I ever said this before, but... It is actually a feature for me currently 😅 I'd be happy if I could keep it. I want to opt-out from versioning private packages completely.

**Comment by ForbesLindesay** [comment]
Is there a way to skip versioning some packages? I was expecting `--ignore` to do this.

**Comment by evocateur** [comment]
> Is there a way to skip versioning some packages?

<strike>Remove the package from the monorepo.</strike>

Less flippantly: Why? Just to "workaround" #707? To express something about the quality of code in `<packageToIgnore>`?

Part of the problem (that keeps prompting questions in this vein, I suspect) is that lerna (and yarn) conflate _versioning_ with _publishing_. Unlike npm, which still has separate `npm version` and `npm publish` subcommands. I dunno. I feel like I keep answering the same questions over and over again.

So, currently, `lerna publish`:
- can be told to skip _all_ `npm publish` calls with `--skip-npm` (terrible option name)
- can be told to skip `git commit` & `git push` with `--skip-git` (terrible option name, again)
- will skip `npm publish` on a package with `"private": true` set in its package.json
- _should **not**_\* allow granular omission of version decisions because of how those changes are detected (since the last git tag, basically)

If you _were_ able to ignore _versioning_ (which implies "and publishing") a given package that _may_ have changes, how do you propose to recognize those changes later, when you _do_ want to publish it? Given the nature of git tags, in the default "fixed" versioning scheme, it's setting yourself up for a footgun.

There are tradeoffs to setting up a monorepo of npm packages. This is one of them.

\*: That you _can_ do this right now with the right combination of options is not intended, undocumented, and liable to break at any time.

**Comment by ForbesLindesay** [comment]
The package in question is the output of a yeoman generator. It is there to test both the output of the yeoman generator, and the packages in the rest of the project. By having it within the monorepo, it picks up the un-published development versions of all the packages that need testing. The problem is that each time the generator runs, it resets the version number to `0.0.0` and the next lerna publish explodes (creates some tags, adds a commit, attempts some publishes, then gives up and leaves everything completely broken). Keeping track of which version that package (that will **never** be published) should have is taking a huge amount of time.

**Comment by ForbesLindesay** [comment]
> If you were able to ignore versioning (which implies "and publishing") a given package that may have changes, how do you propose to recognize those changes later, when you do want to publish it?

 * If it has never had any version bumps or publishes, then it will be as if it is a new package.
 * If it has had some publish/version bump in the past, then it was ignored for a while, it should get compared to when it was last published/version bumped when you remove the ignore flag.

**Comment by evocateur** [comment]
> The package in question is the output of a yeoman generator.

Place it in a location _not_ addressed by lerna (e.g., `mkdir integration && mv packages/generator integration/generator`) and then use relative `file:` specifiers for the repo-local dependencies. `npm i integration/generator` in the root then makes it capable of finding those local dependencies, as well as auto-hoist any non-local dependencies.

Lerna does this itself with its [`helpers`](https://github.com/lerna/lerna/tree/master/helpers) namespace, which are packages that the root depends on, are never published, and are only required in tests.

**Comment by donaldpipowitch** [comment]
(Side note, because I just read it and maybe it isn't widely known: `file:` is deprecated. You can use `link:` instead.)

**Comment by donaldpipowitch** [comment]
Sorry, I misread something. I had a different protocol in mind, not `file:`. It had nothing to do with yarn.

**Comment by massa-man** [comment]
Hi All,

I am going to ask the question here since this is the closer conversation that I have seen around the issue we have. I searched around a lot for an answer but all I could find was a bit ambiguous.

We use Lerna as a monorepo for a lot of our packages, but we also have external projects and repos that are not in the monorepo. Most of these other repos consume (depend) on the packages developed within the monorepo. It is impossible for use to put ALL our repos/projects under the monorepo. As an example, imagine this:

- Repo 1: frontend-packages (lerna monorepo with React components and other packages)
- Repo 2: frontend-app (React app that uses a ton of components from the monorepo)

When developing on frontend-app, it is extremely time consuming, every time anything changes on the monorepo, to publish the packages form lerna to npm, upgrade the packages in the frontend project and test, only to find out it doesn't work and we need to do the process all over again (not to mention the versioning of all these packages which can end up being 1.0.354, etc.

So, when we develop, we checkout the monorepo and then clone the frontend repo into the packages folder in the monorepo. The frontend is excluded in gitignore in the monorepo, and it is also marked as private=true.

The main problem we have is when we publish, if we do not use --skip-git then the publish fails because the frontend project folder is ignored (and it is on a separate git repo), but when we use --skip-git, then we loose all the versioning in git for all the packages we actually DO want to track and version in git correctly, plus the publish function leaves a bunch of files changed and uncommited which developers need to remember to manually commit themselves after each publish.

So, long question short, is there any way to have a package (or a folder inside the monorepo) be part of the bootstrap process (i.e. link its dependencies to the local packages), but completely ignored from the publish process? The frontend project will never be part of the monorepo (it is a completely standalone project), so I am not concerned about not versioning it and then trying to publish it in the future...

Hope this explanation makes sense, and hopefully someone can push me in the right direction here.
