### ISSUE TITLE
`lerna run test` echoes "Error: no test specified"

### ISSUE THREAD

**Issue by sveinburne** [lerna/lerna#1142]
## Expected Behavior

`lerna run test` should not run in npm modules which have no `test` script in their `package.json`.

## Current Behavior

`lerna run test` seems to run in npm modules which have no `test` script in their `package.json`.

## Steps to Reproduce (for bugs)
[Minimal working example](https://github.com/sveinburne/lerna-test-bug)

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.5.1",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "independent",
  "hoist": false
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.5.1 |
| `yarn --version` | 1.3.2 |
| `node --version` | v8.9.1 |

| OS | Version |
| --- | --- |
| Ubuntu | 16.04 |

**Comment by zenflow** [comment]
I just happened to come across the same thing. 

This may be somewhat of an issue that belongs to NPM, since `npm test` seems to be a valid command even in packages that have no `test` script. In these cases, it is NPM that echos "Error: no test specified".

While I don't like the word "Error" being echoed when there just isn't any test, at least it returns with a 0 exit code (indicating the command was successful).

+1 for inspecting the `package.json` to check if there actually is a `test` script

**Comment by sveinburne** [comment]
@zenflow I am currently using `yarn` but you confirm you can reproduce with `npm` right ?

**Comment by zenflow** [comment]
@sveinburne Correct. 

I can also confirm that this issue shows itself when using just `npm run test` (without lerna) ...

```
C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\modules\server-start>npm run test && echo if this is echoed, it means npm run test exited with a 0 exit code

> @manitoulin-transport/server-start@2.0.0 test C:\Users\mbrunetti\Documents\git\mtdirect-monorepo\modules\server-start
> echo 'Error: no test specified'

'Error: no test specified'
if this is echoed, it means npm run test exited with a 0 exit code
```

**Comment by tkrotoff** [comment]
With lerna 2.7, `lerna run` uses `npmClient` from `lerna.json`. Before v2.7, lerna were always using `npm` even if `npmClient` specified `yarn`.
This is due to commit 625df6784dd65a5dd0fc646be7d95ba053ae9b40

I confirm the problem with lerna 2.6: `Error: no test specified`.

With lerna 2.7 and `"npmClient": "yarn"`, it's even worse:
```
execute callback with error
lerna ERR! Error: Command failed: yarn run test
lerna ERR! error Command "test" not found.
```
and lerna stops (with 2.6 it didn't stop - was just an echo message).
