### ISSUE TITLE
Lerna doesn't take save-prefix into account (npmrc)

### ISSUE THREAD

**Issue by yvele** [lerna/lerna#1157]
## Expected Behavior

With the following `.npmrc`

```none
save-prefix = '~'
```

`lerna bootstrap` should save my dependencies with `~` instead of `^` (exactly how npm is doing).

See https://docs.npmjs.com/misc/config#save-prefix

Note: Because of https://github.com/lerna/lerna/issues/361 I have an `.npmrc` file in each sub packages of the monorepo.

## Current Behavior

My dependencies are saved with `^` instead of `~` that has been defined via [save-prefix](https://docs.npmjs.com/misc/config#save-prefix) in my `.npmrc`

## Steps to Reproduce (for bugs)

With the following `.npmrc`

```none
save-prefix = '~'
```

then

```sh
lerna bootstrap
```

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.5",
  "version": "3.13.0",
  "commands": {
    "publish": {
      "ignore": [
        "*.md",
        "package-lock.json",
        "yarn.lock"
      ]
    }
  }
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | N/A |
| `node --version` | 8.9.1 |

| OS | Version |
| --- | --- |
| macOS Sierra |10.12.6 |

**Comment by willclarktech** [comment]
Also applies to `lerna init` (lerna overwrote my `package.json` to replace my preferred prefix with `^`).

**Comment by evocateur** [comment]
Yep, that's because lerna 2.x doesn't have any awareness of npm's configuration.

In lerna 3.x (`master`), it is certainly possible (with the vendored [npm-conf](https://github.com/lerna/lerna/tree/master/utils/npm-conf) lib). It would allow a root `.npmrc` to address all the leaf packages, theoretically. `lerna bootstrap` 3.x [uses it already](https://github.com/lerna/lerna/blob/75b91bd4b1fd3856734331e8105ebcf5d2e2314b/commands/bootstrap/index.js#L68), though for a different purpose.

Although, I'm a little mystified, why is `lerna bootstrap` changing your dependency ranges?

**Comment by Kikobeats** [comment]
How good is auto close issues in order to lose the issue visibility? 🤔

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
