### ISSUE TITLE
[feat]: prepublish script npm hook

### ISSUE THREAD

**Issue by alan-agius4** [lerna/lerna#1169]
At the moment, in order to run a `prepublish`  step when publishing you need to create a script under each modules like `scripts/prepublish.js`. 

This is quite limiting considering the fact one, you are liberality forcing using to have that folder structure and also in most cases one would want to use the same script and not copy and paste it in all modules.

## Expected Behaviour
- Check if a "prepublish" npm script is present in the root "package.json" if so execute it
- Check if a "prepublish" npm script is present in the package to be published "package.json" if so execute it.
- Execute the `scripts/prepublish.js` file script as per current workflow.

## Current Behaviour
There is no prepublish npm hook

**Comment by evocateur** [comment]
No, the `prepublish` (if it exists) in every package to be published is always run (by npm/yarn), because we are just calling `npm publish`/`yarn publish` in those directories (which is done in topological dependency order, so dependents always have their local sibling devDependencies built).

Of course, npm5 has deprecated `prepublish` and it should probably be replaced with `prepare` or `prepublishOnly`. I personally don't see much use in the `scripts/<lifecycle>.js` pattern, but I don't have any plans to remove it.

The problem with a `prepublish` in the root is that it (currently) will run any time anyone runs `npm install` with no arguments in the root, complete with scary looking log and possibly executing something you don't really want to have happen then.

**Comment by alan-agius4** [comment]
To avoid such problems, I avoid calling any custom tasks ‘publish’ and go
for ‘release’ in order to avoid collisions and interferance with ‘yarn/npm
publish’ pre and post hooks.

And I can safely use ‘prerelease’ and ‘prepublish’ hooks for two seperate
things during the publish cycle.

**Comment by gluons** [comment]
Excuse me!

Where is the documentation about `scripts/<lifecycle>.js`?  
I can't find it.

**Comment by kyrisu** [comment]
@evocateur small correction to what you sait:

> the prepublish (if it exists) in every package to be published is always run (by npm/yarn), because we are just calling npm publish/yarn publish in those directories 

It seems that you are [calling publish with `--ignore-scripts`](https://github.com/lerna/lerna/blob/7200fd010a67cdea6b541117e68a0a3c6694e720/utils/npm-publish/npm-publish.js#L22) so it won't run prepublish.

Any reason why that's there and how to overwrite it?

**Comment by evocateur** [comment]
It's already run by a previously executed `npm pack`

**Comment by kyrisu** [comment]
@evocateur you are right. I was thinking about `prepublishOnly` - it only runs on `npm publish` (duh!). So as you mentioned in the previous message it should be probably replaced with `prepare` script.

**Comment by wereHamster** [comment]
`npm pack` doesn't run `prepublishOnly`.

I have a monorepo with multiple packages that are written in typescript, and in `prepublishOnly` I need to run the compiler (`tsc`). Currently my canary releases on npm only contain a package.json because the files are not compiled. Do I need to manually run the prepublish scripts before calling into lerna?

**Comment by evocateur** [comment]
You should be running compilers to generate build output once, from the root. Or move to the prepack lifecycle, if typescript can't handle building multiple packages at once.

**Comment by wereHamster** [comment]
Where can I read more about prepack lifecycle?

**Comment by gluons** [comment]
@wereHamster https://docs.npmjs.com/misc/scripts
