### ISSUE TITLE
Help: Call for maintainers?

### ISSUE THREAD

**Issue by hzoo** [lerna/lerna#1172]
Ref https://twitter.com/left_pad/status/944586480139341825

So this project isn't dead or anything in terms of _usage_ - we have a good amount of [users](https://lernajs.io/#users) and just since we need to use this for [Babel](https://github.com/babel/babel/blob/master/lerna.json) and also in other big projects like Jest, create-react-app, react-router, etc. I'm talking about maintainers:

And I know no one is going to notice these kinds of things, but we haven't really had any activity in the [last month](https://github.com/lerna/lerna/pulse/monthly) for this project, since we don't  have many maintainers period. It's currently (as far as I know) only been @evocateur for the past months, before @gigabo, before I was dumb enough to try to maintain this and Babel with @thejameskyle (who is working on https://github.com/boltpkg/bolt but not sure it's ready to replace this yet at least for Babel I think?), etc. And yarn has workspaces and npm maybe cares about this too.

I don't want to join back in to help maintain but wanted to bring up this conversation again as it seems to happen every few months (like any OSS, not excluding Babel too). Like a lot of these projects, we have a cycle of burnout of 1 maintainer until someone else picks it up again and that really sucks?

---

So even though there are a lot of issues piling up, I don't think we don't have to move that fast for this project and given the lack of resources.. maybe we just need a better polished experience of what's already possible?

So like better testing/stability and some key missing features mostly around making the publishing safer/better (like [`--dry-run`](https://github.com/lerna/lerna/issues/51))? Not sure. One issue I've had is publishing and then finding out someone already published that package name (solved with scoped packages but that's a different solution), so just fixing up those kinds of cases.

Maybe it's fine since it's always been working this way with just 1 person and usually isn't an issue for majority of projects? I don't expect anyone helping out to have to take on the burden but if you want to help and am using it maybe?

**Comment by necolas** [comment]
Hey, I only just started using lerna in a very simple monorepo and ended up with something that works for me. Here's what I am currently doing:

1. Relying on yarn workspaces.
2. Only using lerna to handle version bumps across `package.json` in a script.
3. Doing the git commit and publishing myself.

So that means the way I'm using lerna atm is like this:

```
lerna publish --skip-git --skip-npm --repo-version ${version} --yes
```

**Comment by evocateur** [comment]
I could have been better about messaging the fact my son was born just over three weeks ago, and it turns out it’s really hard to do anything productive when taking care of an infant.

We do need more maintainers, and I would be happy to share the burden.

**Comment by hzoo** [comment]
Yeah totally not your fault and even if that wasn't the case (congrats by the way 🙂), still lack of help overall

**Comment by alan-agius4** [comment]
I can try to help, even reviewing PRs and stuff. that said, I don’t have a big deal of free time . So in reality I only have a few of hours per week available.

**Comment by amorenew** [comment]
Very sad a good open source who doesn't have maintainers 
Unfortunately, I am not expert in this field.

**Comment by marionebl** [comment]
I'd be happy to contribute more to lerna, but won't have enough time to take on full maintainer responsibilities. 

Currently the limiting factor for lerna is PR reviews, right? I wonder how we could enable more people to review and land changes.

**Comment by cezaraugusto** [comment]
I [left a comment in Slack](https://lernajs.slack.com/archives/C190VQD40/p1511509214000029) w/ things I'd like to help so if that's interesting for the project count me in

**Comment by zxqfox** [comment]
I'd like to join to maintain lernajs since we using lerna widely for open source and even some private packages.

Not sure I can make a huge impact to actually closing issue with some things done but I'm totally sure I can publish things and spend few hours to critical issues.

@hzoo Hey, Henry! 😺  Plus one for `--dry-run` (even if it will be just a preset for a couple of other flags).

**Comment by noherczeg** [comment]
It pains me to say this, but I got burned out partially due to the fact that I got a team to manage, and the fact that I tried way too hard to catch up to the level of others in Git and NPM which would be required to achieve higher status than "committer".

I think the project has to have a small amount of folks who are both experts at git, npm, and node as well. If this is a given, others can contribute. Lerna became more complicated as time went by, so it needs proper oversight.

**Comment by alexeyraspopov** [comment]
Wasn't sure if it's worth opening a separate issue, so I'll just drop it here.

@hzoo, have you considered adding Lerna to https://opencollective.com/? I use Lerna and would love to contribute, but I can't find enough time to do it through the code contributions. However, I'd like to thank the team for the effort and help as much as I can at least through donations. I believe that's not only me who thinks the same.

**Comment by ahtee** [comment]
Will try to pay attention more to this repo and help out however I can :) I may not be the most experienced or resourceful person for this though
