### ISSUE TITLE
Managing hotfixes with a Lerna monorepo.

### ISSUE THREAD

**Issue by phyllisstein** [lerna/lerna#1253]
Hey folks! This is a little StackOverflow-y, potentially, but I thought it was worth going to the source before casting a wider net. I'm a little desperate for guidance after scratching my own head raw on my end, but if it's not a good fit for GitHub, please feel free to direct me elsewhere.

My team is interested in converting from our current manyrepo structure for managing a bundle of interdependent Node packages to a Lerna-managed monorepo. We've gotten most of the workflow down, after a little experimentation, but there's one scenario that I still can't wrap my head around.

Let's say we have two apps called `alice` and `bob`, both of which depend on modules `carol` and `dave`. As we're iterating, we publish `1.0.0` and `2.0.0` versions of both the dependent modules---but for whatever reason, `alice` can't upgrade to `carol@2.0.0` and has to stay pinned to `carol@1.0.0`. Lerna can of course handle this, is my understanding, since as soon as the local package doesn't satisfy the version constraint it falls back on the version already published to NPM.

But we discover a fatal bug in `carol@1.0.0`. It's _still_ more work to prepare `alice` for `carol@2.0.0` than to just patch the bug, so we want to release a new patch version (`carol@1.0.1`) with the hotfix. The team's thinking is that this would be easier to manage if `carol` were one repo among many than if `carol` were embedded in a monorepo with the others. To be honest I'm not totally sure what the workflow for creating that patch release would look like in _either_ scenario, but I'm curious whether this is an eventuality for which Lerna is prepared.

Thanks a bunch for any insights!

**Comment by evocateur** [comment]
1. Lerna manages _packages_, not applications.
2. The general pattern among npm packages is to "fix forward" when a situation such as the one you described occurs.
  (Application lockfiles make this trivial, nothing changes the build until a compatible future release of the dependency package is ready)
3. That being said, nothing about Lerna specifically forbids you from creating a hotfix branch based off the `v1.0.0` tag, make some fixes, and then publish `v1.0.1` from that hotfix branch.
  (This is presuming the fix already lives "upstream" in  v2+`master` and you don't need to do any horrible `git flow`-like gymnastics)

This is also somewhat predicated on the use of lockfiles (`yarn.lock` or `package-lock.json`, doesn't matter which), otherwise forking off a previous tag won't guarantee any sort of reproducibility etc etc.

**Comment by doug-wade** [comment]
This question seems to have been answered; please feel free to reopen if there are more follow-up questions.
