### ISSUE TITLE
Dev flags in package-lock.json is removed after first lerna bootstrap

### ISSUE THREAD

**Issue by compulim** [lerna/lerna#1256]
Running `lerna bootstrap` for the first time after cloning a repository, the `package-lock.json` file is changed in a drastic way.

## Expected Behavior
`package-lock.json` should not be updated, or with very minimal but related/reasonable changes.

## Current Behavior
Packages in `package-lock.json` have their `dev: true` flag gone, along with some other values.

## Possible Solution

Run `lerna exec npm dedupe` or any other npm commands that will touch the `package.json`.

Then run `lerna link` again.

> `lerna bootstrap --no-package-lock` does not work, will still touch `package-lock.json`

## Steps to Reproduce (for bugs)

1. `lerna init`
2. `mkdir packages/myapp`
3. `cd packages/myapp`
4. `npm init`
5. `npm install colors --save`
6. `npm install debug --save-dev`
7. Capture the `package-lock.json`, it should have `debug` package marked as `dev: true`
8. Remove `packages/myapp/node_modules`
9. At root, do `lerna bootstrap`
10. Look at `packages/myapp/package-lock.json`, it is touched and `debug` is no longer marked as `dev: true`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.8.0",
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
</p></details>

<details><summary>package-lock.json *before* bootstrap</summary></p>

```json
{
  "name": "myapp",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "colors": {
      "version": "1.1.2",
      "resolved": "https://registry.npmjs.org/colors/-/colors-1.1.2.tgz",
      "integrity": "sha1-FopHAXVran9RoSzgyXv6KMCE7WM="
    },
    "debug": {
      "version": "3.1.0",
      "resolved": "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz",
      "integrity": "sha512-OX8XqP7/1a9cqkxYw2yXss15f26NKWBpDXQd0/uK/KPqdQhxbPa994hnzjcE2VqQpDslf55723cKPUOGSmMY3g==",
      "dev": true,
      "requires": {
        "ms": "2.0.0"
      }
    },
    "ms": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz",
      "integrity": "sha1-VgiurfwAvmwpAd9fmGF4jeDVl8g=",
      "dev": true
    }
  }
}
```

</p></details>

<details><summary>package-lock.json *after* bootstrap</summary></p>

```
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "colors": {
      "version": "1.1.2",
      "resolved": "https://registry.npmjs.org/colors/-/colors-1.1.2.tgz",
      "integrity": "sha1-FopHAXVran9RoSzgyXv6KMCE7WM="
    },
    "debug": {
      "version": "3.1.0",
      "resolved": "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz",
      "integrity": "sha512-OX8XqP7/1a9cqkxYw2yXss15f26NKWBpDXQd0/uK/KPqdQhxbPa994hnzjcE2VqQpDslf55723cKPUOGSmMY3g==",
      "requires": {
        "ms": "2.0.0"
      }
    },
    "ms": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz",
      "integrity": "sha1-VgiurfwAvmwpAd9fmGF4jeDVl8g="
    }
  }
}
```

</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.8.0 |
| `npm --version`  | 5.6.0 |
| `node --version` | 9.3.0 |

| OS | Version |
| --- | --- |
| Windows 10 | 1709 (17093) |
| Ubuntu | 16.04.3 |

**Comment by evocateur** [comment]
Yeah, that's because the leaf node `package.json` files are always mangled during the `npm install` called from `lerna bootstrap` to exclude sibling dependencies.

It's kind of irrelevant from the npm perspective, however, as `package-lock.json` files are never published and are never consulted by consumers when the package is installed. Thus, it's an unfortunate side effect, but makes no difference in practice.

**Comment by compulim** [comment]
Although `package-lock.json` is not published to NPM, it is committed into GitHub. Every time a fresh Git clone + `lerna bootstrap` will result in a big modifications to all `package-lock.json` files under `/packages/` folder.

In order to "mitigate" the side-effect, we will need to go under every package and do anything that will let `npm` touch the `package-lock.json` file, for example, `npm install` a package.

It just sounds kind of strange when `lerna bootstrap` is meant to install dependencies, but in fact, it modified some of the committed files.

**Comment by evocateur** [comment]
All of your dev dependencies should be in the root, anyway. It’s half the point of a monorepo in the first place.

**Comment by evocateur** [comment]
Also, the build/test/lint scripts, of course. Much faster bootstrap that way, too.

**Comment by esprehn** [comment]
We have a large project and can't have all the devDependencies at the root because there's different versions used by different packages. Can this be fixed in lerna instead?

**Comment by evocateur** [comment]
Your project is too large if that is the case.

**Comment by esprehn** [comment]
What makes you say that? We use lerna for our product which contains a number of submodules (server, cloud functions, web app, android, ios, etc.) since it removes the need to have lots of cross repo changes and working in a monorepo is how all our tooling works. Different clients might use different versions of certain build tools. Also not all tools are okay with symlinks inside node_modules, so hoisting all packages breaks some tools.

We really like using lerna, but it seems you're trying to pass judgement on how folks run their projects which makes it hard for us to use it. I'm not sure how you expect people to use lerna in an npm@5 world since it seems the default workflow from before stops working and you're forced into a very opinionated (--hoist + only devDependencies in the root) workflow instead. I guess we could fork lerna at Google, but that'd be unfortunate.

**Comment by evocateur** [comment]
I’m using npm5 + lerna 2.x daily with no issues; the 3.0 alpha completely replaces bootstrap with npm5’s relative `file:` specifier symlinks (coincidentally, very similar to how yarn workspaces hoists things, but much cleaner). Since virtually nobody else has seen fit to contribute to lerna recently, I get to have opinions (founded in facts, but don’t let that stop you from belittling them) about how multi-package repositories should work.

To be blunt, Google (to my knowledge) has contributed fuck-all to Lerna. Have fun forking.

**Comment by compulim** [comment]
I think @evocateur has his point. One might not able to keep all dependencies the same version across multiple projects, but all tooling dependencies (a.k.a. `devDependencies`) should be the same.

If it is a monorepo actively maintained by the team, version bumping is a regular chore the team should take. Reducing number of versions also means better security.

IMHO, all dependencies under the same monorepo should converge over time. If a team decided not to pay their technical debts on time, especially toolchain that help the team everyday, good luck to you.

If you like the project and want to grow it, contribute. If you feel it's too opinionated, make it diverse by contributing. Otherwise, fork it or leave it.

All tools are made to be opinionated and biased to a level of degree. That's diversity.

**Comment by danny-andrews-snap** [comment]
> It's kind of irrelevant from the npm perspective, however, as package-lock.json files are never published and are never consulted by consumers when the package is installed. Thus, it's an unfortunate side effect, but makes no difference in practice.

This isn't entirely true. Many people use a checksum of the package-lock.json file as a cache key in CI to speed up dependency installation. If you only ran `npm install` (and not `lerna bootstrap`) at the top level, and checked in package-lock.json, then when you run in CI, a different package-lock.json will be generated. This is very unexpected behavior.

**Comment by evocateur** [comment]
@danny-andrews-snap You should be using `npm ci` in CI if you're versioning the lockfile, otherwise you're prone to developers forgetting to synchronize manual edits to `package.json` => `package-lock.json`.

**Comment by danny-andrews-snap** [comment]
Just learned about this yesterday! Thanks!

**Comment by danny-andrews-snap** [comment]
This still isn't working properly. Now, I'm getting different results based on wether I run `npm install + lerna bootstrap` or `npm ci + lerna bootstrap`.

`npm install` + `lerna bootstrap` results in packages in package-lock.json having:

```json
"resolved": false
```

`npm ci` + `lerna bootstrap` results in packages in package-lock.json having:

```json
"resolve": ""
```

I think this issue was closed prematurely. Regardless of weather you think it's "irrelevant" from npm's perspective, lerna mangling package-lock.json files like this is incorrect behavior and should be fixed.

Best,
