### ISSUE TITLE
[Feature] Configurable package locations

### ISSUE THREAD

**Issue by gigabo** [lerna/lerna#126]
Hi,

I'd like organization beyond a flat `packages/` directory.

A gulp-style glob array seems natural:

``` json
{
        "lerna": "2.0.0-beta.7",
        "version": "0.2.3",
        "packages": [
                "packages/{core,plugins}/*/package.json",
                "build-tools/package.json",
                "integration-tests/**/package.json"
        ]
}
```

Objections?  Better ideas?

Happy to take it on.

**Comment by thejameskyle** [comment]
I wouldn't be opposed to allowing the `packages` directory to be customizable, especially to account for nested directories. However I'm against allowing multiple directories because it would likely add a lot of complexity and I don't really see a huge benefit

**Comment by gigabo** [comment]
Thanks for considering.  No real interest in just moving the directory here.  Feel free to close.

**Comment by hzoo** [comment]
Ok going to close for now

**Comment by mxstbr** [comment]
Would love to see this reopened, will gladly submit a PR implementing support for this if you see the use for it.

I have that exact use case – over at [Carte Blanche](https://github.com/carteb/carte-blanche) our file layout is a bit different, we have:

```
carte-blanche/
├── package.json
├── plugins/
│   ├── react/
│   │   └── package.json
│   └── source/
│       └── package.json
├── utils/
│   └── package.json
└── webpack-plugin/
    └── package.json
```

Where each plugin (`plugins/xyz/`) is its own package, the core (`webpack-plugin/`) is its own package and we have a few shared utils (`utils/`) that are their own package.

I think in our case it makes sense to be that way, so having an option to change that would be great:

```JS
{
    "packages": [
        "plugins/**/package.json",
        "{webpack-plugin,utils}/package.json"
    ]
}
```

If we want to keep it to a single glob, one could also express those as

```JS
{
    "packages": "{plugins,webpack-plugin,utils}/**/package.json"
}
```

though not sure how the first one is more complex. What do you think?

**Comment by thejameskyle** [comment]
The problem I have with it is that there's no reason it doesn't work within the `packages` organization. You could just as easily have 

```
carte-blanche/
  packages/
    react/
    source/
    utils/
    webpack-plugin/
```

**Comment by mxstbr** [comment]
Yeah I guess it works, but it's quite a bit of work to restructure the build processes – simply saying `"{plugins,webpack-plugin,utils}/**/package.json"` is a lot easier from that perspective.

**Comment by doug-wade** [comment]
Are Redfin, we can't actually just make it work with the `packages` organization.  Specifically, we have a Spring MVC server that uses npm to manage its front-end dependencies.  It needs to live at the top level because of maven requirements.  We also have another top-level React Server instance that has a lot of relative file paths that point to it, for which a migration to `packages/` would be non-trivial

```
redfin
    maven-project
    react-server
    packages
        foo
        bar
        baz
```

I would love to replace our internal npm build tool with `lerna` because `lerna` has a much simpler api and handles dependencies much faster, but we simply can't move all of our node_modules into `packages`.

**Comment by thejameskyle** [comment]
What are the maven requirements?

**Comment by doug-wade** [comment]
I talked to @roblg about it, and it turns out that mostly its the tooling we've built around our maven build system that assumes that our servers are children of the root directory.  Migrating to have our packages in `packages/` instead would require us to change the way our distros are built and deployed, and how much of our build tooling is implemented (for instance, we have a fair bit of legacy code that is copied between our legacy Spring MVC server and our new React Server instance at build time to ease migration that we would have to retool.  There isn't any reason that, had we known that lerna would have this requirement two years ago when we started the React Server project to put all of our private node modules into a folder called `packages`, but we had no way of knowing at the time that would be a requirement.

**Comment by thejameskyle** [comment]
Is customizing the location of the packages directory enough, or does it need to be split into multiple directories for this to work?

**Comment by doug-wade** [comment]
It needs to be split into multiple directories.  In our case, we need some modules to be at the monorepo root, and some modules to be in a configurable directory (we call it `redfin.npm`).  We could actually do without the configurable directory (I could move `redfin.npm` to `packages`), but we can't do without allowing some modules to be at the monorepo root (i.e. siblings to lerna.json), and I'd like to be able to keep most of them in a `redfin.npm`/`packages` directory to prevent cluttering the monorepo root when we can avoid it.

**Comment by thejameskyle** [comment]
Okay, I guess we should do it then

**Comment by mxstbr** [comment]
Yess :tada: Anything we can help out with, or is it a quick change that you just want to get done with?

**Comment by Ondoher** [comment]
Progress? We have packages from two different repos we'd like to maintain as such. Multiple package directories or nested would be great.

**Comment by nruhe** [comment]
We need this feature pretty heavily. What's the ETA on it? If it's going to take a bit, I'm willing to fork the repo and add it myself.

**Comment by gigabo** [comment]
@mxstbr @Ondoher @nruhe Sorry for the delay.  Please take a look at #332 if you get a chance.

**Comment by gigabo** [comment]
Configurable package locations are available in [lerna@2.0.0-beta.31](https://github.com/lerna/lerna/releases/tag/v2.0.0-beta.31)! 🎉

**Comment by SachaG** [comment]
Just to clarify this, does "configurable package location" mean *any* location, even outside of the app's directory? So my main app could be at `~/foo/myApp`, and my packages at `~/bar/myPackages`?

**Comment by evocateur** [comment]
Lerna manages monorepos of npm packages, not applications. The location of those managed packages defaults to `./packages` in the root of the repository, but it can be configured anywhere in the monorepo (and in multiple locations, should you desire).
