### ISSUE TITLE
[Performance] Double (?) memory usage when exec npm scripts

### ISSUE THREAD

**Issue by natew** [lerna/lerna#1276]
So apologies, hard to know where this one goes. But it seems a common use case for Lerna. Basically am running into memory issues with a large mono-repo where you have build scripts for many sub-packages.

We basically have `npm run build` for each package that is then long-running, watching for changes. So to run this the command is `lerna exec --parallel -- npm run build -- -- watch`.

Running this and checking into activity monitor, you see this:

![image](https://user-images.githubusercontent.com/12100/36400233-87d1853e-1584-11e8-8d93-56c910675276.png)

## Expected Behavior

Behaves as expected this is just for memory optimization.

## Current Behavior

Runs npm directly.

## Possible Solution

Perhaps Lerna could be smart here and avoid having the extra `npm` process. By reading your npm script and avoiding the second shell process, you'd save ~20mb of memory per-process. For people with bigger mono-repos (ours is approaching 40 packages) and on unfortunately capped 16GB memory capped Macbook Pro's, this would be a big savings.

Separately, it seems babel uses quite a bit of memory just to watch some files. I may open an issue there as well and discuss with them.

**Comment by evocateur** [comment]
Why not just run your build scripts from the root? It's like half the value-proposition of Lerna itself (dedupe all your package-level linting/testing/building). _Especially_ watchers, those should always be run in the root of any tree, not the leaves.

Philosophically, Lerna is intentionally "dumb" about this because at its core it is "just" a coordinator of existing functionality, gluing together a panoply of packages into a convenient unit. We don't re-implement `npm run` because the npm folks already did a good job of it.

**Comment by natew** [comment]
How would you run babel watchers at root? From what I understand it takes an in dir and and out dir. For now I've just written my own script, outside lerna/npm, which has lowered memory usage now 800Mb.

Also it's all contextual. npm run is great, sure, but in this context, 20Mb overhead per package is not a great. I do think this issue falls a bit more on the babel side though, and I'm coordinating with them.
