### ISSUE TITLE
Please unlock #901

### ISSUE THREAD

**Issue by oliviertassinari** [lerna/lerna#1285]
@evocateur Could you please unlock #901?
I can understand you don't want to increase internal Lerna complexity by supporting this feature. Closing the issue is 💯 fine. But please, don't use your power to shutdown everyone else opinions.
This issue gather people facing the same pain point, let us figure out a solution.

Let's say I fork Lerna to add this feature, how can I make these people aware with a locked issue?

**Comment by evocateur** [comment]
Tag them all from your own fork’s issues. I already give away all my work, it’s not my job to make your fork easier. I thought I made it very clear that the discussion was over.

**Comment by oliviertassinari** [comment]
@evocateur I don't plan on forking the project, it was an example of use case one could have.
Mine is about upvoting https://github.com/lerna/lerna/issues/901#issuecomment-356725527 as the workaround I found (but not perfect as the `preversion`/`version`/`postversion` script output are swallowed). It's something other people could be interested in finding.

**Comment by rosskevin** [comment]
@evocateur 
> I already give away all my work

...and so do many others, including both @oliviertassinari and myself.  We are strong open source contributors to many projects, but comments such as `If anyone wants this, fork lerna and do it yourself. This conversation is over` doesn't encourage contribution, they encourage others to not even bother to engage, further burdening you since you are clearly invested in this project.

It might serve you well to cultivate the community instead of telling to take their effort and go elsewhere.

^^^ all of this is unsolicited advice and I understand it is your prerogative to take it or leave it.  Aside from your harsh handling of the community, I just want to say thank you for your effort here; I appreciate your work and the work of all the contributors to lerna.
