### ISSUE TITLE
Feature Request: configure npm publish retry attempts

### ISSUE THREAD

**Issue by am80l** [lerna/lerna#1299]
## Current Behavior
Lerna publish will continually retry publishing a failed publish until it succeeds. This caused on of our Jenkins build jobs to hang for 13 hours while our internal NPM registry was being upgraded. It should also be noted i am using `lerna publish --conventional-commits --yes`

## Possible Solution
Potentially a configuration to allow for N number of retrys, perhaps defined in lerna.json

## Steps to Reproduce (for bugs)
Try to publish a package through lerna publish while NPM is down. Alternatively, trying to publish over a previously published version seemed to have the same effect.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.9.0",
  "packages": [
    "packages/*",
    "."
  ],
  "version": "independent"
}
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.9.0 |
| `npm --version`  | 3.10.3 |
| `node --version` | 6.5.0 |
-->

**Comment by evocateur** [comment]
Odd, lerna v2.x should only attempt to publish a given package 5 times. v3 doesn't even bother with that, immediately rejecting the Promise chain. The general error handling/prevention of `lerna publish` with all of its sharp edge-cases certainly merits attention.

Historically, the retries were mostly in-place because the publish order wasn't topographically sorted, causing problems when a dependent was published before an updated dependency.

**Comment by am80l** [comment]
Interesting. It should be noted that the failing package was the root package tracked using `"."` in lerna.json. Looking back through the logs, failing/retrying seemed to only ever happen for that top level package. Since it wasn't buying us much, I've since stopped tracking the root package as it seemed to be more problematic during publishing than those managed in `/packages/`.

**Comment by evocateur** [comment]
Ooh, one more reason to remove support for `"."` globs in the `packages` config...
