### ISSUE TITLE
Lerna workflow for web applications

### ISSUE THREAD

**Issue by goldenshun** [lerna/lerna#1329]
On the surface, Lerna appears to support monorepo workflows for any set of node applications that can be represented by a `package.json` file, but I'm struggling to find the right configuration that works well for my web application workflow.  Most of the documentation is tailored for packages that are intended to be published to npm.  I have seen some examples that include applications and lerna _almost_ solves everything but there are a few things I am hoping to get some help with.

# Structure
I need a monorepo that supports multiple web applications that are supported by multiple packages.  Something like this:
```
/apps
  /main
    package.json
  /accounts
    package.json
  /admin
    package.json
  /styleguide
    package.json
/packages
  /components
    package.json
  /theme
    package.json
```
And for reference, my `lerna.json` file looks like this:
```
{
  "lerna": "2.9.0",
  "packages": [
    "apps/*",
    "packages/*"
  ],
  "version": "independent"
}
```
With this structure I can use lerna to create a nice local development experience using things like `--hoist` and `--parallel` for installing dependencies, running multiple watchers, etc..

I can do similar things with just Yarn workspaces, but I also need something that supports my publish and deployment activities.

`lerna publish` works really well when it comes time to _publish my packages to npm_
**but it does not work well for my application deployment**.

# Application Deployment
There are a few styles of application deployment that I am trying to support but for all of them I really want the following to be true:
- An application is only deployed if its code or one of its dependencies was modified
- If an application's package dependency was not modified, it does not need to be rebuilt

I am using [Zeit's Now](https://zeit.co/now) service for my deployments.  There may be another service that works better for what I'm trying to do, but I'm not sure yet.

## Production
At a high level since I am working with packages _and_ applications, I think this process needs to be broken down into two steps:
1. Publish updated packages to npm
2. Deploy updated applications to `now`

The first step is easy:
`lerna publish --scope="pkg-*"`
I prefixed my package names with `pkg-` to make this possible.

Since the first step commits to git, I can't really take advantage of lerna to only deploy the applications that have been updated.

`lerna run deploy --since` or a similar command doesn't really work the way I want so for now I'm resorting to just deploying all of the applications.

I can live with this for for a while, mostly because `now` is doing most of the build/deployment work.

With this setup the `deploy` scripts are declared per application, even though they are all doing similar things with `now`.  The other nice thing about `now` is that it takes care of the heavy lifting of build and deployment.  My local machine is really just uploading the application directories.  Those packages that were published in step 1 can be `npm installed` by `now` in the cloud.  That part is actually quite nice.

## Feature Branch
We make heavy use of feature branches and QA environments for testing, design QA and product QA so its really important that we have a workflow that supports our ability to deploy code in a feature branch to an accessible environment.

**This is where the aforementioned "publish packages then deploy applications" workflow falls apart for me.**

If I tried to perform the above workflow from a feature branch, I need to make sure the packages that get published to npm are _not_ used in production deployments.  So my feature branch deployment needs to look more like:
`lerna publish --scope="pkg-* --canary"`
...which creates an npm version like `@mycompany/pkg-components@1.2.0-alpha.07429358`

So far so good BUT I need references to that dependency to point to the alpha version.  For example, one of the applications has a dependency that looks like this:
```
  "@mycompany/pkg-components": "latest",
```
The alpha prerelease package doesn't satisfy that version so when I try to deploy my application from my feature branch, `now` is going to pull down the prior published version.

I _think_ what I am looking for is an option where a `--canary` publish can also update my application packages to point to the prerelease version:
```
  "@mycompany/pkg-components": "1.2.0-alpha.07429358",
```
But then when published from `master`, it goes back to pointing to the "latest" version.
# Proposal
All of this sounds a little (or a lot) complicated, but I don't think lerna is _that_ far from being able to work for me.  I think what I am proposing for the feature branch scenario is an additional flag `--update-prerelease-dependencies` (I'm sure I can come up with a better name) that can swap anything from "latest" to an explicit version.

**Comment by evocateur** [comment]
Instead of `--scope=pkg-*`, just put `"private": true` in the app package.json files. Don't use `'latest'` to point to a monorepo sibling, that breaks the relationship that lerna can see, and thus the versions never get updated. Apparently this is a `now` pattern? Huh.

`now` is charmingly obtuse about _what_ they're actually doing when deploying, but if at some point it's just creating a webpack bundle and then uploading that, you should be fine to use local `file:` specifiers in the app manifests. If they're actually calling `npm install` on their hosted thingy, well, that's less workable.

I have said before, and I'll say again, `lerna` is _not_ for deploying applications. I don't really see this sort of thing making it into the CLI.

**Comment by goldenshun** [comment]
> charmingly obtuse

I chuckled at that.

Thanks for the tip with `"private: true"`.  `now` simply runs `npm install`, `npm build` and `npm start` for their npm deployments.  I don't think its that obtuse and it works well for single apps, but it is restrictive and does not presently work well for multi-application deployments.

**Comment by evocateur** [comment]
Yeah, I didn’t mean the service itself was obtuse/bad, I actually quite like the pattern of “one-click deploy” where it makes sense. It is reassuring that they’re just calling standard npm commands.

**Comment by goldenshun** [comment]
@j I hear you and what you describe is similar to what I was trying to achieve back when I first opened this thread. I recently realized that my original desire might have been misguided. We are now dealing with multiple, disparate applications that we want to share some code.

Since we want to scale our team and scale our applications, it doesn't really make sense for us to hitch all of those together with the same exact dependencies. In a larger team, surely there will be a scenario where I want to make a change to a package but that package has multiple applications that depend on it. Do I really want to test and deploy the change I made in all of those applications? What if I don't know anything about them? Do I need to reach out to the owners? The concept became undesirable real fast.

What become much more palatable for us was to do what you did and pull all shared stuff into a mono repo and use private npm. The real gain is versioning, which means you can update your package and update the app you care about and allow the owners of other applications to upgrade as they need to. Obviously this workflow isn't as simple as if you were just working on a single application in isolation but we have found it to work well enough for us and lerna does make it easier for us to develop and publish those packages.

**Comment by djskinner** [comment]
I know managing applications as well as packages isn't what lerna is designed for but we have had some reasonable success with it and it feels so close to being a great solution with the best possible developer experience (no npm link shenanigans!). As pointed out the main issue for us also came down to deployment/publishing.

Things break down for us because lerna just looks for the last tag regardless of what it's meaning/name is. That means we weren't able to tag deployments separately from package versioning because lerna would then wrongly use the non-lerna tag as if it were the last version tag.

If it was possible to choose which packages/apps to version and publish (in the case of packages only) e.g. with a `lerna publish --scope` type command then I think we'd have a pretty good solution although I understand there have been rejected requests for a `lerna publish --scope` type functionality in the past so I assume it's not feasible.

**Comment by j** [comment]
@goldenshun @djskinner It'd be nice to have lerna / workspaces accept mono-repo for publishing and have it so that an organization can have a structure such as (eg):

```
example/
  packages/
    react-component-foo
    blog-repository
    account-repository
    account-service
  deployables/ (can be named anything...)
    www/
    admin-www/
    account/
    chromium/
```

And back to what @goldenshun said for big teams / applications.  I'd like to use a mono-repo where it makes sense and organize deployments and that have shared packages.  The main concept would be: "React SSR + GraphQL server".  I'm sure most can get by with just having two separate areas package.json and installing deps within each folder on their own.  Our current use-case does react + chromium stuff so shared code is everywhere but I can't deploy without pain with Lerna.

**Comment by goldenshun** [comment]
@j I do agree that it could be helpful for that use case. In our scenario, we actually have an example app in our lerna mono-repo and sometimes working with that is painful because npm handles linking and peer dependencies quite poorly. It would be nice to be able to use lerna to bootstrap packages for that app but not worry about publishing that app, which does have a `package.json`. As stated before, `lerna publish --scope` could help with that.
