### ISSUE TITLE
Local workspace packages not being linked

### ISSUE THREAD

**Issue by milesj** [lerna/lerna#1330]
Not sure if this is a Yarn workspaces bug, or a Lerna bug, but figured I would report here first. To start, I have this project called [Beemo](https://github.com/milesj/beemo), which is a monorepo with packages like `@beemo/cli`, `@beemo/core`, and `@beemo/driver-*`. Beemo is a configuration layer, and as such, I have another NPM module called `@milesj/build-tool-config`, which depends on the same released version (0.13). Technically I have a reference chain like so:

```
/packages
  /core (@beemo/core)
  /cli (@beemo/cli)
  /driver-* (@beemo/driver-*)
/node_modules
  /@milesj/build-tool-config/
    /node_modules
      /@beemo/core
      /@beemo/cli
      /@beemo/driver-*
```

When I `yarn install`, the dependent versions are hoisted to the root, like the below. At this point, `lerna bootstrap` fails to symlink the local /packages, as I assume Lerna believes that path is already taken. BUT, the `@milesj/build-tool-config` package doesn't depend on all `@beemo` packages, yet the packages that aren't depended on DO NOT get symlinked either (for example, `@beemo/driver-mocha` is not symlinked).

```
# hoisted
/packages
  /core (@beemo/core)
  /cli (@beemo/cli)
  /driver-* (@beemo/driver-*)
/node_modules
  /@beemo/core
  /@beemo/cli
  /@beemo/driver-*
  /@milesj/build-tool-config/
```

If I utilized Yarn workspaces `nohoist` to not hoist the `@milesj/build-tool-config` packages to the root, like the following, `lerna bootstrap` and even `lerna link --force-local` STILL DO NOT symlink anything.

```
# nohoist
/packages
  /core (@beemo/core)
  /cli (@beemo/cli)
  /driver-* (@beemo/driver-*)
/node_modules
  /@milesj/build-tool-config/
    /node_modules
      /@beemo/core
      /@beemo/cli
      /@beemo/driver-*
```

## Expected Behavior

Local /packages should be symlinked to node modules.

## Current Behavior

Local /packages are not symlinked whatsoever, with hoisting, and without hoisting.

## Possible Solution

Provide a way to force symlinking, even if a root package in node_modules already exists with the name.

## Steps to Reproduce (for bugs)

1. Clone the beemo repo.
2. `yarn install`
3. `yarn run bootstrap`
4. Check node_modules folder or run `yarn test` to see it fail.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.0.0-beta.3",
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "commands": {
    "publish": {
      "ignore": [
        "*.md"
      ]
    }
  }
}
```
</p></details>

## Context

I've tried both Lerna 2.9 and 3 beta. This is driving me nuts, as I'm unable to `lerna publish` anymore, or even run tests. Feel free to clone and mess around yourself.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.3 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.5.1 |
| `node --version` | 9.8.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.13.3 |

**Comment by evocateur** [comment]
When using Yarn workspaces, `lerna bootstrap --hoist` has literally no effect whatsoever, as all it does is run `yarn install` in the root. `lerna link` is a silly command, and I'm increasingly itching to delete it (and it's also not going to help you here, because you're not using lerna's linking algorithm, but yarn's).

One notable difference in the Yarn workspaces linking algorithm is that it does not bother with relative symlinks from `packages/foo` to `packages/bar/node_modules`, it just "hoists" all the `packages/*` (via symlink) in to the root `node_modules`, with appropriate scope directories as necessary. That means every leaf package can resolve every other leaf package, should it desire. (It's up to tools like eslint-plugin-import to validate which packages are _actually_ listed in the closest package.json, etc)

So yes, I think this is a Yarn bug. That being said, I don't think having local dependencies (the leaf packages) that are identical to external package dependencies is helping anything.

**Comment by milesj** [comment]
Thanks for the feedback. It makes perfect sense. I'll report this to Yarn.

**Comment by bertho-zero** [comment]
For fix that I added this in my package.json:
```json
"scripts": {
  "install": "lerna link",
  "bs": "lerna bootstrap",
}
```

So I can run `yarn`, `yarn bs` or `lerna bootstrap`.

**Comment by captainkovalsky** [comment]
@evocateur I see that even `link --force-local` doesn't work. Is that expected behaviour?


| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.17 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | VERSION |
| `node --version` | v9.11.1 |

**Comment by evocateur** [comment]
Well, no? I can’t fix “doesn’t work” without reproducible examples.

**Comment by ZempTime** [comment]
For future reference, here's that issue in the yarn repo: https://github.com/yarnpkg/yarn/issues/5538
