### ISSUE TITLE
feature: lerna publish <package>

### ISSUE THREAD

**Issue by reggi** [lerna/lerna#1332]
I'd like to publish a specific package, and all of the packages that that package depends on as well. I have package that depends on several local 'file' packages. I'd love for a way to publish only the modules that are required.

```json
{
  "dependencies": {
    "@reggi/journey": "file:../journey",
    "@reggi/pkg.read-json": "file:../pkg.read-json",
    "@reggi/pkg.throw-error": "file:../pkg.throw-error",
    "babel-runtime": "^6.26.0",
    "lodash": "^4.17.5"
  }
}
```

**Comment by evocateur** [comment]
The `file:` specifiers are overwritten during publish, resolved to the actual version range of the sibling package. If there are no changes in a package, lerna doesn't publish it. If there are changes in a local dependency of a package, that consuming package will also be published, since its local dependency version range has changed.

**Comment by AnaRobynn** [comment]
@evocateur What do you mean?
I'm looking at a repo where I recently published and when I publish again, without changing any code or packages it still prompts me to choose the version bump, which shouldn't happen. I'm running in --independent mode, so I would like to be in control which package actually gets a version bump.

**Comment by evocateur** [comment]
@AnaRobynn If the unchanged package has sibling dependencies that have changed (since the last tag), it will always publish a new version of the unchanged package as well (because versions are cheap, see #707).

If there are _no_ changes (in package directories) in the _entire_ repository since the last tag, `lerna publish` should exit early without any prompting or changes made.

**Comment by reggi** [comment]
I've been using `npm install ../journey` as a way to "install" a sibling package add add the `file` reference. 

@evocateur I still have one open question. If I add a `file` reference and the publish, it converts the reference to the version number, so it can publish, but then does it turn it back to a `file` reference after?

Ideally all I want is a this.

* `lerna -C ./packages/alpha install beta --fileSpecifier`
* `lerna -C ./packages/alpha install beta`

`-C` would have the same usage as `npm` and `git`. The first command would install beta in alpha using the `--fileSpecifier` and ideally this would check the `npm` version if it's 5+ it would be the same as `npm -C /packages/alpha ../beta` if it's an older version of `npm` it would add shim the same functionality.

**Comment by AnaRobynn** [comment]
I'll test it out with two packages that have no single dependency between each other, but just 1 dependency in the top level json.

**Comment by evocateur** [comment]
> Does commands also add a gitHead property in my package.json, is that standard behavior?

The `gitHead` is only meant to be temporary during the execution of `npm publish`, 
the latest 3.x beta has a fix for this (`npx lerna@next ...`). It is something that npm itself adds temporarily during publish, but lerna has to adapt it because the core method does not work when `.git/` isn't in the CWD.

A demo repo would be much easier to explain than talking past each other.

**Comment by reggi** [comment]
This makes sense I would still like to publish a specific package and required other sibling deps deliberately but when the system work it works.
