### ISSUE TITLE
Can't run on packages since X + certain package Y

### ISSUE THREAD

**Issue by vzaidman** [lerna/lerna#1339]
I want to run several commands on packages that changed since `master` + a certain package `some-package`.

## Expected Behavior
There should probably be a way to do it.

## Current Behavior
I didn't find a way to do it.
```
lerna exec --since master --scope some-package
```
doesn't works because `scope` packages override `since`.

## Possible Solution
* make scope extend since instead of overriding it
OR
* add a new parameter like `--base-scope=some-package`

## Steps to Reproduce (for bugs)
run
```
lerna exec --since master --scope some-package
```
where `some-package` didn't change since master.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.9.0",
  "packages": [
    "packages/*"
  ],
  "version": "2.0.0"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

**Comment by evocateur** [comment]
So you're trying to exec something in `some-package`, but _only_ if it has changed compared to an upstream ref? Or _always_ in `some-package`, regardless of changes? I'm a bit confused, since the former case is the current behaviour, and the latter can be accomplished by just removing `--since`.

As for extending the filtered packages, there is `--include-filtered-dependencies`, which will re-add packages that were filtered out by `--since` if they are transitive dependencies of packages matched by `--since`. I don't think it really makes sense to have `--scope` extend the results of `--since`, but I could be wrong.

**Comment by evocateur** [comment]
Ooh, I bet the (horrifically-named) `--force-publish` flag might be what you're looking for, instead of `--scope`? It seems to do the trick in my local testing:

```
$ lerna exec --since master --scope unchanged-pkg -- echo \$LERNA_PACKAGE_NAME
changed-pkg

$ lerna exec --since master --force-publish unchanged-pkg -- echo \$LERNA_PACKAGE_NAME
changed-pkg
unchanged-pkg
```

It's not really documented anywhere, and it really should be named `--force`. It's a very complex option, allowing for boolean, string, or a list of string arguments (the strings are globs, just like scope/ignore).
```bash
--force-publish # equivalent to "*", which is all packages
--force-publish=*
--force-publish=foo
--force-publish=foo,bar # equivalent to the next line
--force-publish foo --force-publish bar
```

**Comment by vzaidman** [comment]
Thank you very much. It solves my problem.

But, maybe we should be renamed to `--extend-scope` and also work with extending the `scope` argument that overrides it for the moment.

**Comment by evocateur** [comment]
I think `--force` is a better description of what it is doing, and only applicable in the context of `--since`. It's such an extreme edge case to scope `--since`, I'm almost tempted to make them exclusive options. Either you're filtering packages with changes since `<ref>`, or you're filtering packages by name globs.

We expect `--since <ref> --scope <pkg>` to be a no-op if `<pkg>` has not changed since `<ref>`, which seems a reasonable expectation given the semantics of the flags. `--scope <pkg> --force <pkg>` doesn't make sense.

**Comment by vzaidman** [comment]
`--force` usually overrides other configs. it's really counter intuitive that it **extends** since and not overrides it.

**Comment by evocateur** [comment]
You're forcing the argument (a glob) to also be included in the filtered packages, regardless of other constraints. This is an edge case.

**Comment by vzaidman** [comment]
so `--force-include` maybe
