### ISSUE TITLE
Question: How to provide chain commands in lerna exec

### ISSUE THREAD

**Issue by nareshbhatia** [lerna/lerna#1354]
I would like to delete the `dist` folder in every package before building it. The following script does not work:

    "build": "lerna exec --parallel -- del-cli dist && babel src -d dist --ignore test.js",

> lerna info version 2.9.0
lerna info versioning independent
lerna info exec in 2 package(s): del-cli dist
src doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! sharing-components-with-lerna-part-1@1.0.0 build: `lerna exec --parallel -- del-cli dist && babel src -d dist --ignore test.js`
npm ERR! Exit status 2

What's the best way to chain these commands?

**Comment by evocateur** [comment]
The simplest way is to split them up (the problem is the `&&`, which isn't considered part of the `lerna exec` command, but a separate command entirely).

```
  "prebuild": "lerna exec --parallel -- del-cli dist",
  "build": "lerna exec --parallel -- babel src -d dist --ignore test.js"
```

In _theory_, you might be able to escape the `&&` so it gets added to the `--`-trailing args, but for clarity I would just split up the phases.

**Comment by nareshbhatia** [comment]
@evocateur, thanks for the workaround. Works like a charm!

Would be good to think of a more robust solution for general use cases.
