### ISSUE TITLE
How to generate first changelogs ?

### ISSUE THREAD

**Issue by bertho-zero** [lerna/lerna#1361]
First of all hi and thank you,

I use lerna for a short time and I would like to generate the conventional changelogs automatically, it works well but how to overload the config of the [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) to be able to run once `lerna publish --skip-git --skip-npm` to generate the changelogs since the creation of the repo?

The [`releaseCount`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-core#releasecountasecount) option of the [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) to 0 would do this job.

**Comment by bertho-zero** [comment]
The `since` option of the `publish` command does not seem to be passed to the `conventional-changelog` call.

**Comment by evocateur** [comment]
If you want to backfill changelogs, I would just use [`conventional-changelog-cli`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli#quick-start) directly. You could even use `lerna exec` to run it in all packages:

```
npm i -D conventional-changelog-cli

npx lerna exec --concurrency 1 --no-sort --stream -- \
  conventional-changelog \
    --preset angular \
    --infile CHANGELOG.md \
    --same-file \
    --release-count 0 \
    --lerna-package \$LERNA_PACKAGE_NAME \
    --commit-path \$PWD

npm rm conventional-changelog-cli
```

(escaping the env vars is important, otherwise they'll be evaluated too early, e.g., `$PWD` will be the root directory, not the package directory)

> The since option of the publish command does not seem to be passed to the conventional-changelog call.

`--since` is not a valid option for `lerna publish`. That it _happens_ to work right now is a bug.

**Comment by evocateur** [comment]
@ashoksudani If you're using lerna, `lerna version --conventional-commits`. If not, use the conventional-changelog CLI that I linked and demonstrated earlier in this thread.
