### ISSUE TITLE
process.env.npm_config_user_agent is not defined when running lerna gloablly

### ISSUE THREAD

**Issue by mndewitt** [lerna/lerna#1369]
@evocateur  In the recent code I added to run bootstrap with `npm ci`, we added a check for the npm config user agent.  I've found that if I have lerna installed globally and run it, `process.env.npm_config_user_agent` is undefined, so `npm ci` will never get called.  However, if I install lerna as a devDep and run as an npm script, the variable is defined and things work as expected.  I also checked `process.env.NPM_CONFIG_USER_AGENT` and that is also globally undefined.

I'm wondering if it makes sense to account for those that have lerna installed globally?  Is it always recommended to install lerna as a devDep and run it with an npm script?  If we should be accounting for it, how would we check the npm user agent from a global terminal?

**Comment by evocateur** [comment]
`lerna` should always be a dev dependency. Probably shouldn't _require_ running from a lifecycle script, to account for `npx lerna`, etc. That being said, CI should be running lifecycle scripts anyway...

**Comment by evocateur** [comment]
We could certainly call `npm config get user-agent`, I guess, but I'd rather not, since a global `lerna` really isn't expected to be used for anything but `lerna init` (itself a command of dubious value).

We already have an npm conf object available in bootstrap's initialize method, we should pass that in instead of reading it directly from `process.env`. Otherwise, it's just going to fail when you try to use a globally-installed lerna. "Fail" in the sense that it... works? But just not as fast...
