### ISSUE TITLE
Changelog labels is ignored

### ISSUE THREAD

**Issue by bertho-zero** [lerna/lerna#1375]
Since the version `v3.0.0-beta.0` the labels from lerna config is ignored in https://github.com/lerna/lerna/blob/master/CHANGELOG.md

https://github.com/lerna/lerna/blob/5e462676b3793b8d4981fc7f8b81af2fc839adf7/lerna.json#L7-L16

**Comment by evocateur** [comment]
Yeah, because we're no longer using [lerna-changelog](https://github.com/lerna/lerna-changelog), which that config is meant to address. I guess we could make a new [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) preset to replicate the decorations, but it's honestly not very high on my priority list.
