### ISSUE TITLE
[Feature] Using Lerna Locally

### ISSUE THREAD

**Issue by thejameskyle** [lerna/lerna#138]
I want to encourage people to run lerna locally, but it's kinda annoying using a CLI based tool with tons of commands locally (you end up aliasing all of them to npm scripts or something else and no gross)

So instead I want to make it so that the global `/usr/bin/lerna` will run the local `./node_modules/.bin/lerna` if it exists.

It'd be nice if this could work independently of versioning, so any version of the global CLI can run any version of the local CLI.

I'm considering just making this another package `lerna-global` that is super dumb: (pseudo code)

``` js
require('child_process').exec(process.argv.slice(1).unshift('./node_modules/.bin/lerna'));
```

**Comment by thejameskyle** [comment]
https://github.com/timoxley/npm-run

**Comment by scriptjs** [comment]
I am wholeheartedly behind running locally but in the way all other modules currently work instead of any tricks with 'usr/bin'. Personally, I dislike -g with anything node and avoid preferring anything global.

I don't use `/usr/bin` at all when I must install something global. bins from global installs are instead executed from  `/.local/bin`. Global installs do not need sudo in this case. Like many that develop commercially, we rely on sinopia/verdaccio. The npm client is often upgraded more often than node.

**Comment by thejameskyle** [comment]
I want to encourage as many people to install locally as possible. I wouldn't mind having a separate `lerna-cli` package just to push people in the right direction. Other packages like gulp have had success doing this.

**Comment by scriptjs** [comment]
@thejameskyle babel-cli also

**Comment by thejameskyle** [comment]
babel-cli doesn't resolve to the local version if you have one installed, it depends on babel-core itself

**Comment by tjbenton** [comment]
All you have to do is add `./node_modules/.bin` or `$(npm bin)` to your `PATH` in your bash files. I know this works quite well for mac, because I've been using it for a couple of years and it's allowed me to not install any global dependencies for my projects.

Here's how to add it to your path in your dot files

```sh
PATH=./node_modules/.bin:$PATH # adds locally installed node modules to the path
export PATH
```

You can also make an [function](http://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules) for it if you don't like messing with the path

```sh
function npm-exec {
   $(npm bin)/$@  
}
```


If you're using a `Makefile` You can put this at the top of it and that also adds it to your path.

```make
PATH := $(npm bin):$(PATH)
SHELL := /bin/bash
```

So the following would work 

```make
bootstrap:
	lerna bootstrap
```


I don't use windows but I asked a co worker who does to look into it. So I will update this if he comes up with anything.

**Comment by thejameskyle** [comment]
I don't want people messing around with there bash config

**Comment by evocateur** [comment]
`ava`'s pattern [here](https://github.com/avajs/ava/blob/ad5122d507bfaa044fc3a2e51e467238e16dba11/cli.js#L7-L16) looks really nice. Wouldn't even need that many changes to make work with our patterns.

**Comment by NMFR** [comment]
Don't know if it will help but you can not have it installed globally:

- Install it as a dev dependency.
- Add lerna as a script in package.json:
  ```
  {
    ...
    "scripts": {
      "lerna": "lerna"
    }
  }
  ```
- Call it locally with npm:
  ```
  npm run lerna -- --help
  ```
  or
  ```
  npm run lerna -- init --exact
  ```

Any arg after `--` will be passed to lerna.
