### ISSUE TITLE
`lerna run` in order

### ISSUE THREAD

**Issue by mistic100** [lerna/lerna#1424]
## Expected Behavior

`lerna run` should/could be executed in the order defined be the dependencies between packages.

## Current Behavior

`lerna run` is executed in alphabetical order

## Steps to Reproduce (for bugs)

I have the following packages :

- build (no dependency)
- calendar (depends on build and core)
- core (depends on build)

If I execute `lerna run build` the packages are built in alphabetical order, thus it fails when building "calendar" because "core" has not been built yet.

Somehow I imagine lerna knows the dependencies tree, so it would be cool to be able to execute `run` (and `exec`) in the order of the tree.

<details><summary>lerna.json</summary><p>

```json
{
  "version": "0.0.0-SNAPSHOT",
  "npmClient": "yarn",
  "lerna": "2.11.0",
  "useWorkspaces": true,
  "packages": [
    "packages/*"
  ]
```
</p></details>

<details><summary>package.json</summary><p>

```json
{
  "version": "0.0.0-SNAPSHOT",
  "scripts": {
    "build": "lerna run build"
  }
```
</p></details>

<details><summary>packages/build/package.json</summary><p>

```json
{
  "version": "0.0.0-SNAPSHOT",
  "scripts": {
    "build": "something"
  }
```
</p></details>

<details><summary>packages/core/package.json</summary><p>

```json
{
  "version": "0.0.0-SNAPSHOT",
  "devDependencies": {
    "@sglk-common/build": "0.0.0-SNAPSHOT"
  },
  "scripts": {
    "build": "something"
  }
```
</p></details>

<details><summary>packages/calendar/package.json</summary><p>

```json
{
  "version": "0.0.0-SNAPSHOT",
  "dependencies": {
    "@sglk-common/core": "0.0.0-SNAPSHOT"
  },
  "devDependencies": {
    "@sglk-common/build": "0.0.0-SNAPSHOT"
  },
  "scripts": {
    "build": "something"
  }
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 5.3.0 |
| `yarn --version` | 1.6.0 |
| `node --version` | 6.14.1 |

Thank you

**Comment by mistic100** [comment]
I just saw the documentation about the `--no-sort` flag. So the behaviour I am experiencing is probably a bug.

I'll try to create a minimal test case.

**Comment by doug-wade** [comment]
@mistic100 any luck creating a minimal repro repo?

**Comment by doug-wade** [comment]
Thanks for getting back to us @mistic100!

**Comment by doug-wade** [comment]
@mistic100 `yarn run build` works in any given module directory because lerna is horking on understanding the dependency graph -- which order to run the script on the modules.  `yarn run build` doesn't provide this functionality, so it doesn't exhibit the behavior.  Put another way, `yarn run build` and `lerna --scope="calendar" run build` works as expected, the same as `yarn run build` in calendar, so there is feature parity.  Does this make sense?

One way to address this is to use [canary releases](https://github.com/lerna/lerna#--canary--c), which use the semver version plus the SHA of the package to distinguish it from other versions, rather than a date.  This allows lerna to understand the dependency graph (since its semver compliant), but also allows you to have the same properties as the continuous deployment pattern.  To find the most recent build, you'd check the `latest` tag; to find a version from a specific date/time, you would use the output of `npm show calendar` to find the dates associated with canary versions.
