### ISSUE TITLE
Need explanation about stream and lerna run (for dependency compilation/typescript)

### ISSUE THREAD

**Issue by appsolutegeek** [lerna/lerna#1428]
Hi,

Previously I was using --parallel to run my commands to compile typescript in the order in which they are dependent but then realised the parallel doesn't do that :-) So my projects were attempting to compile when their dependencies hadn't finished compiling - so I was getting errors in some projects.

So I then ran the "lerna run" without -parallel which seemed to work correctly, running everything in order (I assume the --sort isn't needed here ??? This is the default ??). The only problem here is that I didn't get a nice prefixed package name that --parallel offered me, so if it errored it was quite confusing of where the error happened.

I then found the --stream, which seems to give me the prefixing that was given with --parallel. Although I am little confused, does stream wait on dependencies? i.e. if ProjectA depends on ProjectB, is there a risk my command (tsc) will run in ProjectA before the command has exited in ProjectB?

I am little confused on what --stream does - can anyone elaborate, I did check the documentation but I still don't have a complete understanding.

And finally, would it be possible to "prefix" each command using just the standard "lerna run ...." without passing stream/parallel ??

Thanks in advance

**Comment by doug-wade** [comment]
Hi @appsolutegeek!  I'm sorry to hear this has been confusing for you; I hope I can clear things up.  

You are correct that `--sort` defaults to true.  It doesn't seem to be documented in the README; we should add that.

The package prefixing is not present when you run `lerna run` without parallel or stream because it is not needed.  We buffer the output of each of the child processes (we start up to 4 processes by default, but you can change this using [--concurrency](https://github.com/lerna/lerna#--concurrency)), and then emit all the logs for one package all at once.  We output the name and path of the package before the contents of stderr and stdout, so rather than looking for the prefix, you should scroll up and look for a header.  

Streaming the logs (using --stream) and running them in parallel (with --parallel), on the other hand, prefix the logs with the package name because the logs are interleaved.   That is, you can have log lines from package A, then from package B, then from package A again.  Because of this, there is no way for you to know which package any given log line comes from (unlike `lerna run`, which emits all the logs for one package, then all the logs with another, with a header that indicates which package its from).  Parallel execution streams the logs because we spin up one process per package and runs them all at once; for customers like Babel with ~150 packages, buffering the output of stdout and stderr would wreck havoc on most systems.

I'm going to leave this one open since it seems we need to improve our documentation.  If my answer clears things up for you @appsolutegeek and you have some extra bandwidth, I'd be more than happy to help you submit a PR to update the documentation with a better explanation.

**Comment by appsolutegeek** [comment]
Thanks @doug-wade

**Comment by appsolutegeek** [comment]
@doug-wade Actually, i passed in --concurrency 1 to --stream, so I got the nice colours for each stream but as far as I can see it only calls them one after another which is what i wanted.

**Comment by doug-wade** [comment]
I'm glad to hear you found a solution!  I'm going to close this since it seems its resolved; if that is not the case, feel free to reopen.
