### ISSUE TITLE
feat: lerna command to change the file-specifier in package.json to version number and back again.

### ISSUE THREAD

**Issue by reggi** [lerna/lerna#1430]
I am interested in publishing to the default `npm` registry and a private one one after another. How can I do this? When I run `lerna publish` it will update all the version numbers. I'd like for it not to do that and simply publish the version numbers once.

```
npm config set registry https://registry.npmjs.org
lerna publish
npm config set registry https://registry.custom.com
lerna publish --cd-version=none
```

Is this possible?

**Comment by doug-wade** [comment]
What are you trying to accomplish?  I've had the most success using my private or internal registry as a passthrough to the public registry when the module is not found in the internal registry, but returns the package from the internal registry when it is present.  I'm interested to know what you're doing where you want something in the public registry, but there is also value to having it in the internal registry, and seeing if we can do something else (like a proxy or something, rather than a lerna change).

The one approach you could consider is writing a `release` script and running that instead of publish.  E.g., you would have release run `npm publish --registry="registry1" && npm publish --registry="registry2"`, and then use `lerna run release` instead of `lerna publish`.  This would lose you versioning and filtering what will be published to only those packages that have been changed, but I guess it would work.

**Comment by reggi** [comment]
Hey @doug-wade I am in a icky-situation. This month one package in my mono-repo published to `npm` successfully but it isn't retrievable when you install it at the latest version number. I wrote about the whole thing here: https://gist.github.com/reggi/de7a27ad56110c32ee66a73b647d2abd. It is confirmed an issue with `npm`, and is a bug on their end. I'd like to have a private registry that acts as a backup / override for these cases. 

It is kind of crappy that this happened because I am delayed now by almost a month and I am waiting for `npm` to fix this issue, I have kind of lost faith that `npm` can reliably version and maintain my code. I'd like to publish to a private registry and `npm` so that ideally when then fix the issue I can use `npm`. 

Is there no command that publishes without updating version numbers? That's all I'd need.

**Comment by reggi** [comment]
Hey @doug-wade this is a great write up, thank you very much!

I am facing one issue with publishing using `exec`. I have `file://` specifiers in my monorepo. Using publish they resolve to the latest version. I need a way to resolve them and unresolve them via a command. Any ideas on how to do that or should I just create my own command?

Resulting in this `rectify-version` command (that doesn't exist yet) just an idea.

```
lerna exec --bail=false -- rectify-version --latest && npm publish && rectify-version --file-specifer
```

Is this crazy? Should this be it or am I missing something else?

**Comment by reggi** [comment]
I am down to make this package.json version swapping command but it seems like lerna does internally. Any way we can make this public?

**Comment by doug-wade** [comment]
Here's the [interesting part](https://github.com/lerna/lerna/blob/3574466560f600828a0f288cec8d137a21404f15/commands/publish/index.js#L223) of the publish command.  It is undocumented; my understanding was that we intend to keep it that way until 3.x becomes `latest`.

**Comment by reggi** [comment]
@doug-wade I made the cli tool to convert the package file-specifier to version and back again.

```js
npm i @reggi/dep-pointer-cli --registry https://reggi.registry.com/
```

Should be up on `npm` and github in a couple of days, the `exec` script totally worked to publish to my private registry. Thanks for the help!
