### ISSUE TITLE
Unlinkl/Unbootstrap for deployment ?

### ISSUE THREAD

**Issue by appsolutegeek** [lerna/lerna#1431]
Hi,

Maybe I am missing something here or maybe my workflow is incorrect, would love to hear some comments.

1. My CI Server downloads repo, and does lerna bootstrap to hook up all the symlinks.
2. CI server, runs a publish.
3. Ready for deployment and I need to Zip up the files for the deployment (this is my api and ui, all libraries have already been published with the step above)
4. The problem here is that the symlinks are still in affect as I did a lerna bootstrap previously. How can I do a unlink / unbootstrap ? I need the correct files inside node_modules so that I can package up my app.

The other thing that I don't have correct in my head is that I was using yarn workspaces, so everything is inside the root, but on deployment does it not make sense to have everything in its own node_modules rather than hoisting / workspaces ? Otherwise i need to publish the whole node_modules for the deployment. This does make sense when development but for deployment I don't think it does - anyone have any ideas ?

I know learn isn't really for deploying, I have seen it mentioned a few times but i would welcome any info with regards to the right workflow or the questions I raised above.

Thanks in advance

**Comment by doug-wade** [comment]
You'll need to write a deploy script; as you mention, lerna is not a deploy tool.  Here's [one](https://github.com/doug-wade/yodel/blob/master/scripts/deploy) you might be able to read through to get an idea of how such a deploy script might work.  Note, in particular, that I blow away node_modules, tar up the sources, scp the tarball to the host, untar it and run `npm install --production` -- since you've published all your libraries, there's no need for symlinks at that point.

Hope that helps.

**Comment by j** [comment]
It's so interesting that so many people want this as a feature but it still remains for libraries.
