### ISSUE TITLE
Correct way to use conventional-commits and canary / prerelease

### ISSUE THREAD

**Issue by GordonSmith** [lerna/lerna#1433]
## Question
Made the switch to use conventional-commits and am trying to work out the "correct" way to do a beta or rc release.  My instinct was to do a:
```
lerna publish --exact --conventional-commits  --preid=beta
```
Or
```
lerna publish --exact --conventional-commits  --canary=beta
```
But neither appear to do what I would expect?

**Comment by robertrossmann** [comment]
I experienced this behaviour as well. To complement this issue:

When running

```
lerna publish --conventional-commits --canary=beta
```

### Expected behaviour

- The packages' versions are calculated based on the conventional commits' strategy. These versions are then published to the provided tag with the commit ID appended as expected.
- When new canary release is to be published, the new versions should still match conventional commits's strategy, but they should compare the previous `@latest` tag when deciding on the new version. In other words, if I previously published a canary release with semver-minor changes and I publish another release only containing semver-minor changes, I should not have the package version bumped again.
- If I previously published a semver-minor canary release and now attempt to publish another canary release containing a semver-major change, the package's version should be bumped to the next semver-major version.

### Current behaviour

- The packages' versions are bumped to the next semver-minor version regardless of what changes have been introduced since the last release. The `--conventional-commits` flag seems to have no effect on the release process.

**Comment by evocateur** [comment]
`--canary` and `--conventional-commits` are completely separate code paths.

To control the version bump of `--canary`, pass `--cd-version <keyword>` (`keyword` defaults to "minor" when using `--canary`).

**Comment by robertrossmann** [comment]
@evocateur That is, unfortunately, not a viable option in independent versioning scheme as the version bump would be different for each package, depending on the contents of individual commits (due to `--conventional-commits`).

In my opinion, the current behaviour of this flag's combo is unintuitive, at least. It would be best if they could be somehow aware of each other, and if that is not something the project's maintainers are interested in, perhaps the docs could be made a bit more explicit about this...?

Thanks!

**Comment by evocateur** [comment]
Oh, I know. The two flags aren’t meant to interact, and should probably throw an error or at least warn loudly? PRs to improve the documentation are always welcome!

**Comment by GordonSmith** [comment]
@evocateur What about ```lerna publish --exact --conventional-commits  --preid=beta```, what is the expected behavior there?

I know that both the examples I gave above don't do what I would expect and I was just reaching out to see if any folks had a working process for releasing a "rc" build while using `conventional-commits` (I don't mind doing some manual stuff!!!

**Comment by evocateur** [comment]
Lerna itself does conventional commits with a preid (beta, right now). Exact should be fine, though not really necessary in my experience.

The major difference between that arrangement and canary is that canary does not make any commits, and conventional commits etc always does. Non-canary is not presently very well-suited for CI publishing, for this reason.

**Comment by sgendler-stem** [comment]
The previous comment says Lerna does conventional commits with a preid, but I'm not seeing that.  I branched, made a one line change to a single package, and executed

```
lerna publish --conventional-commits --yes --independent --skip-git --preid=sandbox
```
 and it bumped the patch for everything dependent on that single package, and it bumped the minor version of the package itself (my commit message was 'feat(scope): message' so that is correct), but there was no pre-release tag of any kind applied to any of those versions.  Not 'beta' and not the --preid I specified.  I could find nothing in the conventional commits documentation which suggested a mechanism to force a prerelease via the pull request text or anything else, so I can't figure out how to get a pre-release tag on anything, let alone a user-specified one.  What am I missing?  What I really want is for --preid to be '<label>.<git revision>' so that multiple pull requests don't result in published version conflicts if they both use the same label.  The short git revision should still differentiate the versions.  I have a mechanism to pass the git revision into my publish command, but I do need the publish command to actually pay attention to it.  At the moment, it does not appear to.  

Also, the statement by @evocateur that conventional commits always commits changes doesn't seem to be try.  When I specify --skip-git, it does exactly what I want.  If it also obeyed --preid, it would work exactly as I need it to.  I'm not sure what the argument against that is.  Why wouldn't someone want to be able to do a pre-release of a package with conventional commits?

```
yarn run v1.6.0                                                                                   
$ yarn run lerna publish --conventional-commits --yes --preid=sand --independent --skip-git       
$ /.../.bin/lerna publish --conventional-commits --yes --preid=sand --independent --skip-git                                                                
lerna info version 2.11.0                                                                         
lerna info versioning independent                                                                 
lerna info Checking for updated packages...                                                       
lerna info Comparing with v3015.2.0-6.                                                            
lerna info Checking for prereleased packages...                                                   
                                                                                                  
Changes:                                                                                          
 - @private/lib-common: 1.1.0 => 1.1.1                                                               
 - @private/lib-content: 1.1.0 => 1.1.1                                                              
 - @private/lib-ddex: 1.1.0 => 1.1.1            
 - @private/lib-ddex: 1.1.0 => 1.1.1                                                                 
 - @private/lib-entities: 1.1.0 => 1.1.1                                                             
 - @private/lib-etcd: 1.1.0 => 1.2.0                                                                 
 - @private/lib-job: 1.1.0 => 1.1.1                                                                  
 - @private/lib-log: 1.1.0 => 1.1.1                                                                  
 - @private/lib-migrations: 1.1.0 => 1.1.1                                                           
 - @private/lib-performance: 1.1.0 => 1.1.1                                                          
 - @private/lib-supply-chain: 1.1.0 => 1.1.1                                                         
 - @private/lib-utils: 1.1.0 => 1.1.1                                                                
 - private-api: 1.1.0 => 1.1.1 (private)                                                             
 - private-orchestrator: 1.1.0 => 1.1.1 (private)                                                    
 - saml-auth: 1.1.0 => 1.1.1 (private)                                                            
 - private-super-api: 1.1.0 => 1.1.1 (private)                                                       
 - @private/infra-environments: 1.1.0 => 1.1.1 (private)   
 - @private/infra-templates: 1.1.0 => 1.1.1 (private)                                                
                                                                                                  
lerna info auto-confirmed                                                                         
lerna info publish Publishing packages to npm...                                                  
lerna info published @private/lib-log                                                                
lerna info published @private/lib-etcd                                                               
lerna info published @private/lib-migrations                                                         
lerna info published @private/lib-entities                                                           
lerna info published @private/lib-ddex                                                               
lerna info published @private/lib-content                                                            
lerna info published @private/lib-utils                                                              
lerna info published @private/lib-performance                                                        
lerna info published @private/lib-job                                                                
lerna info published @private/lib-supply-chain                                                       
lerna info published @private/lib-common      
Successfully published:                                                                           
 - @private/lib-common@1.1.1                                                                         
 - @private/lib-content@1.1.1                                                                        
 - @private/lib-ddex@1.1.1                                                                           
 - @private/lib-entities@1.1.1                                                                       
 - @private/lib-etcd@1.2.0                                                                           
 - @private/lib-job@1.1.1                                                                            
 - @private/lib-log@1.1.1                                                                            
 - @private/lib-migrations@1.1.1                                                                     
 - @private/lib-performance@1.1.1                                                                    
 - @private/lib-supply-chain@1.1.1                                                                   
 - @private/lib-utils@1.1.1                                                                          
lerna success publish finished     

```

That is 100% correct EXCEPT for the missing prerelease suffix on the version numbers.

**Comment by sgendler-stem** [comment]
It certainly does SEEM like it shouldn't be that difficult to integrate --preid with the conventional commit recommended versions, since it seems like you could just add it as a suffix with a hyphen and call it good, but I'm guessing that there's going to be complexity added if doing a second pre-release publish, since that might end up with -suffix1-suffix2.  It's too late in my day to try to unwind all of that logic and figure out the best way to specify the preid such that it actually gets passed to the semver library when the version is incremented, rather than doing a dumb string-append to semver's output, but this seems like it would go a long way toward making CI auto-publish workable.

My intended workflow is as follows:

Developer submits pull-request to release branch with update.
  * trigger pre-release publish via conventional commits to increment versions correctly, but add a pre-release suffix of label.short_commit_hash.  
  * build docker images of pre-release services which depend on pre-release packages via npm install
  * push docker image to repo with tag service-version, which is now next {semver}-{label}.{short_commit_hash}
  * update sandbox infrastructure to run image:{semver}-{label}.{short_hash}
  * launch integration test image.  When it completes successfully, it trips a webhook that merges the pull request (or just approves it).

Developer pushes changes to release branch (merges PR):
  * trigger release publish via conventional commits to increment versions correctly and publish to npm
  * build docker images of services, which depend on released packages
  * push docker image to repo with tag service-version, which is now next {semver}
  * update staging infrastructure to run image:{semver}
  * launch integration test image.  When it completes successfully, trip a webhook that asks for release approval.

Release is approved
  * update prod infrastructure to run image:{semver}

For now, I can modify my workflow to build the sandbox versions entirely from local monorepo packages and skip NPM for sandbox testing entirely.  But that means I cannot exercise the npm publish process or build service images via npm install until I am pushing a production release to staging, which is a drag, since those things can break, too.  It would be MUCH better to be able to specify a pre-release suffix when using conventional commits.

**Comment by pantoninho** [comment]
I am experiencing the same issue as @sgendler-stem.

Using `--preid` with `--conventional-commits` results in a correctly bumped version number (according to conventional commits spec), but the preid is not appended to the version number.

I've also tried your tip @evocateur without success.

running one of these:
`lerna version prerelease --conventional-commits` || `lerna version --cd-version=prerelease --conventional-commits`

results in a wrongly bumped version number according to conventional-commits spec (it is always a PATCH).

Having `--preid` work well with `--conventional-commits` would be a killer feature for me.

**Comment by evocateur** [comment]
Basically, an explicit `prerelease` bump will always override the version recommended by conventional commits. The `prerelease` keyword is equivalent to the `prepatch` keyword as far as `semver` is concerned. There is no affordance for prereleases with vanilla conventional commits as far as I can tell, and Lerna is just calling the conventional-changelog API.

**Comment by pantoninho** [comment]
Yes, that is what I initially thought, I was just following your tip above my comment.

To be more clear, what I really wanted for lerna to do is something like OP mentioned.

Imagine I have a package at `0.0.1`. After a `feat` commit, `lerna version --conventional-commits` would upgrade  it to `0.1.0` as it should. If I used `lerna version --preid=beta --conventional-commits` instead, I would expect it to bump it correctly to `0.1.0` (due to the `feat` commit), and then add the `preid` tag, making it `0.1.0-beta.0`.

If I kept doing `feat` or `fix` commits, and bumping with `lerna version --preid=beta --conventional-commits`, it should only increment the `beta` version (e.g. `0.1.0-beta.1` -> `0.1.0-beta.2`, ...etc).

Eventually the release would be ready, and I would just use `lerna version --conventional-commits`. I would expect the `preid` tag to be removed, finally upgrading it to `0.1.0`.

There's also a chance there's a breaking change while publishing prereleases: If package version is `0.1.0-beta.2` and a `breaking change` commit is done, I would expect `lerna version --preid=beta --conventional-commits` to upgrade it to `1.0.0-beta.0`.

Right now, `--preid` gets ignored when using `--conventional-commits`.

**Comment by evocateur** [comment]
Because conventional commits has no concept of an automatic prerelease. `prerelease` is a specific semver convention that lerna applies, always overruling the version bump suggested by `--conventional-commits`.

**Comment by Martaver** [comment]
The workflow that @pantoninho describes is the correct behavior for combining conventional-commits with prereleases. Lerna should be updated to behave in this way.

I also intuitively thought that `lerna version prerelease --conventional-commits` would calculate the correct semver based on commit msgs, and then simply append & subsequently increment the preid - but unfortunately it just does a patch.

**Comment by pantoninho** [comment]
@evocateur maybe I did not explain myself correctly.

I need lerna to be able to guess the next version according to conventional commits specification and also add a preid tag on the version.
I had a look on the source code but I'm very unfamiliar with the project in order to know where to start.

I've found out that on `commands/version/index.js:223`, preid gets completely ignored on that branch:
```
 } else if (conventionalCommits) {
      // it's a bit weird to have a return here, true
      return this.recommendVersions();
}
```

**Comment by hedgepigdaniel** [comment]
> Because conventional commits has no concept of an automatic prerelease. prerelease is a specific semver convention that lerna applies, always overruling the version bump suggested by --conventional-commits.

Hmm, is it possible to use the normal logic from conventional commits to determine the expected bump (without preids), and then add the preids on after?

> There's also a chance there's a breaking change while publishing prereleases: If package version is 0.1.0-beta.2 and a breaking change commit is done, I would expect lerna version --preid=beta --conventional-commits to upgrade it to 1.0.0-beta.0.

I would like to have CI running automated releases with alpha releases on one branch e.g. `next`, stable releases on another e.g. `master`. The way @pantoninho described, this would work well. There would be two steps:

1. Merge changes to `next`. Have automated pre releases with preid of say `beta`, and with the appropriate version bump based on the changes since the last stable release (according to conventional commits). Debug any issues with version numbers.
1. Merge changes from `next` to `master`. Have an automated stable release. The version number would be the same as the latest `beta` release, but without the `-beta.n` postfix.

The way it is, if the package was at `0.1.0`, and I push a commit with a breaking change to `next`, then the pre release version that gets published is `0.1.1-beta.0`. But if I push the same commits to `master`, I'll end up with a surprise `1.0.0` release!

**Comment by hedgepigdaniel** [comment]
This also leads to the undesireable situation where the type of version bump depends on the history of pre releases. Consider the following two alternative timelines, where the same series of code changes is made, but with different prereleases:

### Without prereleases :+1:

1. Start with version 0.1.0
1. Commit `feat: support apples in addition to oranges`
1. Run `lerna publish --conventional-commits` to release `0.2.0`

### With pre-releases :confused:
1. Start with version `0.1.0`
1. Commit `feat: support apples in addition to oranges`
1. Run `lerna publish prerelease --conventional-commits --preid beta --dist-tag beta` to release `0.1.1-beta.0`
   - :warning: As has already been pointed out, the prerelease `0.1.1-beta` should really have been `0.2.0-beta.0`, since it contained a new feature relative to the last stable release
1. After testing the beta release run `lerna publish --conventional-commits` to graduate the release to `0.1.1`
   - :warning: A more serious problem: The stable release `0.1.1` (made after a prerelease) contains a new feature relative to `0.1.0`, but it is only a patch bump! The same problem exists for breaking changes.

**Comment by evocateur** [comment]
@jenniesyip Thanks so much for the detailed analysis! I reopened this issue and added a tag that tells the bot to stay away, sorry about that.

I'm a bit busy at work right now, but I hope to circle back by the end of the week. Much food for thought.

**Comment by erquhart** [comment]
@jenniesyip I raised #1991 to resolve the issues you've laid out, can you read through the OP and let me know if it seems in line with your use case?

**Comment by jenniesyip** [comment]
@erquhart Sorry for the super late reply (so much work to do!)... this looks **amazing** so far! 🎉 ❤️

**Comment by customcommander** [comment]
I'm having a similar issue with Lerna 3.20.2; see my post on [Stack Overflow](https://stackoverflow.com/q/61144530/1244884)

**Comment by miszo** [comment]
@customcommander, did you tried to use flags `--conventional-prerelease` and --conventional-graduate`?
Now I'm testing it at work and it seems to work fine.

**Comment by customcommander** [comment]
@miszo Hey thanks for your comment but it didn't work.

When I run

```
npx lerna publish --conventional-commits --conventional-prerelease --yes 2>/dev/null
```

Then Lerna asks which bump should occur; therefore the conventional commits specification is therefore ignored.

When I had `--conventional-graduate` to that command, Lerna doesn't do anything!

**Comment by amaralc** [comment]
> @customcommander, did you tried to use flags `--conventional-prerelease` and --conventional-graduate`? Now I'm testing it at work and it seems to work fine.

This worked just fine for me.
