### ISSUE TITLE
"package.json does not exist", but it does (with a syntax error)

### ISSUE THREAD

**Issue by rtm** [lerna/lerna#1452]
```
$ lerna bootstrap
lerna info version 3.0.0-beta.20
lerna ERR! ENOPKG `package.json` does not exist, have you run `lerna init`?
$ ls -l package.json
-rw-rw-r-- 1 rtm rtm 807 Jun  6 13:15 package.json
```

Why would something like that happen? Actually, it happens when there was a typo in `package.json`.

**Comment by evocateur** [comment]
It's weird, there is [code](https://github.com/lerna/lerna/blob/1f885f1288f58da6e59261ac6c859f2507f12e3b/core/project/index.js#L46-L49) specifically designed to catch syntax errors in the package.json file...

Oooh, I bet it's the [upgrade](https://github.com/lerna/lerna/commit/9acde7d016e0bc4b341bf947fefd9d5c8f32f51c) of cosmiconfig. I didn't make any effort to persist the `rcStrictJson` config, and that's probably swallowing the syntax error due to a more lenient parser. In combination with lacking a lerna.json file, possibly?

**Comment by rtm** [comment]
@evocateur Thanks for following up. No, there was a lerna.json file. FWIW the syntax error was two consecutive commas.

**Comment by evocateur** [comment]
Well, after failing to reproduce by adding tests, it occurs to me that the `manifest()` getter is indeed swallowing the syntax errors when there is a valid lerna.json (cosmiconfig never gets to it, as it searches for lerna.json first).

I think I have a fix.

**Comment by jaredh159** [comment]
I got this same error after changing the `"name"` field of my root `package.json` _from_ `"root"` to something else.  Switching it back fixed things.
