### ISSUE TITLE
Question: how to generate package-lock.json per-package when switching to npm

### ISSUE THREAD

**Issue by MatthewHerbst** [lerna/lerna#1462]
We have a Lerna mono-repo in a structure such as:

```
/
  /packages
    /package1
    /package2
    /package3
    ...
```

We currently use Yarn, but would like to switch back to npm.

We have a `yarn.lock` file at the root of our mono-repo, but do not have per-package `yarn.lock` files since we never enabled Workspaces. When moving to npm, we would like to ensure that we have per-package `package-lock.json` files, which properly mark devDependencies with `"dev": true`.

I have not been able to find a way to generate these files.

What I've tried:

Attempt: `npm run lerna boostrap --hoist`
Outcome: `package-lock.json` generated at the top-level only (maybe this is expected due to the `--hoist`?), but, with no `"dev": true` tags. Also, it includes no local packages (again, not sure if this is expected or not).

Attempt: `cd packages/package1 && npm install`
Outcome: install fails because `npm` does not know how to find a local package

Attempt: `npm run lerna add express --scope=package1`
Note: `package1` already has `express` in its `package.json`
Outcome: `package-lock.json` files are added for all packages except `package1`. Further, these files do not mark devDependencies with `"dev": true`, and, do not include local packages (which I assume they should, but correct me if I'm wrong about that)

I was expecting that when I ran `npm run lerna boostrap --hoist` it would generate the per-package `package-lock.json` files for me.

How can I generate these files (correctly), or is the single top-level one generate by the `bootstrap` command correct? If so, how can I get it to properly tag things with `"dev": true`, and include local dependencies?

**Meta info:**
Node version: 8.11.1
npm version: 6.1.0
Lerna version: 2.11.0

**lerna.json**
```
{
  "lerna": "2.11.0",
  "npmClient": "npm",
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```

[The above is also asked in this StackOverflow question.](https://stackoverflow.com/questions/50805531/how-to-generate-per-package-package-lock-json-for-existing-lerna-mono-repo)

**Comment by tivac** [comment]
I'm running the `lerna@3` beta and have moved all `devDependencies` to the root `package.json`.

```bash
> npm i
> lerna exec -- npm i
```

I've been pretty happy with this workflow so far but I understand that if you're stuck on `lerna@2` that doesn't help much.

**Comment by MatthewHerbst** [comment]
@tivac that's an interesting idea, but yeah, for now can't go to `lerna@3`.

**Comment by evocateur** [comment]
why not `lerna@3`? i've been using it "in production" for months now.

**Comment by MatthewHerbst** [comment]
@evocateur changing to `lerna@3`, while something we plan on doing, is well out-of-scope for the current project of switching from yarn to npm. Further, even when we switch to `lerna@3`, we are never going to move all of our dependencies into one place at the top. Not only does that break traditional package structure (including a myriad of tools), but it also locks us in to use Lerna/hoisting/using a mono-repo.

I'd appreciate it if you could assist in the original question, which is how to generate `package-lock.json` files in Lerna, ideally per-package with local packages includes and devDependencies marked as such.

**Comment by evocateur** [comment]
Literally run `lerna bootstrap` with no options? (Assuming you have npm5 active in the $PATH)

**Comment by MatthewHerbst** [comment]
@evocateur that makes some progress, thanks! Two issues: local packages are not in the `package-lock.json` when they should be, and, `devDependencies` are not properly marked with `"dev": true`. Any idea how to get either of those behaviors, or is that not currently possible?

**Comment by MatthewHerbst** [comment]
Also, is there a way to run `lerna bootstrap --hoist` and not have `--hoist` change the top-level `package-lock.json`? We want to use `--hoist` when building for speed, but we want the top-level `package-lock.json` to reflect the top-level `package.json`.

**Comment by evocateur** [comment]
The top-level manifest should be devoted to shared devDependencies, and shouldn’t be a published package itself. Hoisted bootstrap really doesn’t play well with lockfiles, which is among the reasons why I recommend using relative file: specifiers to express sibling dependencies (thus enabling the root lockfile to manage the entire tree, _including_ the lerna-managed packages).

**Comment by MatthewHerbst** [comment]
Thanks for the quick responses! Yeah, the only thing we have in our top-level `package.json` is lerna and some linting tools. We have a lot of non-shared devDependencies between our packages, so we can't (well, don't want to) bring them all up to the top-level.

What do you mean by relative file specifiers? I don't think I've seen any language about that - did I miss it in the docs?

Would lerna be open to PRs that enabled:

- `--hoist` to work while properly generating/maintaining per-package `package-lock.json` files
- `"dev": true"` for devDependencies in per-package `package-lock.json` files

Also, I don't think this has been answered: is there a reason local packages don't show up in the `package-lock.json` files? (And if not, a PR to allow that as well?)

**Comment by tivac** [comment]
> What do you mean by relative file specifiers? I don't think I've seen any language about that - did I miss it in the docs?

Here it is in the npm docs, they call it [Local Paths](https://docs.npmjs.com/files/package.json#local-paths)

And here's an example from a `lerna@3` project:

https://github.com/tivac/modular-css/blob/2d7d299817acb25e085bca315cf14654ec4df8c1/packages/rollup/package.json#L23

**Comment by franher** [comment]
Hello guys, 

I'm using lerna v3.0.0-beta.21, npm v6.1.0 and node v8.11.3.

I have the same issue. Doing `lerna bootstrap` it generates only the package-lock.json on the root, but not into every package.

@MatthewHerbst did you resolve the issue at the end? Thank you

**Comment by jakewhelan** [comment]
Using `lerna@3.0.0-beta.21` package-lock is not generating per (nested) package when using `npx lerna bootstrap`

Have also tried `npx lerna exec -- npm i`, and tried using also `lerna@2.11.0` and `lerna@2.9.0`

None of these work.

Lerna project current looks like this:
```
packages/
  foo/
    bar/
      package.json
    baz/
      package.json
```

Lerna.json
```json
{
  "lerna": "2.11.0",
  "packages": [
    "packages/rollup/*"
  ],
  "version": "independent"
}
```

**Comment by jakewhelan** [comment]
Using `lerna@3.0.0-beta.21` package-lock is not generating per (nested) package when using `npx lerna bootstrap`

Have also tried `npx lerna exec -- npm i`, and tried using also `lerna@2.11.0` and `lerna@2.9.0`

None of these work.

Lerna project current looks like this:
```
packages/
  foo/
    bar/
      package.json
    baz/
      package.json
```

Lerna.json
```json
{
  "lerna": "2.11.0",
  "packages": [
    "packages/foo/*"
  ],
  "version": "independent"
}
```

**Comment by thomasboyt** [comment]
I recently converted a couple separate repos into a single Lerna 3 monorepo. I had some trouble (which will probably lead to docs issues & PRs), but thanks to a few example projects I could look at like https://github.com/CondeNast-Copilot/atjson/, I managed to figure out how to configure [my repo](https://github.com/thomasboyt/pearl-monorepo) correctly.

This lockfile problem is really my only big lingering question. Currently, my project's lockfile only contains the top-level `devDependencies`, and not the hoisted dependencies. This also seems to be an issue with the atjson repo (for example, the [react dep in this package](https://github.com/CondeNast-Copilot/atjson/blob/e48b2eb7554436bdb56ae9c713629ac21c581eae/packages/%40atjson/renderer-react/package.json#L27) is [not present in the package-lock.json](https://github.com/CondeNast-Copilot/atjson/blob/latest/package-lock.json)) , so I at least know I'm not the only person with this problem.

Now, this isn't a show-stopper, necessarily. It just means, practically, I don't have a lockfile for my repo, which is a survivable issue, and I think a hit I'm going to just take for now. But it does seem like something that either needs resolution before 3.0's release, by finding a way to hoist lockfile dependencies, or a heck of a lot of docs justifying why it doesn't have a lockfile.

In addition, `lerna add` complicates this tremendously. If you `lerna add` a package, you will... find a newly-generated `package-lock.json` for each repo. In addition, there's all sorts of npm commands that will regenerate `package-lock.json`, like `npm link`.

> Hoisted bootstrap really doesn’t play well with lockfiles, which is among the reasons why I recommend using relative file: specifiers to express sibling dependencies (thus enabling the root lockfile to manage the entire tree, _including_ the lerna-managed packages).

I don't understand this as a workaround, but I've seen it mentioned in a few issues now, so I'm curious - how does using `file:` specifiers cause the root lockfile to have hoisted dependencies? Or does it mean you have deduplication without using the `--hoist` mechanism, somehow? I know lerna's repo uses this, and lerna is the only project I've seen that has a `package-lock.json` that contains all dependencies, but I assumed that had nothing to do with `file:` specifiers and was just because [lerna is self-hosting and specifies itself as a dependency](https://github.com/lerna/lerna/blob/master/package.json#L24), causing it to import every package and include them in the lockfile, which is... not a workable solution for most repos, I think?

**Comment by evocateur** [comment]
To use relative file specifiers:
```
npx lerna link convert
npm i packages/*
```

Now you don't need `lerna bootstrap`, and everything is serialized in the root lockfile.

To update the lockfile for leaf package dependencies, `npm i packages/*` again. Any individual changes to leaf dependency ranges will necessitate running `npm i`.

Zillow's fork of airbnb/javascript does it: https://github.com/zillow/javascript/blob/latest/package.json

**Comment by thomasboyt** [comment]
Ah, thanks! I'll give this a shot.

So I assume a new best practices guide would look something like

- Use `npx lerna link convert` (or just `npx lerna link` if you haven't already bootstrapped?) to create relative file specifiers
- Run `npm install packages/*` to install every package in the repo as a dependency of the root project, which will result in `file:` dependencies in the root project
- Put *all* devDependencies in the root-level `package.json`, because presumedly `npm install packages/*` will not install devDependencies of the packages (I might be wrong on this/maybe there's a way to configure it?)
- When you add a new package, run `npm install packages/newpackage` from root, and re-run `lerna link`
- To install the project fresh, just run `npm install && npx lerna link` in the root, and never run `npx lerna bootstrap`

Wonder if there are any hidden downside to this format, but it seems good to me. I'll give it a shot in my repo!

**Comment by evocateur** [comment]
Pretty much exactly, except you only ever need to run `lerna link convert` once, regardless of bootstrap status. `npm install` itself handles all the linking seamlessly from that point on.

**Comment by lucasowens** [comment]
So for relative file path specifiers is there a way to no-hoist? I like this idea, but currently the serverless framework needs it's own node_module folder in order to deploy. Any work around for this?

**Comment by jazen** [comment]
I noticed it too—serverless won't find plugins otherwise.

**Comment by evocateur** [comment]
Sounds like serverless needs to fix something.

npm will automatically "bundle" conflicting majors under the relevant leaf node_modules. However, there is no way (that I am aware of) to tell npm to force this status.

I don't recommend deploying from a lerna layout, in any case. Too many conflicting priorities that lerna itself will never likely support, as it is not a deployment tool.

**Comment by lucasowens** [comment]
It does sound like a serverless issue. Lerna is not being used as a deployment tool, serverless is, it just isn't smart enough to find the packages. I'll stick with workspaces for now. Thanks.

**Comment by bmuenzenmeyer** [comment]
> Pretty much exactly, except you only ever need to run `lerna link convert` once, regardless of bootstrap status. `npm install` itself handles all the linking seamlessly from that point on.

@evocateur @thomasboyt does this set up steps assume running lerna NOT in independent mode?

**Comment by evocateur** [comment]
The versioning mode makes no difference when using local file specifiers.

**Comment by zachwolf** [comment]
Has anyone else used this pattern run into issues with `.bin` executables not being found? Reduced test case of what I'm running into: https://github.com/zachwolf/monorepo-issue-reduced-test-case

**Comment by evocateur** [comment]
@zachwolf Thanks for the very clear reproduction! And yes! I have!

A few things, sorry they're a bit jumbled in my head as I braindump:

1. I am fairly certain `npx lerna run yellow` from the root of your example would still work, because `lerna run` still calls `npm run <foo>` in a subshell with [execa](npm.im/execa), which adds parent `node_modules/.bin` to the PATH automagically via [npm-run-path](npm.im/npm-run-path).

2. However, this is not the case when you've, for example, run `lerna link convert` and are now using relative `file:` specifiers from the root. In a way, the `file:` specifiers are telling npm to treat the local packages as install targets, symlinking _only_ the "production" dependencies. Because of the way the node_modules resolution algorithm works, it makes sense that code in those leaf directories can still require modules that are actually installed in the root `node_modules` directory.

3. However, `npm run` itself only appends `node_modules/.bin` to the PATH _once_, for the CWD (the leaf directory, as your reproduction ably demonstrates). `npm run` does _not_ do the fancy npm-run-path logic, but instead uses [npm-lifecycle](npm.im/npm-lifecycle) internally (lerna does too).

This `npm-lifecycle` behavior is frustrating to me for a number of reasons, especially various lifecycles that are called during `lerna version` and `lerna publish` that will fail if they don't use the grody relative paths in the lifecycle script (`"prepare": "../../node_modules/.bin/babel ..."` etc). I don't have a solution just yet, but it probably involves a PR upstream to `npm-lifecycle` (at worst,  a lightweight fork?).

For the most part, I cheat when explaining to folks the workaround for this issue, telling them they should _always_ run dev scripts from the root, and using the `lerna run` cheat to paper over the missing binary resolution. I _still_ believe one should run dev scripts from the root, but this obviously has shortcomings, especially in the version and publish lifecycles I described earlier.

**Comment by kirill-konshin** [comment]
@evocateur can you elaborate more what is the difference between using `file:` and package names when referring to neighbor packages? How does it affect what will appear in `package-lock.json`'s and which is a better way if some packages are published?

**Comment by ryancat** [comment]
> Has anyone else used this pattern run into issues with `.bin` executables not being found? Reduced test case of what I'm running into: https://github.com/zachwolf/monorepo-issue-reduced-test-case

I think in readme file someone mentioned the following:
> Note that devDependencies providing "binary" executables that are used by npm scripts still need to be installed directly in each package where they're used.

I guess if you are running scripts by `lerna run`, the root bin path should be still available in PATH. However if you have your own scripts running executables, they would need to be installed in the packages as well.

This actually leads me to another question -- I know I should only run `lerna link convert` one time. However, if I add a new package and would like to convert its devDependencies to root and start to use `file:` specifiers, what should I do? If I run `lerna link convert` again, isn't it going to change other packages devDependencies that I meant to add?

Or I guess I will need to use filter flags for future, incremental changes on new packages.

**Comment by ryancat** [comment]
I guess there are two ways to solve the problem, one is with `lerna link convert` and the other is `lerna bootstrap --hoist`. However, I don't think either of them is 100% working with npm.

I like the idea of converting all devDependencies to root and use `file:` specifiers. This for sure simplifies things a lot. However, I feel this may break assumptions npm and many packages made such as packages should be self-contained. Adding a new package, or separating a package in the future will be more difficult too. Running npm script within the package is painful as the executables are not on PATH in the package. I ended up install a bunch of devDependencies back to the package just to be able to run linters and husky scripts, which is annoying.

On the other hand, the main complain I had with `lerna bootstrap --hoist` is the lock file. It seems only generating the `package-lock.json` file at top level, and there are errors in that file. 

Since only the root level lock file will be recognized by npm when `npm install` runs, it makes no sense to keep a `package-lock.json` file in sub-packages to use `lerna bootstrap`. Without a lock file, I can only hope all of my dependencies' authors are great developers to maintain good semantic versioning, which is super risky. 

For now, I am thinking to write a simple nodejs script to run `npm install ` in each packages. After that, I will run `lerna link` to symbol link my packages so that they will work correctly. 

The script can be found here https://gist.github.com/ryancat/3e0e134833662b8441b055fac6f9f8f8

**Comment by ryancat** [comment]
For now, I am thinking to write a simple nodejs script to run `npm install` in each packages, so that the `package-lock.json` file will be updated and used. I will use the `file:` specifiers for my packages in the `package.json` file so that I don't need to link them anymore.

The script can be found here https://gist.github.com/ryancat/3e0e134833662b8441b055fac6f9f8f8

**Comment by ryancat** [comment]
Actually -- I realized `lerna bootstrap` may have fixed the package-lock.json generation and `dev:true` flags.

**Comment by phil-lgr** [comment]
I've read the whole thread including other links and still can't find a solution for file: dependencies that have a `"bin":`

In my root package.json I have a package that has a bin:

```
"dependencies": {
    "@lerna-ts-starter/core-cli": "file:packages/core-cli",
```

when I npm install, I get a chmod error since this package is not yet built. Any idea of how to tackle this?

**Comment by jd-carroll** [comment]
> Ah, thanks! I'll give this a shot.
> 
> So I assume a new best practices guide would look something like
> 
> * Use `npx lerna link convert` (or just `npx lerna link` if you haven't already bootstrapped?) to create relative file specifiers
> * Run `npm install packages/*` to install every package in the repo as a dependency of the root project, which will result in `file:` dependencies in the root project
> * Put _all_ devDependencies in the root-level `package.json`, because presumedly `npm install packages/*` will not install devDependencies of the packages (I might be wrong on this/maybe there's a way to configure it?)
> * When you add a new package, run `npm install packages/newpackage` from root, and re-run `lerna link`
> * To install the project fresh, just run `npm install && npx lerna link` in the root, and never run `npx lerna bootstrap`
> 
> Wonder if there are any hidden downside to this format, but it seems good to me. I'll give it a shot in my repo!

I'm trying to wrap my head around these ideas, but cannot seem to get my `npm install packages/*` to work.  Instead of using a `projects` folder, I am using `common` and it keeps trying to install something from the "common" user on GitHub:
```
$ npm install common/*
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/common/README.md.git
npm ERR! 
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
npm ERR! git@github.com: Permission denied (publickey).
```

**Is there a consolidated version of these best practices somewhere for nom?**

**Comment by Vishesh30** [comment]
> > What do you mean by relative file specifiers? I don't think I've seen any language about that - did I miss it in the docs?
> 
> Here it is in the npm docs, they call it [Local Paths](https://docs.npmjs.com/files/package.json#local-paths)
> 
> And here's an example from a `lerna@3` project:
> 
> https://github.com/tivac/modular-css/blob/2d7d299817acb25e085bca315cf14654ec4df8c1/packages/rollup/package.json#L23

Hi @tivac  In your example i see that you have used the "file:../package" for local dependency however this cannot be used to publish the package if so is the case then how the "file" dependency are changed while publishing the package.

**Comment by tivac** [comment]
@Vishesh30 lerna changes them automatically during publish.

**Comment by Vishesh30** [comment]
> @Vishesh30 lerna changes them automatically during publish.

@tivac Thanks for a quick response. As i understand that it is currently not possible to generate lock files per package , I mean there are options like below:-

1. Directly use lerna bootstrap without --hoist flag ------- This does generate lock file but increases the install time way to high.
2. Use "lerna exec -- npm i" ------ This will generate the lock file but "install" times are way higher not a viable solution with 25 packages in my repository.
3. I came with an approach where i create a script to generate package-lock files and called it in postinstall of every package ------ This seems to be doing the Job and is also install times are not impacted.  In our case the version of the packages would be updated by the pipeline However, with this approach the lock files would contain the older versions( before the version is updated by pipeline) hence wanted to check if i can use the "file" dependency and would it help.

Any Suggestion from your end .?

**Comment by Vishesh30** [comment]
I couldn't find a concrete solution to generate lock files for all packages. I mean there are ways but, everything is increasing the installing time to very high. Below are 2 ways to generate package-lock.json file for all packages:-

1. Directly use lerna bootstrap **without** --hoist flag ------- This does generate lock file but increases the install time way to high.
2. Use "lerna exec -- npm i" ------ This will generate the lock file but "install" times are way higher not a viable solution with 25 packages in my repository.


As above 2 solutions were taking way to much time hence i could not use any of them for my scenario hence, i came up with a third way or i would call it a workaround , this is also not the cleanest solution but does the job with very slight increase in installation time.

1) Create a npm script in all your packages which would generate only package-lock file without installation which would be something like below:-
           ` "genPackagelock": "npm i --package-lock-only"`

2) In you root package.json file as part of postinstall call the above defined script for all the packages as below:-
             `"postinstall": "lerna run --parallel genPackagelock"`

The above "postinstall" basically generates package-lock.json file for all the packages along with the internal dependencies.

I am not closing the Bug because the above solutions are a workaround and not one of the best solution.

@tivac  - Any thought on above proposal.?

**Comment by runemadsen** [comment]
I am having the same problem. This is what the documentation states for the `bootstrap` command:

> When run, this command will:
> 1. `npm install` all external dependencies of each package.

That, as far as I can see, is false. When I run `lerna bootstrap` it logs `lerna info bootstrap root only` and only runs `npm i` in the root folder.

How can we run `npm i` for each of the packages?

I really like the idea of `lerna`, but I must say that the documentation makes it really hard to get started.

**Comment by runemadsen** [comment]
An update to my problem: After hours of debugging, I realized that if you have ever run `lerna link convert`, a number of `file:` dependencies to all the packages will be inserted in the global `package.json`, and this is what prevents `lerna` from running `npm i` inside of each package. I had manually remove the `file:` dependencies inside each package, but had forgotten to remove these. After removing them, everything works fine.

**Comment by iddan** [comment]
Following @Vishesh30 answer I successfully used `npm run bootstrap -- -- --package-lock-only`

**Comment by mellis481** [comment]
> Ah, thanks! I'll give this a shot.
> 
> So I assume a new best practices guide would look something like
> 
> * Use `npx lerna link convert` (or just `npx lerna link` if you haven't already bootstrapped?) to create relative file specifiers
> * Run `npm install packages/*` to install every package in the repo as a dependency of the root project, which will result in `file:` dependencies in the root project
> * Put _all_ devDependencies in the root-level `package.json`, because presumedly `npm install packages/*` will not install devDependencies of the packages (I might be wrong on this/maybe there's a way to configure it?)
> * When you add a new package, run `npm install packages/newpackage` from root, and re-run `lerna link`
> * To install the project fresh, just run `npm install && npx lerna link` in the root, and never run `npx lerna bootstrap`
> 
> Wonder if there are any hidden downside to this format, but it seems good to me. I'll give it a shot in my repo!

@evocateur Is there a need to update the Lerna README?  Early on in the README, it says "The two primary commands in Lerna are lerna bootstrap and lerna publish".  `bootstrap` is not mentioned at all in the "best practice" steps that you said @thomasboyt essentially nailed so I'm finding this very confusing/misleading.
