### ISSUE TITLE
Use workspace package.json to retrieve version number

### ISSUE THREAD

**Issue by alex-pex** [lerna/lerna#1473]
### Improvement
on monorepository version number

## Expected Behavior

When useWorkspaces = true, I should be able to skip the version field in lerna.json, and set it in the root workspace package.json.

Some tools expect the repository version to be held by the root package.json (eg: changelog generators)

## Current Behavior

If version is not set in lerna.json, "current version" equals _null_.

## Possible Solution

Lerna could look at lerna.json>version field, and if not set but workspaces enabled, fallback to root package.json>version.

On publish, Lerna should update the version at the same location (if the version was found in package.json, it should update it in package.json)

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `npm --version`  | 5.8.0 |
| `yarn --version` | 1.7.0 |
| `node --version` | 8.9.4 |

| OS |
| --- |
| Windows 10, with Git Bash or WSL |

**Comment by evocateur** [comment]
The version field of the root manifest in a monorepo is irrelevant, as it should not itself be a published package. Using yarn workspaces doesn't make a difference in this regard.

> Some tools expect the repository version to be held by the root package.json

If they are designed to work in a monorepo, those tools are broken.

If not, which is much more common, those tools need to be updated to understand monorepos. Otherwise, their output is suspect, as the structure of a monorepo is not intended to mimic that of a "traditional" package repository (one package :: one repository).

[conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) made this transition, and is available on `lerna publish` via the `--conventional-commits` option.
