### ISSUE TITLE
--conventional-commits doesn't work on fixed mode

### ISSUE THREAD

**Issue by wzalazar** [lerna/lerna#1484]
## Expected Behavior
When I execute this command `lerna publish --conventional-commits --yes` with this configuration

**lerna.json**
https://github.com/react-core/react-core/blob/5c97d2bc38d131d77a69b28327c5deb5a61b7cce/lerna.json#L1-L16

```
{
  "lerna": "2.9.0",
  "version": "0.1.38",
  "packages": [
    "packages/*"
  ],
  "command": {
    "init": {
      "exact": true
    },
    "publish": {
      "independent": false,
      "conventionalCommits": true
    }
  }
}

```

I will expect to upate all packages with the same version

Repository, https://github.com/react-core/react-core

## Current Behavior

After the last commit in Button package for example with `fix: test` with the above configuration, the following package changed to version v0.1.38, 
https://github.com/react-core/react-core/tree/master/packages/Button

but the remaining packages are still in v0.1.37

**Comment by evocateur** [comment]
`--conventional-commits` "not working" with the default fixed versioning mode is certainly news to me, since Lerna itself [uses it](https://github.com/lerna/lerna/blob/f674f354f0260c57d885c181e16c9ce23ac252a8/lerna.json#L15). (You shouldn't pass `"independent": false` under `command.publish`, it's not controlled there)

> but the remaining packages are still in v0.1.37

That's exactly how Lerna works. The only change since `v0.1.37` was in `packages/Button`, and since no other package depends on `@react-core/button`, no other package is published.

**Comment by wzalazar** [comment]
ok, thanks @evocateur
