### ISSUE TITLE
Allow lerna publish to not update dependency package.jsons if they do not match semvers

### ISSUE THREAD

**Issue by bdwain** [lerna/lerna#1489]
## Expected Behavior
If I have a monorepo with package A and B, where A depends on B, I want to be able to hard code the version of B that A depends on if there is a bug in B. For example, if A's package.json normally contains this:

`B: "^4.5.6`

but then B@4.5.7 contains a bug, I would like to move forward with the version of A while hard coding B to 4.5.6

`B: "4.5.6"`

And then I'd like B to remain at 4.5.6 until I manually add a caret back in. This way if B gets updated with a different change that does not fix the bug, I don't accidentally pull it into A.

## Current Behavior
If I hard code A to B@4.5.6, any change to B will bump A's version.

## Possible Solution
There's an argument to be made that if the new version of B does not match A's old semver, A's version of B should not be bumped. But since that would be a breaking change, I think a good middle ground would be to enable this behavior only with an option to publish. Something like `--respect-semvers` or something.

## Context
I work on a project with many teams, and we want to easily be able to move forward with development if one the libraries in our monorepo has a bug in it. We typically hard code the version of that library to the last working version if a bug is released, but this would not work if we tried to use lerna publish (because we can't always fix the broken dependency right away).

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.11.0 |
| `node --version` | 9.11.0 |

**Comment by bdwain** [comment]
If B's tests don't cover the buggy scenario, the bug could get released. All bugs that get released in any project got past the testing phase. 

Why do you think A and B should not be in the same monorepo? Basically what I'm making is a monorepo for the internal front end platform my company is using. The main app is broken up into many subapps, which are independent packages that contain a specific high level feature or page or something. There are also helper libraries used by multiple subapps and the app, including some helpers that are used by all subapps. We need a monorepo because there are often changes that affect multiple packages at once, especially when those changes are breaking changes in the helper libraries.

In the example I gave above, package A is the main app, and package B is a subapp. If there's a bug in a subapp, I want to hard code its version in the app and but still allow changes to other subapps to be merged and pulled into the app.

**Comment by evocateur** [comment]
> In the example I gave above, package A is the main app, and package B is a subapp. If there's a bug in a subapp, I want to hard code its version in the app and but still allow changes to other subapps to be merged and pulled into the app.

It is for exactly this reason that I suggested the application live in a separate repository from the sub-applications, if you are unwilling to let the local links persist. The app repo’s lockfile becomes the release gate, and (assuming the sub-apps do not depend on other sub-apps), you can achieve the behavior you desire.

Otherwise, why not just “fix forward” once the bug is revealed? If you’re just using lerna as infrastructure to coordinate several local paths into an eventual webpack bundle, you might as well treat the bug as an application-level priority.

**Comment by bdwain** [comment]
I see. That would be one option, but in the future, we'll potentially have multiple apps, and I wouldn't want to break out so many separate repos because it starts to defeat the purpose of a monorepo.

It may be that my use case is kind of weird and not for what lerna is designed to do. I've been looking at writing my own scripts for bumping versions and publishing because I have a bunch of different requirements.

**Comment by bertho-zero** [comment]
I'm working on a project with an organization very similar to @bdwain.

This option would answer the need of a lot of people (e.g: https://github.com/lerna/lerna/issues/718), this is to improve the independent mode so that the packages can be really independent of each others.

The `--respect-semvers` option would only be available for independent mode.

With this option instead of automatically bumping all the dependencies of the updated packets one could propose to update them **or not** if the version of the updated package goes out of range in the dependency.

The main discomfort comes from here (for the independent mode with `--respect-semvers` option): https://github.com/lerna/lerna/blob/d40ffb776e3bda7c097931d28399f8c146368926/utils/collect-updates/collect-updates.js#L57-L58

The other change to add for the independent mode with the `--respect-semvers` option is to keep the lockfiles up-to-date, knowing that only the root lockfile is used, the lockfiles of dependencies are ignored by yarn and npm.
