### ISSUE TITLE
lerna + npm ci = double install time

### ISSUE THREAD

**Issue by track0x1** [lerna/lerna#1502]
## Expected Behavior

When using Lerna as a local, devDependency with `--ci`, installation time should be faster because it is using `npm ci` under the hood.

## Current Behavior

When using Lerna as a local devDependency with `--ci`, you will waste time installing dependencies twice because you first need to `npm (c)i` to install your local Lerna dependency, then `lerna bootstrap --ci` will run `npm ci` ([ref](https://docs.npmjs.com/cli/ci)) which removes the newly installed `node_modules` and then install them again based on `package-lock` or `npm-shrinkwrap`.

The only potential solution at the moment is to rely on a globally installed version of Lerna, so then in your repository you only need to run `lerna bootstrap --ci`.

## Context

Installation time when using lerna `--ci` was taking a significantly longer amount of time compared to just running `lerna bootstrap` (without ci).

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.0-beta.21 |
| `npm --version`  | 5.8.0 |
| `node --version` | 8.10.0 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.4 |

**Comment by evocateur** [comment]
Your root package.json shouldn't be a lerna-managed package itself. Yes, it is strictly _possible_ to do that, but I really don't recommend it, for this and _many_ other reasons.

Without providing your `lerna.json` config, I'm making a wild assumption, but the fix is to use your root package.json as dev dependency coordinator only, not a lerna-managed package.

Use [local `file:` specifiers](https://github.com/npm/npm/blob/latest/doc/spec/file-specifiers.md) and `npm i packages/*` once and you don't have to use `lerna bootstrap` at all, one `npm ci` to rule them all.
