### ISSUE TITLE
Allow bumping cross-dependencies for major versions only

### ISSUE THREAD

**Issue by junyper** [lerna/lerna#1506]
We are using fixed versioning mode and would like to be able to set up cross-package dependencies so that they specify only the major version (e.g. 5^). 

Currently, every time we run lerna publish all of the cross-package dependencies are updated to specify major, minor and patch versions (e.g. ^5.20.1).

Example:
Repo version is 5.20.1
We'd like to have all cross package dependencies set to ^5 (unless pinned)

If we release 5.20.2:
We'd like all package versions to bump to 5.20.2, but cross-package deps stay at ^5

If we release 6.0:
We'd like all package versions to bump to 6.0.0, and cross-package deps change to 6^ (unless pinned)

The reasoning here is that we think it will give consumers the ability to pull in a patch for only one of the modules, but have control over the versions of the shared dependencies that are pulled in, hopefully avoiding duplication.

And because we are using fixed versioning they will know that they are doing something risky by not keeping everything in sync.

Is this something that lerna would support? Or should we look into alternative solutions? Are we trying to do something we will regret?

**Comment by hbetts** [comment]
@junyper, I believe the versioning behavior of Lerna intentionally bumps the minimum version of the cross package dependencies to the new version of that dependency under the assumption that if you're releasing a new version of a package from a mono-repository, any package that is released from the same mono-repository _and_ depends on the other released thing, should require the new version.

In your example, let's assume you refactor _package A_ and _package B_. In _package A_ you add a new feature. In _package B_ you use the new feature from _package A_. 

You run your release and the version is bumped to `5.21.0` for both packages.

Lerna _should_ set the _package A_ dependency in _package B_ to be `^5.21.0`, because _technically_ _package B_ depends on the feature released in version `5.21.0` of _package A_.

**Comment by hbetts** [comment]
> Thinking through that scenario, could the package A version in package B then be ^5.21?

@junyper in that scenario _package A_ version is updated to `^5.21.0`, which is equivalent to `^5.21`.

Is that sufficient?

However, what if you modified both _package A_ and _package B_, but those changes didn'tt depend on each other. You would still expect each package to be versioned at `5.21.0`, but, because their changes don't depend on each other, you won't want _package A_ dependency in _package B_ to be updated.

How that is done in practice, I don't know, because Lerna would have to know that changes in _package A_ aren't required by _package B_. That's more than what Lerna can infer on its own.

@evocateur for advice on this one.

**Comment by junyper** [comment]
I think what I’m asking for is: if I manually set a version to ^5 or ^5.21 lerna would leave it alone unless it’s a major version, and then it would update everything to ^6.

**Comment by evocateur** [comment]
What scenario causes this “duplication” that you’re trying to avoid?

**Comment by ryankshaw** [comment]
here is the exact scenerio we are running into:

we have a monorepo (https://github.com/instructure/instructure-ui) that has a bunch of different packages for making ui components that is set up as a lerna repo:
in that repo there is a package for:
* buttons
* dialogs
* pagination
* etc.

now lets say I fix something in the "pagination" package and I want to use that in a consuming app. so I bump consumingApp's package.json to say `"@instructure/ui-pagination": "5.21.0"` but I leave everything else at 5.20.x. 

ui-pagination depends on buttons and so what will happen is that yarn will not just upgrade ui-pagination but also either:
* add a new entry for ui-buttons, so that the pagination package gets its *own* copy of ui-buttons in its own node_modules and creating unnesicary bloat of js sent to the browser
* change the existing "ui-buttons" entry in yarn.lock to 5.21.0 from 5.20.0, which will mean ui-buttons and *everything in consumingApp* will start using the new buttons, along with whatever other changes have happened there), even though we have not QAed that and what we wanted in this change  was just to pull in the one fix for the pagination component.

so we are asking for this so we can upgrade one package ("ui-pagination") and get that merged into consuming apps in small changes

**Comment by evocateur** [comment]
Your example repo appears to be lacking tags on master? That’s kind of breaking lerna publish.

Without the tags that lerna publish creates, every publish is publishing the world, instead of just the packages that have changed since the last release (and their dependents). With proper tags, a change in a pagination component that has no other local dependents will only publish the pagination package, which sounds exactly what you’re going for?

(Also, consider using the `--npm-tag` option to control which dist-tag the package is published to instead of the default “latest”. Dist tags are the npm way to express release quality)

**Comment by junyper** [comment]
@evocateur we create tags for releases, but we are using fixed versioning. We use the `--npm-tag` option to publish with either `latest` or `rc`.
