### ISSUE TITLE
Feature:  bootstrap --hoist-devonly

### ISSUE THREAD

**Issue by GordonSmith** [lerna/lerna#1526]
## Expected Behavior

Same as "hoist" except the only packages hoisted are those specified in devDependencies

## Current Behavior

When hoisting dependencies, it can be relatively easy to get some of the intra-package dependencies wrong.  
But when not hoisting dependencies you will get syntax errors during the build process

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
Have you tried `lerna link convert`? It essentially does what you're asking (hoist devDependencies to the root), but instead of rickety `lerna bootstrap` logic, it lets npm manage the packages (which it does much better).

The end result of a one-time execution of `lerna link convert` is that `lerna bootstrap` is replaced by `npm install`. One caveat, if you transpile your packages, is that you'll need to move that action to the root "prepare" lifecycle (e.g., `lerna exec -- babel src -d lib`).
