### ISSUE TITLE
After upgrading to lerna 3.0 the updated command with the --since flag throws

### ISSUE THREAD

**Issue by jbailey4** [lerna/lerna#1544]
## Expected Behavior

The `lerna updated` command is documented and accepts the `--since` flag

## Current Behavior

When using something like [`lerna-current-dir-updated`](https://github.com/jlegrone/lerna-current-dir-updated) to conditionally run tests in CI, the `lerna updated` command throws an error:

```bash
ERR! lerna Unknown argument: since
```
Also, I don't see any documentation on the `updated` command anymore after lerna@3.0, so I'm not sure if this expected and there is a recommended upgrade path.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | `3.0.0-rc.0` |
| `npm --version`  | `5.8.0` |
| `yarn --version` | `1.5.1` |
| `node --version` | `8.2.1` |

I can provide more details if this is expected to be an actual issue.

**Comment by jbailey4** [comment]
Just saw this in the new [changed](https://github.com/lerna/lerna/blob/v3.0.0-rc.0/commands/changed/command.js#L10) command docs.

Any reason though these commands (`changed`/`updated`) do not support the `--since` flag? Instead of checking since last "publish", how can you now check since last checkout?

**Comment by evocateur** [comment]
`lerna changed` is meant to be a way to report what _would_ be published if `lerna publish` (or `lerna version`) were run. Neither of those commands accept `--since` anymore, as it fundamentally breaks the contract of lerna's versioning scheme(s).

There are plenty of ways to check what changed since a given revision with `git`, I don't think `lerna` needs to duplicate those.

**Comment by jlegrone** [comment]
@evocateur `--since` was useful for setups where `publish` is not run on every change to the target branch of a pull request.  This is somewhat common for teams that follow a "git-flow" model where pull requests are opened against `develop` and changes are only published to npm for merges to `master`.

In this scenario, the `since` flag provides a nice way to determine whether a package or any of its dependencies which are managed by lerna have been updated in any given PR (which requires more awareness of npm and lerna than a simple `git` solution).  This is great for teams that want to only run a minimal subset of their test suites for pull requests.

Would you consider a ticket/PR to restore this functionality to `changed` valid?

**Comment by evocateur** [comment]
@jlegrone That's what `--canary` was envisioned for. It even has properly-incrementing prerelease versions, now.

The exact same functionality as `lerna changed --since` in v2.x can be accomplished by `lerna ls --since` in v3.x.

**Comment by jlegrone** [comment]
Aha! Thanks, I didn't notice that was an available flag until trying it from the cli. 😄
