### ISSUE TITLE
lerna version --conventional-commits --yes; doesn't seem to follow conventionalcommits.org or that angular conventions

### ISSUE THREAD

**Issue by kirbdee** [lerna/lerna#1554]
## Expected Behavior
with a commit message
```
test: updated tests
```

lerna version --conventional-commits; shouldn't have bumped the version

## Current Behavior
it bumps version +0.0.1

## Steps to Reproduce (for bugs)
create a change and commit with `test: updated tests`, run `lerna version --conventional-commits --yes`

output:
```
$ lerna version --conventional-commits --yes
12:13:26   lerna info version 3.0.1
12:13:26   lerna info versioning independent
12:13:28   lerna info Looking for changed packages since XXX@0.1.1.
12:13:28  
12:13:28   Changes:
12:13:28    - XXX: 0.1.1 => 0.1.2
12:13:28  
12:13:28   lerna info auto-confirmed 
12:13:28   lerna info git Pushing tags...
12:13:32   lerna success version finished
```
<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

With changes to tests within a package or possibly other non semver chaging commits such as "chores" and "docs" expected versions to not be bumped

via conventionalcommits.org / https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit
## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.1 |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | 8 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
That's because lerna does not employ `conventional-changelog-*` to determine what _changed_, only what _version_ to assign to those changes (and generate a changelog).

If you want lerna to ignore certain files when determining if a package has changed, use [`--ignore-changes`](https://github.com/lerna/lerna/tree/master/commands/version#--ignore-changes). It can also be placed in lerna.json, at the root level, which is by far the most convenient:
```json
{
  "version": "independent",
  "ignoreChanges": [
    "**/__fixtures__/**",
    "**/__tests__/**",
    "**/*.md"
  ]
}
```

(Placing it at the root means it will also apply to `lerna diff`, which makes for cleaner, more focused operation of that command overall)

**Comment by kirbdee** [comment]
Thanks for the explaination, that makes sense.
