### ISSUE TITLE
Lerna commit tags even when auth error occurs

### ISSUE THREAD

**Issue by StarpTech** [lerna/lerna#1578]
As titled. I just want to publish my packages but I entered the wrong credentials for GitHub. After that, I had to reset my last commit and remove the last tag of the repo. I think lerna publishing procedure should behave transactionally.

**Comment by evocateur** [comment]
I fail to see how it is lerna's responsibility to ensure you have the correct git credentials. Assuming you meant npm credentials, since otherwise you wouldn't have been able to push commits/tags to remote.

Lerna v3 does all git operations (if any) and _then_ all npm operations when `lerna publish` is called. If you fail to publish anything, immediately call `lerna publish from-git` after resolving your npm credentials issue. No new git commit or tags will be created, only packages published.

Half-tempted to make this the default behavior when `lerna publish` is run on a tagged release (after running `lerna version`, basically).

**Comment by evocateur** [comment]
I don't see why successful git operations need to be rolled back just because the npm operations failed. There is no requirement from npm that the code it publishes be pushed upstream (or even committed, _or even using git_).

The git operations, if reverted and rerun immediately, would have identical results. Transactions are only necessary when that is _not_ the case.

I can see an argument for moving the npm auth validations before any local changes, or improving the error messaging if publish fails after successful versioning.

**Comment by StarpTech** [comment]
> I don't see why successful git operations need to be rolled back just because the npm operations failed. There is no requirement from npm that the code it publishes be pushed upstream (or even committed, or even using git).

It's not about git or npm, this is how `lerna publish` works. `Lerna publish` rely on git and npm. Lerna is responsible for publishing and when it's not possible I expect the same state as before the execution. I don't want to think about which side-effects it provoked.

> I can see an argument for moving the npm auth validations before any local changes, or improving the error messaging if publish fails after successful versioning.

I agree the error message can be improved but I wouldn't change the order because all operations can be reverted except the npm publishing.

```
change package.json
create tags
npm publish
```

When any error is occured in the process e.g invalid json file, duplicate tags, npm auth error I expect that the previous state is restored.

**Comment by evocateur** [comment]
That's not really how lerna has ever worked, or expected to work. Lerna coordinates existing CLI to accomplish its goals, and the failure/revert case has always been manually running the commands.

Lerna isn't enterprise software, it is not transactional, and it has ways of recovering from registry auth failures in the way I described.
