### ISSUE TITLE
Why preuninstall and postuninstall are not called by lerna?

### ISSUE THREAD

**Issue by laszl0** [lerna/lerna#1604]
I have 2 .sh scripts that should run.

One is when preinstall or postinstall, does not matter when, as lerna runs it.

The second  should clean up what happened earlier, either preuninstall or postuninstall.
But it's not run by lerna.

Question: Why?

Sorry if this is not the right place/format to ask this question.

**Comment by evocateur** [comment]
You generally should not rely on the "install" or "uninstall" lifecycle scripts, they are run on **all** executions of `npm install` and `npm rm`, _even for external consumers_.

That being said, lerna never calls either of those lifecycle scripts because it never uninstalls anything (that is, it never calls `npm rm`).
