### ISSUE TITLE
[Feature] git-push subtree support

### ISSUE THREAD

**Issue by matthewmueller** [lerna/lerna#161]
would be cool to be able to easily push micro-services to different remotes using the same repo:

https://coderwall.com/p/ssxp5q/heroku-deployment-without-the-app-being-at-the-repo-root-in-a-subfolder

**Comment by thejameskyle** [comment]
Can you detail an actionable feature request? I'm not sure what to do with this.

**Comment by matthewmueller** [comment]
sure. you have an application with multiple services like this:

```
/packages
   /api
   /www
   /auth
```

they each have their own git repositories but you can easily push them to various remotes.

`lerna push api heroku` to deploy the latest API
`lerna pull api origin` to pull the latest from remote origin

**Comment by thejameskyle** [comment]
I'm gonna have to learn more about how git subtrees work. I don't want super specific things in Lerna when I can open up the api and put them in user-space.

**Comment by bitliner** [comment]
@thejameskyle have a look at this article in case https://medium.com/@v/git-subtrees-a-tutorial-6ff568381844#.o0jw5ms0x

I think it explains git sub tree quite well.

On my project I started using lerna + git subtree. I think some other week and I will be able to contribute and build something for lerna.

**Comment by thejameskyle** [comment]
Can you push changes to a subtree repo from the parent repo? It seems like this would just cause conflicts all the time

**Comment by bitliner** [comment]
@thejameskyle yes, you can: `git subtree push --prefix=... origin master`.

Why there should be conflicts? 

For sure, using a wrapper provided by Lerna would help to manage things more carefully and properly.

**Comment by thejameskyle** [comment]
In order to make this a pleasant experience we'd have to abstract away all of the git subtree commands.

I'm hesitant to do that because I'm want to shift the mental model of Lerna to fit in better with Yarn since the plan is to merge the two tools. In which case the lerna workflow would become less tied to git within Yarn.

**Comment by bitliner** [comment]
@thejameskyle I think still git is essential, especially if child project are deployed using git hooks. Would yarn/lerna be able to manage git hooks? 

I would like to push only one child repository to its remote bare repository.

**Comment by thejameskyle** [comment]
There isn't much being done with git right now. Aside from `git tag` and `git commit` there is only one other command [`git push`](https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L129) and it's the only thing that interacts with your remote git repo.

`git tag` and `git commit` can be optional in Yarn+Lerna because packages don't have to exist in repositories. It could even detect if it's a mercurial repo and work with that instead.

In Yarn, `lerna publish` would also have to be broken into two separate commands `yarn version` and `yarn publish` which solves the CI-based publish scenario better.

**Comment by F1LT3R** [comment]
I seem to have bumped into this issue myself: https://github.com/lerna/lerna/issues/457

My assumption was that Lerna would _just work_ with multiple Node **and** Git repositories simultaneously. Is this not the case?

This being my first venture out into the world os monorepos (having been managing each npm package with it's own git repo previously), I am finding it very surprising that it would be handled another way.

Do most monorepos really manage their projects without multiple git modules for each npm package?

Wouldn't lack of git submodule support, make debugging suites of tests suites across say... 50 npm modules, in CI a huge headache? I would have thought that the dev team would want notifications on a specific build failure for a specific component, rather than to have to dig through all running tests in an ecosystem. Perhaps that can be done anyway? Not sure I see how that would work.

**Comment by bitliner** [comment]
@F1lt3r I agree with you that a tool for  monorepo should help more by providing more automation (I actually have at least 20 packages, you can imagine how time it is in setting up the repo and push). I think the best idea would be to write a separate wrapper and then discuss if it is worth to integrating it into lerna.

**Comment by F1LT3R** [comment]
Agreed @bitliner 

Hard for me to understand why Lerna would have much trouble doing this. In my mind the git command would just run with the cwd being the package dir if it had a .git/ dir in, and Lerna would track the submodule hash.

Your approach sounds good @bitliner but I suppose you would --ignore git with Lerna in that case?

**Comment by bitliner** [comment]
@F1LT3R I was thinking more about a solution with `git subtree`. I am quite busy at the moment, feel free to create a repository, we could start from defining requirements and once we have them we could think of an implementation.

**Comment by F1LT3R** [comment]
@bitliner what is the advantage of subtree over submodules? (I've not used subtree)

Over the last few days I hacked together a little tool to manage the project I'm working on. 

Demo: https://www.youtube.com/watch?v=IfnSDgQjTVw
NPM: https://www.npmjs.com/package/robonaut

Perhaps it's a demo of how I would have expected Lerna to work. This is the first time I've ventured into mono-repo world, and I think I see that I'm operating under a completely different paradigm than others (at least for the moment).

**Comment by rattrayalex** [comment]
Personally I'd love to see Lerna support git submodules. For example, easy access to babylon from within babel.

**Comment by scottmas** [comment]
Another use case not mentioned here is cases where you want an internal company facing mono-repo to make code review, etc easier, but you just want the rest of the world to see the individual repos. For instance, Stripe.com has a ton of API libraries that each live in a separate repo and occasionally get PR's from community members. But if you were a stripe employee, you probably would want to see all the individual repos all lumped together in one big mono repo. 

FWIW, I'm a fan of subtrees. The pushing and pulling works a lot more smoothly with my workflow.

**Comment by bitliner** [comment]
@scottmas I would also add or generalize that the every company might have the need to outsource some development without sharing the whole codebase, for security purpose. 

Sharing small part of the whole codebase would make outsourcing and collaboration much easier.

I am actually using git-subtree in order to make the process smooth with external developers.

An issue is that commits should be rewritten, especially when pushing an internal module to an open source community. If you don't do so, you are going to publish sensitive information that you might not want to exposure to the outside world.

Git-subtree do not expose this functionality by default, and git-filter might be required in order to fix the problem.

**Comment by scottmas** [comment]
Any update on this? We basically have been forced to roll our own Lerna and would like to use Lerna if possible.

**Comment by rattrayalex** [comment]
I use git submodules out of necessity. In case it's helpful to others, here's the script I've slapped together for releasing multiple libraries to npm simultaneously: https://github.com/lightscript/lightscript/blob/master/scripts/release.js

It has problems but stil beats doing everything by hand.

**Comment by epiloque** [comment]
Ideally lerna should not manage git. The rationale is that git workflows tend to get quite complex over time and unique to the project. Personally I would like to see a hooks-like functionality that would enable integration with CI pipelines, git &c.

**Comment by photusenigma** [comment]
I agree with @epiloque and others who say Lerna should not manage git.   That's not it's purpose.    
I'd suggest we simply tell developers they need to figure out how to manage their code so that it presents to Lerna as "monorepo-ish" (even if it's not), and then close this ticket.

I'll give my argument first, and a proposed solution (specifically for using git subtrees) immediately after.  The solution is one I've crafted for the team I'm currently working with, and so far it seems to work well!  

Note: Near the end of my ramble here **I'm including a link to an example github repo** I've created that demonstrates the proposed solution...done without gulp/grunt or extra bash scripts.
   
   
## The argument:
My take is that Lerna is (and should be) focused - specifically - on helping you manage your npm dependencies across projects/packages so large or complex solutions can be broken out into easier to manage parts...which become their own projects and packages.  

It's important to realize all developers will not want to take the same approach to how they bring projects together to make a working environment.  This is how it should be, and Lerna should not be restricting developers to do it a certain way.  Doing so will make Lerna less appealing to some developers who really need it's core competency.  

On the flip side...for the Lerna devs to try to figure out how to support a variety of source code management solutions and mono-repo management approaches is unwise.  I think it would be an unfortunate distraction from making Lerna great at what it does.

I think Lerna is a great solution.  It's not too heavy handed, doesn't try to do too much.  Don't ask it to do more than it should.

## A proposed solution
_Compose a monorepo-ish solution._      
This should not be Lerna's responsibility.   
    
It's relatively easy to use git subtrees to bring external code in as nested npm projects...in a manner that allows developers (or CI) to both push changes back to the remote project, and pull new changes from it if needed.
    
From Lerna's perspective it will look like a monorepo.  From the developers perspective they will need to be aware that it's something pulled together from subtrees....so they need to be a bit more careful and intentional in how they commit code.  Also, they need to be aware that changes they might make in code pulled in as a git subtree will need to be pushed back up to the subtree origin - as appropriate.

Yes, It's a little more overhead, but you are asking to have a usable solution that is unquestionably more complex.  If you need to break out your solution this way, you should absolutely expect it not to require at least a little more oversight and managment...but it doesn't have to be unreasonable.

_I Recommend considering  [git-subtree](https://github.com/plitex/git-subtree) npm cli tool._    
Highly recommend it!    

Seems to work well with Lerna, and I'm easily managing subtrees...either via a nice subtree.json file, or by using the commandline to add them (and the subtree.json is updated accordingly).

_It's worth noting that I very rarely recommend npm repos with so few watchers/stars.  When I found the project it only had one each.  I'm fully aware the git-subtree project has nearly no traction (yet), but I expect it will soon...if something doesn't change elsewhere to address the same issue.  I think this is a great little and well encapsulated solution.  It does the job I was about to spend a couple days writing custom scripts for...and it does it well._
    
## The example project I promised...
Here's the example project I mentioned above.  It was created for demo purposes.  It's still being tweaked and extended, but I hope it's enough for you to understand how this approach works.     
Feel free to copy to your hearts content!    
https://github.com/photusenigma/multi-repo-multi-project-v2
    

### Worth noting...I've explored this concept a lot
I have a lot of years developing front-end solutions like this.  There has been odd mixes of gulp/grunt scripts (..and before that - Ant!), and recently got to play with FormidableLabs [builder](http://formidable.com/open-source/builder/) and [multibot](https://github.com/formidablelabs/multibot).   I've never had such an elegant and beautiful solution, and...right now I can do it all without requiring any of those things!



I've been watching Lerna since I first heard of it shortly after it became official.  I was watching what Babel team was doing before that...taking hints from some of the choices they made.   I'm extremely impressed by the fact something can be put together so simply using these tools these days!  
    
If it doesn't fit well with an architecture you've already adopted...that's a different matter.  That happens.  Sometimes you need to consider reworking the architecture to better leverage the right tools.  If done carefully and well....it's can be absolutely worth it.

**Comment by akfish** [comment]
In my case, one of my packages is a fork of another project and it is published as a npm package. I would expect it work on both sides: git submodules for keep track of upstream repo and lerna for managing npm packages.

IMHO, this is not about managing git with lerna. What we need is for lerna not to break normal git workflow.

**Comment by NeoVance** [comment]
I keep seeing a theme...

> Lerna is for managing npm dependencies. It should not be managing git repositories.

If that is the case, than it should be no problem to remove the opinionated code that requires lerna to work on a mono-git repo (otherwise throwing an error complaining about the existance of submodules), and allow it to work for those of us who would like to manage our repositories the way we want to (in my case using submodules). A submodule is just a directory with git repo initialized in it after all, and git has no problem tracking changes in submodules.

**Comment by bitliner** [comment]
I would also add: 

- `git subtree` commands are quite easy to manage/run - if you want to add a subproject, just use git-subtree directly
- the only integration, that I see the need of, is with `lerna publish`, in order to automatically push the subtrees/subprojects too (otherwise I need to do that manually)
- `git-subtree push` of a sub project has usually a problem - it is going to push also the commits that affect the files of other subprojects - making the history of that subproject a bit dirty - this would be something to address in case (by git filtering?)

**Comment by evocateur** [comment]
Thanks for the bump, whoever it was. This is a dead issue, as no pull requests have been forthcoming.
