### ISSUE TITLE
Remove my contributions to Lerna

### ISSUE THREAD

**Issue by seansfkelley** [lerna/lerna#1622]
Due to #1616. I don't want to get into the politics of ICE of the enforceability of a license change, but as a past contributor I strongly condemn this type of toxic politicizing of the open source community and want no part in it.

Per https://github.com/lerna/lerna/pull/1616#issuecomment-416820399, I would like all my contributions removed. I will not be opening my own PR to do so.

@kittens @evocateur @jamiebuilds

**Comment by seansfkelley** [comment]
Ping also @hzoo @gigabo @noherczeg @joscha @wtgtybhertgeghgtwtg @jezzay @rygine (those contributors higher on [the list](https://github.com/lerna/lerna/graphs/contributors) than I) in case you aren't aware and would like to do the same.

**Comment by androolloyd** [comment]
since his commits occurred under MIT, we can simply revert and then re issue without him as the author correct?

**Comment by orthecreedence** [comment]
From what I've read, this project does not have a CLA. That means that in order to relicense, you either need to remove the contributions of the people who have not given EXPLICIT PERMISSION to relicense, or you need to reprogram thsoe sections of code.

This is not just for the contributors who complain, this is for every contribution that has been made to the project by those who have not explicitely agreed to relicense. The people who have contributed *own* their code, and have contributed it under the license terms of the MIT license. You cannot relicense *their* code without *their* permission.

And you cannot just remove their code and add it back in again without naming them as authors, because they *own* the code and it is not yours to do with as you please *without permission*.

It seems that if this license change is a serious endeavor and not just virtue signaling, the Lerna team is going to have to a) ask permission from a lot of people or b) rewrite a lot of code.

Otherwise, you're effectively stealing people's code.

**Comment by pluma** [comment]
As there is no CLA, @seansfkelley is the only person who can clarify how "remove my contributions" is supposed to be interpreted.

Since he's explicitly doing it because he disagrees with the relicensing, I would expect it to mean "revert my commits in this repo and don't include the code I committed in any future releases".

IANAL but I'm not sure whether there's a legal requirement for the lerna maintainers to comply. I think it depends on what exactly creating a PR on a GitHub repo implies and I'm not aware of any legal precedent for that. That said, if I were a maintainer I would comply out of courtesy.

**Comment by rubbingalcoholic** [comment]
> IANAL but I'm not sure whether there's a legal requirement for the lerna maintainers to comply. I think it depends on what exactly creating a PR on a GitHub repo implies and I'm not aware of any legal precedent for that. That said, if I were a maintainer I would comply out of courtesy.

IANAL but you're using his code without a license. Ironic.

**Comment by pluma** [comment]
@rubbingalcoholic I'm not even using lerna, actually.

**Comment by seansfkelley** [comment]
IA(also)NAL.

What I had intended was "remove entirely or rewrite from scratch" such that the code was definitely no longer mine. This is under the assumption that a simple history/blame change to remove my name would be insufficient to make it no longer "my code" (as it would certainly feel, from my perspective) and would potentially violate the terms under which I contributed the code.

I am accepting the offer that was presented to me by @kittens as:

> your contributions are either removed or rewritten to remove attribution.

"Remove attribution" seems to suggest that changing the name is all that was offered, which is unfortunate.

**Comment by jamiebuilds** [comment]
For the record, there are only 69 (nice) lines of code in the repo which are still attributed to you @seansfkelley. Would you like those removed, or would you like your original commits removed from history and have everything rebased on top of it. Both are pretty easy

**Comment by Sieabah** [comment]
@seansfkelley Just file a DMCA takedown request.

**Comment by pluma** [comment]
@Sieabah Unless you're a lawyer, that's dangerously bad advice. As others and I have explained before, it's not at all clear whether the project maintainers are legally required to comply with the request. Filing DMCA claims without having a valid basis is a federal offense. So if it turns out that I'm right and there's no legal obligation, he'd commit a felony.

That said, the suggestion is silly because you're responding after the maintainers have already started complying with the request out of courtesy. So it would not only be a potential felony but also pointless and needlessly aggressive.

**Comment by Sieabah** [comment]
> That said, the suggestion is silly because you're responding after the maintainers have already started complying with the request out of courtesy. So it would not only be a potential felony but also pointless and needlessly aggressive.

The irony. I was merely stating a suggestion, if you take everything someone says as legal advice then that's your problem. It would be on the person filing the takedown request to ensure they have the right to do so. 

Here you go though:
IANAL, if the MIT license does not explicitly transfer ownership then the legal owner should be able to request anything be done to that code, including removing it from all previous releases of Lerna. If it is not complied with the original author could file a DMCA request to take down the project until it has been rectified.

I assume the people who made the license change don't have much more legal experience than the average person so they probably overlooked a lot of edge cases which can get this project terminated.

**Comment by makeready** [comment]
if this is "toxic politicizing of the open source community" then perhaps that's what's needed.

**Comment by seansfkelley** [comment]
Since you're offering, I'd prefer those commits removed from history entirely, yes, both content and attribution.

You are, of course, free to reimplement the behaviors yourself, which I would recommend so as to avoid breaking regressions.

**Comment by seansfkelley** [comment]
Thank you for restoring some sanity, @evocateur!
