### ISSUE TITLE
Shouldn't you be leaving github?

### ISSUE THREAD

**Issue by StoneCypher** [lerna/lerna#1623]
You just pulled the rug out from all your users and their users, making the build stack for many of the web's most popular libraries illegal on a great number of providers, over your politics.

#2 on your list of forbidden vendors is Microsoft.  Github is a Microsoft property.

**Comment by grxy** [comment]
:rekt:

**Comment by StoneCypher** [comment]
Note: 

* `gitlab` runs on a spread between `Microsoft` and `Google` servers, and both `Microsoft` and `Google` do business with ICE, so gitlab is out too.
* `bitbucket` also hosts at aws, so bitbucket is out
* `sourceforce` is at american internet services, which is level3, which is centurylink, so they're out too

Looks like Canonical's `launchpad` is at websitewelcome, which is hostgator, which should be safe for your current license

**Comment by pluma** [comment]
I don't see anything in the license prohibiting you from doing business with the companies listed as long as you don't use them as a proxy to do business with the ICE. The license clearly penalises companies for doing business with the ICE.

If the intent of the license is for the prohibition to be viral, it should clearly specify that. Microsoft isn't using lerna if you run lerna on a Microsoft server you pay for. They're not providing lerna as a service if you install lerna on a Microsoft server you use.

It's like prohibiting a paper plant that's also a publisher from publishing copies of your (otherwise free) book. People can still use that paper plant's paper to publish copies of your book, but the paper plant itself can't publish copies.

**Comment by orthecreedence** [comment]
The license is about virally penalizing companies that do business with ICE, yet the project is doing business with one of the companies in their list they specifically prohibit. And that's ok, because reasons?

Look, I'm all for protest. But this relicensing is not thought through at all. If this is a serious protest, they need to ask permission to relicense (from all contributors) and rewrite the code from anyone who doesn't explicitely agree. I really think moving off of an ICE-collaborating hosting platform would be warranted as well...

**Comment by nickmccurdy** [comment]
The GitHub ToS requires allowing GitHub (and therefore Microsoft) the ability the host the source code to power the user interface. The license prevents GitHub from using Lerna, but not Lerna from using GitHub.

That being said, I honestly find this hypocritical. You are supporting GitHub (and therefore Microsoft) by using it to run open source projects like Lerna.

**Comment by jamiebuilds** [comment]
Lerna is not a subsidiary of Github
