### ISSUE TITLE
Protect Lerna Viability

### ISSUE THREAD

**Issue by webOS101** [lerna/lerna#1632]
The long term viability of Lerna is in Jeopardy. The recent action to restrict the license in contravention of established open source principles creates unnecessary fear, uncertainty and doubt.

Two actions are necessary to correct this:

1) Remove the non-compliant modifications to the license file.

2) Remove @jamiebuilds from the maintainers list.

The second is necessary because this person has taken the hard work of others and used that to advance a personal agenda without their permission.  This is not the sort of person we need leading an open source project.  Who or what is next on the hit list?  There's no indication this would be the last modification to the license agreement.  As long as @jamiebuilds still has the ability to modify the license, there is no reason to believe we wont face continual modifications to the license.

**Comment by evocateur** [comment]
#1633 fixes this, thank you for your patience.

**Comment by webOS101** [comment]
Thank you.

**Comment by hedgepigdaniel** [comment]
> As long as @jamiebuilds still has the ability to modify the license, there is no reason to believe we wont face continual modifications to the license.

I think that's quite disingenuous, considering the change was made in a PR and was [approved by other maintainers](https://github.com/lerna/lerna/pull/1616). If all the maintainers are [in this together](https://github.com/lerna/lerna/pull/1633#pullrequestreview-150833900) as @TheLarkInn  said, then it seems wrong to remove a maintainer and extensive early contributor from the organisation because you decided after approving their PR that it didn't work out well.

There are clearly a lot of software engineers who are concerned with the ethical implications of their work. This is right, because we are all responsible for the consequences of our actions. I hope that Lerna and other open source projects welcome this concern, discuss it openly, and try to find a productive way to act on it.

**Comment by evocateur** [comment]
Opening the PR itself was not actually the grounds for removal. Approvals are not impervious to reconsideration. I will be writing a blog post as soon as I am able to detail the full reasoning and context.
