### ISSUE TITLE
Skip private packages with no version field in lerna version

### ISSUE THREAD

**Issue by HosseinAgha** [lerna/lerna#1649]
As described by https://github.com/lerna/lerna/issues/810#issuecomment-301781565 and https://github.com/lerna/lerna/issues/810#issuecomment-346123436 some npm packages don't have (or need) a npm version field because none of the package's code can be used by other packages. e.g. http servers.  
 
## Expected Behaviour
Lerna should skip *_private packages_* with *_no version field_* in `lerna version`.  
IMHO the package author's intention is pretty obvious when they don't have a version field and also marked their package as private.   
If the package was not private and there were no version field in package.json we can warn user about the issue and suggest a version `0.0.0` for example, instead of showing and setting a wrong `null` value.

## Current Behaviour
As shown in https://github.com/lerna/lerna/issues/810#issuecomment-301781565 Lerna prompts for new version and changes the package version to `null` incorrectly.

## Steps to Reproduce (for bugs)
1. create a npm package with no version field
2. run `lerna version`
3. press enter when prompted for version

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "lerna": "3.2.1",
  "packages": [
    "projects/*"
  ],
  "useWorkspaces": true,
  "npmClient": "yarn",
  "command": {
    "run": {
      "npmClient": "yarn"
    }
  }
}
```
</p></details>

## Context
One of the main goals of using semantic versioning is to reduce breaking changes to minimum. So users of your code can use and update their dependencies with the ease of mind.  
Some npm packages does not ship in shape of a library. They use `package.json` for dependency management and something like docker for shipping the application code. This may not make much sense for libraries but is a common practice in application development.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.2.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS High Sierra | 10.13.X |

**Comment by HosseinAgha** [comment]
@evocateur thank you for your response.   
Thats exactly what I'm trying to say here. I don't expect lerna to handle my applications let alone bundle them!   
I also happen to have some npm packages in my monorepo that need to be versioned and published.  
All I want from lerna is not to suggest incorrect `null` versions when there is not version field in private packages.

**Comment by evocateur** [comment]
Yeah, you're right, sorry. When a package is explicitly private, we shouldn't force folks to assign a version if they choose to remove it.

There is a huge caveat, however: If any of your local siblings try to depend on that private package, they're gonna have a bad time. I suppose that's fair, given your use case.

**Comment by HosseinAgha** [comment]
I want to link https://github.com/yarnpkg/yarn/issues/6371 as yarn also has this issue.  
I also read https://github.com/lerna/lerna/pull/707 and I'm pretty sure we should bump dependency versions for private packages with no versions even if we don't touch the version field.

**Comment by richsoni** [comment]
@evocateur I also have this same situation as @HosseinAgha.  In regards to the case you brought up:

```
There is a huge caveat, however: If any of your local siblings try to depend on that private package, they're gonna have a bad time. I suppose that's fair, given your use case.
```

I would imagine these to be the three types of packages:
```
//packages/public/package.json
{
  "name": "@demo/public",
  "private": false,
  "version": "0.0.0"
}

//packages/private_lib/package.json
{
  "name": "@demo/private_lib",
  "private": true,
  "version": "0.0.0"
}

//packages/hidden_package/package.json
{
  "private": true,
}
```

Given those the following conditions should apply:
* `hidden_package` is ignored by `lerna link` because it has no `name`
* `hidden_package` is ignored by `lerna version` because it has no `version`
* `hidden_package` is ignored by `lerna publish` because it is private
* `private_lib` is ignored by `lerna publish` because it is private
* all commands work for `public`

If the following package format occurred:
```
  "name": "@demo/versionless",
  "private": true|false,
```

* `lerna link` would fail if a package adds `@demo/versionless` to the `dependencies`.  `lerna publish` would fail.  `lerna version` would fail.

And for this case:
```
  "version": 0.0.0,
  "private": true|false
}

* `lerna version` could work, but `lerna publish` and `lerna link` would ignore this package since it has no name

**Comment by wilhen01** [comment]
+1 to the above suggestion, would love a way to exclude private packages from versioning. We also have a repo containing a mixture of packages, some of which are published and some of which are not, and versioning is completely redundant for the non-published packages.

**Comment by HosseinAgha** [comment]
@wilhen private packages with no version field are already ignored after #1654.  
If you are using lerna to handle workspaces you should be OK by removing the version field and making your package private but if you are using Lerna with _yarn workspaces_, yarn will completely ignore this type of package during installation and linking!   
I opened https://github.com/yarnpkg/yarn/issues/6371 in yarn but unfortunately their issue management is an absolute mess.

**Comment by wilhen01** [comment]
@HosseinAgha That's useful information, but why do we have to remove the version field to get the behaviour? For the packages in question it would be useful to be able to version them ourselves (i.e. manually) - it seems like either we have Lerna versioning or we get no versioning at all.

**Comment by HosseinAgha** [comment]
@wilhen01 according to your [previous comment](https://github.com/lerna/lerna/issues/1649#issuecomment-467066475) you said versioning is redundant for non-published packages so why do we need a version field for them in the first place?  
If the package is an application package and is not a dependency of other packages why should we version it? package version !== application version.  
If it is a library (used by other monorepo packages) but should be private, you should definitely let `Lerna version` handle versioning for you because by handling it yourself super awkward situations may happen.

**Comment by wilhen01** [comment]
The automated versioning provided by Lerna is redundant in this instance, that doesn't mean all versioning is redundant (sorry, that maybe wasn't clear in my previous comment). The packages in question are application packages rather than library packages, but package.json is still a convenient place to track versioning. I guess we'll find some other way to handle it.

**Comment by mjgchase** [comment]
I would love this feature , atm when running publish my private application packages are getting version bumped , the application packages are git submodules and the git add -- command fails as the package.json from the sub-module is included in the git add -- command.

 **fatal: Pathspec 'packages/application/package.json' is in submodule 'packages/application**'

**Comment by JamesHenry** [comment]
Hi Folks 👋 

A lot has happened since this issue was opened, and I think we are good shape now!

First, the original issue of lerna not being happy with private packages without version fields looks like it was fixed not too longer after this issue was originally opened.

Second, the related issue of yarn workspaces not being happy with no version fields on private packages has been resolved as much as it's going to be I believe.

By that I mean, that whilst it is still not possible in yarn v1 workspaces, yarn v1 has not been the latest major version of yarn for a very long time.

Yarn v3 with its `nodeLinker: node-modules` is essentially just a much better yarn v1, so I would encourage you to check it out if you haven't. If you want to take it even further, yarn v3 has a totally different `PnP` approach to package resolution, which is what you get if you don't set `nodeLinker: node-modules`.

For both the PnP and node-modules linkers in Yarn v3, it has not issues with private packages without version fields, I verified just now 🎉 

Therefore I am going to close this one.

Thanks all!
