### ISSUE TITLE
--since filter for version command?

### ISSUE THREAD

**Issue by miralemd** [lerna/lerna#1651]
## Expected Behavior

`version` command should support `--since` filter.

## Current Behavior

`version` command does not support `--since`.

## Context

When using lerna in a project with independent versioning, it's useful to specify since which ref the new release should be based on (in order to properly generate changelog and new semver). In lerna 2.x this was possible by providing a `--since` option, but for lerna 3.x the option was removed for the `publish` and `version` commands. I can't find any docs on why this has been removed, or if it simply was forgotten? If it was deliberate, what would be the recommended way/workflow of cutting independent versions?

**Comment by evocateur** [comment]
`lerna publish` was never meant to be filterable (`--scope`, `--ignore`, and `--since`), and v3 fixed this. `lerna version` is an extraction of logic from `lerna publish`, so the same intention applies.

The recommended way of cutting independent versions remains the same:
```
lerna publish
```

Why was `--since` needed in the first place? I'm not sure what you mean by "properly generate changelog and new semver". Is `--conventional-commits` not working as you expect?

**Comment by miralemd** [comment]
The case I have is 'staggering' the releases so not all packages are published on the same commit, which was possible in 2.x since I could `--scope` during publish. I realize now though that's not really an optimal workflow, and not even possible in 3.x.

Thank you for the clarification, and for an awesome tool!
