### ISSUE TITLE
Adding a `lerna audit` command

### ISSUE THREAD

**Issue by DMPS** [lerna/lerna#1663]
## Expected Behavior

You should be able to run a single command `lerna audit` and see a collated report on the vulnerabilities within each of your packages.

## Current Behavior

If you are using NPM 6 or above, you can run `lerna exec npm audit` which will run npm audit in each of your packages then pipe the results to your terminal. As npm audit can become quite verbose, I suggest lerna uses the _--json_ flag to shrink the information displayed to a more general overview of the monorepo. 

## Possible Solution

As mentioned above, NPM exposes a _--json_ flag which outputs the vulnerability in a simple JSON format on stdout. I suggest we use the metadata property in the output to display the number of vulnerabilities in the project in the whole. A future PR could even collate any vulnerabilities which are shared across projects to help monorepo maintainers to prioritize certain dependencies.

I would love to work on this feature if it fits with the maintainer's vision for Lerna.

## Yarn Support

Yarn is coming out with a similar feature fairly soon, and it seems to have a similar syntax.

[Yarn Issue](https://github.com/yarnpkg/yarn/issues/5808)

**Comment by evocateur** [comment]
That sounds like a great idea! I imagine you'd want to structure the command somewhat similarly to `lerna ls`, at least initially. Let me know if I can help with any other pointers around the codebase.

**Comment by DMPS** [comment]
Thanks, @evocateur! I have a few questions about the implementation:

1. NPM uses the package-lock.json in order to accurately determine the versions within a package. Unfortunately, we run into trouble when `lerna bootstrap` creates the _node_modules_ for a package with only internal dependencies (like in the basic fixtures within Lerna). In that special case, Lerna doesn't generate a package-lock.json for the package and therefore `npm audit` throws an error. In order to correct this behavior, we would have to update `lerna bootstrap` to always create a package-lock.json even for packages which don't need it (perhaps using `npm i --package-lock-only`). How do you think I should move forward?

1. In order to properly test `lerna audit`, I need a package which I know will always have certain vulnerabilities. As NPM uses their own proprietary vulnerabilities database, the best solution seems to be to create a deliberately compromised package on NPM then pull that package in for testing. As this approach is starting to be closer to integration testing than unit testing, I would appreciate any other, simpler ideas. Also, if you know anyone else who could help with testing this command, please ping them.

**Comment by DMPS** [comment]
Apologies, I accidentally closed the issue

**Comment by garthk** [comment]
@DMPS you don't need a vulnerable package: you need a vulnerable version of a package. Try [`hoek@2.16.3`](https://www.npmjs.com/advisories/566) or [`tunnel-agent@0.4.3`](https://www.npmjs.com/advisories/598) or [`stringstream@0.0.5`](https://www.npmjs.com/advisories/664) or [`macaddress@0.2.8`](https://www.npmjs.com/advisories/654) or anything else with an advisory.

@evocateur could you point to whatever code alters `package.json` before and after `npm install` or `npm ci`?

**Comment by erikhofer** [comment]
Any progress on this?

> NPM uses the package-lock.json in order to accurately determine the versions within a package. Unfortunately, we run into trouble when `lerna bootstrap` creates the _node_modules_ for a package with only internal dependencies (like in the basic fixtures within Lerna). In that special case, Lerna doesn't generate a package-lock.json for the package and therefore `npm audit` throws an error.

There is another issue. Even if there is a `package-lock.json`, internal dependencies are not included in it (maybe only if they are unpublished?). This makes `npm audit` fail as well.

    npm ERR! code ELOCKVERIFY
    npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
    npm ERR!     Missing: mypackage@1.0.0

**Comment by philmander** [comment]
I am using a workaround where I have `npm audit` in the `prepare` phase of each Lerna package, but I also sandwich this in a script to temporarily add the missing (linked) dependencies to the package-lock and then after revert. Adding simply the package name and version seems to work.

**Comment by chyzwar** [comment]
Can we keep it open ?

**Comment by evocateur** [comment]
PR welcome.

**Comment by drewpc** [comment]
#1462 has good discussion and is related.

**Comment by paprende** [comment]
> I am using a workaround where I have `npm audit` in the `prepare` phase of each Lerna package, but I also sandwich this in a script to temporarily add the missing (linked) dependencies to the package-lock and then after revert. Adding simply the package name and version seems to work.

This also worked for me as a workaround. Can we have a way where a `lerna audit` command temporarily adds the missing (linked) dependencies to the package-lock before running `npm audit` in that package?

**Comment by mikrivorot** [comment]
> There is another issue. Even if there is a `package-lock.json`, internal dependencies are not included in it (maybe only if they are unpublished?). This makes `npm audit` fail as well.
> 
> ```
> npm ERR! code ELOCKVERIFY
> npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
> npm ERR!     Missing: mypackage@1.0.0
> ```

A workaround for this error:
1. Use `lerna link convert` to replace `"mypackage": 1.0.0` with `"mypackage": "file: ../.."` in all package.json files (this allows `npm i` to resolve dependencies, (!) but also this command pulled up to the root of a Lerna repo `devDependencies`)
2. Run `npm i --package-lock-only` to include internal dependencies to `package-lock.json` files 
3. Run `npm audit`/`npm audit fix` etc.

At the end it is necessary to:
1. Revert `lerna link convert` command by hand, because `lerna` provides no command for this
2. Fix `package-lock.json` files (remove internal dependecies, e.g. using `lerna bootstrap`)

**Comment by tnobody** [comment]
Hi,

we had the same problem with our [lerna based repo](https://github.com/sakuli/sakuli) and created a dedicated [script](https://github.com/sakuli/sakuli/blob/develop/scripts/npm-audit.js) for this task. Since we needed for other repos I published it on npm: https://www.npmjs.com/package/lerna-audit

Maybe this could help some people as a workaround.

Some remarks: The script was especially for our use-case so there are no configuration options (like package-scopes). It simply does the following things:
- execute `lerna ls --json --loglevel=silent` to get information about the lerna managed packages
  - Therefore it depends on a globally installed `lerna`(It didn't test it without it)
- Foreach package 
  - it saves the contents from `package.json` into memory
  - removes all entries from `dependencies` and `devDependencies` which points to another package from the monorepo
  - overrides the `package.json`with the adjusted dependencies
  - executes `npm audit` in package
  - If npm audit fails it executes an `npm audit fix` automatically
  - it will eventually write the original contents from `package.json` back to the file

The script is in no meaning complete, resilient or very well tests (e.g. for cross-platform) and since it does file operations on the package.json file, make sure you have committed everything before you run it.

If you like it you are welcome to help me to improve this util until this became a feature of lerna itself.

**Comment by chawax** [comment]
> Any progress on this?
> 
> > NPM uses the package-lock.json in order to accurately determine the versions within a package. Unfortunately, we run into trouble when `lerna bootstrap` creates the _node_modules_ for a package with only internal dependencies (like in the basic fixtures within Lerna). In that special case, Lerna doesn't generate a package-lock.json for the package and therefore `npm audit` throws an error.
> 
> There is another issue. Even if there is a `package-lock.json`, internal dependencies are not included in it (maybe only if they are unpublished?). This makes `npm audit` fail as well.
> 
> ```
> npm ERR! code ELOCKVERIFY
> npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
> npm ERR!     Missing: mypackage@1.0.0
> ```

Just found this NPM package that solved this same problem I had : 

https://www.npmjs.com/package/lerna-audit

**Comment by mcandre** [comment]
`lerna exec -- npm audit` works, however `lerna exec -- npm audit fix` breaks, because the underlying `npm audit fix` command expects files to be in a conventional Node.js structure rather than a lerna structure.

That's why it's so important to implement these security features, or at least not break the old ones.

**Comment by mesqueeb** [comment]
Also related:
https://github.com/lerna/lerna/issues/2124

This feature should be very high priority security wise!

**Comment by mcandre** [comment]
As a workaround, temporarily de-lerna your Node.js projects.

**Comment by JamesHenry** [comment]
Hi Folks 👋

Please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
