### ISSUE TITLE
Regression: 3.4.0 fails to publish to private registry

### ISSUE THREAD

**Issue by fenduru** [lerna/lerna#1685]
## Expected Behavior

Prior to [this commit](https://github.com/lerna/lerna/commit/65fc603451c9547b10d6e0fe0a2e999e35da95c9) our publish would be sucessful when passing both `verifyRegistry` and `verifyAccess` as `false` in our base Lerna config (that we consume by using the `extend` feature).

## Current Behavior

`lerna publish` fails due to the error: `401 Unauthorized - GET https://registry.yarnpkg.com/-/whoami`

## Possible Solution

From my perspective all of the new features surrounding registry verification etc. has been nothing but anti-value since upgrading to Lerna 3, as all of our packages are published to an internal Artifactory registry. I think that the presence of a custom registry in the `yarn config` should disable all of these checks, or at least there should be a flag to do so.

## Steps to Reproduce (for bugs)
Not sure how to provide a reproducer

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

I'm filing this on behalf of one of my co-workers, I'll update with more details as I have them

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
This is like the third issue today that is being caused by Yarn's incompatible registry proxy. I'm half tempted to detect their proxy and just overrule it with the public npm registry, it's the same damned thing (except for how broken Yarn's proxy is).

I would have hoped Artifactory could get their shit together enough to implement such a basic authentication endpoint. But then they love to have multiple endpoints between install and publish, so ¯\_(ツ)_/¯

**Comment by fenduru** [comment]
For my publish workflow I would expect no requests to be made to yarn OR npm's registry since I'm not publishing there

**Comment by ixalon** [comment]
We see this too with our publishConfig pointing to a private artifactory registry (*.jfrog.io) (without yarn involved - we use npm):

```
401 Unauthorized - GET https://registry.npmjs.org/-/whoami
lerna ERR! EWHOAMI Authentication error. Use `npm whoami` to troubleshoot.
```

**Comment by evocateur** [comment]
@fenduru Of course, but you'd also expect a third-party registry could maybe implement extremely basic endpoints to validate one's authentication? `npm whoami` is a pretty basic thing. 50% of the "my lerna publish command failed" issues I deal with are because of bad authentication credentials.

@ixalon Does `npm whoami` work with the same registry config?

**Comment by ixalon** [comment]
@evocateur `npm whoami` returns the same error, however `npm whoami --registry https://subdomain.jfrog.io/subdomain/api/npm/npm-local/` returns the correct user.

**Comment by fenduru** [comment]
@evocateur I don't disagree with you in theory, but in practice I have two things (Lerna and Artifactory), neither of which I own, and one of which released a new version that no longer works (and previously did). Not to mention that while I suspect this issue would still happen if it was trying to `whoami` against my artifactory, in this case it isn't even doing that - it is trying to `whoami` against `registry.yarnpkg.com` which should really not be involved in the first place (i.e. the check *could* pass against artifactory assuming they had the right endpoints, but will *never* pass against `registry.yarnpkg.com` from my CI build boxes)

Our artifactory doesn't use auth at all though (it is behind corporate firewall), so I'm not surprised that auth-related things don't work. For example, `npm whoami` fails for me because I don't have those config keys set up (because my artifactory doesn't need them).

On a technical note, it seems like this code path is doing error handling before an error actually occurs. I wonder if we could get the same value (i.e. addressing those 50% of "my lerna publish command failed" issues before they get filed) by instead checking for things like registry authentication *after* the publish actually fails, and in a diagnostic capacity rather than for control flow.

**Comment by mikepham** [comment]
I have a similar problem, except the private registry is Nexus and I narrowed it down to how the URL is constructed. I don't know that there's a workaround for my situation. 

Lerna: https://<repo>/repository/npm/-/whoami
Repository: https://<repo>/repository/npm/whoami/-/whoami

I also use scoped packages and have such in `.npmrc`.

```
lerna notice cli v3.4.0
lerna info versioning independent
lerna info Verifying npm credentials
404 Not Found - GET https://<repo>/repository/npm/-/whoami - Not found
lerna ERR! EWHOAMI Authentication error. Use `npm whoami` to troubleshoot.
```

**Comment by dotansimha** [comment]
For me it happens when any registry is set, even the public one.
This workaround worked for me:
```
yarn logout
npm logout
npm login
```

> Don't login to Yarn.

And then run `lerna` with `npm` or `npx` and not with `yarn`.

**Comment by roughcoder** [comment]
We also used scopes and Artifactory.

After half a day of trying to get Artifactory to work differently we have now just resorted to creating an account on npm so that `npm whoami` works just to get past the arbitrary test that has been added even though we never push to npm.

We had to make 2 changes overall, firstly within the `.npmrc` to add the npm registry auth. (this allows `npm whoami` to pass)

```
@somescope:registry=https://yourrepo.jfrog.io/yourrepo/api/npm/npm/

registry=https://registry.npmjs.org/

//clearscoredev.jfrog.io/clearscoredev/api/npm/npm/:_authToken=<token>
//registry.npmjs.org/:_authToken=<token>
```

and now also use the `--registry` flag on the `publish` command to point to out private repo

```
lerna publish --yes --registry https://yourrepo.jfrog.io/yourrepo/api/npm/npm/
```

Although this works it does have quite a gaping issue, if a project has not been updated to use the `--registry` flag our private modules could be published publicly to npm.

**Comment by adanilev** [comment]
Is skipping the `getNpmUsername` check if `--no-verify-access` is passed something that would be accepted if a PR was raised? 

We're using Nexus and whoami doesn't work either as mentioned in #1687. Don't have a viable workaround at the moment.

**Comment by marcofugaro** [comment]
Happens to me also when running the command with `yarn run`

**Comment by lucasowens** [comment]
We started seeing this issue today, and we are still running `v3.3.0`

**Comment by mattbishop** [comment]
+1 this bug is occurring in Azure DevOps pipelines.

**Comment by HsuTing** [comment]
I had the same bug, and I think the problem is [here](https://github.com/lerna/lerna/blob/master/commands/publish/lib/get-npm-username.js#L12).

[npm-registry-fetch](https://www.npmjs.com/package/npm-registry-fetch#optstoken) need the `token` in the `opts`, but the `opts` in the function `get-npm-username` did not have any token. I had print the `opts` before fetching, and this `opts` is just the `@lerna/npm-conf` data.

To test, I overwrote the code like:
```js
fetch.json("-/whoami", {
  ...opts,
  token: '<token>',
}).then(success, failure)
```
and this worked to find the user.

So, maybe this problem is caused by `@lerna/npm-conf`?
I think #1697 is the same problem, too.

**Comment by markmarkyesyes** [comment]
For #1697, the issue isn't hitting the endpoints for artifactory; it is that lerna will not read the registry field in my .npmrc. If there is a configuration step causing this disconnect I would be happy to discuss it and open a PR for documentation around third party registry integration.

**Comment by tianyn1990** [comment]
facing the same issue when update lerna version to `v3.4.0`, so i back to `v2.11.0`

**Comment by guillaumechervetaxa** [comment]
I'am facing the same situation to publish into public npm registry from travis ci.

It seems that the publish is not working when I set a .npmrc at the root folder of the project.
https://github.com/AxaGuilDEv/react-oidc/tree/chore/npm
https://travis-ci.com/AxaGuilDEv/react-oidc/builds/86311432

when I remove it, I am able to publish from my machine with "npm login" before the "publish" command.

**Comment by cyril-lakech** [comment]
Solution maybe https://github.com/lerna/lerna/issues/1705

**Comment by wldcordeiro** [comment]
From reading the release notes of 3.4.1 it looks like patches were made to address this issue?

**Comment by gouegd** [comment]
Thanks @natoehv !
I had an issue with artifactory throwing a 401 when trying to publish via lerna (although manually publishing via npm works). Using yarn's resolutions for a clean install fixed it with the version you gave.

**Comment by tomaswitek** [comment]
Hi I am successfully publishing to a private Nexus with lerna v3.4.3 using this flag `--no-verify-access`

Example
```
lerna publish --no-verify-access
```

Here are docs:
https://github.com/lerna/lerna/tree/master/commands/publish#--no-verify-access

Of course you have to have the right metadata in .npmrc file.

Cheers

**Comment by lucamjj** [comment]
Hi, 
Any news on this issue?

We use a private Nexus with Lerna v3.4.3 (but I also tried 3.5.1) and we tried the above fixes, but nothing worked for us, still getting this error.

**Comment by KingScooty** [comment]
Having the same issues as @lucamjj

**Comment by dlebedynskyi** [comment]
@lucamjj  we are using nexus as well. 
`lerna publish --no-verify-access` helps for me.

**Comment by evocateur** [comment]
Still lacking any verifiable reproduction, so I'm not likely to make progress on this.

**Comment by evocateur** [comment]
v3.8.4 gives up and stops expecting third-party registries to demonstrate any form of competence.

**Comment by ixalon** [comment]
@evocateur Thanks for the workaround. However to be clear, at least with artifactory, the issue was not with the 3rd-party implementation of the registry API, the issue was that learna always ran the whois command against the npmjs registry, even when publishing to a scope controlled by another registry.
