### ISSUE TITLE
Using --scope with publish

### ISSUE THREAD

**Issue by yodasw16** [lerna/lerna#1692]
## Expected Behavior
I would like to be able to run `lerna publish --scope <package-1>` and publish just that package and not any of the others in my repo.

## Current Behavior
Currently I can only run `lerna publish` and since all 7 of my packages have changes they will all publish. If I try to use the --scope filter with publish, I get the error "Unknown argument: scope".

## Possible Solution
Allow --scope to work with lerna publish

## Steps to Reproduce (for bugs)
1. Type `lerna publish --scope <package-1>`
2. See error

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/**/*"
  ],
  "version": "independent"
}
```
</p></details>

## Context
I have 7 packages and they all have changes. 2 of them are new and I would like to publish "alpha" versions so my clients can try them out. I'm not ready to publish the other 5 packages. I thought --scope would allow me to publish only the 2 packages that I want, but it doesn't work. Maybe there is another solution that I just didn't see in the docs.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4 |
| `npm --version`  | 5.6 |
| `node --version` | 8.11.2 |

| OS | Version |
| --- | --- |
| macOS | 10.12.6 |

**Comment by evocateur** [comment]
`--scope` is not allowed for a tagged publish because that would fundamentally break the ability to properly publish the _ignored_ packages. This is because `lerna publish` uses git tags to identify releases, and it does not distinguish between the target package, merely the "most recent" annotated git tag.

This is the compromise you must accept when you dump a bunch of packages into the same repository. They are no longer _truly_ independent, even though the version numbers might seem to imply otherwise.

If you're not ready to publish a package, they should be made private (put `"private": true` in their respective package.json files. They will be versioned, yes, but never published to a registry. To avoid versioning them at all, you shouldn't merge them into `master` (or wherever you publish from).

One way to publish non-versioned prereleases is by using the [`--canary`](https://github.com/lerna/lerna/tree/master/commands/publish#--canary) + [`--force-publish`](https://github.com/lerna/lerna/tree/master/commands/version#--force-publish) flags:
```
npx lerna publish --canary --force-publish <package-1>
```

**Comment by thomasbertet** [comment]
@evocateur can you elaborate or point out some more informations about this ? 
I think I don't quite understand.

> `--scope` is not allowed for a tagged publish because that would fundamentally break the ability to properly publish the ignored packages

Does this mean I can make it work without tagging ? What would be the caveats ? What is a `ignored` package ? 

>  This is because `lerna publish` uses git tags to identify releases, and it does not distinguish between the target package, merely the "most recent" annotated git tag.

Sorry if that sounds a bit dumb, but can you elaborate on why we should rely on git tags ?
If you have any resources on how Lerna works that could help me understand, please share :)

Also, from your POV, do you see any future with the ability to do "single" package release ? 

I would like to use a mono-repo infrastructure for many reasons independent of the release (workspaces mainly) and willing to separate the releases of each packages becauses the teams working on these packages are not the same.

Thanks anyway for your help & your effort on maintaining Lerna, much appreciated!
