### ISSUE TITLE
Lerna add is not reading .npmrc in home folder or project root

### ISSUE THREAD

**Issue by markmarkyesyes** [lerna/lerna#1697]
(Apologies for the need to redact some information from screenshots and logs, I hope it doesn't rob too much context)
## Expected Behavior

Running `lerna add package-name` reads the private registry set in my `.npmrc` file and installs from that source.

## Current Behavior

`lerna add package-name` ignores both an `.npmrc` file in the project root and the computer's home folder, and attempts to install packages from the public npmjs registry.

<img width="803" alt="screen shot 2018-09-21 at 2 16 29 pm" src="https://user-images.githubusercontent.com/18623918/45901624-29033980-bda9-11e8-933a-f701a3a8c67c.png">

## Possible Solution

I have a high suspicion that this is something silly I have missed, but after an hour and a half of searching through issues and posts I am not able to resolve it. Replicated this on a coworkers machine with an identical environment.

## Steps to Reproduce (for bugs)

1. npm i -g lerna@3.4.0
2. mkdir lerna-poc && cd lerna-poc && lerna init && cp ~/.npmrc . && lerna add privatePackage

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
0 silly argv { _: [ 'add' ],
0 silly argv   globs: [],
0 silly argv   lernaVersion: '3.4.0',
0 silly argv   '$0': 'lerna',
0 silly argv   pkg: '@scope/packageName' }
1 notice cli v3.4.0
2 verbose rootPath /Users/UserName/Developer/lerna-poc
3 error Error: 404 Not Found - GET https://registry.npmjs.org/@scope%2fpackageName - User not found
3 error     at res.buffer.catch.then.e (/Users/UserName/Developer/.nvm/versions/node/v6.11.4/lib/node_modules/lerna/node_modules/npm-registry-fetch/check-response.js:104:15)

```
</p></details>

## Context

We are investigating moving a large horizontal codebase to a monorepo because of dependency hell, but due to the large corporate setting, we need to be able to work from a private registry for this application.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.0 |
| `npm --version`  | 3.10.10 |
| `yarn --version` | 1.6.0 |
| `node --version` | 6.11.4 |

| OS | Version |
| macOS Sierra | 10.12.6 |
| NAME | VERSION |

**Comment by Martaver** [comment]
Also experiencing this behavior. My own `npm get registry` returns the correct registry. We're proxying public packages in our private repo, so `npm info <my_package> version` gives us our own private version. However `lerna add <my_package>@<private_version>` won't install it, reporting that the version doesn't exist since it's permanently trying to hit the public registry.

**Comment by Martaver** [comment]
I believe I've found the issue... `lerna` uses the `pacote` package to add deps which accepts the same options as `npm-registry-fetch`. It passes the `registry` option to it in `commands/add/index.js:162` sourced from `this.options`, which is never set.

The `lerna add` command also doesn't recognise the `--registry` argument.

This is the documentation for `npm-registry-fetch`'s `registry` option: https://www.npmjs.com/package/npm-registry-fetch#optsregistry
You can see that when registry isn't specified, it defaults to a hardcoded NPM public registry. 

This would explain why `lerna add` always sources from the public NPM registry.

Expected behaviour should be for `pacote` to use the system configured NPM registry, instead of a hardcoded value. But this isn't likely to happen soon.

In `core/command/index.js` we can see that lerna allows for overrides to the command options sourced from lerna.json, which allows for a workaround adding the following to your `lerna.json`:

```
{
	"command": {
		"add": {
			"registry": "<private_repo_url>"
		}
	}
}
```

This is pretty inconvenient though, since we have our local npm client already configured and maybe even a `.npmrc` file in our repo. We shouldn't have to explicitly provide the registry to the `add` command.

The best current solution would be for `lerna` to source the current npm registry in its configuration and pass that. We can use the `registry-url` package for this.

After requiring it in `commands/add/index.js` we can update line `163` to:

```
registry: this.option.registry || registryUrl()
```

This fix works on my local build of lerna.

**Comment by cronon** [comment]
facing the same issue during `lerna bootstrap` execution - it wants to download private packages from public repo, though private repo is specified in .npmrc file

**Comment by markmarkyesyes** [comment]
@Martaver Thanks for the excellent deep dive into this problem. Depending on how my week goes, I will try to open a PR for this in lerna as a proposal for your solution before the weekend.

**Comment by jbockle** [comment]
lerna publish is also having the issue not using the defined registry in `.npmrc`, I have to use `--registry` option
