### ISSUE TITLE
How to upgrade from Lerna v2 to v3?..

### ISSUE THREAD

**Issue by busticated** [lerna/lerna#1711]
hey there 👋 

apologies if this is a dupe - i tried searching through the README and issues here but couldn't turn up an answer.

is there an upgrade guide of any sort explaining how to take a project using lerna v2 to v3?

if not, perhaps i can take a crack at it as i go through the process. all tips / pointers very much appreciated 🙏 

thanks!

**Comment by wldcordeiro** [comment]
There isn't one as far as I can tell, there is the breaking changes list in the changelog for 3.0 which I used. For most usage it seemed unchanged, `publish` though changed in what arguments exist and that was my biggest hurdle.

**Comment by evocateur** [comment]
I recommend the following:
```
npm i -D lerna@latest
npx lerna link convert
```

There's not a lot of migration documentation, sorry.

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, due to its age it is no longer applicable because at the time of writing we are version 5.x of lerna.

If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
