### ISSUE TITLE
lerna does not respect $PATH variable

### ISSUE THREAD

**Issue by lucasbraun** [lerna/lerna#1758]
I want to use a different git version than the one in `/usr/bin` because that one is too old for `lerna publish`) to work. I have added my newer git version (which works with lerna) to $PATH, but `lerna` seems to pick the one in `/usr/bin` nevertheless (even if I explicitly remove `/usr/bin` from $PATH). I was able to track the problem down to `execa` which seems to be the root cause of that problem and I created a ticket there (with more information how to reproduce my problem):
https://github.com/sindresorhus/execa/issues/153

Could you please integrate their changes as soon as they become available? That would be much appreciated.

Thanks!

**Comment by ThisIsMissEm** [comment]
This seems like an issue where we'd need to know what the expected behaviour of `execa` is in order to resolve.

**Comment by westmark** [comment]
We encountered this exact problem today. The issue is that `execa` defaults the option `preferLocal` to true, which means it will by default _prepend_ some paths, including the path for the node executable(`process.execPath`). In our case it prepended with `/usr/bin` which contained an old version of git. This happened on a Jenkins server outside of our control and was poorly maintained(apparently).

We don't expect `execa` to change this behaviour, so we propose that `lerna` default to sending `preferLocal: false` in all calls to `sync()`, or at least allow `preferLocal` to be configurable in `lerna.json`.

**Comment by evocateur** [comment]
How exactly does execa's `preferLocal` option cause this error? [npm-run-path](https://www.npmjs.com/package/npm-run-path) is what is actually [modifying the env](https://github.com/sindresorhus/execa/blob/bfc9a4e228b7f865c4cff113fb5c015ebc0e01cc/index.js#L62-L64) when preferLocal is `true`, but I don't see how it would prepend paths like `/usr/bin` by itself.

**Comment by evocateur** [comment]
Looking deeper, I do indeed see the problem in npm-run-path. There is an open PR that needs some help. This option won't change in lerna because it is necessary to make hoisted executables work, as well as maintain parity with `npm run` semantics.
