### ISSUE TITLE
lerna run stuck alpine docker

### ISSUE THREAD

**Issue by zefexdeveloper** [lerna/lerna#1797]
I have this `Dockerfile` and the last command should run but it doesn't for some reason:

```
FROM node:11.2.0-alpine

WORKDIR /usr/src/app

RUN yarn global add lerna

COPY package.json yarn.lock ./
RUN yarn --pure-lockfile

COPY packages/server/package.json packages/server/package.json
COPY lerna.json .

RUN lerna bootstrap

ADD packages/server packages/server

ENV NODE_ENV=development

EXPOSE 4000

CMD ["yarn", "start"]
```

In order to check what was happening I did `docker run -it server:latest sh` and inside of the shell I ran manually `yarn start`, that is a script inside my `package.json` for `lerna run start`, but it gets stuck at:

![image](https://user-images.githubusercontent.com/30276092/49132365-f569f180-f2ba-11e8-9aa2-bccdb36180f7.png)

Any idea of what might be happening?

**Comment by evocateur** [comment]
It's not clear to me why lerna has to run this command, and I'm not a Docker whiz, but I assume `--stream` is necessary because otherwise no stdio is emitted and Docker is probably waiting for that. By default, `lerna run` batches up the stdio and only emits it after the subprocess has exited. `--stream` avoids this batching, immediately piping stdio to the current shell.
