### ISSUE TITLE
lerna bootstrap does not respect --ignore-scripts, but docs say it should

### ISSUE THREAD

**Issue by Slapbox** [lerna/lerna#1800]
## Expected Behavior
`lerna bootstrap --ignore-scripts` should not run prepublish scripts

## Current Behavior
`lerna bootstrap --ignore-scripts` runs prepublish scripts anyway

## Steps to Reproduce (for bugs)
1. `lerna bootstrap --ignore-scripts` (at least on Windows 7)

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "version": "3.0.0",
  "useWorkspaces": true
}
```
</p></details>

## Context
**Problems this causes:** Lots of time spent rebuilding native node dependencies in my case

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.4.3 |
| `npm --version`  | 6.2 |
| `yarn --version` | 1.12.3 |
| `node --version` | 10.13.0 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| Windows 7 | x64 |

**Comment by Slapbox** [comment]
I guess you can't pass the argument directly to `lerna`. This works to ignore scripts: 

`lerna bootstrap -- --ignore-scripts`

My issue is resolved, but I'm going to leave this open in case the maintainers feel this could use clarification in the docs.

**Comment by evocateur** [comment]
In your case, it's actually Yarn workspaces that is causing the problem (`{ "npmClient": "yarn", "useWorkspaces": true }` in your lerna.json). `lerna bootstrap` just calls `yarn install` instead of going down the rabbit-hole of logic that includes `--ignore-scripts`. Passing the flag after `--` passes it directly to yarn, which is the correct path for passing flags directly to the package manager (the option happens to be named the same in both lerna, npm, and yarn).

**Comment by Slapbox** [comment]
Thanks for providing some clarity on that @evocateur. Always appreciate your help.
