### ISSUE TITLE
`publish from-package` ignores `allowBranch` command contrary to docs

### ISSUE THREAD

**Issue by itaylor** [lerna/lerna#1823]
It appears that the new `publish from-package` command doesn't support, `allowBranch` or possibly any of the arguments of the `version` commands, but [the docs](https://github.com/lerna/lerna/tree/master/commands/publish#options) would lead one to believe that it does:
> lerna publish supports all of the options provided by lerna version in addition to the following:

## Current Behavior
```bash
$ lerna init
lerna notice cli v3.6.0
lerna info Creating package.json
lerna info Creating lerna.json
lerna info Creating packages directory
lerna success Initialized Lerna files
$ echo '{
>   "packages": [
>     "packages/*"
>   ],
>   "version": "0.0.0",
>   "command": {
>     "publish": {
>       "allowBranch": "foobar"
>     }
>   }
> }' > lerna.json
$ git add *
$ git commit -m "test"
$ git push origin master
$ git branch
* master
$ lerna version major
lerna notice cli v3.6.0
lerna info current version 0.0.0
lerna ERR! ENOTALLOWED Branch 'master' is restricted from versioning due to allowBranch config.
lerna ERR! ENOTALLOWED Please consider the reasons for this restriction before overriding the option.
$ lerna publish from-package
lerna notice cli v3.6.0
lerna info Verifying npm credentials
lerna http fetch GET 200 https://registry.npmjs.org/-/npm/v1/user 757ms
lerna notice from-package No unpublished release found
lerna success No changed packages to publish
```

## Expected Behavior
I would have expected the same output as from `lerna version major`, that the branch is not allowed. 
Although in the above example, it did not publish because this was an empty repo with no packages, if there had been some there it would have published them, despite the branch `master` not being in the `allowBranch` config.

## Possible Solution
It seems like `lerna publish from-package` is not running any of the validation steps that `lerna version does`

## Context
We had an incident where our CI server accidentally published private branches to our internal NPM (artifactory) because we believed from the docs that the allowBranch config would have prevented it.
 
## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.6.0 |
| `npm --version`  | 5.6.0 |
| `yarn --version` | 1.12.3 |
| `node --version` | v8.11.3 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.1 |

**Comment by evocateur** [comment]
This is why it is always safer to run `lerna version` and `lerna publish from-git` (or whatever) in sequence. They are increasingly separate concerns, and in a future breaking release will be completely separated.

**Comment by evocateur** [comment]
To be clear, only the options that `lerna version` provides that are _used_ in `lerna publish` will be respected. Since `lerna publish from-package` skips nested execution of `lerna version` (as there is nothing to be done in that capacity), none of `lerna version`'s validation will occur.

Put another way: In cases where no `git` changes are going to be made (like `from-package`, `from-git`, or `--canary`), most of the `git`-related validation will be skipped. We still validate that the working tree is clean in all cases, however.

Now that I've rephrased it twice, I tend to agree that `lerna publish from-package` _should_ respect the `--allow-branch` config.

(`from-git` doesn't make sense, since it only operates on existing tagged releases, and `--canary` is always "off the grid", since it never publishes versions that will override any existing release)
