### ISSUE TITLE
Lerna breaks npm-run-all when loglevel is silent

### ISSUE THREAD

**Issue by GuyMograbi** [lerna/lerna#1842]
- Configure your npm to be silent by having `.npmrc` file with `loglevel=silent`
 - have `npm-run-all` in `postinstall`. 

## Expected Behavior
Everything should work as if I was using npm

## Current Behavior
Lerna breaks `npm-run-all` as it passes --silent to lerna that does not know how to handle it. 

`npm-run-all` uses `NPM_EXECPATH` which is replaced by `lerna`.    
The value in `NPM_EXECPATH` should be compatible but is not. 

## Possible Solution
support flag --silent

## Steps to Reproduce (for bugs)
 - Configure your npm to be silent by having `.npmrc` file with `loglevel=silent`
 - have `npm-run-all` in `postinstall`. 

Opened bug for `npm-run-all` to remove `--silent` at: https://github.com/mysticatea/npm-run-all/issues/158

**Comment by evocateur** [comment]
What _specific_ execution are you attempting to run in a `postinstall` phase?

Not having all the details, it seems like the workaround is to pass an explicit `--npm-path npm` argument to `npm-run-all`?

**Comment by GuyMograbi** [comment]
> "What specific execution are you attempting to run in a postinstall phase?"

I am running some other npm tasks. Example package.json could look like this: 


```
{
    "name": "example", 
    "version": "0.0.0", 
    "scripts": {
        "postinstall": "npm-run-all bower:install webdriver:update", 
         "bower:install": "bower install --allow-root ",
         "webdriver:update": "webdriver-manager update --versions.standalone=3.5.3   --versions.chrome=2.42"
      }
}
  
```
> "Not having all the details, it seems like the workaround is to pass an explicit --npm-path npm argument to npm-run-all?"

I will test this and update you, but this is a workaround. According to `npm-run-all` since Lerna is overriding `npm_execpath` variable, it should support the same flags as npm would. In this case `--silent` at least for `lerna run...` subcommand.

**Comment by evocateur** [comment]
> since Lerna is overriding `npm_execpath` variable

That's not Lerna, that's [npm-lifecycle](https://github.com/npm/npm-lifecycle/blob/d7a014f9393da76ee0ecf6701be84ed1ea613b83/index.js#L82), the official extraction of programmatic `npm run`. There's not much I can do from the Lerna side, as that env var is set no matter what I pass in (or set).

In this particular case, `lerna run` should never be _called_, because it isn't a general replacement for `npm run`, as `npm-run-all` seems to think. An explicit `--npm-path` is the easiest, clearest fix.

Another way of "fixing" this is to kick `lerna bootstrap` to the curb, run `npx lerna link convert` once, move the current `postinstall` to `prepare`, and live the glorious life of one root `npm install` (just like the lerna source).
