### ISSUE TITLE
[feature] Single source of semver string for shared dependencies?

### ISSUE THREAD

**Issue by estaub** [lerna/lerna#1882]
I have a lot of non-dev dependencies that I want to keep consistent across packages by specifying the version in only one place. 

A natural way to do this might be to use a version specifier on the root dependency, but totally wild-card ("" or "*") each package's dependency version.  At publish time, lerna could detect this condition and replace the wild-card in each package with the root-specified version.

So if _some-monorepo_'s `package.json` said:
`  "react": "^16.8"
`
and package _some-package_'s `package.json` within _some-monorepo_ said:
`  "react": ""
`

then published, _some-package_'s `package.json` would read the same as the root:
`  "react": "^16.8"
`

Publication would not affect the version in the local package.json, only in the tarball.

If there's some fear of regression (collision with a valid use of wild-card in this context), the trigger for version replacement might alternatively be:
- only one of `"*"` or `""`, leaving the other free.
- a magic tag, say `__lerna-root` or something.

One virtue of this scheme is that the full wild-card or tag is a big signal to go look in the root.

I don't have experience with scopes, but it seems like maybe they need to be considered for this.

If there's some already-existing way to accomplish this that's nearly as easy, I'm all ears!

**Comment by estaub** [comment]
Can you explain?  I don't see how peerDependencies can be used to create a single point where shared dependency versions are specified - they must be replicated throughout the package.json's where the dependencies are used.  The best I can see is using them to cause an error when a package.json deviates, by creating a peerDependency in a base package.  While this has some value, it still requires upkeep of all the dependencies, and sometimes creation of dummy packages where dependencies differ between packages. But maybe there's some idiom I don't know.

I'd think that there'd be a strong association between wanting this and using a monorepo, hence the thought that it might be a good lerna feature.

**Comment by evocateur** [comment]
If you specify all your leaf package dependencies on react as a peer with a reasonably broad range, you can control the exact version in the root. Peers are preferred for packages like React that are singletons.

I don't see the point of a Lerna-specific wildcard because I don't want to manage packages (Lerna isn't a package manager) and the burden of changes of this nature are among the trade-offs one accepts when choosing the monorepo pattern.

I'm certainly open to new sub commands to help streamline this sort of thing. `lerna upgrade` and `lerna remove` are two such commands that have long sought implementations.
