### ISSUE TITLE
Transitive dependencies (peer dependencies are not linked by lerna)

### ISSUE THREAD

**Issue by slavafomin** [lerna/lerna#1892]
Hello!

First of all, thank you for this great tool and your hard work.

However, I've encountered a problem, which I cannot find a way to untangle without using some nasty workarounds.

I have a monorepo with several packages, some packages are components, which I'm building using other packages. I've pictured all the important dependencies on the following image:

![deps-scheme](https://user-images.githubusercontent.com/1702725/51699272-627cd780-201d-11e9-80df-10c44fd2fedc.png)

Rectangles are my local packages, ovals are third-party dependencies. Arrows show dependencies. Dashed arrow is a peer dependency.

The `Component Package` is a package I'm trying to build.

The `Bundler` is our internal build tool. It's an orchestrator like Gulp or something.

`Bundler` is using a `Build Scenario` to run `Rollup Processor` and compile the source code in the `Component Package`. However, the Rollup's configuration file as well as plugins configuration is stored inside of a `Build Scenario` package, which depends on `License Plugin`.

The `License Plugin` requires the `Rollup` under the hood in order to check it's version. So, it's a peer dependency for it. I've marked it with a dashed arrow in the image.

The `Rollup Processor` is a package which actually depends on the `Rollup` (which it executes).

When normal `npm install` is done inside of the `Component Package`, all dependencies are properly installed, i.e.: `Component > Scenario > Processor > Rollup`. So when `License Plugin` is trying to load the `Rollup` it gets the installed version correctly.

The problem arises with lerna linking. When lerna links all the packages, the `License Plugin` doesn't get a link to the `Rollup`, because it doesn't depend on it directly, but only transitively through a peer dependency. 

In the end, I can't build the `Component Package`, because the `License Plugin` couldn't find a `Rollup` dependency.

Take notice, that I can't make `Rollup` a dependency of the `Scenario`, because the scenario doesn't care about an actual rollup version to use. It is controlled by the processor.

I think that lerna linking should take peer dependencies into account and try to link to them through the dependencies of the parent packages. In my example, it should see that `License Plugin` is using `Rollup` as a peer dependency and it should start looking for a package to link by resolving dependency chains from it's parent `Build Scenario`.

I know it looks complicated, but it's a viable use case and it should be implemented in order to make such transitive dependency schemes work.

The ["hoisting" feature](https://github.com/lerna/lerna/blob/master/doc/hoist.md) could help here, but it's too aggressive in my opinion and it has its own problems.

What do you think?

**Comment by slavafomin** [comment]
Today, I've tried to use yarn with workspaces and disabled hoisting — the aforementioned problem has not surfaced. It looks like yarn takes such dependencies into consideration. It would be great to make it work with `npm-cli` as well.

**Comment by evocateur** [comment]
Actually, what yarn is doing is installing almost everything in the root `node_modules`, which is resolved correctly when scripts run from the various leaf nodes.

Generally speaking, a package specified in `peerDependencies` should _also_ be specified in `devDependencies`. That's how the pattern works for "traditional" npm packages, and in a monorepo it's best to just install those peers in the root and let the node module resolution algorithm do the work.

The best practice for monorepos, in my opinion, is to run all dev scripts from the root, not the leaf nodes. It helps reduce repetition, is often times faster, and avoids weird bugs like this.

**Comment by slavafomin** [comment]
@evocateur So, if License Plugin on my scheme would add Rollup as a dev dependency, will lerna install it? And if so, shouldn't lerna install only non-dev dependencies for non-local packages?

**Comment by evocateur** [comment]
Just install the license plugin in the root. Any leaf package that has a peer dependency on that license plugin will automagically get it due to how Node resolves imports. Lerna doesn't have to do anything.

**Comment by slavafomin** [comment]
@evocateur why are you closing this issue? It's a legitimate problem. Your advice on "Just install the license plugin in the root" is a dirty workaround and not a proper solution.

**Comment by evocateur** [comment]
My mistake, here's the solution: Install _both_ the license plugin _and_ Rollup in the root.

If you think that's too "dirty", then `Build Scenario` also needs a direct (dev) dependency on Rollup. This is no different than installing a package like [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) which _explicitly_ mentions installing it's peer dependencies.

I closed this issue because it is not Lerna's job to replace package managers. I gave you the solution for `npm`, explained why Yarn appeared to work, and I don't know what else to say.

**Comment by AlexLeung** [comment]
I faced a problem where my monorepo had the following structure

- Package `@mymonorepo/X` has a peerDependency on `some-npm-package`
- Package `@mymonorepo/Y` has a dependency on both `@mymonorepo/X` and on `some-npm-package`

I expected that when I ran `@mymonorepo/Y`, it would work, since it installs the `some-npm-package` that `@mymonorepo/X` was asking for as a peer dependency. However when I ran `@mymonorepo/Y`, here was a module not found error coming from the source file of `@mymonorepo/X`, saying that `some-npm-package` could not be found.

Now in reality this is a problem with npm and not with lerna. See [this post](http://chevtek.io/you-can-finally-npm-link-packages-that-contain-peer-dependencies/) which describes the issue that plagues even normal `npm link`. The solution I found involves running `@mymonorepo/Y` with the node CLI flag `--preserve-symlinks`

**Comment by evocateur** [comment]
Or just install `some-npm-package` in the root of the repo? The `node_modules` resolution algorithm is your friend.

**Comment by gaurav5430** [comment]
> Actually, what yarn is doing is installing almost everything in the root `node_modules`, which is resolved correctly when scripts run from the various leaf nodes.
> 
> Generally speaking, a package specified in `peerDependencies` should _also_ be specified in `devDependencies`. That's how the pattern works for "traditional" npm packages, and in a monorepo it's best to just install those peers in the root and let the node module resolution algorithm do the work.
> 
> The best practice for monorepos, in my opinion, is to run all dev scripts from the root, not the leaf nodes. It helps reduce repetition, is often times faster, and avoids weird bugs like this.

can you elaborate more on the pattern why peer deps should also be added as dev deps, and what do you mean by traditional nom packages?

**Comment by AlexLeung** [comment]
@gaurav5430 if you use Yarn 2 workspaces then you won't have to worry about node_modules hell anymore. So glad I switched to Plug n Play.

**Comment by polkovnikov-ph** [comment]
Well, here is a use case. I have a monorepo with several projects and `eslint-config` for them. `eslint-config` depends on a plugin. Due to [decision](https://github.com/eslint/eslint/issues/3458) (or lack thereof) by `eslint` authors, the two options are:

- Put the plugin into each and every depending package as explicit dependency. Versions of plugins are duplicated and may diverge, so it's not really an option.
- Make plugin a peer dependency of `eslint-config` package, and entrust package manager to install it into all dependents of `eslint-config`. When I use `lerna bootstrap` to install dependencies, and `lerna` doesn't install `peerDependencies`, I find myself in an awkward situation when authors of two widely used packages have mutually exclusive opinions on how things should work, and neither of those packages works correctly.

Cc @mdjermanovic @evocateur

**Comment by gaoxiaoliangz** [comment]
@evocateur Think about this use case.
packages
- `A` (peer dep `C@v1`)
- `B` (peer dep `C@v2`)

Now I cannot install `C` in the root, since `A` and `B` depend on different versions of `C`, how can I solve this?
