### ISSUE TITLE
`lerna publish` doesn't publish due to no change since last release in CI

### ISSUE THREAD

**Issue by imolorhe** [lerna/lerna#1903]
Hello,

I am trying to publish packages in travis CI for my project, along with other deployment processes. For my setup, I create a tag with a new version for the project and the deployments are triggered on every new tag. I want to publish the packages for that tag in the CI.

I use `lerna publish from-git --force-publish=* --no-git-tag-version --no-push --yes` to publish but it doesn't work, saying that there are no changes to publish.

Is there something I am missing, or is it not possible to achieve this with lerna?

**Comment by marikaner** [comment]
To my understanding this is not possible. I saw another request of this kind before https://github.com/lerna/lerna/issues/1868. But it would be very helpful in our case, too.

**Comment by evocateur** [comment]
_Assuming_ you're using `lerna version` when you "create a tag", all you need in CI would be `lerna publish from-git --yes`. Creating a tag from a Github release (or whatever) isn't sufficient, as there is more going on than just `git tag` when Lerna versions a release.

I'm unclear why you think you need `--force-publish` (the `*` is implicit)? `lerna version` is already able to identify what changed since the last release and only version those packages (and their dependents).

**Comment by evocateur** [comment]
"external files", like, outside the git repo? That doesn't sound safe, or supported, for that matter.

`lerna version` does all the tagging and pushing for you, anything you do separately I can't exactly diagnose, and likely isn't working because it's not creating all the tags (if it's independently versioned, that is).

**Comment by imolorhe** [comment]
Not outside the repo, but outside the packages directory.

**Comment by imolorhe** [comment]
The full command I use for versioning with lerna is:

`lerna version $NEW_VERSION --force-publish=* --no-git-tag-version --no-push --yes;` where $NEW_VERSION is an argument passed to the script.

**Comment by imolorhe** [comment]
I don't want lerna to push anything to the repository. I can make do with tagging locally though (I'd make all the necessary changes before calling lerna so it adds the changes to the tag).

**Comment by evocateur** [comment]
> `lerna version $NEW_VERSION --force-publish=* --no-git-tag-version --no-push --yes;`

Honestly, I don't even know why you're using `lerna version`, you're 80% of the way to your own custom publisher.

Things outside the package directories shouldn't be required by the packages, that's basic npm etiquette (no different than a "traditional" one-per-repo package).

This request is out of scope for lerna, sorry.

**Comment by evocateur** [comment]
[collect-updates](https://github.com/lerna/lerna/blob/master/utils/collect-updates/collect-updates.js) is where the rubber hits the road. But in general terms, once we've identified the subpaths where packages live, we just loop through them and run `git diff --name-only ${PREVIOUS_TAG} -- packages/${PACKAGE}` and if there are [changes that aren't ignored](https://github.com/lerna/lerna/blob/aaa182565606a93a6e03ea23ec2c702041c7ca0d/utils/collect-updates/lib/make-diff-predicate.js#L14) we add them to the list of packages to operate on.

Deceptively simple.

**Comment by alexjsdev** [comment]
so i have a question that i can't seem to find the answer too... I changed the root babel config that is used by all the packages in my lerna monorepo, how do i get lerna to republish (which is when it will re-transpile) all the packages so they will be using my latest babel config? Since my babel config is outside of the `packages/` directory, lerna is saying there are no changes to publish...

**Comment by acao** [comment]
@alexjsdev also just discovered this as well, has made things much more harmonious to skip `lerna version` altogether, was able to grok this from the maintainer's comments in various gh issue threads! good to know that force-publish is working was about to try it out for forcing prerelease graduations?

**Comment by appsparkler** [comment]
I bumped the version of the package that I wanted to publish and then I was able to publish it. 😀
