### ISSUE TITLE
publishing a package that contains a private dependency

### ISSUE THREAD

**Issue by oreporan** [lerna/lerna#1906]
## Expected Behavior
When publishing a package that has a dependency to another package marked `private: true`
Expect that the public package is published successfully, including the code from the private package without having to publish the private package.

## Possible Solution
Replace `import x from private-package` -> `import x from ../../package/location`

<details><summary>lerna.json</summary><p>

```json
{
    "lerna": "2.11.0",
    "packages": [
        "packages/*",
    ],
    "version": "0.0.0",
    "npmClient": "yarn"
}

```
</p></details>

## Context
We want to publish a package without its private deps

**Comment by evocateur** [comment]
That should definitely fail, in my opinion. Lerna is not magic, and attempting to publish packages with private `dependencies` literally means you're publishing broken packages. If anything, Lerna should throw an error when this is attempted.

(adding private local packages to `devDependencies` is perfectly fine, since no consumer ever installs `devDependencies`)
