### ISSUE TITLE
Feature: Provide an option to ignore merge commits in lerna changed command

### ISSUE THREAD

**Issue by Feiyang1** [lerna/lerna#1909]
I'd like to have an option to ignore all merge commits in lerna changed command.
We have a release branch we use as a staging area for the next release while the development continues in the master branch. Eventually we will publish the release candidate in the release branch and merge it back to the master branch.
In the next release cycle, the updates in the merge commit are seen as changes and the same package gets bumped again even though it doesn't have any change except for the version bump in package.json from the last release.

## Expected Behavior
Provide an option to ignore merge commits when running `lerna changed`

## Current Behavior
Merge commits are considered in `lerna changed` with no option to opt out

Related issues:
https://github.com/lerna/lerna/issues/1377

**Comment by evocateur** [comment]
Pretty sure [`lerna ls`](https://github.com/lerna/lerna/tree/master/commands/list#readme) combined with [`--since`](https://github.com/lerna/lerna/tree/master/core/filter-options#--since-ref) would accomplish this? Without an argument, it just looks for the last release tag in the current branch. It accepts any git ref you can think of (tag, branch, sha). It always excludes merged tags.

I'm a little unclear what your process is exactly because my eyes glaze over when trying to follow your explanation, sorry.

```
npx lerna ls --since
```

**Comment by Feiyang1** [comment]
You are absolutely right. Thank you!
It would be nice if `lerna changed` can be configured to find the last tag in all branches instead of --first-parent as described in https://github.com/lerna/lerna/issues/1377#issuecomment-431914036

Is it something you would consider?

**Comment by evocateur** [comment]
`lerna changed` is not filterable like `lerna ls` is. It's intentional, as `lerna changed` is meant to preview `lerna publish` and `lerna version`, neither of which are filterable by `--scope` or `--ignore`.

As for finding the last tag in all branches, surely `git` has enough flags and subcommands where one can do that without burdening `lerna` with yet more complexity.
