### ISSUE TITLE
Publish attempt without being logged in failed and can't re-publish

### ISSUE THREAD

**Issue by gauntface** [lerna/lerna#1912]
Lerna is fairly aggressive in *thinking* it's published a package when it hasn't.

I attempted a publish, it failed when I wasn't logged in to npm.

Lerna now believes it's published because the packages are version bumped locally, there are no new commits and that's it.

I'm now having to figure out the --force-publish flag, which I struggle to get working with zsh:"

```
$ lerna publish --force-publish=*
zsh: no matches found: --force-publish=*
```

```
$ lerna publish --force-publish="*"                                                  1 ↵
info cli using local version of lerna
lerna notice cli v3.10.7
lerna info current version 0.0.6
lerna info Looking for changed packages since v0.0.6
lerna WARN force-publish all packages
lerna ERR! ERELEASED The current commit has already been released. Please make new commitsbefore continuing.
```

**Comment by gauntface** [comment]
Note for those hitting this / for myself in the future:

Lerna makes the git tags as well as bump the versions. To force publish after a failed NPM publish, you'll need to delete the tag locally (and presumably remotely) to be able to perform a force publish.

**Comment by evocateur** [comment]
Clearly I'm not doing a good enough job of documenting the existing options for `lerna publish`, because there have been [positional arguments](https://github.com/lerna/lerna/tree/master/commands/publish#positionals) available for several months now to help in just the sort of situation you're describing here.

You don't need `--force-publish` if you're on the commit generated by `lerna version`. `lerna publish from-git` is all you need in that context.

**Comment by gauntface** [comment]
My assumption is that running the same command should work.

Ideally, in this specific example, lerna would check if I'm logged in before making any local changes and failing early.

An `npm whois` check could be run early in the publish command and exit if the command returns an error.

**Comment by evocateur** [comment]
> My assumption is that running the same command should work.

That assumption unfortunately suffers from the fact that the repository context has changed, so it's not actually the "same" command, as it is operating with different tags etc. In the next major, `lerna publish` will no longer implicitly call `lerna version` (#1767), so your assumption in this case will have a better chance of matching the actual behavior.

> Ideally, in this specific example, lerna would check if I'm logged in before making any local changes and failing early.

Your npm auth is orthogonal to your git auth. `npm publish` doesn't care whether or not the code being packaged is already pushed to the remote (or even _in_ version control, for that matter). Lerna already verifies npm auth (if you're using the default public registry) before attempting to publish (but _after_ implicitly versioning).

**Comment by gauntface** [comment]
Would it be possible for lerne to verify npm auth *before* versioning?

**Comment by davidhouweling** [comment]
I have an issue where one of the prepare scripts sometimes fails out due to certain issues... when it does it stops the publish entirely, however lerna has already pushed to git the publish and the tags even though none of the packages were actually published. Ideally the push to git shouldn't occur until after the publish has been completed for the packages... and if a package fails, it should revert all publish commit and all the tags.
