### ISSUE TITLE
lerna ls --since REF --json returns empty string with no changed packages instead of empty array

### ISSUE THREAD

**Issue by bdwain** [lerna/lerna#1945]
## Expected Behavior
`lerna ls --since REF --json` prints [] if there are no changed packages

## Current Behavior
`lerna ls --since REF --json` prints an empty string if there are no changed packages

## Possible Solution
not sure off the top of my head but i'd be happy to do a pr to fix it

## Steps to Reproduce (for bugs)
on master, run `lerna ls --since master --json`

## Context
i have a script that runs this to get changed packages. It needs a special case to handle no packages which is unnecessary

the behavior seems to have changed recently. it used to return a non-zero exit code if there were no unchanged packages, which also seemed wrong.

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.0 |
| `yarn --version` | 1.12.3 |
| `node --version` | 10.14.2 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by evocateur** [comment]
`lerna ls` has never exited non-zero with no results. `lerna changed` _does_ exit non-zero, as it was intended to be a filter for `lerna publish` in CI (for example). (`lerna changed` is equivalent to `lerna ls --since`)

ba54439 was a bit overzealously trying to avoid an empty `console.log()`. Perhaps testing `result.text.length` instead of `result.count` is more appropriate? It would still emit an empty array, in your case.

I have a fix forthcoming.

**Comment by evocateur** [comment]
As for the non-zero exit with no results, that's a breaking change. I largely agree with it, btw, as it matches the behavior of `grep` with no results.

**Comment by bdwain** [comment]
thanks!
