### ISSUE TITLE
lerna exec environment variable LERNA_PACKAGE_NAME is not passed in makefile

### ISSUE THREAD

**Issue by vroudge** [lerna/lerna#1965]
## Expected Behavior
`$(LERNA_PACKAGE_NAME)` should contain the name of the package

## Current Behavior

`LERNA_PACKAGE_NAME` is empty

## Steps to Reproduce (for bugs)

1. Using a makefile in a monorepo with multiple packages.
```
build:
	@./node_modules/.bin/lerna exec -- echo $(LERNA_PACKAGE_NAME)
```

2. running `make build` echoes nothing.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.4.0",
  "packages": [
    "packages/*"
  ],
  "version": "1.0.0",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "npmClientArgs": [
    "--no-lockfile"
  ]
}```

</p></details>

## Context

Trying to automate a build in a makefile such as 

```
build:
	@./node_modules/.bin/lerna exec --parallel -- babel --config-file ../../babel.config.js --source-maps inline --no-babelrc -d ./dist src
	@./node_modules/.bin/lerna exec -- docker build -t xxx/$(LERNA_PACKAGE_NAME) .
```

**Comment by dschnare** [comment]
I've experienced the same behaviour with a bash script with the following switches enabled:

```
set -euo pipefail
```

I can echo `LERNA_PACKAGE_NAME` using vanilla example just fine if I comment out the flags.

```
# test.sh
# set -euo pipefail
lerna exec -- echo ${LERNA_PACKAGE_NAME}
```

**Comment by dschnare** [comment]
I've also experience some really odd behaviour that may or may not be related. If I were to call `source` in the executed commands passed to `lerna exec` then the current working directly is reset to the monorepo project directory and NOT the package being executed.

Example:
```
# test.sh
lerna exec --scope app-* --stream -- . somefile.env && ls
```

```
# somefile.env
VAR=47
```

NOTE: I can't actually even use `source` I have to use `.` instead because the `source` command is apparently not found when lerna executes.

The directory listing is of the repository directory and not of the each individual package!
Reason I *think* this could be related is because I can't for the life of me use `$LERNA_PACKAGE_NAME` to construct the file name of the sourced file. Even if I follow the examples and escape the `$`:

```
# test.sh
ENV_PREFIX=.env
lerna exec --scope app-* --stream -- . ${ENV_PREFIX}/\$LERNA_PACKAGE_NAME.env && ls
```

In this case `$LERNA_PACKAGE_NAME` is never expanded and so the file is never found.

**Comment by dschnare** [comment]
As a follow up, this expands `$LERNA_PACKAGE_NAME` as an empty string. I would have expected it to be available.

```
# test.sh
ENV_PREFIX=.env
lerna exec --scope app-* --stream -- . ${ENV_PREFIX}/${LERNA_PACKAGE_NAME}.env
```

**Comment by dschnare** [comment]
I've solved my issues.

1) I was using `&&` and `;` to combine commands expecting `lerna exec` would be read the entire line after `--` and execute the command line
2) I wasn't handling delayed expansion correctly

What works:

```
set -euo pipefail
ENV_PATH=/home/ubuntu/.env

export ENV_PATH
lerna exec --scope app-* --stream -- '. ${ENV_PATH}/${LERNA_PACKAGE_NAME}.env && npm run build'
```

**Comment by evocateur** [comment]
Yeah, woulda told you to single-quote the whole command after `--` had I seen this earlier, sorry. If you don't, as you discovered, the entire line is interpreted by `bash` before `lerna` ever sees it, and `&&` is not passed into `process.argv`.
