### ISSUE TITLE
Missing HTTP_NPM_SCOPE header when publishing

### ISSUE THREAD

**Issue by m2bright** [lerna/lerna#1968]
We are attempting to do a lerna publish to packagecloud.io. The packagecloud.io API is failing with a 422 indicating that the NPM_SCOPE parameter is not set properly. After speaking with one of their engineers, they are expecting that the HTTP_NPM_SCOPE parameter be set properly, and in fact it is not being passed.

## Expected Behavior

We are expecting that `lerna publish` will publish to packagecloud.io.

## Current Behavior

We are told that the `HTTP_NPM_SCOPE` parameter is not being set by lerna, when the publish is being called.

## Possible Solution

Can we add that as part of the publish?

## Steps to Reproduce (for bugs)

1. Have a packagecloud account.
2. nvm install (lts/dubnium) (this is node 10.15.3 and npm 6.4.1)
3. run npm publish ( It will publish)
4. run lerna publish (it will fail with a 422 indicating that the npm-scope variable is missing.)

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
{
  "packages": [
    "dev/*"
  ],
  "npmClient": "npm",
  "command": {
    "publish": {
      "yes": true,
      "ignoreChanges": [
        "*.md",
        "*.spec.js"
      ]
    }
  },
  "useWorkspaces": true,
  "version": "independent"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context

We want to use lerna to publish and maintain a monorepo. We can't publish. Everything else works great, lerna version, lerna bootstrap, lerna list - but the publish doesn't work.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` |3.13.1 |
| `npm --version`  |6.4.1 |
| `yarn --version` | 1.12.3 |
| `node --version` | 10.15.3 |

| OS | Version |
| --- | --- |
| ubuntu | 14.04 |

**Comment by evocateur** [comment]
I have no idea what `HTTP_NPM_SCOPE` _is_. A header? An env var? Lerna uses the same publish mechanism as npm itself (since v6.6.0), does `npm publish` work with recent versions?

**Comment by m2bright** [comment]
Npm publish works fine. It is a header.

**Comment by evocateur** [comment]
A `lerna_debug.log` from a failed publish would be appreciated.

**Comment by m2bright** [comment]
I was looking for one, but nothing was produced. Is there a specific way to
generate one?

**Comment by armandocanals** [comment]
Hi! Armando from packagecloud checking in.

After digging into this issue, it looks like what's happening is that Lerna is passing the full `@scope/package-name` instead of just `@scope` to `libnpmpublish` which sets it as the `HTTP_NPM_SCOPE` header. 

https://github.com/lerna/lerna/blob/a7ad9b60d27b390fde21fd2837f2d97320c4603e/utils/npm-publish/npm-publish.js#L34

The official registry supports both `@scope` and `@scope/packagename` for HTTP_NPM_SCOPE, but packagecloud does not.

From what I understand, this header is supposed to include just the `@scope` for a package.

I'm inclined to say that Lerna should only pass the `@scope` to `libnpmpublish` instead of the entire `@scope/packagename`, but I'm not familiar with the needs of the project, so I could be wrong.

We're also discussing how to handle this better at packagecloud.

**Comment by evocateur** [comment]
The docs for [project-scope](https://github.com/npm/npm-registry-fetch#-optsproject-scope) are kinda vague on exactly what they should be used for. I'm cool with passing `spec.scope` (from `npm-package-arg`) there, instead.
