### ISSUE TITLE
RFC: TypeDoc plugin for Lerna

### ISSUE THREAD

**Issue by marcj** [lerna/lerna#1999]
I used lerna now in at least 6 Typescript projects and I use for almost all of them TypeDoc. I saw TypeDoc does not support Lerna structure out of the box, so when you generate the documentation for a lerna structure you end up having all declaration in several modules (each per file) or one big module. 

So this is why I coded a little plugin for Typedoc that allows to have documentations like:
https://marshal.marcj.dev/ ([Github](https://github.com/marcj/marshal.ts)). It's a TS project based on several packages, as you can see at the right side now clearly, thanks to the plugin.

Here's the plugin: https://github.com/marcj/typedoc-plugin-lerna-packages

I thought it might be worth to link to it somewhere so people know they can build easy Typescript docs with Lerna as well. Let me know what you think.

**Comment by evocateur** [comment]
Sure, PR very welcome!

**Comment by JamesHenry** [comment]
Hi Folks 👋

In light of its age, and in order to allow our small team to focus on what matters most to Lerna v6 users in late 2022, I'm going to close this one. If you have any requests that could enhance your usage of Lerna 6, then please do let us know by opening a new discussion (for a feature) or issue (for a bug report) with as much context as possible.

You can also check out our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

Many thanks 🙏
