### ISSUE TITLE
`lerna bootstrap` does not create package-lock when no external dependencies are present

### ISSUE THREAD

**Issue by bajtos** [lerna/lerna#2015]
When running `lerna bootstrap` in a project with npm config `package-lock=true`, there is no `package-lock.json` file created for packages that have only monorepo-local dependencies.

## Expected Behavior

`package-lock.json` is created for all monorepo packages, regardless of their dependencies.

## Current Behavior

No package-lock file is created for some packages.

## Possible Solution

Even if there are no external dependencies, `lerna bootstrap` should still run `npm install` to get an empty package-lock file created.

## Steps to Reproduce (for bugs)

1. Create a monorepo with two packages: `core` and `util`
2. `lerna add --scope core util`
3. `lerna add --scope core debug`
3. `lerna bootstrap`
4.  Good: `packages/core/package-lock.json` was created, it contains an entry for `debug` module. Bad: there is no `packages/util/package-lock.json`.

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.3.0",
  "packages": [
    "packages/*"
  ],
  "version": "independent"
}```
</p></details>

<details><summary>lerna-debug.log</summary><p>
<!-- browsers demand the next line be empty -->

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | n/a |
| `node --version` | v10.15.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.3 |

**Comment by revelt** [comment]
Imho, the current Lerna's behaviour seems logical. Correct me if I'm wrong but thinking logically, performing an `npm install` is asking npm to install some packages. Now, since they're all linked from local, there can be two cases:

1. those packages were **published** before but with lesser versions/features and newer, unpublished versions have been linked for dev purposes. 
2. those packages **don't exist on npm yet**.

**In case no.1.**, the lockfile will be wrong (containing data about wrong-version packages), won't it? It will sure not come empty like you wish?!?
**In case no.2.** npm will return a non-zero exit code, the GET from npm will 404 and npm won't generate any lockfiles for you. I just tried this, creating a dummy package with non-existent dependency and performing `npm i`.

---

Thinking about implementation in Lerna, if we wanted to create an empty lockfile, it seems we can't do it via `npm i` and also it's dangerous to try to mimic the npm API manually because while lockfiles have `lockfileVersion` key, compatibility of artificially-generated lockfile with npm CLI is difficult to guarantee and even unit-test.

Do correct me if my reasoning is flawed. Also, **please elaborate on the technical reasons why exactly do we need empty lockfiles created.** Considering my current understanding, I'd say other features are more important than this (but do convince me otherwise).

**Comment by bajtos** [comment]
@revelt thank you for coming back to me.

To speed up our CI builds, we want to install dependencies using `npm ci && lerna boostrap --ci`. That's the goal I want to achieve, I apologize for not mentioning it in the issue description.

It was my understanding that every package must have a `package-lock.json` file, otherwise `lerna boostrap --ci` will fail. Apparently that's not the case as I found today with `lerna@3.13.2`. It's true that `npm ci` fails when there is no package-lock present, but it seems that `lerna bootstrap --ci` is clever enough to skip calling `npm ci` when there are no external dependencies to download & install.

As a result, the fact that `lerna boostrap --no-ci` does not create empty lock files is perfectly fine, because `lerna bootstrap --ci` does not need them.

I think this issue can be safely closed now. Sorry for taking your valuable time for something that I could have found on my own.
