### ISSUE TITLE
Adding Git dependency through CLI

### ISSUE THREAD

**Issue by willemneal** [lerna/lerna#2029]
Currently the only way that I have figured out how to add relative git dependencies is doing as suggested in the README; add the dependency to the `package.json` of a package and then run `lerna bootstrap` at the top. However, is it possible to add a relative git dependency via `lerna add`?

**Comment by revelt** [comment]
This is a related to a ticket #1839 but actually a different feature.

If I understand correctly, the situation is, we are at `packages/a` and we want to symlink/alias existing `packages/b`. No fancy `lerna bootstrap` which might take some time, no laptop fans buzzing, no Internet access needed, just one alias created. OK, maybe `package.json` could be updated too for convenience (because exact dependency's version is not known, what to put in `package.json`).

@willemneal did I describe the feature correctly?

---

Considering wiring up in general, here all we've got at the moment:

Dan posted two recipes on #1839:

> Also, for the specific question of "how to add a local dependency?", you have two options:
> 
> 1. `lerna add`
>    
>      
>        
>          
>        
>      ```
>    npx lerna add @my-org/core ./apps/admin
>    ```
>    This command automatically runs `lerna bootstrap`, leaving the `node_modules` tree in the correct state.
> 2. Manual edit + `lerna bootstrap`
>    In `apps/admin/package.json`:
>    
>      
>        
>          
>        
>         "dependencies": {
>    +    "@my-org/core": "file:../../packages/core",
>         "external-dependency": "^1.0.0"
>       },
>    Then `npm install` in the root (or `npx lerna bootstrap`, same diff)

I'd add another, **3rd way** — if dependency is _already_ symlinked by lerna on another package, you can manually copy aliases to dependencies from `node_modules` folder of one package to another where those are missing. That's what `lerna bootstrap` would do, except from clean slate.

The exact solution, **4th way** (if I understood correctly) could be achieved with a standalone CLI app.

Imagine, a CLI app is called from a lerna monorepo's subfolder where one of packages sits. Lite version of `lerna add`. You'd say "CLI, give me alias to X". What it would do is it would go up the folder, scan sibling packages, if any are found, create a symlink and if missing, add an entry in package.json. If none are found, that must be an external package. What CLI would then do, it would do to Lerna root's node_modules, check in there for bootstrap-hoisted packages, is the desired package in there already hoisted. If yes, it would symlink it to package's `node_modules` and create an entry in package.json. If not, — exit with a non zero code — use Lerna's `add` and `bootstrap`. Such CLI is opinionated because it caters just bootstrap-hoisted package way of working. Such CLI seems doable to me and in theory I could make it, it's just a matter of time.

Or this could be a candidate new feature to Lerna's `add`.

**Comment by evocateur** [comment]
I'm not sure why you'd need or want a `git://` dependency on a _sibling_ package. It's already being published along with the dependent. I'm increasingly regretting #1033.
