### ISSUE TITLE
After using file specifiers, second and later `npm install` won't install dependencies in package

### ISSUE THREAD

**Issue by ryancat** [lerna/lerna#2083]
## Expected Behavior
When using file specifiers, the first time `npm install` will install all devDependencies at root level, and dependencies for packages in package level. A package-lock.json file is generated after first `npm install`. After that, run `lerna clean` to clean all `node_modules` in packages, and run `npm install` again, we expect package dependencies are installed at package level, just like the first time.

## Current Behavior
The second or later `npm install` with an existing package-lock.json file will not install dependencies at package level, but at the root level. This cause packages cannot build as module not found from its (not exist) node_modules folder 

## Steps to Reproduce (for bugs)

1. run `npm install` with just `package.json` file
2. see package dependencies are installed in package level
3. run `lerna clean` to remove all package node modules
4. run `npm install` again with the generated `package-lock.json` file
5. see package dependencies are installed at root level
6. package build will fail

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.13.1 |
| `npm --version`  | 5.4.2 |
| `node --version` | 8.7.0 |

| OS | Version |
| --- | --- |
| macOS High Sierra | 10.13.5 |

**Comment by evocateur** [comment]
You should never need to run `lerna clean` when using relative `file:` specifiers, it is a holdover from legacy `lerna bootstrap`. Also, yikes, that's an old version of npm. I would recommend updating to the latest 6.x, many things about the local `file:` specifiers have improved dramatically since v5.4.2.

Did you run `npx lerna link convert` once before expecting `npm install`/`npm ci` to replace `lerna bootstrap`? If not, I suspect you are lacking a local `file:` ref in the root package.json. (Apologies if that's not the case, I'm literally flying blind here...)

**Comment by ryancat** [comment]
Thanks for the reply! I got this issue when checked in my package-lock.json file and running this on our CI environment. The node modules folder is not installed in the package, despite it has dependencies. When I try to debug the issue, I ran lerna clean to just remove the node modules folders locally. 

It maybe a bug for npm 5. I can try later with npm 6.

**Comment by ryancat** [comment]
Confirmed that npm 6 fixes this issue.
