### ISSUE TITLE
App + packages example

### ISSUE THREAD

**Issue by KaboomFox** [lerna/lerna#2092]
Does the lerna community recommend having apps in addition to packages in the same monorepo? 

How do people handle the build time of updating a package that affects 10 other packages and the App at scale?

**Comment by evocateur** [comment]
I do this all the time, however, a couple **huge** caveats:
1. Don't publish your apps (`"private": true` in their package.json), bundle them and upload the tarball somewhere.
2. Locate the apps under a different directory than `packages` (or wherever your libs live). Lerna doesn't care, you can configure as many `packages` locations as you want.

https://github.com/lerna/lerna#lernajson has a big tree describing this pattern.

> How do people handle the build time...

Build less? Or use tools like [pectin](https://github.com/evocateur/pectin) or patterns like [TypeScript project references](https://www.typescriptlang.org/docs/handbook/project-references.html) to streamline the process. In any case, builds (and testing/linting) should be run from the root of the repo, which generally affords time savings due to less stop-start churning vs per-package build/lint/test operations.

**Comment by KaboomFox** [comment]
@evocateur, awesome. Thanks for the resources. This was I was looking for.

**Comment by boblauer** [comment]
In this scenario where apps and packages live together, is it recommended that the apps still read the packages from npm? Or would you recommend reading them directly from the monorepo?
