### ISSUE TITLE
How to develop Lerna locally?

### ISSUE THREAD

**Issue by villesau** [lerna/lerna#2098]
## Expected Behavior

```
$ git clone git@github.com:lerna/lerna.git && cd lerna
$ npm i
$ npm test
```

should run the tests successfully

## Current Behavior

Tons of different errors.

## Possible Solution

Not sure.

## Steps to Reproduce (for bugs)

1. `git clone git@github.com:lerna/lerna.git && cd lerna`
2. `npm i`
3. `npm test`
4. Errors :/

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` Latest fork
| `npm --version`  6.4.1
| `yarn --version` 1.13.0
| `node --version` v10.15.0

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.4 |

**Comment by evocateur** [comment]
`npm install` seems to have problems with correctly installing local `file:` dependencies from a fresh clone. `npm cit` (`npm ci && npm test`) works, as it does not attempt to "update" local installs.

In general, unless you are trying to change the installed dependencies somehow, you should use `npm ci` instead of `npm i` (when a lockfile is present, as with Lerna).
