### ISSUE TITLE
when lerna publish failed, should reset version number

### ISSUE THREAD

**Issue by bluelovers** [lerna/lerna#2129]
when lerna publish failed, should reset version number

1. lerna publish
2. lerna ask add version ( force, can't skip )
3. something error (E.g test fail)
4. fix the error test

5. do again lerna publish
6. lerna ask add version again (but pkg version already change by last time)

## Expected Behavior

1. when error, reset version back to before lerna publish
2. allow skip add version number

## Current Behavior

version jump by how many time u fail, if didn't reset changes

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by bluelovers** [comment]
and need reset git tag

**Comment by seeliang** [comment]
shall upload tag after release

**Comment by JamesHenry** [comment]
Hi Folks 👋 

In light of its age I'm going to close this one. Since this issue was created (I think), versioning and publishing were separated into two different commands: `lerna version` and `lerna publish`.

Technically, there is still an extremely long-standing backwards compatibility built into `lerna publish` to make it behave like both commands in one, but we do not recommend it.

It is preferable to handle versioning (and any errors that might occur) first, and then handle publishing as its own step (with its own error handling). On a side note, we recently made publishing like this idempotent, meaning you can safely retry the command as many times as you want in case the network dropped/npm was down etc.

Many thanks!
