### ISSUE TITLE
publishConfig.access is, by default, set to public when running lerna create!

### ISSUE THREAD

**Issue by dannycodes** [lerna/lerna#2144]
Lerna Create, _by default_ sets `publishConfig.access = public`.
This overrides the expected behavior of NPM!

Here are the NPM docs on the matter:
`https://docs.npmjs.com/misc/config`
```access
Default: restricted
Type: Access
When publishing scoped packages, the access level defaults to restricted. If you want your scoped package to be publicly viewable (and installable) set --access=public. The only valid values for access are public and restricted. Unscoped packages always have an access level of public.```

## Possible Solution
Don't set publishConfig.access by default. 

## Context
I discovered this issue while using scoped packages. Very scary.

**Comment by evocateur** [comment]
I dunno, I personally find the `restricted` default to be worse. You can always configure this "durably" (that is, no CLI flag required) in lerna.json:
```json
{
  "command": {
    "create": {
      "access": "restricted"
    }
  }
}
```

**Comment by paleite** [comment]
@evocateur It's good to know that this can be changed in `lerna.json`, however, while you personally find it to be worse, it objectively _overrides the expected behaviour_ of NPM, as @dannycodes already mentioned.

Software behaving unexpectedly is potentially _dangerous_, since it makes peoples assumptions _implicitly wrong_. In this particular case, it would publish something that's expected to be private, _potentially leaking keys_, trade secrets, et.c.

Personally, I think making things public should be opt-in, but objectively speaking, **unexpected behaviour can be harmful**.

**Comment by smber1** [comment]
> @evocateur It's good to know that this can be changed in `lerna.json`, however, while you personally find it to be worse, it objectively _overrides the expected behaviour_ of NPM, as @dannycodes already mentioned.
> 
> Software behaving unexpectedly is potentially _dangerous_, since it makes peoples assumptions _implicitly wrong_. In this particular case, it would publish something that's expected to be private, _potentially leaking keys_, trade secrets, et.c.
> 
> Personally, I think making things public should be opt-in, but objectively speaking, **unexpected behaviour can be harmful**.

Agreed, it's pretty bad. We just accidentally published a sensitive company package onto the public internet :(.

**Comment by evocateur** [comment]
`lerna create` never _automatically_ publishes the package it just generated. If you're not willing to audit the output before publishing, I don't know what to tell you. Lerna is opinionated software, and you're welcome to PR [documentation](https://github.com/lerna/lerna/blob/master/commands/create/README.md) warning of this intentional default and workarounds.
