### ISSUE TITLE
When using lerna with npm-run-all for a npm script, lerna parses the script names and use its own CLI to run, skipping the root package.json scripts.

### ISSUE THREAD

**Issue by TimeDropsSB** [lerna/lerna#2145]
For context, I use yarn for my `npmClient`.

Consider the following scripts in the root package.json:

```js
"scripts": {
    "preversion": "npm-run-all -s pretty lint",
    "lint": "lerna run lint",
    "pretty": "lerna run pretty",
    "update-version": "lerna version"
}
```

Then execute `yarn update-version`, which runs the `update-version` script above.

## Expected Behavior

After `lerna version`'s prompts are filled out, the `preversion` script is ran.  When npm-run-all is ran at this point, I expect it to run script names that are in the same package.json as it.  Therefore, it should run the `lint` and `pretty` scripts above - in sequence - by running `lerna run lint` then `lerna run pretty`.

## Current Behavior

Lerna seems to parse each of the script names ran by npm-run-all, then invoke them through its own CLI.  Therefore, it does not look at the root-level scripts with the name; instead, it heads directly to each of the packages and invoke each scripts that match the name of the script.  That is, it goes to package A and invokes `yarn run lint`, then package B and does the same thing, etc. then repeat for `yarn run pretty`.

## Steps to Reproduce (for bugs)

1. Given the root package.json above, run `yarn update-version`.

<details><summary>lerna.json</summary><p>

```json
{
  "npmClient": "yarn",
  "packages": [
    "packages/packageA",
    "packages/packageB"
  ],
}
```
</p></details>

## Context

Lerna using its own CLI to parse npm-run-all script names seems contradictory to the expected behavior of npm-run-all.  There are times I will want to invoke other root scripts first before having lerna go through each package.  For example, the `preversion` script may have something else I want to invoke that only exists at the root.

The solution to the problem above right now is to use `yarn run pretty && yarn run lint` instead but I want to be able use npm-run-all for more control and consistency in my scripts.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.15.0 |
| `npm --version`  | 6.5.0 |
| `yarn --version` | 1.15.2 |
| `node --version` | 10.15.0 |

| OS | Version |
| --- | --- |
| Windows 7 | |

**Comment by dfernandez79** [comment]
I ran into the same issue but with publish lifecycle scripts. I put a `run-s lint build test` in a `prepublishOnly` script of each package. The result: the `lint build test` was run in the root project instead of the package, causing it to run multiple time. The workaround is easy in my case, but the behavior is unexpected. (OS macOS 10.14.5, node v11.14, Lerna 3.15, npm 6.9.0, npm-run-all 4.1.5)

**Comment by dfernandez79** [comment]
@TimeDropsSB I did a quick search for similar issues, and I found:
https://github.com/lerna/lerna/issues/1944
https://github.com/lerna/lerna/issues/1842

What I learn from reading those issues:
- Lerna sets `NPM_EXEC_PATH` to lerna
- `npm-run-all` uses `NPM_EXEC_PATH`, and then runs lerna instead of npm or yarn

The Lerna behavior is by design, and possible workarounds are:
- Using `npm-run-all` with `--npm-path` (see https://github.com/lerna/lerna/issues/1842#issuecomment-450678716)
- Do not rely on `npm-run-all` running leaf package scripts, move the scripts to the root project (see https://github.com/lerna/lerna/issues/1944#issuecomment-481478467)

My conclusion:
Each project has it's own design decisions , it's ok. This design decision doesn't fit my needs/goals:
- I prefer to keep each leaf package independent, so is easy to "refactor" them and move to other repo. I had similar experiences working with monorepos in Java (mostly with Maven/Gradle), and moving too many things to the root project was good at the beginning, but painful when the project grows.

- By modifying `NPM_EXEC_PATH` or having to move scripts to the root, my packages become very dependent of lerna. I prefer not to do that... I'll see if I can manage the repos using just yarn workspaces + some scripts to automate versioning and publish, not ideal (lerna has more options to handle hoisting) but that setup may fit better to my use case.

**Comment by TimeDropsSB** [comment]
@dfernandez79 Thanks for looking into it.   It's too bad there is a conflict between Lerna and npm-run-all but understandably so.

In any case, this is not too much of a problem in my case though since like I said in the first post, the easiest way to solve it is to just change the script to  `"preversion": "yarn run pretty && yarn run lint"` instead.  It's the least intrusive solution and I believe is the correct way to handle this.  The downside is that you can't flip between running as `npm` vs. `yarn` but since I am using Yarn workspaces, the assumption is to use Yarn anyway so there's no problem there.
