### ISSUE TITLE
Upgrading version of package used on monorepo root

### ISSUE THREAD

**Issue by tunnckoCore** [lerna/lerna#2153]
## Expected Behavior

Upgrade the package version like it happens if it is used inside another workspace package. 

## Current Behavior

Doesn't do it.

## Possible Solution

Don't know.

## Steps to Reproduce (for bugs)

Example: https://github.com/tunnckoCoreHQ/hela/blob/v3-next/package.json#L26 
I'm using one of my monorepo packages as a dependency to the monorepo root.
Usually when new release is done, Lerna updates the package version if this package is used inside other monorepo packages. But Lerna doesn't update its version if it is in the root. In the example, `@hela/cli` is just one of the packages of this monorepo.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "useWorkspaces": true,
  "npmClient": "yarn",
  "version": "3.0.0-alpha.66",
  "command": {
    "version": {
      "message": "chore(release): version %s"
    }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.15.0 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | 1.16.0 |
| `node --version` | 10.x |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| ArchLinux | none |

**Comment by maapteh** [comment]
Root will not be published (private). Simply create a package which has all dependencies it needs. You can point it to that package.

**Comment by tunnckoCore** [comment]
I don't want to publish the root. The thing is that I used one of the packages of the monorepo as dependency of that same monorepo.

**Comment by maapteh** [comment]
ah ok, sorry i deleted my answer before i read your comment. I will try what you are saying locally.

**Comment by tunnckoCore** [comment]
Of course, I have workarounds, but that's kidna ugly.

https://github.com/tunnckoCoreHQ/hela/blob/v3-next/package.json#L12

I'm directly calling the source of the cli, not the installed one. The thing is that I also need to build its deps before be able to run it. In this case it's only one, the `hela/core`, but still.

If lerna upgrade the version of this package in the root, then I will always have the latest "production" cli.

**Comment by maapteh** [comment]
ok, we have your scenario but then we simply add the app in a package. In root there are only things like to centrally unit test, our typescript version for everything etc etc.
So what if you add the start part and its dependencies in a single package? `@tunnckocore/hela-app` This can have references to other own packages and will be updated always when one of its deps changes.

**Comment by tunnckoCore** [comment]
There's no app. There are only 2 packages in a monorepo. One of them is dependant on the other. The thing is that this cli can be used to help develop itself. 

It's like other tools/CLIs do, most popular example is that rollup uses itself to develop/build/bundle itself. The difference is that rollup isn't a monorepo.

**Comment by maapteh** [comment]
ok
```
.
├── /.jest-{cache|coverage}       # Jest testing files
├── /packages/                    # Main modules
│   ├── /cli/                     # Your cli
│   ├── /core/                    # Your core
│   ├── /dev/                     # Your dev
│   └── /sample/                  # Your sample where you include cli just like you do now in root
├── /.huskyrc                     # Git hooks
└── /lerna.json                   # generic lerna settings
```

so in module sample you can put deps on the other packages, and the start is just the same as you have now in root. Basically most from root comes into a package which consumes other packages.

**Comment by evocateur** [comment]
I would use a relative `file:` specifier in the root, and have your build run in a `prestart` lifecycle, with `start` pointing to the built output path.

**Comment by tunnckoCore** [comment]
> @maapteh: npm then turn that package to private too.

Just realized that this is an option. Yesterday I published such package (didn't want but...)

@evocateur, maybe an option, yea.

And yet, if there was ignore flag or `--ignore-changes` was working as expected, life would be easier.

**Comment by dcwarwick** [comment]
OK, I have hit the same (I think) issue with lerna. We have a jest config that we put into its own package in our monorepo as it is used by several different other packages, and we want to use the same jest config for our top-level test suite, so I added the jest config package as a dev dependency to the root package.json, but the next time `lerna version` bumped the version for the jest config package everything broke because it did not update the version in the root package.json.

Is there a particular reason that lerna does not update versions of packages if they are mentioned in the root package.json? If there isn't, can this be quite easily fixed? And if there is, how should I be going about setting up some shared resources that are used *both* by one or more of the packages in my monorepo *and* by tools run at the root level?

**Comment by Coolpix** [comment]
Lerna will manage all the package.json that are located inside the configured workspace. 

If you have all your packages inside /packages and in the Lerna configuration you have that the workspace is in /packages it will never find the root package.json.

To do this configure your workspace adding ./, in my case using npm I have this configuration of pnpm workspace

`packages:
  - 'apps/**/*'
  - 'packages/*'
  - './'`

**Comment by dlqqq** [comment]
Try the solution I posted as a comment here: https://github.com/lerna/lerna/issues/2879#issuecomment-1454803610

**Comment by JamesHenry** [comment]
Hi Folks 👋 

As noted by @evocateur many years ago now, the correct way to approach this is to use `file:` (or `workspace:` which didn't exist at the time) specifiers in your root package.json when referencing dependencies/devDependencies on packages within your workspace.

These are preferable even when not dealing with the root package.json because they make it super explicit that this is a local relationship and should not be resolved from the npm registry.

Referencing your root package.json as if it is one of your workspaces (using `.`) is not desirable as it creates a very confusing and non-representative project graph, and has knock on effects on script targets. @Coolpix and @dlqqq I would strongly encourage you to reconsider your approaches here.

The source of truth for the version of the workspace when publishing in lock step is the `lerna.json`. The root `package.json` does not require a version for any publishing purpose because it is never published, so the most appropriate thing is to remove the version field from it (making sure it has `"private": true` as well).

Hope that helps!
