### ISSUE TITLE
Publish in lerna 3 check for remote branch but lerna 2 does not

### ISSUE THREAD

**Issue by testica** [lerna/lerna#2187]
## Expected Behavior

I want a flag or something to be able to prevent [this check](https://github.com/lerna/lerna/blob/b62088e873b71bbac0f6325394d16542c4551deb/commands/version/index.js#L123) when publish. In lerna 2 I didn't face this issue because remote branch validation didn't exist.
## Current Behavior

Using lerna 3, local branch doesn't exist remotely, so it throw "ENOREMOTEBRANCH"
## Possible Solution

I know a solution is push manually the branch before publish, but there is no way to prevent this check? I need to push the commits produced by lerna publish, so I can't set the flag --no-push
## Steps to Reproduce (for bugs)

1. Create a local branch
2. Run lerna publish
3. Get ENOREMOTEBRANCH output

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.14.1 |
| `npm --version`  | 6.4.1 |
| `node --version` | v8.12.0 |

| OS | Version |
| --- | --- |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
In general, you shouldn't be publishing from a short-lived ("feature") branch.

However, it is unclear to me why you can't run
```sh
lerna version --no-push
# inspect the commits, i guess?
git push --follow-tags
lerna publish from-git --yes
```

Unless I've misunderstood what you're trying to do?

**Comment by JamesHenry** [comment]
Hi Folks 👋

In light of its age, and in order to allow our small team to focus on what matters most to Lerna v6 users in late 2022, I'm going to close this one. If you have any requests that could enhance your usage of Lerna 6, then please do let us know by opening a new discussion (for a feature) or issue (for a bug report) with as much context as possible.

You can also check out our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

Many thanks 🙏
