### ISSUE TITLE
How to build and publish only the packages that are changed

### ISSUE THREAD

**Issue by Neha3011** [lerna/lerna#2201]
Hi, I was wondering if there is a way to build only the packages that are changed. When i run command `lerna changed`, it shows all the components even though they have not change.
I was hoping to use this and write some script around it if there is no direct way

Thanks for help.
lerna version: 3.16.4

**Comment by evocateur** [comment]
Build, as in run the `build` script in packages that have changed since the last release, sure:
```
npx lerna run build --since
```

Publish? Sorry, no. #707 etc etc

**Comment by mepaJanitza** [comment]
I have the problem, that i want to build only changed, and also its locale dependency (package):
so consider following structure

packages
-- package1
-- package 2
-- spa

$lerna changed
package2
spa

And Package2 has package1 in its devDependency

so when i run :

lerna run build --since

it runs build just for the changed packages (package2 and spa), which seems right, but how can i build the locale dependency (package 1) too?, so that i dont have to build every package on my CI
