### ISSUE TITLE
Publish and link package subdirectory (like lib/dist/build)

### ISSUE THREAD

**Issue by slikts** [lerna/lerna#2209]
Re-raising this issue: #1282 (also #901 and #91)

The main use case for publishing the build artifact staging directory (usually named `dist`/`lib`/`build`) is to enable deep imports without including the build directory in the path. The `main`/`module`/`browser` package properties only enable *bare* imports like `require('package')` instead of deep imports like `require('package/directory/module')`.

Deep imports are a common pattern and have the advantages of being more efficient and removing the need for workarounds like tree shaking. Eventually this issue should be solved by [import maps](https://github.com/WICG/import-maps), but publishing the build directory is the a reasonable option until import maps are available.

I'd be willing to contribute a PR if there were some pointers about the required changes for this feature.

**Comment by evocateur** [comment]
[`lerna publish --contents`](https://github.com/lerna/lerna/tree/master/commands/publish#--contents-dir) (optionally configured per-package via [publishConfig.directory](https://github.com/lerna/lerna/tree/master/commands/publish#publishconfigdirectory)) already does this.

As for linking _to_ the generated directory, you'd need to change [this line](https://github.com/lerna/lerna/blob/bb048cb306b5cfcb039aa98f667cf3751cf0ad20/utils/symlink-dependencies/symlink-dependencies.js#L80) to use `dependencyNode.pkg.contents` instead of `dependencyNode.location`, and then somehow change [this line](https://github.com/lerna/lerna/blob/bb048cb306b5cfcb039aa98f667cf3751cf0ad20/utils/symlink-binary/symlink-binary.js#L22) to use the same [contents](https://github.com/lerna/lerna/blob/master/core/package/index.js#L98) field somehow? And probably need to make the [`pkg.bin` field](https://github.com/lerna/lerna/blob/bb048cb306b5cfcb039aa98f667cf3751cf0ad20/core/package/index.js#L66-L73) resolvable from contents, as well (it's currently hard-code).

**Comment by slikts** [comment]
Mentioning for completeness' sake that the motivation for this is practical: importing large libraries is not free; it [takes time][bench] to parse the code, also to typecheck it if using TS, etc. Tree shaking also works better when using separate modules.

[bench]: https://github.com/slikts/deep-vs-bare-import-bench
