### ISSUE TITLE
lerna publish should handle retry 403s better

### ISSUE THREAD

**Issue by starpit** [lerna/lerna#2259]
## Expected Behavior

retries in lerna publish should gracefully handle 403 for the version that is being published. i.e. if lerna is trying to publish 3.4.5, gets a network hiccup, retries, and that retry fails due to 403, then lerna should only warn, not fail.

## Current Behavior

instead, lerna treats 403s as a sign of failure, when, according to my understanding, a 403 on npm publish means that the intended version already exists. if this is a retry, then that's a warning not a failure.

```bash
lerna http fetch PUT 200 http://registry.npmjs.org/@kui-shell%2fplugin-wskflow 11783ms
lerna http fetch PUT 403 http://registry.npmjs.org/@kui-shell%2fplugin-proxy-support 24971ms attempt #2
lerna ERR! E403 You cannot publish over the previously published versions: 3.0.29.
```

and then we are left with uncommitted changes, because lerna optimistically pushes updates to my repo, but then leaves some of the commit hashes uncommitted, because it gave up. ugh.

## Possible Solution

lerna publish could remember that it is doing a retry, and only warn on 403s seen during retries.

## Steps to Reproduce (for bugs)

this is an erratic condition, subject to network conditions and the status of npmjs

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.16.4 |
| `npm --version`  | 6.9.0 |
| `yarn --version` | n/a |
| `node --version` | v10.16.2 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.14.6 |

**Comment by thasmo** [comment]
I would also like to see better error handling for 403 responses, especially for `You cannot publish over the previously published versions` where `lerna publish --canary` was used to release a nightly package which was already published. Currently running `lerna publish --canary` on a CI server for a repository branch without new commits since the last publishing, it throws this error. It would be nice to have `lerna` not fail with an error, when the version to publish has already been published but rather print a notice/message.

**Comment by davsuas** [comment]
Hello, I have the same error since 10 days ago. It happens randomly. Some times it publish my packages successfully other completely fails.

In my case I'm using Bitbucket pipelines, everything was running well but now the publish step fails.


`+ npx lerna publish from-package --registry $NPM_URLS --yes
lerna notice cli v3.18.4
lerna info versioning independent
lerna info ci enabled
Found 4 packages to publish:
 - $WORKSPACE/labelbox => 1.0.2
 - $WORKSPACE/augmented-box => 1.2.20
 - $WORKSPACE/card-slat => 1.0.3
 - $WORKSPACE/priceandtotalreturn-chart => 1.0.4
lerna info auto-confirmed 
lerna info publish Publishing packages to npm...
lerna notice Skipping all user and access validation due to third-party registry
lerna notice Make sure you're authenticated properly ¯\_(ツ)_/¯
lerna WARN ENOLICENSE Packages $WORKSPACE/labelbox, $WORKSPACE/augmented-box, $WORKSPACE/card-slat, and $WORKSPACE/priceandtotalreturn-chart are missing a license.
lerna WARN ENOLICENSE One way to fix this is to add a LICENSE.md file to the root of this repository.
lerna WARN ENOLICENSE See https://choosealicense.com for additional guidance.
lerna http fetch PUT 403 $NPM_URLS/$WORKSPACE%2faugmented-box 18ms
lerna ERR! E403 403 Forbidden - PUT $NPM_URLS/$WORKSPACE%2faugmented-box`

Hope this info can help to solve the issue.

**Comment by dotansimha** [comment]
Same issue here with lerna 3.19.0

**Comment by boredland** [comment]
I'm seeing this sporadically in my Github Actions and always wondered why it occurs. Thanks for the explanation and I hope your proposal will be picked up!

**Comment by ductiletoaster** [comment]
Doubling down on the suggestion that these types of errors should be notices/warnings. This could even be configurable with a flag. Or even better make retry logic configurable

- retryTimeout: number
- retryAttempts: number
-publishFailuresResultInError: boolean

**Comment by chrisvdp** [comment]
I'm seeing this happen with lerna 3.20.2 in my ci pipeline publishing to npme. Get an error

```
lerna http fetch PUT 403 https://registry.ourcompany.npme.io/@company%2fcode 129102ms attempt #3
lerna ERR! E403 You cannot publish over the previously published versions: 2.7.0.
```

But when I check the registry I can see that the package was published.

**Comment by svda** [comment]
Happens here every now and then as well, one of the packages simply isn't published because of a network glitch. Having a retry mechanism that looks at the error response and then does conditional retries would make lerna more resilient.

**Comment by pokatomnik** [comment]
Any updates in this issue?

**Comment by jdferreira2429** [comment]
Having the same issue. any update here?

**Comment by dotansimha** [comment]
The 403 are coming from NPM. It might seems like an auth issue, but it's rate limiting. For example, see this: https://github.com/atlassian/changesets/issues/427 
I managed fixed that by limiting the amount of publish requests sent to npm.

**Comment by matyasf** [comment]
We are seeing this issue too. Any update?

**Comment by porkus1990** [comment]
push - We have the same issue from time to time. Any update?

**Comment by wjureczka** [comment]
here also :(

**Comment by JamesHenry** [comment]
Hi Folks 👋 

I'm pleased to say that modern `lerna publish` is idempotent.

You can see it in action here: https://www.youtube.com/watch?v=kh4TaiKbC8c

Please update to the latest lerna to benefit from this feature.

Many thanks!

**Comment by jmccann** [comment]
Quick question.  I watched the video and its cool that it uploads all other package even if other packages have been uploaded. 👍 

But I did see the following:
![Screenshot 2023-03-16 at 1 44 04 PM](https://user-images.githubusercontent.com/1228349/225722074-edbb0e5d-d5d1-4435-8f7e-b03d5e1a4efb.png)

I see an `ERR! E403` at the end of the output.  What I don't know is if it returns a non-zero exit code or not back to the shell.  From watching the video it seems that the command would sill error and not warn?

I think this is an issue if trying to run this stuff in CICD pipelines.  Because things would publish properly but still return non-zero code?

So wondering if you could clarify on that.

Thanks for all the work on this!! 👍

**Comment by fahslaj** [comment]
@jmccann Thanks for pointing this out. I'm not sure why the output in the video shows an error, but I can confirm that Lerna will succeed and the command will finish. The output will look like this:
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/6913035/225738821-81117392-ffcd-4f33-984d-ed6c5840cd2d.png">

This is with Lerna v6.5.1
