### ISSUE TITLE
Force publish only specific package(s)

### ISSUE THREAD

**Issue by tunnckoCore** [lerna/lerna#2316]
## Expected Behavior

Pass `--force-publish` and some other flag to only force publish specific or multiple packages, but not all. One may say to use with `--ignore-changes` but it seems to not work, meaning that it treats all the packages and seems to ignore the `ignore-changes` flag completely.

The use case is when you have `dist` changed but not sources, but you know for sure that the `dist` is different (has changed) and want to bump version.

## Current Behavior

No way of doing it? `--force-publish` and `--ignore-changes` doesn't play well together.

## Possible Solution

Don't know.

## Steps to Reproduce (for bugs)

1. Have 5 or 10 packages
2. Want to force publish only 2-3
3. ignore the rest

Removed the rest of the issue template, since it doesn't apply.

**Comment by evocateur** [comment]
> Removed the rest of the issue template, since it doesn't apply.

I'd say the version of `lerna` that you're using is rather applicable. As is the exact command(s) you attempted. And what (if any) configuration is present in `lerna.json`.

I'll practice reading your mind, I guess. Hand-waving, I assume you tried something like this:

```
npx lerna publish \
  --force-publish foo-package \
  --force-publish @scope/bar-package \
  --ignore-changes '**'
```

One thing to note, if you _do_ ignore everything except an explicit subset, any changes outside of the subset will be forever lost to subsequent publishes, as far as Lerna is concerned. That is, the next time you run `lerna publish` _without_ all the fancy forcing, it won't consider the previously-ignored packages to have changed, and thus won't publish them.

I would recommend you avoid using the `--ignore-changes` flag for this purpose, and just accept that Lerna will publish what has changed since the previous release tag _in addition to_ the stuff you forced (which is valid in this case, for sure, build changes and whatnot won't get recognized).

**Comment by tunnckoCore** [comment]
Oh, yea.

Lerna version `3.16.4`

```json
{
  "$schema": "http://json.schemastore.org/lerna",
  "version": "independent",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "packages": [
    "configs/*",
    "packages/*",
    "@tunnckocore/*"
  ],
  "changelog": {
    "cacheDir": ".cache",
    "ignoreCommitters": [
      "*bot"
    ],
    "nextVersion": "Unreleased"
  },
  "command": {
    "version": {
      "conventionalCommits": true,
      "createRelease": "github",
      "message": "chore: release package(s)",
      "signGitTag": false,
      "signGitCommit": false,
      "allowBranch": [
        "master"
      ]
    }
  }
}
```

> I assume you tried something like this:

Tried a few ways, I don't remember exactly, it was before a few days or weeks ago.  Last night just had the same need to only publish because I minified the build files. Such cases are rare, but some times are needed and it's weird to make some weird source change just for the sake to be able to publish the changes.

> One thing to note, if you do ignore everything except an explicit subset, any changes outside of the subset will be forever lost to subsequent publishes, as far as Lerna is concerned. That is, the next time you run lerna publish without all the fancy forcing, it won't consider the previously-ignored packages to have changed, and thus won't publish them.

Interesting, very strange and crazy. So it means Lerna writes some things to the disk so later it knows? Why is that at all? Even more when if you are just using flags, not the config file.

**Comment by evocateur** [comment]
> Interesting, very strange and crazy.

It's literally how tags work in git? That's what Lerna uses to determine what changed since the last release. The "last release" is the previous annotated git tag.

You can always pass specific globs to `--force-publish` if you don't want to version the world. It has the same caveats when combined with `--ignore-changes`, however, and is generally only used to ensure certain packages _always_ get published (Babel itself uses this for some of their packages due to a weird dependency graph).

**Comment by tunnckoCore** [comment]
Ookay. Got it, I have something in mind that can help.

**Comment by geret1** [comment]
Sorry to bring again this topic to the present days but I just need to understand (a bit more) the way of publishing specific packages.

In particular, I have a monorepo with lerna 4.0.0 with multiple components (still not published) and I want to take more control of publishing (one-by-one) so I followed up on all your comments and it works the first time.

`lerna publish --force-publish @repo/my-first-pkg --ignore-changes '**'` < it creates the tag in GH and everything looks fine (apparently).

But it fails the second time because it request to publish all packages. What did I do wrong? no idea :(
