### ISSUE TITLE
Find the dependency of the packages Using Lerna

### ISSUE THREAD

**Issue by zeegeek** [lerna/lerna#2367]
## Expected Behavior

Suppose I have 6 packages. A, B, C, D, E, F.
Now, how you i know that D is dependent on which component.
If i make change on only D then i have to build only the packages which are dependent of D. Not Others

**Comment by rlespinasse** [comment]
You can check the [`lerna list --graph`](https://github.com/lerna/lerna/tree/master/commands/list#--graph) command. 

And to also run dependent packages, you can play with [`lerna run build --since master--include-dependent`](https://github.com/lerna/lerna/blob/master/core/filter-options/README.md#--include-dependents).

**Comment by kerryj89** [comment]
_As of v4.0.0_

Here's one way to find what packages depend on package a, granted my package dependency tree is shallow so your mileage may vary.

```
{
  "package-a": [],
  "package-b": [
    "bootstrap",
    "package-a"
  ],
  "package-c": [
    "bootstrap",
    "package-a"
  ],
}
```

Running the following:
`lerna ls --graph | xargs | grep -Eo '[A-Za-z0-9-]+: \[[^]]*your-package-name[^]]*\]' | cut -d':' -f1`

Will yield:
```
package-b
package-c
```

--

In my situation I wanted to add a package with an exact version to my other packages that depended on it.

```
target_dep="your-package-name"
deps=($(lerna ls --graph | xargs | grep -Eo '[A-Za-z0-9-]+: \[[^]]*'${target_dep}'[^]]*\]' | cut -d':' -f1))
echo $deps

for i in "${deps[@]}"; do
    lerna add ${target_dep} --scope=${i} --exact --no-bootstrap
done

lerna link --force-local
```

I used `no-bootstrap` flag because I just want Lerna to update the package.json to the exact version without going through the lifecycle scripts, but followed up with `lerna link --force-local` in order to symlink all the packages.

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, it seems like the community was able to provide a solution/answer to the question so I am going to close this one for now.

If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
