### ISSUE TITLE
lerna version prepatch --force-publish=pkg1,pkg2 is not working

### ISSUE THREAD

**Issue by see** [lerna/lerna#2399]
`lerna version prepatch --force-publish=@vangojs/vuepress-theme-vango,@vangojs/vuepress-theme-vango-cli ` is not working

## Current Behavior

![QQ截图20200102115018](https://user-images.githubusercontent.com/19725091/71651119-21756300-2d56-11ea-8e34-aa6dc9b2a8a4.png)

<details><summary>lerna.json</summary><p>

```json
{
  "changelog": {
    "labels": {
      "pr(enhancement)": ":rocket: Enhancement",
      "pr(bug)": ":bug: Bug Fix",
      "pr(documentation)": ":book: Documentation",
      "pr(dependency)": ":deciduous_tree: Dependency",
      "pr(chore)": ":turtle: Chore"
    },
    "repo": "vangojs/vuepress-theme-vango",
    "cacheDir": ".changelog"
  },
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "conventionalCommits": true
    }
  },
  "version": "independent",
  "npmClient": "yarn"
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.1 |
| `npm --version`  | 6.13.4 |
| `yarn --version` | 1.21.1 |
| `node --version` | v10.18.0 |

| OS | Version |
| --- | --- |
| Windows 10 | 1909 |

**Comment by evocateur** [comment]
Your screenshot indicates `lerna` at v3.16.4, not 3.20.1 as the issue template claims. Probably not a root cause of this issue, but notable. (no nesting under an `@vango` directory is necessary either, the filters are based on package names, not directory paths)

I see both forced packages in the log output, but I don't see the tags in your [repo](https://github.com/vangojs/vango-vuepress/tags). Neither is the `0.0.3-alpha.0` represented in the relevant package.json files.

You're using conventional commits, yet attempting to pass a manual bump ("prepatch"). Why not use [`--conventional-prerelease`](https://github.com/lerna/lerna/tree/master/commands/version#--conventional-prerelease)?

Using a 0.0.x version range is fraught with errors, in my experience. You might try manually editing the versions to `1.0.0-alpha.0` and running `npx lerna version --conventional-prerelease` again?

**Comment by upcwangying** [comment]
Sorry, the `lerna` version should be 3.16.4. Run the command `lerna version --force-publish = pkg1, pkg2`. Why do all modified packages generate a new version number?  I thought that it should be the specified package to generate a new version number and repo tag, and then push it to the github release.
