### ISSUE TITLE
lockfile doesn't update the version of dependant packages

### ISSUE THREAD

**Issue by ItamarGronich** [lerna/lerna#2434]
## Expected Behavior

`package-lock.json` file of dependant packages should be updated with the correct version when commiting the lock files to git repo.
For example, when publishing two packages A and B where A depends on B. When B is updated, A's package lock should update it's version and also B's version

## Current Behavior

Only A's version is updated.

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "independent",
  "command": {
    "version": {
      "message": "chore(release): [skip ci] publish new versions"
    }
  }
}
```
</p></details>

## Context

Need to run `npm i` to generate the correct lock files and manually commit them.

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.15.0 |
| `npm --version`  | 6.2.0 |
| `node --version` | v10.9.0 |

| OS | Version |
| --- | --- |
| macOS Mojave | 10.14.6 |

**Comment by Clement134** [comment]
I have the same issue. Is there any workaround to automate this with lerna ?

**Comment by liranhershko** [comment]
Have a look at https://github.com/lerna/lerna/issues/1415#issuecomment-455790478
There seems to be a workaround.

**Comment by cckrause** [comment]
is there any plan to fix this issue? As it seems like it's more a concept Problem. As the documentation states:

> Publish packages updated since the last release (calling lerna version behind the scenes).
> This is the legacy behavior of lerna 2.x
> Publish packages tagged in the current commit (from-git).
> Publish packages in the latest commit where the version is not present in the registry (from-package).
> Publish an unversioned "canary" release of packages (and their dependents) updated in the previous commit.

Given 3 packages:
A: 1.0.0
B: 1.0.0
C: 1.0.0

```
A(1.0.0) {
    B(1.0.0)
} 
B (1.0.0) {
    C(1.0.0)
} 
C (1.0.0)
```

If you change all of the packages Lerna bumps the versions accordingly:
Given 3 changes
A: 1.1.0 feature
B: 1.1.0 feature
C: 1.0.1 patch

Results in the following updated dependency tree
```
A(1.1.0) {
    B(1.1.0)
} 
B (1.1.0) {
    C(1.0.1)
} 
C (1.0.1)
```
The solution mention in this post https://github.com/lerna/lerna/issues/1415#issuecomment-455790478 looked promising and is working as expected:
`npx lerna clean --yes && npx lerna exec -- npm install --ignore-scripts --package-lock-only --no-audit && git add packages/*/package-lock.json`

But the problem with this approach is that lerna runs all version scripts before publishing **ANY** package. So running the script is kind of useless as it will not succeed because of the fact npm would not be able to resolve any dependency. 

The only solution would be to run all the whole publish process as stated above for all the dependencies in reverse order to make this whole thing work. I'm a little shattered as this is one core feature i was expecting to be working with lerna as i started using lerna in the first place. The only other way i could imagine is to not using a package-lock file. Is there any particular reason this is not implemented already? Am i missing out anything here?
