### ISSUE TITLE
bootstrap fails silently

### ISSUE THREAD

**Issue by joscha** [lerna/lerna#247]
With #217 being merged, `lerna bootstrap` now silently fails without giving a reason.
```
➜  npmE lerna bootstrap
Lerna v2.0.0-beta.22
Independent Versioning Mode
Linking all dependencies
Errored while running BootstrapCommand.execute
1
```
instead of:
```
Lerna v2.0.0-beta.22
Independent Versioning Mode
Linking all dependencies
normalizeTree             ▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟╟
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "xxx@^0.0.0" "skatejs@1.0.0-beta.2"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/xxx
```

with
```javascript
//  stdio: "ignore"
```
in https://github.com/lerna/lerna/pull/217/commits/86bb31e46d1012f82b76043350db4d83f7701844#diff-5463599b8d45d087bae97f0d5df54fdaR15

**Comment by gigabo** [comment]
Ouch.  It's just emitting exit code on failure instead of the (no longer captured) `stderr` output.

Just setting `stdio: ["ignore", "ignore", "inherit"]` can be pretty verbose with warnings even in the success case.  Not a great experience with the progress bar.  Guess we can capture `stderr` output with `["ignore", "ignore", "pipe"]` without regressing on #213.  I can put a patch for that together in the morning.

Thanks for reporting @joscha!

**Comment by joscha** [comment]
We could disable the progress bar I guess - makes it faster for npm v3
anyway (https://github.com/npm/npm/issues/11283) 😂
