### ISSUE TITLE
Lerna avoid symlink process

### ISSUE THREAD

**Issue by reactuser35** [lerna/lerna#2479]
I'm using the below command

lerna bootstrap --hoist

I want lerna to install all dev and prod dependencies of the packages to the main root node_modules. **Some packages are dependencies of each other.**

When I run the bootstrap command it installs all the dependencies to the root node_modules. But after that process it symlink some of the packages to each other.

I just want the install all dependencies to the root node_modules including dependent packages.I don't want any symlink dependency.

How can I avoid symlink process ?

**Comment by revelt** [comment]
Just to give some highest-level context, in general, in my understanding, Lerna suits best npm package monorepos where those packages are real micro-libraries (programs) as opposed to front-end components.

When developing micro-libraries, Lerna solves a problem of automating cross-symlinking which allow to chain-develop packages — for example, I'm currently working on dependency chain of four programs, all at once: [string-match-left-right](https://gitlab.com/codsen/codsen/tree/master/packages/string-match-left-right/) which does string matching, then [tokenizer](https://gitlab.com/codsen/codsen/tree/master/packages/codsen-tokenizer/) which uses it then [parser](https://gitlab.com/codsen/codsen/tree/master/packages/codsen-parser/) which uses tokenizer, then finally [linter](https://gitlab.com/codsen/codsen/tree/master/packages/emlint/) which uses parser. With Lerna I can work on all 4 and parser's tests help to catch tokenizer's bugs and all the way down. Equally, when I tinker with string matcher, I can run unit tests on every single package in a monorepo, to ensure a new feature didn't break anything. It's like [dont-crack](https://github.com/bahmutov/dont-crack) but automated, at monorepo-scale.

That's where Lerna is strongest.

There are [other tools of Lerna-level](https://github.com/korfuri/awesome-monorepo#build-systems--dependency-management-tools) that help to manage the complexity and I encourage you to **research them deeply**. Each tool solves a specific challenge, do ensure that Lerna is the right tool to solve your challenges. For example, [fusion.js](https://github.com/fusionjs/fusionjs) uses [jazelle](https://github.com/fusionjs/fusionjs/tree/master/jazelle), that's based on Bazel.

Now, straight to your questions.

> I want lerna to install all dev and prod dependencies of the packages to the main root node_modules.

It's very important to distinguish have the "dependencies" been published to npm and are being consumed from the Internets, or are "tinkered with" and exist only on local. I assume that it's the latter case.

> When I run the bootstrap command it installs all the dependencies to the root node_modules.

That's public packages, those outside of monorepo. They are assumed to be published to npm and not "tinkered with". Basically, it's `npm i`.

> But after that process it symlink some of the packages to each other.

That's unpublished packages, those that been "tinkered with" locally and you can't `npm i` them from Internets. They might have been published previously but on local we have newest, unreleased versions of them. That's why we keep them in a monorepo, otherwise we'd `npm i` if they could be consumed from the internet.

> I just want the install all dependencies to the root node_modules including dependent packages. I don't want any symlink dependency.

I have huge suspicion that this root is your web project's root and you will aim webpack onto it. Anyway, in theory, with some scripting help, it can be done. 

Basically, first, run `bootstrap` without `hoist`, then use make or other script to copy all package folders into root `node_modules`. That's a scripting task, use what you know best: make, Node CLI's, Bash scripting, whatever you know best. It's a task to copy bunch of folders from folder A to folder B. For example, here's a script where I manually "go into" each package in a monorepo and run `npm publish` from that path: https://gitlab.com/codsen/codsen/-/blob/master/scripts/republish.sh (script) + https://gitlab.com/codsen/codsen/-/blob/master/Makefile ("parent" makefile). Something like that.

But anyway, I suspect you are using a wrong tool for the job. Maybe Lerna is not the right tool for you?

Please don't forget to post here, how it went, so that we can help you further or to close this ticket.
