### ISSUE TITLE
`lerna` does not create links on local referenced dependencies in package.json

### ISSUE THREAD

**Issue by ejmarino** [lerna/lerna#2491]
I have some projects and I changed its dependencies by using file references in package.json:
por example:
```
	"dependencies": {
		"@gcw/model": "file:../gcw-model",
		"angular-animate": "1.7.9"
       }
```
`npm install` (version 6.13.7) creates a link in node_modules linking to the folder.
but lerna bootstrap (even lerna link --force-local) does not create it.

## Expected Behavior

I expect that every time I execute lerna bootstrap, I have all my projects with links between them created.

## Current Behavior

If I run npm install on every project. NPM does create the links, and Lerna does not delete it, which is ok, but if I delete the links, lerna does not create them either.

## Steps to Reproduce (for bugs)
1.  Create a lerna style project with 2 or more projects
2.  Declare the dependency of one project to another referencing it using `file:../my-dep-proj`
3.  Ensure that you don't have already the link created inside node_modules
4.  Run `lerna boostrap`, and see it doing nothing about the link.

```json
{
  "packages": [
    "packages/*"
  ],
  "version": "0.20.0"
}
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.13.7|
| `node --version` | v13.10.1 |

| OS | Version |
| --- | --- |
| Windows 10 Pro | 1909 18363.657|

**Comment by jceb** [comment]
I was able to reproduce the behavior with `npm` 6.14.6, `yarn` 1.22.4, `lerna` 3.22.1, and `node` v12.18.3.
When I referenced the local packages with a version number instead of the `file:..` link `lerna bootstrap` created the links.

**Comment by jceb** [comment]
This issue seems to be a duplication of #2352

**Comment by ericprud** [comment]
I dropped some [research results and workarounds](https://github.com/lerna/lerna/issues/2352#issuecomment-753682568) there; mentioning here 'cause this is still open.

**Comment by ericprud** [comment]
On Jan 4, 2021, I created a PR to enable the expected behavior from `file:` intra-module dependencies (instead of versioned deps). This is how npm (and maybe yarn?) enable mono-repos.
-- https://github.com/lerna/lerna/pull/2789

On Jul 27, 2021, stefan-toubia asserted that that using `file:` leads to performance problems:
-- https://github.com/lerna/lerna/issues/2352#issuecomment-887633399

I think it's worth investigating that as using `file:` makes the whole process less opaque to users and possibly less brittle in the face of an orphaned version (if it were less opaque, i'd understand what situations make it brittle).
