### ISSUE TITLE
Lerna `ignoreChanges` does not work

### ISSUE THREAD

**Issue by ktalebian** [lerna/lerna#2522]
`lerna publish` keeps failing because `package-lock.json` is modified but it's in `.gitignore`. My `lerna.json` is 
```json
{
  "lerna": "3.20.2",
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "ignoreChanges": [
        "packages/package1/package-lock.json",
        "packages/package1/package-lock.json",
        "package-lock.json",
        "packages/*/package-lock.json"
      ]
    }
  },
  "version": "1.0.0"
}
```

## Expected Behavior
To publish a new version even if `package-lock.json` is modified

## Current Behavior
`lerna publish` is printing:

```
lerna info execute Skipping releases
lerna ERR! Error: Command failed: git add -- packages/package1/package.json packages/package1/package-lock.json packages/package2/package.json packages/package2/package-lock.json lerna.json
lerna ERR! The following paths are ignored by one of your .gitignore files:
lerna ERR! packages/package1/package-lock.json
lerna ERR! packages/package2/package-lock.json
lerna ERR! Use -f if you really want to add them.
...
```

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.0 |
| `npm --version`  | 6.14.3 |
| `node --version` | 12.14.1 |

**Comment by aprilandjan** [comment]
Maybe you should add `"ignored-file"` in `ignoreChanges`, for example:

```
{
  "lerna": "3.20.2",
  "packages": [
    "packages/*"
  ],
  "command": {
    "publish": {
      "ignoreChanges": [
        "ignored-file"
      ]
    }
  },
  "version": "1.0.0"
}
```

**Comment by ktalebian** [comment]
@aprilandjan sorry, but I don't see the difference between your comment and my original question. I too have the `package-lock.json` files in the `ignoreChanges`. So what are you suggesting that is different than mine?

**Comment by aprilandjan** [comment]
@ktalebian sorry I misunderstood your problem and give a meaningless comment days ago.

I am able to reproduce your situation if I chose to ignore `package-lock.json` files. After digging into lerna cli a little more, it seems that when `lerna` run publish and is about to bump a version for package, it always:

1.  Try to update its `package-lock.json` file if it exits([source](https://github.com/lerna/lerna/blob/master/commands/version/lib/update-lockfile-version.js#L9)). so if you use yarn, this will not be problem i guess.
2.  Add the updated `package-lock.json` file  to `changedFiles`([source](https://github.com/lerna/lerna/blob/master/commands/version/index.js#L532))
3. Pass these `changedFiles` to the command `git add`([source](https://github.com/lerna/lerna/blob/master/commands/version/index.js#L619)). Since these lock files are marked as ignored in `.gitignore`, the command will fail, thus make the `publish` command failed.

I'm not familiar with npm `package-lock.json` things and it's hard to say whether this behavior is by design  of lerna or not, but it's better to check if the file is in project ignored list or not. To avoid this error for now, maybe you can:

1. Use `yarn` instead of `npm`, in `lerna.json` you can set `npmClient` to `yarn`;
2. Delete `package-lock.json` files manually before run `lerna publsh`;
3. Just add `package-lock.json` into git track list, that is the reasonable way to handle these lock files.
