### ISSUE TITLE
Can not publish the same packages to multiple private registries

### ISSUE THREAD

**Issue by dantodev** [lerna/lerna#2563]
## Expected Behavior

When I run the following commands in the following order:

```bash
lerna version
lerna publish from-package --registry https://registry-a.com
lerna publish from-package --registry https://registry-b.com
```

I expect the new versions of all packages get published on registry-a.com and registry-b.com.

From[ lerna docs](https://github.com/lerna/lerna/tree/master/commands/publish#bump-from-package) for `lerna publish from-package`:

> [...] the list of packages to publish is determined by inspecting each package.json and determining if any package version is not present in the registry.

## Current Behavior

Currently the packages will only be published to registry-a.com. When lerna tries to publish to registry-b.com it only outputs the following:

```
lerna notice cli v3.20.2
lerna notice from-package No unpublished release found
lerna success No changed packages to publish
```

Adding `--force-publish` doesn't help either.

<details><summary>lerna.json</summary><p>

```json
{
  "version": "0.8.8",
  "npmClient": "npm",
  "registry": "https://registry-a.com/",
  "packages": [
    "packages/*"
  ]
}
```
</p></details>

## Context

Due to an acquisition my company has to move all package to a different registry but the packages still need to be available from our current registry to serve legacy environments that cant access the new registry due to networking reasons. This also includes new package versions, so I have to publish the same packages/versions from my lerna project to two different registries.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.20.2 |
| `npm --version`  | 6.12.0 |
| `node --version` | 12.13.0 |

| OS | Version |
| --- | --- |
| Windows 10 | 10.0.18363 Build 18363 |

**Comment by AlanSl** [comment]
Do you have anything configured in your leaf packages' package.json `publishConfig`? Or in `.npmrc`? Because apparently any in-file config always overrides any CLI flags, apparently by design 🤔 

I had a similar issue where my registry-a (in my case, GitHub packages) was set up in each package's package.json like:

```
  "publishConfig": {
    "registry": "https://npm.pkg.github.com/"
  },
``` 
...and I wrote an npm script to publish to a local Verdaccio, for local dev testing purposes, using the `--registry` flag, something like this:

```
    "local-publish": "lerna publish from-package --registry=\"http://localhost:4873/\" --no-git-tag-version --no-push --no-verify-access",
```
My expectation was that the `--registry` flag would override the `publishConfig`. The opposite happened.

Reading the docs closer, it appears to be the opposite by design: it seems that any publishConfig or `.npmrc` overrides the CLI flag. The reasoning appears to be that the CLI flag is global while publishConfig is per-package so more specific (while I was seeing it as, the in-file config is the fixed default and the per-command CLI flag is more specific).

I'm going to try resolving this by removing all in-file registry config and using npm scripts with `--registry` flags for all publishing. Not ideal, because if someone accidentally or carelessly runs `lerna publish` instead of these scripts, it could end up on the default NPM registry...

**Comment by dantodev** [comment]
Oh I see, its also the case in my project. I had registry set in my lerna config.

Very confusing, but thank you.
