### ISSUE TITLE
devDependencies in top level or individual package?

### ISSUE THREAD

**Issue by christophercliff** [lerna/lerna#258]
The babel repo has many dependencies in the [top level `package.json`](https://github.com/babel/babel/blob/22eb40d204f6d7fddc5bda4f82c85c17fe0d6710/package.json#L4-L46) but also [some in the individual packages](https://github.com/babel/babel/blob/e64aeb73164d1b164c1eafde424c88d8d4f77f0b/packages/babel-cli/package.json#L33-L35).

What's the reasoning there?

**Comment by thejameskyle** [comment]
The way I choose to divide things up is push all common devDependencies to the top-level unless I'm importing those devDependencies within tests or something.

For example [cf-ui](http://github.com/cloudflare/cf-ui) depends on `assert-equal-jsx` in a lot of packages. Because it is a package that is imported within `packages/*/test/*.js`

**Comment by cchamberlain** [comment]
@thejameskyle is it safe to say that strictly non-cli build / deploy dependencies can be moved to the top?
