### ISSUE TITLE
Support for conventional commits with scope

### ISSUE THREAD

**Issue by marboro92** [lerna/lerna#2630]
According to the conventional commits guide https://www.conventionalcommits.org/en/v1.0.0/ 

Commits can be scoped, ex: "feat(Component): an update"

## Expected Behavior
My understanding would be  that scoped commits would be added to the changelog and release notes.

## Current Behavior
Only conventional commits without scope are added to the changelog and release notes

## Possible Solution
Could you clarify which options in the conventional commits guide are supported? 

## Steps to Reproduce (for bugs)

1. commit a scoped commit ex: "feat(Component): an update"

<details><summary>lerna.json</summary><p>

```json
{
  "version": "3.0.1",
  "npmClient": "yarn",
  "useWorkspaces": true,
  "command": {
    "version": {
      "createRelease": "github",
      "ignoreChanges": [
        "**/__snapshots__/**",
        "**/**.spec.js",
        "**/**.story.js",
        "*.md",
        "./docs/*",
        "./components-e2e/*"
      ]
    },
    "publish": {
      "conventionalCommits": true,
      "allowBranch": ["master"]
    }
  }
}
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context
Scope would provide sections in the change log in addition to fix/feature/chore.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | VERSION |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by jpSimkins** [comment]
Conventional commits with scope is useless from my experiences with Lerna. I have yet to have any breaking change or a feat bump the version properly, all I ever get are minor increments. I would really appreciate a proper implementation of scope as this is currently unusable.

I have not tested with scope being a path in the repo. I assume this is what is required for this to work although this is not required by conventional commits' spec.

**Comment by JamesHenry** [comment]
@taenykim agreed! I don't believe this is an issue, I have used it frequently myself. I think it's just a case that this issue is naturally out of date after such a long time.

@marboro92 Sorry this issue never got responded to, hopefully you have seen that recently Nrwl took over stewardship of lerna (announcement here https://github.com/lerna/lerna/issues/3121), and we are excited to kick things on from here.

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

I will close this one for now, if you run into any issues with the latest version of lerna please feel free to use one of our new issues templates: https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
