### ISSUE TITLE
node v4 "Too many args"

### ISSUE THREAD

**Issue by dawsonbotsford** [lerna/lerna#270]
node `5` and `6` pass while `4` fails with `Too many arguments`

command ran: `$ lerna run test`. And `npm test` is running `xo && ava`.

Here's the full Travis output:
https://travis-ci.org/dawsonbotsford/openg/jobs/143505486

**Comment by thejameskyle** [comment]
What? According to my twitter feed, the node people *love* arguments

**Comment by thejameskyle** [comment]
I cloned and installed your repo locally and used the same version of node that travis was. I wasn't able to reproduce you error.

I'm going to close this, but if you have any more information that can help me debug then I will reopen it

**Comment by inyono** [comment]
I ran into the same problem. The reason was that I unintentionally installed lerna v1. It works with v2, though.

**Comment by dawsonbotsford** [comment]
I faced this in Lerna 2: 

```json
  "lerna": "2.0.0-beta.24",
  "version": "independent"
```

**Comment by gigabo** [comment]
Hi @dawsonbotsford, I've opened [a PR](https://github.com/dawsonbotsford/openg/pull/7) to get your tests fixed up in node v4.

Turns out `openg-cli` was missing a dep on `shelljs`.  This wasn't reported well because travis was actually using `lerna@1.1.3`.  I updated your travis config to have it use the local copy of Lerna rather than a separate globally-installed copy.
