### ISSUE TITLE
lerna --help shows "cli.js" as command name

### ISSUE THREAD

**Issue by MHebes** [lerna/lerna#2747]
When running `lerna --help`, the commands are listed as being run with `cli.js`. A minor bug.

## Expected Behavior
The help command output should look like this:

```
$ lerna --help
Usage: lerna <command> [options]
# ...
```

## Current Behavior
It actually looks like this:
```
$ lerna --help
Usage: cli.js <command> [options]
# ...
```

## Possible Solution
Get the argv[0] from the correct place, or maybe hardcode `lerna` into the printout.

## Steps to Reproduce (for bugs)
1. Open `cmd` or a `mingw64` shell on Windows.
2. `npm install -g lerna`
3. `lerna --help`
4. Observe output.

## Context
Not a huge problem :)

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 6.14.4 |
| `yarn --version` | N/A |
| `node --version` | v12.16.3 |

| OS | Version |
| --- | --- |
| Windows 10 | 1909 |

**Comment by Mathias54** [comment]
this problem is related to yargs dependency. 

in `cli/index.js` there is this code in line 20: 

```
  return globalOptions(cli)
    .usage("Usage: $0 <command> [options]")
```

From [yargs docs](https://github.com/yargs/yargs/blob/master/docs/api.md#usagemessagecommand-desc-builder-handler): "$0 will get interpolated to the current script name or node command for the present script similar to how $0 works in bash or perl."

Lerna is using version "14.2.2" while yargs latest version is version. I'll check out if this is still a problem in the version "16.2.0".
