### ISSUE TITLE
Lerna doesn't stop dev server of create-react-app

### ISSUE THREAD

**Issue by Janealter** [lerna/lerna#2909]
Lerna doesn't stop dev server of `create-react-app` (this is `webpack-dev-server`) if I use `lerna run dev --parallel --stream`. If I type Ctrl + C the server still working and listening to port 3000.

## Expected Behavior
Lerna should stop the server, as in version 3.22.1.

## Current Behavior
Lerna doesn't stop the server after using Ctrl + C.

## Possible Solution
Using version 3.22.1 of Lerna =)

## Steps to Reproduce (for bugs)
1. Create react app inside `packages` by command `npx create-react-app react-app`
2. Create `package.json` in the root directory with script `lerna run start --parallel --stream`
3. Run `yarn start`
4. Type Ctrl + C in the terminal

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "useWorkspaces": true
}
```
</p></details>

## Context
I have created the monorepo with `client` and `server` packages. In `client` directory I have react app, in `server` - node app. I have wanted to develop these apps with help of the Lerna command `run` that should start react app (script `react-scripts start`), node app (script `ts-node-dev --ignore-watch node_modules src/main`), and stop both after typing Ctrl + C.

## Your Environment
Terminal: Git Bash inside VSCode

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 6.14.12 |
| `yarn --version` | 1.22.10 |
| `node --version` | 14.16.1 |

| OS | Version |
| --- | --- |
| Windows | 10.0.19042 |

**Comment by stuyy** [comment]
Having the same issue.

**Comment by interactive-web-dev** [comment]
The simplest workaround I could think of was using [kill-port](https://www.npmjs.com/package/kill-port) before running the lerna command. I don't love keeping track of hardcoded port numbers, but it suits my needs for a small project. I opted to install kill-port as a dev dependency in the root folder, since the port connection is only an issue when starting the react app with lerna.

<details>
  <summary>root package.json script before:</summary>
    "scripts": {
     "start": "lerna run --parallel start --stream"
    }
</details>
<details>
  <summary>root package.json script after:</summary>
    "scripts": {
     "start": "kill-port 3000 && lerna run --parallel start --stream"
    }
</details>

It has the advantage of being forward-compatible for projects that get maintained infrequently - no harm in trying to kill a port that new future versions of lerna have closed properly.

**Comment by JamesHenry** [comment]
Hi Folks 👋 

I'm sorry you ran into issues here. I'm pleased to say that the modern task runner (powered by Nx) that we shipped first as opt-in in v5 and then as the default in v6 (the latest major at the time of writing) does not suffer from this issue. I walked through all the steps of the OP with the modern default task runner and everything exits just fine.

Please update to the latest `lerna`, and of course if you run into any fresh issues please create a new github issue with as much context/steps to reproduce as possible.

Many thanks!
