### ISSUE TITLE
Security Vulnerability in @lerna/conventional-commits

### ISSUE THREAD

**Issue by Flavyoo** [lerna/lerna#2916]
## Expected Behavior

No Security Vulnerability

## Current Behavior

Security vulnerability in trim-newlines package. See https://github.com/conventional-changelog/conventional-changelog/issues/808
## Possible Solution

Update conventional-changelog-core to latest once they have resolved the issue on their end.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | VERSION |
| `yarn --version` | VERSION |
| `node --version` | VERSION |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by hsharif-rh** [comment]
@Flavyoo  This security vulnerability is also being flagged for the latest version `4.0.0`.

I wonder this will be patched...

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, the relevant packages have been updated and you will no longer see any `npm audit` issues when using the v5 releases of lerna we have cut since we took over.

![image](https://user-images.githubusercontent.com/900523/173338555-25aefc47-85a9-492e-ad18-03894fd8150a.png)


If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
