### ISSUE TITLE
High severity vulnerability in normalize-url

### ISSUE THREAD

**Issue by rouke-broersma** [lerna/lerna#2926]
```
Dependabot cannot update normalize-url to a non-vulnerable version
The latest possible version that can be installed is 3.3.0 because of the following conflicting dependency:

lerna@4.0.0 requires normalize-url@^3.3.0 via a transitive dependency on parse-url@5.0.2
The earliest fixed version is 4.5.1.
```

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0|

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, the relevant packages have all since been patched and there are no such audit warnings when using our latest v5 packages we released since we took over.

If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
