### ISSUE TITLE
Security issue from dependencies

### ISSUE THREAD

**Issue by dalisoft** [lerna/lerna#2947]
# Security issue from dependencies

https://github.com/advisories/GHSA-7p7h-4mm5-852v

## Expected Behavior
No vulnerability

## Current Behavior
In GitHub security section: `lerna@4.0.0 requires trim-newlines@^1.0.0 via a transitive dependency on meow@3.7.0
`

## Possible Solution
-

## Steps to Reproduce (for bugs)

1. Install `lerna` on your project
2. Publish to GitHub
3. Allow GitHub scan your codebase

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 7.19.0 |
| `yarn --version` | 1.22.10 |
| `node --version` | v16.4.2 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by joeythomaschaske** [comment]
Somewhat related, but this package should really only be in your `devDependencies` and you can avoid this by running `npm audit --production`.

This is the recommended solution from react, since it will never be deployed to production the audit warnings aren't really detrimental.

https://github.com/facebook/create-react-app/issues/11174

**Comment by cronon** [comment]
I can't agree. A vulnerable devDependency can inject malicious code to the production code, or it can steal developer's data. Therefore vulnerabilities within devDependencies has to be treated seriously as well.

**Comment by joeythomaschaske** [comment]
@cronon Not an issue if you have a security linter https://github.com/nodesecurity/eslint-plugin-security

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, the relevant packages have been updated and you will no longer see any `npm audit` issues when using the v5 releases of lerna we have cut since we took over.

![image](https://user-images.githubusercontent.com/900523/173338555-25aefc47-85a9-492e-ad18-03894fd8150a.png)


If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
