### ISSUE TITLE
TypeError when running npx lerna init

### ISSUE THREAD

**Issue by M4FFS** [lerna/lerna#2979]
## Expected Behavior
`npx lerna init` works

## Current Behavior
it doesn't; results in a `TypeError`

## Steps to Reproduce (for bugs)

1. yarn add lerna --dev
2. npx lerna init

<details><summary>lerna.json</summary><p>

(There is no lerna.json because the `init` command is what's failing)
</p></details>

## Context

Unuseable 

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 7.20.6 |
| `yarn --version` | 1.19.1 |
| `node --version` | 14.17.4 |

| OS | Version |
| --- | --- |
| macOS Big Sur | 11.5.2 |

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, due to its age it is no longer applicable because this issue is no longer present in the v5 releases we have cut since we took over the project.

If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
