### ISSUE TITLE
 ERR! ERR_TLS_CERT_ALTNAME_INVALID

### ISSUE THREAD

**Issue by haoyinag** [lerna/lerna#3001]
### Steps
1. npm i -g lerna
2. lerna init
3. lerna create @usi-utils/pattern
4. lerna add immer
5. lerna publish
 
### error
```bash
....
lerna ERR! ERR_TLS_CERT_ALTNAME_INVALID request to https://registry.npm.org/@usi-utils%2fpattern failed, reason: Hostname/IP does not match certificate's altnames: Host: registry.npm.org. is not in the cert's altnames: DNS:*.cloudwaysapps.com, DNS:cloudwaysapps.com
```
### npm
```bash
$ npm get registry
https://registry.npmjs.org/
```

### *.json
```bash
# package.json
{
  "name": "root",
  "private": true,
  "useWorkspaces": true,
  "npmClient": "yarn",
  "devDependencies": {
    "lerna": "^4.0.0"
  }
}

# packages\pattern\package.json
{
  "name": "@usi-utils/pattern",
  "version": "0.0.6",
  "description": "> TODO: description",
  "author": "Yu Nan <haoyinag0@hotmail.com>",
  "homepage": "https://github.com/haoyinag/yunan#readme",
  "license": "ISC",
  "main": "lib/pattern.js",
  "directories": {
    "lib": "lib",
    "test": "__tests__"
  },
  "files": [
    "lib"
  ],
  "publishConfig": {
    "registry": "https://registry.npm.org/"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/haoyinag/yunan.git"
  },
  "scripts": {
    "test": "echo \"Error: run tests from root\" && exit 1"
  },
  "bugs": {
    "url": "https://github.com/haoyinag/yunan/issues"
  },
  "dependencies": {
    "immer": "^9.0.6"
  },
  "gitHead": "7d1e8464eed13192c13c7634399a05feed158413"
}

```

### Environment 
| Executable | Version |
| ---: | :--- |
| `lerna --version` | "^4.0.0" |
| `npm --version`  | 6.14.13|
| `yarn --version` | 1.22.5|
| `node --version` | v14.17.3|
  
### And
I search for a long time to find the answer but all get  "npm config set registry https://registry.npmjs.org/" that doesn't work ,

I even set "209.95.59.244   registry.npm.org" in hosts that i don't know it doesn't work or not .

**Comment by JamesHenry** [comment]
Hi @haoyinag 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, it seems like it is not something the lerna can influence or control because it seems to be something relating to your communication with the npm registry.

For example the presence of `DNS:*.cloudwaysapps.com` in your logs there is unexpected, perhaps you have some proxy configuring or VPN installed or your computer and this is impacted your requests. Maybe check the configuration in any `.npmrc` files in your project or computer user's root directory (e.g. `~/.npmrc` on a mac) as well.

Because this is not something lerna can directly influence I am going to close this one for now.

If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
