### ISSUE TITLE
Should we document that `--force-local` updates dependency lockfiles?

### ISSUE THREAD

**Issue by AndrewSouthpaw** [lerna/lerna#3007]
While hunting around for a way to generate `package-lock.json` files for all our lerna packages ([related thread](https://github.com/gathertown/gather-town/pull/4376)), we discovered it's possible to pass `--force-local` and that gets the lockfiles to actually be updated. It works because of [this line](https://github.com/lerna/lerna/blob/a47fc294393a3e9507a8207a5a2f07648a524722/commands/bootstrap/index.js#L149).

That's great, because it's what _we_ want, but it seems strange because we don't necessarily want/care about the stated behavior of `--force-local`:

> When passed, this flag causes the bootstrap command to always symlink local dependencies regardless of matching version range.

Not a problem in our case, but seems strange.

## Expected Behavior

Either `bootstrap` updates lockfiles, or there's a flag like `--update-lockfile` or `--save` or something to indicate we want to update lockfiles.

## Current Behavior

We either use `--force-local` or one of the other workarounds discussed in other systems.

## Possible Solution

It makes more sense to me that bootstrap would update lockfiles, since I think of it as being analogous to `npm install` which does the same, but maybe that metaphor is faulty. (I would imagine most think of bootstrap that way though.)

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.22.1 |
| `npm --version`  | 6.14.15 |
| `node --version` | 14.17.6 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS | 10.14.6 |

**Comment by liamuk** [comment]
Hi all -- another member of @AndrewSouthpaw's team here.

I think in particular the issue is that we use `--include-dependencies --scope` and [this particular line](https://github.com/lerna/lerna/blob/a47fc294393a3e9507a8207a5a2f07648a524722/commands/bootstrap/index.js#L149) that Andrew pointed out doesn't have the right behavior when you use `--include-dependencies --scope`

It looks to me like this logic is there to disable package-lock when you are installing registry versions of local dependencies (I'm making this deduction based on the warning that gets printed on the next line). When we use `--include-dependencies --scope`, it is always true that `filteredPackages.length !== this.targetGraph.size` (because we're only targeting a subset of all the modules in our repo), regardless of whether or not we're installing registry versions.

The reason `--force-local` is a workaround is because it bypasses this conditional branch altogether.
