### ISSUE TITLE
lerna publish return Error 400

### ISSUE THREAD

**Issue by jianhao** [lerna/lerna#3012]
The first release failed because the owner was not added, and then after adding the owner, when using the parameter from-git to publish again, an error of 400 was returned.

Then I added the maintainers field in package.json, it was fine, but I did not find the introduction about this part in the document

lerna version: v4.0.0
node version: v14.15.4

Error screenshot：
<img width="1135" alt="wecom-temp-1cf93b20b2cb8bec24baf708b8235faf" src="https://user-images.githubusercontent.com/30502487/137666835-fe86307f-eea1-4242-b8a2-2129dae1e580.png">

**Comment by JamesHenry** [comment]
Hi @jianhao 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

In the case of this specific issue, lerna doesn't have any special logic around npm `maintainers`, so this must have been an error returned from the npm registry when you were trying to publish. For example, maybe your npm account was not configured to have the right access, or the `package.json` file had conflicting `maintainer` metadata and the npm regsitry decided it was invalid.

Because these things are not something we can influence or control on the lerna side I am going to close this one for now.

If you run into any issues on the latest version of lerna, please feel free to open a new issue and follow the instructions:
https://github.com/lerna/lerna/issues/new/choose

Many thanks 🙏
