### ISSUE TITLE
lerna ERR! Error: Command failed with exit code 1: git commit -F

### ISSUE THREAD

**Issue by suiboyu** [lerna/lerna#3041]
I use lerna for multi-packet management，However, some errors were encountered at runtime:

When I run this command：

```bash
"ver": "git checkout -f master && git pull && npx lerna version --include-merged-tags --conventional-commits --conventional-graduate --yes"
```

The error message is as follows：

```js
lerna ERR! Error: Command failed with exit code 1: git commit -F /tmp/fec17535-b9bd-4dac-8e45-5742d7068470/lerna-commit.txt
lerna ERR! Stashing changes... [started]
lerna ERR! Stashing changes... [skipped]
lerna ERR! → No partially staged files found...
lerna ERR! Running tasks... [started]
lerna ERR! Running tasks for *.{js,jsx,ts,tsx} [started]
lerna ERR! Running tasks for *.{css,md} [started]
lerna ERR! Running tasks for *.{js,jsx,ts,tsx} [skipped]
lerna ERR! → No staged files match *.{js,jsx,ts,tsx}
lerna ERR! prettier --write [started]
lerna ERR! prettier --write [failed]
lerna ERR! → 
lerna ERR! Running tasks for *.{css,md} [failed]
lerna ERR! → 
lerna ERR! Running tasks... [failed]
lerna ERR! 
lerna ERR! 
lerna ERR! 
```
I wish someone could help me。
😭😭😭😭😭😭😭😭😭😭😭

**Comment by JamesHenry** [comment]
@suiboyu when you run `lerna version` it will do a few things, including create a commit for you. In this case it looks like it was not able to create that commit.

Unfortunately there is not enough information here to assess why that might be the case.

The only hint there is that you some lifecycle scripts wired up (maybe precommit?) given it seems to be trying to run "tasks" and prettier. It looks a bit like lint-staged to me.

This suggests there is more going on in your set up than we can see here, and at this stage we would have to err on the side of this being a configuration/setup issue, rather than a lerna issue.

We are absolutely not ruling out that it could be a lerna issue, however, so if you believe it is could please kindly head over to https://github.com/lerna/repro in order to provide a minimal reproduction of your issue using the latest version of lerna, and fill out as much information as possible on a new issue on our new issue template https://github.com/lerna/lerna/issues/new/choose

Many thanks!

**Comment by lbyupup** [comment]
I have the same problem, how can I solve it?

**Comment by damianfabian** [comment]
running the command with `HUSKY=0 npm run lerna:version` fix it for me.
