### ISSUE TITLE
--use-workspaces and npm

### ISSUE THREAD

**Issue by johncmunson** [lerna/lerna#3060]
The docs state that `--use-workspaces` "enables integration with yarn workspaces". However, it makes no mention of npm. This is strange because npm also supports the concept of workspaces and is Lerna's default package manager.

So naturally, I am wondering if `--use-workspaces` is safe to use with npm workspaces or not. Really, I would just like the ability to tell Lerna to use the workspaces that I already have defined in package.json so that I don't have to define them again.

https://github.com/lerna/lerna/blob/main/commands/bootstrap/README.md#--use-workspaces

**Comment by yooouuri** [comment]
You can create a Lerna.json and set workspaces there?

**Comment by johncmunson** [comment]
Given the following root-level package.json...
```
{
  "workspaces": [
    "packages/*"
  ]
}
```
I can confirm that using "packages"...
```
{
  "packages": [
    "packages/*"
  ],
  "version": "0.0.0"
}
```
is NOT equivalent to "useWorkspaces"...
```
{
  "useWorkspaces": true,
  "version": "0.0.0"
}
```

At least not when using npm. I have not tested this with yarn.

But when you're using npm, the two methods above will produce very different results when analyzing the structure of node_modules, both at the root level and at the workspace level.

It would be nice if the docs were more clear surrounding the intended usage of "useWorkspaces", how exactly it operates, and whether or not it's supposed to be compatible with npm workspaces.

**Comment by ghost91-** [comment]
Hey, bumping again. Now that maintenance has been handed over to Nrwl, are there any plans to add proper support for npm workspaces? I think not much would actually need to be done, most of the necessary changes can probably be backported from [Lerna Lite](https://github.com/ghiscoding/lerna-lite), which is only based on workspaces and dropped the whole custom bootstrapping process. I think the most important change would be properly handling the subpackage versions in the root package-lock.json file, when bumping versions (see https://github.com/ghiscoding/lerna-lite/blob/main/packages/version/src/version-command.ts#L657).

**Comment by JamesHenry** [comment]
Hi Folks, I believe all the issues raised in this thread have since been addressed! If you encounter any specific problems please open a new dedicated issue and provide as much information about your circumstances as possible.

Additionally, please take a look at our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

One of the key items covered at length on there (please do read it for full context) is that now that we find ourselves in late 2022, it no longer makes sense for lerna to supplement package management concerns (such as installation, boostrapping, linking etc) which are covered reliably for monorepo workspaces by the three main package managers: npm, yarn and pnpm. `lerna bootstrap` et al were developed in a completely different era of the JavaScript ecosystem.

If you have any specific concerns please do join in on that discussion, and provide as much context as possible.

Many thanks 🙏
