### ISSUE TITLE
Lerna version error

### ISSUE THREAD

**Issue by varndellDrugDev** [lerna/lerna#3073]
running lerna version --conventional-commits --yes gives an Error: Command failed with exit code 1: git commit -F C:\Users\q1028004\AppData\Local\Temp\9292a093-3d93-48a5-8ed4-95ea2e98b69c\lerna-commit.txt

## Expected Behavior
For the change log to get updated.

## Current Behavior
By running the above, I get the indicated error message

## Steps to Reproduce (for bugs)

1. Make a change
2. push to repository
3. Run lerna version --conventional-commits --yes

<details><summary>lerna.json</summary><p>

```json
{
  "version": "independent",
  "npmClient": "npm",
  "useWorkspaces": true,
  "packages": ["packages/*"],
   "command": {
      "publish": {
          "conventionalCommits": true,
          "access": "private",
          "npmClient": "npm"
      },
      "version": {
          "push": false,
          "allowBranch": ["feat/*", "develop"]
      }
  }
}

```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
verbose git [
146 verbose git   'commit',
146 verbose git   '-F',
146 verbose git   'C:\\Users\\q1028004\\AppData\\Local\\Temp\\9292a093-3d93-48a5-8ed4-95ea2e98b69c\\lerna-commit.txt'
146 verbose git ]
147 error Error: Command failed with exit code 1: git commit -F C:\Users\q1028004\AppData\Local\Temp\9292a093-3d93-48a5-8ed4-95ea2e98b69c\lerna-commit.txt
147 error lerna notice cli v4.0.0
147 error lerna info versioning independent
147 error lerna success run No packages found with the lifecycle script 'lint-staged'
147 error lerna notice cli v4.0.0
147 error lerna info versioning independent
147 error lerna notice filter changed since "HEAD"
147 error lerna notice filter excluding dependents
147 error lerna info Looking for changed packages since HEAD
147 error lerna info Executing command in 11 packages: "npm run precommit"
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Context
I'm just trying to updated the change log files.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 4.0.0 |
| `npm --version`  | 6.14.13 |
| `node --version` | 14.17.3|

| Windows 10 | 19042.1466|
| --- | --- |
| NAME | VERSION |

**Comment by JamesHenry** [comment]
@varndellDrugDev when you run `lerna version` it will do a few things, including create a commit for you. In this case it looks like it was not able to create that commit.

Unfortunately there is not enough information here to assess why that might be the case.

The only hint there is that you have a precommit script wired up which appears to be trying to trigger lint-staged, but you do not have lint-staged set up. This suggests there is more going on in your set up than we can see here, and at this stage we would have to err on the side of this being a configuration/setup issue, rather than a lerna issue.

We are absolutely not ruling out that it could be a lerna issue, however, so if you believe it is could please kindly head over to https://github.com/lerna/repro in order to provide a minimal reproduction of your issue using the latest version of lerna, and fill out as much information as possible on a new issue on our new issue template https://github.com/lerna/lerna/issues/new/choose

Many thanks!
