### ISSUE TITLE
FATAL ERROR：Ineffective mark-compacts near heap limit  Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by changlin2569** [lerna/lerna#3120]
I have 9  packages. This error will occur when running locally. I guess it may be the cause of link. Is it the trigger of circular link？

**Comment by JamesHenry** [comment]
@changlin2569 it's important that you help us to help you, we will need a lot more details than this.

Please kindly fill out the issue template with as much information as possible: https://github.com/lerna/lerna/issues/new/choose

For bugs, please use https://github.com/lerna/repro in order to provide a minimal reproduction of your issue.

Many thanks!
