### ISSUE TITLE
I ran into this issue as well where my lerna publish failed due to some issue with our repository but the tags were created and now i am not able to republish that since it says no updated packages to publish

### ISSUE THREAD

**Issue by stormt** [lerna/lerna#3123]
I ran into this issue as well where my lerna publish failed due to some issue with our repository but the tags were created and now i am not able to republish that since it says no updated packages to publish

lerna info Checking for prereleased packages...
lerna info No updated packages to publish. 

what is the solution for this? how can i republish already created tags by lerna

_Originally posted by @vittalas in https://github.com/lerna/lerna/issues/455#issuecomment-411891018_

**Comment by revelt** [comment]
It has happened to me before. So, under default settings `lerna version` will push your git tags to remote. This behaviour can be disabled (I do that). If your publishing failed, the first thing is to double-check, 1. what exactly got published to npm; 2. what useless git tags were pushed to git remote. The easiest way to draw up the tag list is to check the git commits list, for example, my commitizen neatly listed all of them in the commit message:

![Screenshot 2022-06-20 at 21 38 35](https://user-images.githubusercontent.com/8344688/174674905-8726e537-d118-47f1-93a5-4344ddc25602.png)

Once you have the tags, delete them in two steps:

```
// step 1 - delete local git tags
git tag -d tag1 tag2
// step 2 - delete git tags on the origin
git push origin --delete tag1 tag2
```

I assemble both commands in sublime text and copy-paste into the terminal.

If the publishing failed but artefacts got pushed to git remote, force-push and override the git remote. Remember to do the tags as well. In general, git tags are separate from normal commits and they can linger even after --force push.

A good example helps a lot, check my setup: https://github.com/codsen/codsen/blob/main/.semaphore/semaphore.yml

Personally, I bump versions via `lerna version`, then generate changelogs via commitizen, then publish the package to npm without even using `lerna publish` (to granularly control what happens when).

Also, you'll notice I push tags right after the npm publishing (which happens via `turbo run`) — each package tries to publish via an npm script `"letspublish": "yarn publish || :",` — npm works in such way that un-bumped version packages won't publish. This `|| :` part exits with zero code, it never exits with non-zero code this way.

Also, never run CI right away, "gung-ho" — test it out first, row by row. During early runs, always either comment out the publishing CI yml rows or simply cut them out and back them up. Also, you can add debug lines to CI — add commends from `git changed` to `npm run lerna changed` — log all things on CI, check what's going on. Just mind the secrets. Build your CI script slowly, gradually, line-by-line.

**Comment by JamesHenry** [comment]
Closing in favour of #455
