### ISSUE TITLE
lerna Unknown argument: parallel

### ISSUE THREAD

**Issue by enadon** [lerna/lerna#3130]
when I am trying to start project with comand "lerna run start --parallel" I am getting error "lerna Unknown argument: parallel". What may cause this problem?
## Expected Behavior

project is starting normally

## Current Behavior

![image](https://user-images.githubusercontent.com/61207987/168878651-a9f17405-0628-481a-ba53-1844b7d57b67.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

<details><summary>lerna.json</summary><p>

```json
<!-- Please paste your `lerna.json` here -->
```
</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
<!-- If you have a `lerna-debug.log` available, please paste it here -->
<!-- Otherwise, feel free to delete this <details> block -->
```
</p></details>

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 3.0.6 |
| `npm --version`  | 6.14.11 |
| `node --version` | 14.15.5 |

| OS | Version |
| --- | --- |
| NAME | VERSION |

**Comment by ghiscoding** [comment]
just a guess here, but I think it might be because `start` is a reserved word in npm script as defined in this npm doc [using-npm: scripts](https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-start) and so npm (not lerna) says "hey I don't have a --parallel option, so I don't know what to do with that". I would guess that npm as priority over lerna when it's reserved words/commands. I made similar mistake with `npm install` in which I went in an infinite loop, without knowing, because I used the script name `install` to do `npm install` 😄

**Comment by JamesHenry** [comment]
Thank you @ghiscoding, that seems like a good explanation here!

@enadon please follow @ghiscoding guidance here and use a non-reserved (reserved by npm, not lerna) script name for your custom script and parallel should work as expected.
