### ISSUE TITLE
Question: How to publish a github private package

### ISSUE THREAD

**Issue by dimitardanailov** [lerna/lerna#3131]
Greetings, 

My manager gave me a task to make a research how to publish a **Private** package on github with Lerna. We've an organization account in Github.

**Comment by alexandercerutti** [comment]
Hey @dimitardanailov, we are proficiently publishing several monorepo packages on private github packages through lerna. It is not different from publishing on NPM but you have to authenticate to the registry and configure `package.json` repository field for each package you want to publish of the monorepo to have the correct path and for the root `package.json`.

**Monorepo package**

```json
{
	// ...
	"repository": {
		"url": "https://github.com/<organization>/<monorepoName>",
		"directory": "packages/<projectName>",
		"type": "git"
	},
}
```

**Monorepo root package.json**:

```json
{
	// ...
	"repository": {
		"url": "https://github.com/<organization>/<monorepoName>",
		"type": "git"
	},
}
```

You can see Github Packages doc here: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry

Hope this helps you!

**Comment by kerryj89** [comment]
If you are not using Github's solution above, you can use https://github.com/ramasilveyra/gitpkg.  I have been using it successfully for over a year on BitBucket.  The tool basically runs `npm package` behind the scenes and publishes only the package contents up as a detached git tag instead of to the npm registry.  You would then copy the tag link (often .tar.gz) and paste it in.

```json
// package.json
...
  "dependencies": {
    "@private-co/private-project": "https://user:pass@bitbucket.org/private-co/private-project/get/whatever@latest.tar.gz"
  }
...
```

If you browse that tag you will only see the package contents and not the entire repo, which was one problem I had with using npm's git integration (no shallow clone or subdirectory targeting so it would have to download over a GB each update).  I am not sure if they are treating git integration any better today, but it does rub against their private package business plan so I wouldn't be surprised if they haven't improved it.  Npm and Yarn v1's git integration understands semver, but it sadly doesn't attempt to on .tar.gz if I recall correctly.

This way of consuming packages however is not without it's downside.  Npm and Yarn has .lock files which they use to verify the integrity of your packages.  I have to run a preinstall npm script that removes my private packages from the lock files, so that's something you will have to debate with your team about.  Without doing that, while your @latest tag might have been updated, npm/yarn doesn't look beyond the filename and checksum for it so it prevents installing it when checksums mismatch (it doesn't look at the package version or have granular options to ignore certain packages).

**Comment by dimitardanailov** [comment]
@kerryj89 
Thank yoy very much for the additional information. My task requires to use Github. For me your comment is not so useful but could be useful for someone with goal: BitBucket.

---

@alexandercerutti

Thank you very much for your comment. I did a succesfull deploy. The only difference between your proposal and my current implementation is: `"directory": "packages/<projectName>",`. 

I'd like to share with the community: 
```
"publishConfig": {
    "registry": "https://npm.pkg.github.com"
  },
 ```
 
publishConfig is required package.json configuration.

**Comment by jakubprogramming** [comment]
> @kerryj89 Thank yoy very much for the additional information. My task requires to use Github. From my point of view: Your comment is not so useful but could be useful for someone with goal and target: BitBucket.
> 
> @alexandercerutti
> 
> Thank you very much for your comment. I did a succesfull deploy. The only difference between your proposal and my current implementation is: `"directory": "packages/<projectName>",`. I don't use this option.
> 
> I'd like to share with the community:
> 
> ```
> "publishConfig": {
>     "registry": "https://npm.pkg.github.com"
>   },
> ```
> 
> publishConfig is required package.json configuration.

Without the publishConfig it did not work for me. Thanks a lot for sharing this!
