### ISSUE TITLE
When running bootstrap, linked dependencies bin links fail with "EPERM: operation not permitted, symlink" on Windows.

### ISSUE THREAD

**Issue by cchamberlain** [lerna/lerna#319]
Not sure if this is an issue that may only exist with scoped packages or Windows but when I run bootstrap on a simple lerna repo with 2 scoped packages, the dependent package (@tixinc/config) which has a few bin scripts fails during symlinking.

![image](https://cloud.githubusercontent.com/assets/424694/17864558/64043910-6853-11e6-87ea-7c6ff9cb4f49.png)

If I go into the packages/js folder and `npm link ../config` directly, it works:

![image](https://cloud.githubusercontent.com/assets/424694/17864604/93af31ec-6853-11e6-8c6e-798857c953c7.png)

I've tried running lerna clean prior to bootstrap and get the same results regardless of concurrency. Here is the project structure:

![image](https://cloud.githubusercontent.com/assets/424694/17864662/cd45b4c6-6853-11e6-945a-3e5e3eea74fa.png)

**Comment by rygine** [comment]
This is a permissions error. Node needs to be run as administrator in order to create symlinks.

**Comment by cchamberlain** [comment]
Thanks @rygine, appears that was it.

**Comment by christianacca** [comment]
A better solution would be to use 'junction' links on windows rather than 'symbolic link'.

'junction' links on windows do not require admin/elevated permissions.

There is a similar (outstanding) issue and PR that solves it on the [linklocal project](https://github.com/timoxley/linklocal). Maybe this can be used as a reference for a similar change to lerna.

Here is the PR in question: https://github.com/timoxley/linklocal/pull/23
