### ISSUE TITLE
lerna doesn't install npm: alias packages

### ISSUE THREAD

**Issue by Botz** [lerna/lerna#3252]
## Current Behavior

If i add a dependency in a lerna package with npm protocol like
`"@nuxt/bridge": "npm:@nuxt/bridge-edge"`
the dependency will not be installed, and everything seems ok after an `lerna bootstrap`
In my demo Repo this is the only depdendency i don't have a node_modules folder and package-lock.json is empty

## Expected Behavior

packages with npm protocol should be installed or at least there should be an error that this isn't supported

## Steps to Reproduce

1. add a npm alias dependency to one of your lerna packages e.g.: `"@nuxt/bridge": "npm:@nuxt/bridge-edge"`
2. lerna bootstrap
3. check if there is a dependency called `@nuxt/bridge` in your node_modules folder or in your package-lock.json

### Failure Logs / Configuration

See repo: https://github.com/Botz/npm-protocol-lerna

</p></details>

### Environment

macos 12.4 Apple M1
node 14.17.6
npm 6.14.17
lerna 5.1.8

**Comment by ghiscoding** [comment]
as mentioned by original Lerna's author in this recent [comment](https://github.com/lerna/lerna/discussions/3140#discussioncomment-3033079) `bootstrap` should be deprecated in the future, basically you don't need `lerna bootstrap` anymore since all package managers support workspaces and do a better job at linking and symlinking than Lerna could do with bootstrap. However you're using an old version of npm, you should update to at least npm 7 and take advantage of [npm workspaces](https://docs.npmjs.com/cli/v8/using-npm/workspaces#defining-workspaces) docs), it will take care of the symlinks and should resolve your issue with dependencies not being installed.
