### ISSUE TITLE
Publish don't major the version

### ISSUE THREAD

**Issue by borisdamevin** [lerna/lerna#3344]
## Current Behavior

Publish first version of package from version `0.0.0` target version `0.1.0` and not version `1.0.0` like the docs say: 

> Note: If you have a major version zero, all updates are [considered breaking](https://semver.org/#spec-item-4). Because of that, running lerna publish with a major version zero and choosing any non-prerelease version number will cause new versions to be published for all packages, even if not all packages have changed since the last release.

## Expected Behavior

Publish version from `0.0.0` to `1.0.0`.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
    "version": "independent",
    "useWorkspaces": true,
    "useNx": true,
    "command": {
        "publish": {
            "message": "chore(release): publish",
            "ignoreChanges": [
                "**/*.md",
                "**/.github/*"
            ]
        },
        "version": {
            "conventionalCommits": true,
            "changelogPreset": {
                "name": "conventionalcommits"
            }
        }
    }
}
```
</details>

### Environment

* Windows 11

**Comment by GOGOGOSIR** [comment]
I had the same problem when I published in independent mode, using lerna publish --conventional-commits . Even if breaking change is set during git commit, the major version number still cannot be upgraded

**Comment by dazlious** [comment]
same here

**Comment by JamesHenry** [comment]
I'm not clear on what is being reported here, because the documentation provided seems to back up what you are declaring is a bug/undesired behaviour?

The linked documentation confirms that any version pre v1 is considered breaking, so when you perform a breaking change in v0, it is appropriate to move to v0.1.

v1.0.0 is considered a "special" version by the specification in which a developer is declaring a whole new chapter in the project's lifecycle - the public API is now fixed and will only change in subsequent major version changes (v1->v2 etc)

Lerna version can take in any semver specifier as a positional argument, so when it comes time to declare v1, so you can always do `lerna version 1.0.0` right?

Have I misunderstood what is being reported here?

**Comment by borisdamevin** [comment]
A breaking had to update the major version number and not the feature number.

For me, the logic between the explaination and the docs don't match.

**Comment by JamesHenry** [comment]
> A breaking had to update the major version number and not the feature number.

@borisdamevin That's exactly what happens, _as long as_ you are at version `1.0.0` or later, exactly as defined by the semver specification that you yourself link to.

In semver, everything before version 1.0.0 is **intentionally** allowed to be a breaking change, so the presence of a breaking change when the version is at `0.x` would definitely not dictate the need to move to `1.0.0` - that would not make sense with the semver specification.

More quotes from the spec:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes. 

I'm sorry that you do not agree with the specification here, but in order to have a tool that behaves most predictably to the broadest possible userbase, it is important that we align ourselves with the relevant standards when they exist.

Again, if you do not wish to take advantage of this special `0.x` semver behaviour, please simply start your packages out at `1.0.0` or later and everything will behave as you expect.

I'm going to close this one as lerna is behaving in accordance with the semver spec, and there is a known solution for folks who don't agree with the spec and want all changes to cause major version bumps from day 1 (simply start your package at version `1.0.0` or later).

Thanks all!
