### ISSUE TITLE
Error using `run`: "The legacy task runner option `--npm-client` is not currently supported"

### ISSUE THREAD

**Issue by tay1orjones** [lerna/lerna#3490]
## Current Behavior

Renovate (dependabot) attempted to update our project to the newest version (https://github.com/carbon-design-system/carbon/pull/12934), but CI fails with the error

```
lerna ERR! run The legacy task runner option `--npm-client` is not currently supported. Please open an issue on https://github.com/lerna/lerna if you require this feature.
```

## Expected Behavior

I believe this option should still be available. The error message was added in https://github.com/lerna/lerna/pull/3457. The docs [still mention it](https://github.com/lerna/lerna/tree/main/commands/run#--npm-client-client). I couldn't find a deprecation notice in the changelog.

## Steps to Reproduce

We have the following build script [in our project](https://github.com/carbon-design-system/carbon/blob/1270bab7e329f9e5ebadeb6278d08b53bec3d7e5/package.json#L18):

```
lerna run build --stream --prefix --npm-client yarn
```

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "3.13.4",
  "version": "independent",
  "npmClient": "yarn",
  "npmClientArgs": ["--frozen-lockfile"],
  "useWorkspaces": true,
  "ignoreChanges": [
    "actions/**",
    "**/__fixtures__/**",
    "**/__tests__/**",
    "**/docs/**",
    "**/e2e/**",
    "**/examples/**",
    "**/*.md"
  ],
  "command": {
    "version": {
      "message": "chore(release): %s"
    }
  }
}

```

</p></details>

### Environment
```
 Environment info:

  System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.3.1 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Utilities:
    Git: 2.36.1 - /opt/homebrew/bin/git
  npmPackages:
    lerna: ^6.0.0 => 4.0.0
```

**Comment by tay1orjones** [comment]
Removing the use of the `--npm-client` flag allows our build to succeed. `npmClient` is still specified in `lerna.json` but we don't hit an error.

**Comment by JamesHenry** [comment]
Hi @tay1orjones, sorry for any confusion here. Behind the scenes lerna has always delegated a lot of the task running heavy lifting to other libraries.

The `nx` task runner, which lerna delegates to in modern lerna versions, (instead of `p-map` and `p-queue` like it used to) will already always pick the appropriate npm client to use based on your package manager.

E.g. in your case it will detect you are using `yarn` and use that. Therefore the flag is no longer required with the modern task runner in lerna and that's why this error occurs if you try and use it.

The only case we no longer support here, is if for some reason folks were using one package manager for installation etc and then a different one for task running.

We can't think of any good reason to do that and so that is why we wanted to folks to open an issue if they ran into that situation.

Please let me know if you have any questions, or any further issues with lerna
