### ISSUE TITLE
Changelog update twice for same version in my case

### ISSUE THREAD

**Issue by whatwg6** [lerna/lerna#3502]
## Current Behavior

Changelog generate twice for same version, when exec lerna version --no-push --force-publish

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/18499153/213205631-ab92d785-d724-498f-8034-21998902421e.png">

## Expected Behavior

correct changelog

## Steps to Reproduce

```bash
$ git clone https://github.com/whatwg6/github-7tu1gg
$ yarn
$ npx lerna version --no-push --force-publis
```

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "useWorkspaces": false,
  "version": "0.0.2",
  "packages": [
    "."
  ],
  "command": {
    "version": {
      "allowBranch": [
        "main"
      ],
      "conventionalCommits": true,
      "exact": true
    },
    "publish": {
      "message": "chore(release): %s [ci skip]"
    }
  }
}

```

### Environment

- mac os
- node 16.18.0

**Comment by whatwg6** [comment]
After debug found lerna version command will update `pkg` and `root` changelog, in my case `pkg` and `root` was the same one. so changelog was update twice.

https://github.com/lerna/lerna/blob/510c3e993be09f8f070dd07ca3ee7d352d00e491/commands/version/index.js#L558
https://github.com/lerna/lerna/blob/510c3e993be09f8f070dd07ca3ee7d352d00e491/commands/version/index.js#L593

**Comment by fahslaj** [comment]
Hi @whatwg6 , thank you for opening an issue. I have cloned the repository that you linked and it appears that the root is being picked up as a package when it shouldn't be. This is due to the `packages` property in `lerna.json` including `"."`. I can see from your screenshot that you still have a "packages" folder. Consider changing the value of `packages` in `lerna.json` to `"packages/*"`. This will tell Lerna to look for package.json files in `packages/` but not in the root directory.

**Comment by whatwg6** [comment]
@fahslaj Sorry! screenshot was uncorrect. https://github.com/whatwg6/github-7tu1gg was right project structure and still has this problem.

**Comment by fahslaj** [comment]
@whatwg6 it looks like that repository has no packages in it. The issue is that the "packages" property in your `lerna.json` file has a value of `[ "." ]`. Lerna looks for package.json files at those paths, and "." includes the root package.json.

If your packages are in a nested folder, then update "." to be the folder name. If not, then you can use a value of `[ "**/*" ]` to detect all folders in the root of the repo.
