### ISSUE TITLE
ci: install only changed package dependencies

### ISSUE THREAD

**Issue by kalagin** [lerna/lerna#3507]
## Description

Maybe Im wrong, but if we have many packages and create MR - bootstrap is very heavy operation:

```json
"bootstrap": "lerna exec -- npm install",
```

now, we are using this solution:

```json
"bootstrap-changed": "changed=$(npx lerna changed --json | jq -r '[.[] | .name] | join(\",\")') && npx lerna exec --scope \"{${changed},}\" -- npm install",
```

## Suggested Implementation

this command install node_modules **only** for changed packages. Its improve CI/CD experience

```
lerna bootstrap --since
```

Thank you!

**Comment by fahslaj** [comment]
Hi @kalagin , thank you for the suggestion. Bootstrapping and package management capabilities are no longer the focus of Lerna, and starting from Lerna 7, "bootstrap", "add", and "link" will be in maintenance-only mode. For more information, see the [Lerna 7 Roadmap](https://github.com/lerna/lerna/discussions/3410).

It looks like you are using `npm` as your package manager. I would highly suggest you consider [using npm workspaces with Lerna](https://lerna.js.org/docs/getting-started#package-dependency-management) by setting `"useWorkspaces": true` in `lerna.json`. This will provide more features and a better overall package management experience without the need to run `lerna bootstrap` at all.

**Comment by pvieira91** [comment]
+1 
We are still using lerna bootstrap because of the capability of running bootstrap scoped to a package. AFAIK npm workspaces do not support that. 
Example: 
We have two main github workflows. One for our app and other for the libs. Both app and libs live in a monorepo. 
Once a commit is made on a lib the libs workflow is triggered. New versions are published. The package.json of the main app is updated which triggers the app workflow. For the app workflow we don't want to build the lib packages again... instead we want to get them from registry. Bootstrap --scope app give us that. It ignore symlinks and install everything from registry.
With the deprecation of lerna bootstrap we will lose that feature.

**Comment by fahslaj** [comment]
Thank you for your feedback @pvieira91 . You are correct that lerna bootstrap does allow an easy way of accomplishing that behavior. However, I believe that can also be accomplished by running `npm install --workspaces=false` from within the app's directory, or via `lerna exec`:

`lerna exec --scope=my-app -- npm install --workspaces=false`

**Comment by pvieira91** [comment]
> Thank you for your feedback @pvieira91 . You are correct that lerna bootstrap does allow an easy way of accomplishing that behavior. However, I believe that can also be accomplished by running `npm install --workspaces=false` from within the app's directory, or via `lerna exec`:
> 
> `lerna exec --scope=my-app -- npm install --workspaces=false`

This doesn't work. Lerna bootstrap would look at both the root's package json as the scoped package's package.json. 

For example

monorepo
---package.json
---packages/
------a/
---------package.json
------b/
---------package.json

If I run 
lerna bootstrap --scope a

lerna will install dependencies from monorepo/packages/a/package.json and monorepo/package.json. And it's not only install them separately it like it merges both package.json files.
