### ISSUE TITLE
Unknown argument: passWithNoTests

### ISSUE THREAD

**Issue by DoneDeal0** [lerna/lerna#3510]
I have a monorepo managed with `Lerna 6.4.0`. One of the folder don't contain any tests. When launching the tests with `yarn lerna run test`, I have the following error:

> No tests found, exiting with code 1
       Run with `--passWithNoTests` to exit with code 0

But when launching the command with the flag `yarn lerna run test --passWithNoTests`, I receive the error:

> ERR! lerna Unknown argument: passWithNoTests

How to ignore folders that don't have any tests?

```json
{
  "packages": ["app-one/*", "app-two/*", "app-three/*"],
  "npmClient": "yarn",
  "useWorkspaces": true,
  "version": "3.1.1"
}
```

### Environment

```
 Environment info:

  System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.19 - ~/Desktop/myapp/node_modules/.bin/yarn
    npm: 8.5.1 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Utilities:
    Git: 2.39.0 - /usr/local/bin/git
  npmPackages:
    lerna: ^6.4.0 => 6.4.0
```

**Comment by ghiscoding** [comment]
Lerna options are camelCase when provided in `lerna.json` but they must be kebab-case when provided in the shell, so you should try this instead
```sh
yarn lerna run test --pass-with-no-tests
```

**Comment by fahslaj** [comment]
Hi @DoneDeal0 , thank your for opening this issue. Though not explicitly stated, I'm going to assume you are using `jest` as a test runner.

Lerna requires that arguments passed to scripts be separated with "--". So the following command _should_ work: `yarn lerna run test -- --passWithNoTests`. However, it doesn't because yarn strips out the `--`. You can see this behavior work appropriately with `npx`: `npx lerna run test -- --passWithNoTests`.

If using yarn, you may need to put the `--passWithNoTests` argument inside of your script. Or, you could globally install lerna and run it directly with `lerna run test -- --passWithNoTests`.

Lastly, I'll point out that `--passWithNoTests` has no effect if there are test files that exist without assertions. It will only pass if there are no test files detected at all. See the [jest docs](https://jestjs.io/docs/cli#--passwithnotests) for details.

**Comment by DoneDeal0** [comment]
Thank you!
