### ISSUE TITLE
Specify the source directory

### ISSUE THREAD

**Issue by pedronauck** [lerna/lerna#360]
We're using lerna to build our react's application and to build that we split few parts of our code base into npm modules. For example, we have a package called `utils` that have a lot of scripts splitting by type, something like a internal lodash with more specifics scripts.

So, we have a big problem to import this scripts into our applications. When we were using this modules without lerna - just with npm - we could publish just the `dist` folder and use the import like that:

``` js
import { something } from 'utils/myModule';
```

And that's what we want. So, to do that, we needed just to publish de `dist` folder, because npm doesn't support configuration for a `main` folder, just a `main` file (and that's is sucks).

With lerna we can't do that (at least I don't know how), because are linked the intire folder from the package and when we do the import as above, npm will try to find `myModule` script in the root directory of the package. And we do that in the import:

``` js
import { myModule } from 'utils';

const { something } = myModule;
```

So, is there any way to link just the `dist` folder or other solution do can get the import like above?

**Comment by seansfkelley** [comment]
This shouldn't be too different from what you do when you publish -- if you require `foo/bar`, you need to have `bar.js` as a direct child of the `foo` directory. The downside is that this means you have to scatter compiled files all over your source tree while you dev it. I used to use these nested imports, but now I just plop everything into `index.js` and use destructuring imports (as in your examples) to fetch what I need. You can also use [nested destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Nested_object_and_array_destructuring), though it can get unreadable.

**Comment by thejameskyle** [comment]
This should be fixed by bootstrap using symlinks.

**Comment by duclet** [comment]
Wait, how does the bootstrapping helps here. Based on your example in the README.md, the symlink would be `packages/babel-core/node_modules/babel-generator` symlinks to `packages/babel-generator` but it really should be `packages/babel-core/node_modules/babel-generator` symlinks to `packages/babel-generator/dist`?

**Comment by duclet** [comment]
npm just publish a folder with a package.json file. It doesn't care how it is done. Many projects don't just publish the git repository but a dist folder only. That was the original question for this issue as I see it. Bootstrapping with the symlink does nothing to resolve the issue since it isn't even pointed to the right place.

**Comment by guscastro** [comment]
@duclet We have gone to great lengths to set up our monorepo working around this limitation and would appreciate if this could be revisited so that we could return to the default lerna structure.

For projects which require transpilation, it is quite limiting not to be able to have different working (`src/`) and publishing directories (`dist/`). Given the growth of TypeScript (source: StackOverflow developer surveys),  I can only see this becoming a bigger issue. I don't think anyone particularly likes having `.ts`, `.js` and `.js.map` files sitting in the same directory, nor at the root of your package in version control.

I understand the position of the lerna maintainers to stick to the NPM way, but the reality is that NPM is flexible enough to support this development pattern and `lerna` isn't. Ultimately, it is not NPM that is opinionated here, but lerna.

All we need here is to be able to tell lerna to symlink monorepo `node_modules` to the `<package/workspace>/dist` directories. Our current build pipelines will take care of ensuring that directory conforms to NPM requirements (i.e.: that it has a `package.json`). I imagine this will also be the case for others who have requested this feature.

**Comment by evocateur** [comment]
And `files` allows you to include directories in the tarball that results from `npm pack`.

**Comment by duclet** [comment]
That only helps in publishing, not during development. Also, that would also just include the "dist" in the name.

**Comment by evocateur** [comment]
> that would also just include the "dist" in the name.

Your consumers shouldn’t be aware of package structure.

**Comment by duclet** [comment]
And that is exactly why this whole issue was created for.

**Comment by evocateur** [comment]
No, this issue was opened to remove a single path item in a subpath import, which is itself user-hostile pattern.
