### ISSUE TITLE
Lerna doesn't take root .npmrc into account (on Linux)

### ISSUE THREAD

**Issue by yvele** [lerna/lerna#361]
## Expectation

With the following monorepo structure :

``` none
packages/
    foo/
        index.js
        package.json     --> with a @private/bar dependency
.npmrc                   --> with a custom registry
lerna.json
package.json
```

lerna is bootstraping fine on Mac OSX.
`@private/bar dependency` is installed properly with the custom registry. 
## Problem

But when I'm running it on **Linux**, bootstrap is failing to install the `@private/bar` dependency.
## Workaround

After struggling with this issue.. I finally found a workaround. Juste copy the `.npmrc`file on each package :

``` none
packages/
    foo/
        .npmrc         --> Workaround!
        index.js
        package.json
.npmrc
lerna.json
package.json
```
## Extra infos

Working fine on Mac OS X
Problem with Linux on both Ubuntu and Gentoo
Reproducing the problem with both lerna `v2.0.0-beta.30` and `v2.0.0-beta.28`

Inside my .npmrc :

``` none
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
access = restricted
```
## Extra questions

Does windows users have the same issue?
How does lerna install dependencies? Why is this different on Mac OS X and Linux?

**Comment by thejameskyle** [comment]
Lerna intentionally does not use the root `.npmrc`, see my comment over here: https://github.com/lerna/lerna/issues/296#issuecomment-261080345

**Comment by yvele** [comment]
@thejameskyle I agree with `.npmignore` files, but some of us are using private repositories and a global `.npmrc` would be really usefull

**Comment by danielo515** [comment]
@thejameskyle what you said makes no sense.
Forcing people to duplicate any kind of stuff is never a good idea, giving choices IS.
Why can't I choose if lerna should use the root `.npmrc` file ? Just because, maybe, someday,someone may want to opt out ? So I am forced to include an absolutely useless file (because is the same stuff over and over again) on all the packages that I want to include on my monorepo even knowing that any of them is going to opt-out from my current repository ? 
Sorry, but I see it as a waste of time.
As a general advice, since what you are building is a tool it is usually a good idea is to make it fit the need of the target users, and listening to their opinions and needs and giving solutions to them ( specially through options) is always a good idea.
If you want each package to behave like a normal package, why have you included hoisting ?

And what about the other question ? Why is this working on MACOS ?

Regards

**Comment by evocateur** [comment]
@danielo515 You can configure lerna with a [`--registry`](https://github.com/lerna/lerna/#--registry-registry), pass [extra arguments](https://github.com/lerna/lerna/#bootstrap) (such as `--no-package-lock`) to bootstrap via CLI or lerna.json, and control the `access` of a scoped package in each package.json's `publishConfig` block (just like any other package). We don't read the root `.npmrc` because we don't control `npm`'s behavior in this regard, not because we hate users.

Hoisting is an installation optimization that takes advantage of the node module resolution algorithm to reduce duplicate work. It is not meant to do anything else.

**Comment by danielo515** [comment]
Hello @evocateur 

I do use the `--registry` flag, but it has nothing to do with installing dependencies from private repositories. I also use publishConfig on each package, but none of those deals with the fact that I need to install deps from a private repository for ALL my packages. You said that you don't control npm behavior, but npm behavior is to use the closest `.npmrc` file, which is not happening in my case.

PD: Thanks for the extra arguments documentation by the way, I'll use them.
