### ISSUE TITLE
lerna run tsc to support dist folder as part node_modules

### ISSUE THREAD

**Issue by gudipudipradeep** [lerna/lerna#3673]
tsconfig.json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "es2015",
    "moduleResolution": "node",
    "rootDirs": ["."],
    "outDir": "node_modules/@fortune-sheet",
    "allowJs": true,
    "sourceMap": true,
    "jsx": "react",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "skipLibCheck": true,
    "noImplicitAny": false,
    "noLib": false,
    "lib": ["es5", "dom"],
    "forceConsistentCasingInFileNames": true,
    "declaration": true,
    "esModuleInterop": true,
    "baseUrl":"./",
    "paths": {
      "@fortune-sheet/core": ["packages/core/src"],
      "@fortune-sheet/react": ["packages/react/src"]
    }
  },
  "include": ["packages/**/src"],
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
    "**/*.test.ts"
  ]
}

above tscconfig.json creating outDir is node_modules/@fortune-sheet but generated format is not supporting.

<img width="689" alt="image" src="https://user-images.githubusercontent.com/8638634/236162506-8590c953-e8cf-4aca-9984-9c2006a0cd03.png">
it is creating src instead and package.json is missing as part of output to support as node_modules.

**Comment by fahslaj** [comment]
@gudipudipradeep from your description, it appears that `lerna run tsc` is running appropriately and that it is `tsc` that is not doing what you would expect. I am closing this issue since it looks to be an issue or misconfiguration of typescript.

If you believe this to be incorrect, then please provide more details into how this issue is related to Lerna.
