### ISSUE TITLE
[Question] lerna publish error

### ISSUE THREAD

**Issue by royJang** [lerna/lerna#368]
when i exec lerna publish
`Error updating version as latest
Error: Command failed: npm dist-tag ls tm-a-header`

what can i do

**Comment by royJang** [comment]
version:independent
node-version:4.4.5
npm-version:3.10.8

**Comment by thejameskyle** [comment]
Can you create a repo that reproduces this error?

**Comment by troianoandres** [comment]
Any news on this? I'm having the same issue as the one described. 

Basically when I try to publish some packages the command `npm dist-tag ls <pkg>` fails because of something unexpected into its JSON file (In my case it says `Unexpected token y in JSON at position 0`). 

For some reason, npm guesses that I'm not logged as the right user.

After all this, even with the error, the package is published as expected.

If you like I can add the error message with stripped information that might be useful for you.

Thanks!

**Versions**
lerna: 2.0.0-beta.30
node: v6.3.1
npm:  v3.10.3

**Comment by busybeaver** [comment]
same issue here:
node: v6.9.4
npm: 3.10.10
lerna: 2.0.0-beta.37

**Comment by doug-wade** [comment]
@busybeaver it seems like you have an invalid package.json -- I can repro this with `npm`:

```
» npm dist-tag ls
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/home/dwade/n/bin/node" "/home/dwade/n/bin/npm" "dist-tag" "ls"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! file /tmp/pretest/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 'y' at 12:3
npm ERR!   y
npm ERR!   ^
npm ERR! File: /tmp/pretest/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/pretest/npm-debug.log
dwade /tmp/pretest » cat package.json                                                                                   1 ↵
{
  "name": "pretest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "pretest": "echo 'pretest'"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  y
}
```

I don't believe it's reasonable to expect `npm dist-tag ls` to work with invalid json, but even if it were, this issue would belong in the [npm repo](github.com/npm/npm).  I'm going to close for now; if you have a repro with a valid package.json that succeeds with `npm`, or if I've misunderstood, we can revisit.
