### ISSUE TITLE
[Feature] Switch to Yarn

### ISSUE THREAD

**Issue by cpojer** [lerna/lerna#371]
https://github.com/yarnpkg/yarn

please! I want to switch to Yarn on Jest :)

**Comment by joshblack** [comment]
Would this require just adding configuration for an `installer` for this command: https://github.com/lerna/lerna/blob/master/src/NpmUtilities.js#L19

Or something a little more verbose?

**Comment by BenGale** [comment]
From a real quick look:

Could be worth having a YarnUtilities and instead of importing the NPM one, import something that knows how to read the config (not read enough of the source yet to know how config is managed) and give back the correct implementation. Shouldn't be too bad as the commands needed map pretty well to each other from the looks of it.

**Comment by hzoo** [comment]
cc @kittens @thejameskyle

**Comment by thejameskyle** [comment]
I'm considering just using yarn instead of npm client since it's compatible and fixes a lot of issues we've had

**Comment by thejameskyle** [comment]
That being blocked on supporting private packages etc

**Comment by laurentdesmet** [comment]
This would close #334, like @thejameskyle [already mentioned](https://github.com/lerna/lerna/issues/334#issuecomment-246478045), if it's really ultrafast according to [its marketing](https://yarnpkg.com/). I didn't test yarn yet, but I'm very excited to try it out 😃 .

**Comment by marvinhagemeister** [comment]
@laurentdesmet Just gave it a go and the hype is real! It's day and night between yarn and npm install times. I'm rooting for them to fix the remaining issues, most notably private and scoped package dependencies. They really did an amazing job!

**Comment by laurentdesmet** [comment]
Just tried it and I was blown away with the performance improvement. An `npm install` in the root of our company's monorepo managed by lerna went from 1m51s to 8s. This is amazing! I can't wait for scoped dependency support, together with support for yarn within lerna. Awesome job and lots of respect for the creators!

**Comment by tomdale** [comment]
I would love to be able to use Yarn in one of my monorepo projects today, because it doesn't have any scoped or private packages. Not sure when the ETA for that landing in Yarn is, but if it's a ways out it would be a bummer to block Lerna support on it. I am losing days of my life to npm at present. 😭

**Comment by tomdale** [comment]
Yarn and Lerna are fantastic by the way. Y'all are killing it.

**Comment by natew** [comment]
We've added it and are using it now in our branch :)

https://github.com/motion/lerna/pull/4

**Comment by iamchenxin** [comment]
Maybe should add an option in lerna.json for choosing npm or yarn?

**Comment by timche** [comment]
@natew Why not open a PR?

**Comment by timche** [comment]
@natew [Why are you using npm again? :S](https://github.com/motion/lerna/commit/b6cca0bcd8c458f222b431b749d57cfc610d5862)

**Comment by psirenny** [comment]
:disappointed: If only yarn supported scoped packages

**Comment by pi0** [comment]
**Good news!** I have made a wrapper package for `npm` which globally converts and wraps all `npm` commands to `yarn`, which fallback comp-ability to features like scoped packages :) 
Please check out [YarNPM](https://github.com/pi0/yarnpm)

**Comment by steelbrain** [comment]
@timche Yarn doesn't support all of npm, we're only using it for npm installations.

There are a few things to consider. First of all is that Yarn needs a package published with the same name as you're trying to link or it would fail. It's being tracked in https://github.com/yarnpkg/yarn/issues/946

Another important thing to keep in mind is that, we have to make Lerna execute the npm commands in sync instead of parallel or it conflicts with itself and some processes of it add packages and extract them, others remove them and it ends up crashing.

**Comment by cpojer** [comment]
@natew can you send a PR for this? :)

**Comment by steelbrain** [comment]
@cpojer No PR would fix this before yarnpkg/yarn#946 is solved :)

**Comment by timche** [comment]
Also bootstrapping doesn't work with concurrent processes: https://github.com/yarnpkg/yarn/issues/683

**Comment by timche** [comment]
> Another important thing to keep in mind is that, we have to make Lerna execute the npm commands in sync instead of parallel or it conflicts with itself and some processes of it add packages and extract them, others remove them and it ends up crashing.

Related issue: https://github.com/yarnpkg/yarn/issues/683

**Comment by ccorcos** [comment]
P.S. it appears Yarn might end up absorbing Lerna: https://github.com/yarnpkg/yarn/issues/946#issuecomment-264597575

**Comment by seansfkelley** [comment]
I wrote a stripped down version of Lerna built upon Yarn, and it was worth every minute. I only ever used bootstrap, run and exec, so this was a pretty easy task: the basic trick is to wrap every Yarn command in a task that mangles the package.json to remove local package names, runs the task, then unmangles it. There are a few subtleties along the way (e.g. make sure you keep any changes that Yarn applies to the package.json), but despite all the hacks it's quite stable. Stable enough that I committed to using it for production builds. 

I would much prefer Lerna-in-Yarn, but this has already improved build stability and fever considerably. The code's not great, but if there's interest I may clean it up to release it as an interim solution.

**Comment by cpojer** [comment]
@seansfkelley we'd love to work with you if you are interested in bringing all this into Yarn in a hack-free way :)

**Comment by seansfkelley** [comment]
@cpojer sounds worthwhile. I'm unclear, from the one brief linked comment, how much of Lerna is expected to make it into Yarn. There are a number of Lerna features I ported that are a must for managing a monorepo, though may drag Yarn away from it's apparent mission as a mostly-just-npm replacement. Can you clarify any further on the current thinking here?

**Comment by cpojer** [comment]
We don't have a concrete plan yet. The team at FB is planning to spend a few great days with their families for Christmas and then come back with a ton of energy in January. We were planning to sketch out what this may look like sometime next month :)

**Comment by seansfkelley** [comment]
Sounds reasonable! I'll try to work on cleaning it up over break and then I can present it here as a citable example.

**Comment by seansfkelley** [comment]
Alright, I finally got around to doing this! You can find it at https://github.com/palantir/yerna. Be warned, the code is pretty sloppy in places.

**Comment by xaka** [comment]
What about instead of doing a complete switch, as it might take more time in order for community to benefit from yarn, we abstract `npm install` part and add an option to `lerna.json` to use either npm or yarn as installation mechanism? I might be wrong, but it seems it's matter of replacing `npm install ...` with `yarn add ...`.

**Comment by seansfkelley** [comment]
The short answer to your question is "not really". The docs include some details on [_why_ I went to the bother of making something from scratch](https://github.com/palantir/yerna#motivation), but to call out the parts immediately relevant here, it's unfortunately [not a simple drop-in](https://github.com/palantir/yerna#how-it-works):

> Lerna was free to make all kinds of symlinks and npm would happily chug along ignoring them. Yarn, in its strictness, will clear out these symlinks _and_ will attempt to download packages that we know to be local-only.

Which leads to gross hacks, and then after a certain point I just decided to double up and use Yerna to implement some [flags I really, really need for my work](https://github.com/palantir/yerna/blob/71f737d163a35819fe8efa6bb77a1cd85b024eaf/bin/yerna#L35...L42) (along with some other miscellaneous features).

I don't plan to change Yerna (or Lerna, or Yarn) significantly in the foreseeable future, mostly because I'm a bit burnt out on this whole thing (and it's no secret that [I have been frustrated with the pace of development on Lerna](https://github.com/lerna/lerna/issues/408)). However, you are more than welcome (encouraged, even!) to rip ideas right from Yerna for Lerna and/or Yarn.

**Comment by aymericbeaumet** [comment]
In the meantime you can use this workaround to install the dependencies with yarn and link them together with [linklocal](https://github.com/timoxley/linklocal):

```bash
$ npm i -D linklocal
```

```json
{
  "scripts": {
    "postinstall": "lerna exec --concurrency=1 -- yarn && lerna exec --concurrency=99 -- linklocal"
  }
}
```

**Comment by julien-f** [comment]
@cpojer Any news on this? :)

**Comment by joshduck** [comment]
@cpojer Any more thought gone into this? We're using Lerna and would like to use Yarn too. Are the approaches likely to be compatible? A big blocker for us would be allowing non NPM packages.

**Comment by thejameskyle** [comment]
We would have to expose a specific API from Yarn for this purpose. That API would have to expose a lot of internal Yarn implementation details. It would probably be a mistake at this point to add.

Instead the plan is to merge Lerna into Yarn as "workspaces". The Yarn team doesn't have time for that right now, but I'm hoping to get a chance to work on it within the next few months.

**Comment by cpojer** [comment]
@joshduck we are hiring at FB London ;)

**Comment by joshduck** [comment]
Awesome to hear @thejameskyle. So it sounds like waiting for a blessed solution is the ideal instead of trying to hack around the issue ourselves? @cpojer Move the team to Brisbane and I'm on board!

**Comment by cpojer** [comment]
@joshduck we are a bit behind. We'll be speccing this out soon but it'll take a while until anything is ready. On Jest, we use lerna + npm and it is working reasonably well. Make sure to hoist your dev dependencies to the top level and use yarn for that :)

**Comment by thejameskyle** [comment]
@cpojer I've already started working on a fully fledged RFC for it. I can share that soon

**Comment by Alxandr** [comment]
@thejameskyle please do link the RFC here when it's complete :)

**Comment by hzoo** [comment]
> Make sure to hoist your dev dependencies to the top level and use yarn for that :)

A good idea 😄, also try out `--hoist` to move up the devDeps (was added in https://github.com/lerna/lerna/releases/tag/v2.0.0-beta.35). Or can do it manually like we have in Babel

**Comment by guigrpa** [comment]
Whether lerna is finally integrated into yarn or vice versa, in the meantime you can try this out: http://github.com/guigrpa/oao. I'd greatly appreciate any feedback!

**Comment by hzoo** [comment]
Curious what we need to do in Lerna that Yerna/oao/other tools are doing to support Yarn. Obviously we are going to be much slower to implement but I'd like to see this happen (since I would want it for Babel)

**Comment by gigabo** [comment]
Opened https://github.com/lerna/lerna/pull/605 for pluggable npm clients.

```sh
lerna bootstrap --npm-client=yarn
```

So much faster! 🚀

**Comment by hzoo** [comment]
In https://github.com/lerna/lerna/releases/tag/v2.0.0-beta.38, stay tuned for updates on Yarn's side in the near future!

**Comment by cpojer** [comment]
@hzoo it doesn't seem like that works well on CI: https://ci.appveyor.com/project/Daniel15/jest/build/2335 and https://circleci.com/gh/facebook/jest/367?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link for https://github.com/facebook/jest/pull/3032

**Comment by Scarysize** [comment]
Nice to see progress on this! I tried this on a lerna repo, sadly the installation just gets stuck on one package. What's a good way to debug this behaviour, I can't share the repository, but would like to help!

**Comment by timoxley** [comment]
@cpojer @hzoo a temporary workaround: `lerna bootstrap --concurrency=1`. It's possible that running multiple instances of yarn blows through the limited memory of the CI container.

**Comment by timoxley** [comment]
@aymericbeaumet note if you're using `linklocal`, you need to specify dependencies as relative paths using `file:`, rather than by version e.g. 

```js
{
  …
  "dependencies": {
    "my-dependency": "file: ../my-dependency"
  }
}
```

This has the added benefit of making all regular `yarn` and `npm` commands work independent of lerna, for `packages/*` which aren't published to npm. Otherwise [yarn will complain](https://github.com/lerna/lerna/issues/501) that it can't find the unpublished package in the registry.

**Comment by silenaker** [comment]
@Scarysize I tried the beta.38. Of course, i also failed on bootstraping but there is no problem now. you may need clean your yarn cache first

**Comment by hzoo** [comment]
Hm ya, I haven't had time to look into it, for some reason failing on node 4 for Babel https://github.com/babel/babel/pull/5396

**Comment by Scarysize** [comment]
I'm on node `7.7.1` if this is relevant.

**Comment by gigabo** [comment]
FYI https://github.com/lerna/lerna/pull/638 addresses a major source of trouble with Yarn in `beta.38`.

**Comment by k3n** [comment]
@timoxley 

Is it `--concurrency=1` or `--concurrency 1` or either?

The [docs|https://github.com/lerna/lerna#--concurrency] demonstrate the latter.

**Comment by timoxley** [comment]
@k3n either.

**Comment by Scarysize** [comment]
@gigabo Nice, seems like the PR is merged now. When can we expect another beta release?

**Comment by billschaller** [comment]
`lerna bootstrap --hoist` is not symlinking binary deps when using yarn for me.

**Comment by billschaller** [comment]
Yeah - for some reason, I run `lerna bootstrap --hoist` with npmClient set to yarn in lerna.json, I run the command once, and it sets up the symlink in the packages/thing/node_modules/.bin directory - if I run it again, it deletes the symlink and doesn't restore it.

**Comment by gigabo** [comment]
@billschaller That should be addressed by #638 when it lands.  It didn't make it into `beta.38`, unfortunately.

**Comment by billschaller** [comment]
@gigabo oh, woot, thanks :)

**Comment by marionebl** [comment]
@gigabo @evocateur lerna supports yarn so this can be closed, right?

**Comment by cpojer** [comment]
Yup, lerna has Yarn workspaces support and we use it for Jest and other tools. It's super fast and awesome.
