### ISSUE TITLE
Question: What's the NPM Workspaces equivalent to "nohoist" ?

### ISSUE THREAD

**Issue by dep** [lerna/lerna#3723]
I have a rather large, complex monorepository that was using `lerna bootstrap` extensively for dependency management. I am open to switching to `npm` workspaces, but one thing we leaned on quite a lot for application-level needs was setting `nohoist` on a number of specific dependencies within the codebase.

What is the npm workspace equivalent to this?  Or is npm intelligent enough to not need this concept? Thanks in advance.

**Comment by dep** [comment]
Also follow-up question, how do I build a single app only? What's the equivalent of this?

```
npx lerna bootstrap --scope=<some-scope> --include-dependencies --concurrency 2
```

**Comment by JamesHenry** [comment]
Hi @dep, for custom hoisting requirements I highly recommend modern yarn (v3+). It allows you a lot of control over what gets hoisted and you can even do things like disable hoisting on a package by package. I recommend using the node modules linker, rather than PnP mode in modern yarn, so that it is much closer to your current setup.

I have yet to run into a hoisting setup that couldn't be made to work with modern yarn, but if you run into specific issues please feel free to open an issue comparing what you used to do with `lerna boostrap` and what does not seem to be working with yarn.

It's possible that pnpm is also strong in this regard, but I have that first hand experience with yarn.

Here is an example that had custom hoisting requirements that I helped out on a while ago, including a video walkthrough: https://github.com/google/blockly-samples/pull/1597

Over the coming days I will create a specific helper video on the topic of hoisting for the website and also post that to this issue once it is ready.

Hope that helps!

**Comment by dep** [comment]
Thanks @JamesHenry !
