### ISSUE TITLE
Vulnerable dependencies ( indirect security issues ?? )

### ISSUE THREAD

**Issue by daudmalik06** [lerna/lerna#3772]
Hello maintainers,

I wanted to bring to your attention that after installing the package, I ran a vulnerability scan with vulert abom on the lock file and discovered that there are 4 vulnerable dependencies present with High risk. As these vulnerabilities can potentially impact the security of the entire project, I am unsure whether to report this under responsible disclosure.

For your reference, here is a link to the report of the yarn.lock file I scanned: https://vulert.com/vuln-scan/list/0e666ed8-1cf8-48de-9901-e4d4281ff5a3

I recommend that we take immediate action to address these vulnerabilities and ensure the security of the project. Please let me know if you require any further information.

p.s. this is the lock file i scanned: https://github.com/lerna/lerna/blob/main/package-lock.json

Thank you.

**Comment by JamesHenry** [comment]
Lerna is a development time only tool. It is never run as a server which takes user input. These "exploits" are absolutely not applicable and common sense needs to be applied when reviewing these.

I can see you are the creator of the tool you are linking to. You may want to differentiate yourself from your competition by adding a layer of nuance in your reporting which takes what I've just said into account, because the biggest issue with these audit reports is noise like this.
