### ISSUE TITLE
Debugging package B (source code) in referenced package A

### ISSUE THREAD

**Issue by Mahdibenamor** [lerna/lerna#3862]
Is there any way to debug on vs the source code of referenced package B from package A

**Comment by fahslaj** [comment]
Hi @Mahdibenamor , if you are using npm workspaces, then the packages should be linked within the workspace. You can set debug points within package B and they should be reached when running package A. 

If you have any processes that process or bundle the code, then you may need to make sure to set those break points on the bundled assets.

**Comment by Mahdibenamor** [comment]
Yeah, but the problem, it hit the compiled code, from the node-modules, not actually the ts code.

**Comment by fahslaj** [comment]
Can you confirm that the version in the package.json file of package B is compatible with the dependency requirement of package A? If the version of package B in the repo does not satisfy the requirement of package A, then npm will download package B from the registry to satisfy the dependency instead of linking locally.

**Comment by Mahdibenamor** [comment]
I close, this bug, to miss configuration in package.json file. 
Don't change a lot there !!😁

**Comment by Mahdibenamor** [comment]
I close, this bug, to miss configuration in package.json file.
Don't change a lot there !!😁
