### ISSUE TITLE
Our project fails every `npx lerna publish from-package --yes` while trying to publish undefined

### ISSUE THREAD

**Issue by heath-freenome** [lerna/lerna#3883]
## Current Behavior

react-jsonschema-form has been using lerna for years. A long while ago our `npx lerna publish from-package --yes` started failing and we've tried a bunch of things to fix it. Every time we release a new version, the github job successfully publishes all of our packages and then fails with the same message at the end, thereby causing the action to fail. That message is:

```
lerna info lifecycle react-jsonschema-form@undefined~publish: react-jsonschema-form@undefined

> react-jsonschema-form@undefined publish /home/runner/work/react-jsonschema-form/react-jsonschema-form
> lerna publish

lerna ERR! lifecycle "publish" errored in "react-jsonschema-form", exiting 1
```

Here's a link to the latest failure
https://github.com/rjsf-team/react-jsonschema-form/actions/runs/6697926916/job/18198848974

## Expected Behavior

The publish works successfully and allows our github action to complete successfully

## Steps to Reproduce

Take a look at our [repo](https://github.com/rjsf-team/react-jsonschema-form) and see if you can't see something off in our configs, our github actions, or our `package.json` files.

**Comment by fahslaj** [comment]
Hi @heath-freenome , it looks like you have a script named "publish" at the root of the code repository. "publish" is a reserved word for a lifecycle script for the publish action. This can be seen in the [lerna publish readme](https://github.com/lerna/lerna/tree/main/libs/commands/publish#lifecycle-scripts) - step 9 is to "run the publish lifecycle in root". This means that Lerna is trying to run that script during the process of publishing, which I don't think is the intention, since it looks like that script is manually used to run `lerna publish` in the first place.

The fix to this would be to rename your top level npm script to something that is not a lifecycle script, such as "release" or "publish-packages". This will prevent Lerna from trying to automatically run it when publishing.

**Comment by heath-freenome** [comment]
@fahslaj Thanks for the reply. As far as I can tell, we don't even use the script. I'll try renaming it first

**Comment by fahslaj** [comment]
Closing this issue as it looks like the 5.13.4 release on your repo succeeded after the change. Feel free to follow up if you are still experiencing issues.

**Comment by heath-freenome** [comment]
Yup, it worked! Thanks
