### ISSUE TITLE
High vulnerability because of "kind-of" package

### ISSUE THREAD

**Issue by elangoRamar** [lerna/lerna#3931]
Current Behavior
Hi I am using the latest version of lerna (8.0.2). But when i try to audit the project, i am getting high vulnerability because of package `kind-of` which is a dependency of lerna.

<img width="739" alt="Screenshot 2024-01-09 at 6 11 45 PM" src="https://github.com/lerna/lerna/assets/130338823/5d1b3327-e8dc-4c5a-a863-a0f181ae635b">

How to fix it?

## Steps to Reproduce

Install the latest version of lerna and do yarn audit.

**Comment by ghiscoding** [comment]
This notification and issue is invalid, the last version of [clone-deep](https://www.npmjs.com/package/clone-deep) that Lerna uses is 5 years old that dependency is itself using `"kind-of": "^6.0.2"` and because of the caret `^` it should always get latest `minor` version which has the fix (6.0.3), if you delete your yarn lock file (or run `npm audit fix`) it will fix it for you. 

Since this is a transitive dependency, Lerna has nothing to do and no way of fixing it by itself and even if Lerna lock file is updated, the user (you) will still have to fix it on his side (again by either deleting yarn lock file and redo `yarn install` or by running `npm audit fix`)... in summary that is not a Lerna issue

**Comment by elangoRamar** [comment]
Thanks @ghiscoding . Deleting `yarn.lock` and reinstalling fixed the issue.
