### ISSUE TITLE
lerna ERR! E409 Failed to save packument. A common cause is if you try to publish a new package before the previous package has been fully processed.

### ISSUE THREAD

**Issue by victor-onwukwe** [lerna/lerna#4016]
## Current Behavior

After a failed first attempt at lerna publish (70% of packages got published before failure), I get this message:

```lerna ERR! E409 Failed to save packument. A common cause is if you try to publish a new package before the previous package has been fully processed.```

This is my release command:

```"release": "lerna clean --yes && lerna bootstrap && lerna run --parallel build && lerna publish from-package"```

## Expected Behavior

I expect it to publish all packages successfully
It has been working just fine before now

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "packages": [
    "packages/*",
    "docs"
  ],
  "version": "independent",
  "stream": true,
  "hoist": true,
  "command": {
    "bootstrap": {
      "npmClientArgs": ["--no-package-lock"]
    },
    "publish": {
      "ignoreChanges": ["**/stories/**", "**/tests/**"]
    }
  }
}

```

</p></details>

### Environment

  System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 9.4.2 - ~/.nvm/versions/node/v19.6.0/bin/npm
  Utilities:
    Git: 2.39.2 - /usr/bin/git
  npmPackages:
    lerna: ^6.5.1 => 6.6.2

**Comment by Jolg42** [comment]
Like I mentioned in https://stackoverflow.com/questions/78557158/lerna-err-e409-failed-to-save-packument

I opened a ticket for Prisma packages and mentioned the following:

I checked https://status.npmjs.org/ and there is no known incident with the npm registry. But this does not look correct.

Our publishing pipeline fails continuously since `Wed, 29 May 2024 15:57:32 GMT`, our pipeline is visible at https://github.com/prisma/prisma/actions/workflows/release-ci.yml There you can see 9 different versions that failed to be published. Out of those some were retried a few times and also failed.

- First occurrence: `Wed, 29 May 2024 15:57:32 GMT npm error 409 Conflict - PUT https://registry.npmjs.org/@prisma%2fdebug - Failed to save packument. A common cause is if you try to publish a new package before the previous package has been fully processed.`
https://github.com/prisma/prisma/actions/runs/9289279373/job/25562781978#step:5:474

- Last publish as of today: `Fri, 31 May 2024 09:26:45 GMT npm error 409 Conflict - PUT https://registry.npmjs.org/prisma - Failed to save packument. A common cause is if you try to publish a new package before the previous package has been fully processed.`
https://github.com/prisma/prisma/actions/runs/9315846538/job/25642855801#step:5:2513

**Comment by Jolg42** [comment]
I'll keep you updated if I get any answer, if you could do the same that would be great! I'm very curious to see what happens, hopefully it's a simple fix on their side 🤞🏼

**Comment by Jolg42** [comment]
We have 2 publish that succeeded recently, and no more failure, so it might be resolved for you too I guess.

**Comment by victor-onwukwe** [comment]
> We have 2 publish that succeeded recently, and no more failure, so it might be resolved for you too I guess.

Hello @Jolg42 thank you! I've tried it out now and it's working fine. All packages have been successfully published.

**Comment by andrew-s-faulkner** [comment]
I'm now getting this error. The above thread is literally the only record I can find of this issue happening to anyone. It sounds like this is a sporadic error caused by an issue relating to the npm servers?
