### ISSUE TITLE
Lerna should respect no-lockfile setting

### ISSUE THREAD

**Issue by justnewbee** [lerna/lerna#4066]
## Current Behavior

I tried to use lerna with pnpm. And I am not a fan of lock files, so I intentionally disabled it, and added it in git ignore.

.npmrc

```ini
lockfile=false
```

```json
{
  ...
  "npmClient": "pnpm",
  "npmClientArgs": ["--no-lockfile"]
}
```

When running `lerna publish`, lerna gives me error

```txt
lerna ERR! Error: Command failed with exit code 1: pnpm install --lockfile-only --ignore-scripts --no-lockfile
```

I removed those hard coded "--lockfile-only" in lerna package, and ran into another error:

```txt
lerna ERR! Error: Command failed with exit code 128: git add -- packages-dev/markdownlint-config/package.json packages-dev/npm-package-json-lint-config/package.json packages-dev/ts-config/package.json packages-dev/stylelint-config/package.json pnpm-lock.yaml
```

## Expected Behavior

Lerna will respect no lockfile setting, and will not use `lockfile-only`, nor do `git add pnpm-lock.yaml`.

## Steps to Reproduce

Just pnpm workspace + lerna, and run `lerna publish`.

### Failure Logs / Configuration

<details><summary>lerna.json</summary><p>

```json
{
  "$schema": "node_modules/lerna/schemas/lerna-schema.json",
  "version": "independent",
  "npmClient": "pnpm",
  "npmClientArgs": ["--no-lockfile"],
  "allowBranch": [
    "lerna/pub"
  ]
}
```

</p></details>

<details><summary>lerna-debug.log</summary><p>

```txt
44 error Error: Command failed with exit code 1: pnpm install --lockfile-only --ignore-scripts --no-lockfile
44 error Scope: all 5 workspace projects
44 error  ERR_PNPM_CONFIG_CONFLICT_LOCKFILE_ONLY_WITH_NO_LOCKFILE  Cannot generate a pnpm-lock.yaml because lockfile is set to false
44 error     at makeError (/Users/newbee/zombie/kcuf/node_modules/.pnpm/execa@5.0.0/node_modules/execa/lib/error.js:59:11)
44 error     at handlePromise (/Users/newbee/zombie/kcuf/node_modules/.pnpm/execa@5.0.0/node_modules/execa/index.js:114:26)
44 error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
44 error     at async VersionCommand.updatePackageVersions (/Users/newbee/zombie/kcuf/node_modules/.pnpm/lerna@8.1.8_encoding@0.1.13/node_modules/lerna/dist/index.js:9857:11)
44 error     at async Promise.all (index 0)
```

</p></details>

### Environment

lerna notice cli v8.1.8
lerna info versioning independent

 Environment info:

  System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 22.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - /opt/homebrew/bin/npm
  Utilities:
    Git: 2.45.2 - /opt/homebrew/bin/git
  npmPackages:
    lerna: ^8.1.8 => 8.1.8

**Comment by JamesHenry** [comment]
@justnewbee I am sorry for the delay on this one. Everyone is entitled to their opinion but there is an overwhelming amount of benefits to using lock files vs not.

Lock files serve several critical functions in modern JavaScript development:

- They ensure reproducible builds across all environments - development, CI, and production. Without them, two developers running npm install on the same package.json at different times could end up with different dependency versions, even within semver ranges.

- They provide an important security benefit by preventing supply chain attacks through dependency updates that haven't been explicitly reviewed.

- They significantly speed up installation times since the package manager doesn't need to recalculate the dependency tree on every install.

- They maintain consistent behavior across team environments, eliminating the "works on my machine" class of problems that can arise from subtle version differences.

Given these benefits, we consider lock files to be an essential part of our project's infrastructure and best practices. While we appreciate the feedback, we will continue to maintain and require the use of lock files in this project and projects which use it.

Please let me know if you have any other questions or concerns!
