### ISSUE TITLE
[bootstrap] Support for "prepare" npm event-script 

### ISSUE THREAD

**Issue by wzrdzl** [lerna/lerna#421]
As of npm@4 `prepublish` is split  into `prepare` - that behaves exactly the same as `prepublish` did before - and `prepublishOnly` that is only executed before the actual publish. IMO if `prepublishOnly` script is present in a  bootstrapped package it should be run instead of `prepublish` since it makes more sense.
 
What is your opinion on this?
If this makes sense I can implement it and open a PR

**Comment by gigabo** [comment]
Oh boy, I hadn't heard about that yet.  Thanks for bringing it up @wizardzloy.

Do you have a link to some documentation about this change?

**Comment by wizardzloy** [comment]
The description of it is here https://github.com/npm/npm/releases/tag/v4.0.0 under the "NEW prepare SCRIPT. prepublish DEPRECATED (BREAKING)" section. Unfortunately, I didn't find any section in the documentation about that. 

After a closer look, I figured out that `prepublishOnly` wouldn't serve our needs because of its behavior that doesn't make any sense to me but looks like is intended. The thing is: the files generated in the `prepublishOnly` script are not included in the tarball during publishing (https://github.com/npm/npm/issues/15147) which kills the whole idea of using `prepublishOnly` as a replacement to `prepublish`.

Although `prepublish` is deprecated now and is renamed to `prepare`, so maybe we should add support for `prepare` scripts nevertheless.

**Comment by gigabo** [comment]
Yeah, looks like we might have some work to do before npm 5 lands.

Thanks for the research @wizardzloy.  You interested in taking this on?

**Comment by evocateur** [comment]
One thing I learned about `npm run` recently that might help this: calling `npm run --json` will give you a list of the scripts that exist for a given package. In fact, I'm using it right now in a CI script (with the `--parseable` flag instead, because bash) to run certain scripts only if they've been defined (e.g, `npm run build` will fail if `"scripts": { "build": "..." }` doesn't exist in package.json).

Combined with a little filtering on `npm --version`, it would seem feasible to determine correctly what script one should be running during "pre" and "post" phases.

**Comment by wizardzloy** [comment]
@gigabo sure I can pick it up, but let's agree on the logic. Should it be:
1. prefer `prepare`, if not present then try `prepublish`
or 
2. check the npm version, if <4 go for `prepublish` (don't try to `prepare`), otherwise do 1.

What sounds more logical to you?

**Comment by gigabo** [comment]
Seems like Lerna's behavior should be consistent with the active `npm`.

So I think we would need a hybrid of those two options?  If I'm understanding the release notes right in npm 4 `prepublish` is _deprecated_, but still supported.

> we've added a `prepare` command that runs in the exact same cases where `prepublish` ran, and we've begun a deprecation cycle for `prepublish` itself only when run by `npm install`, which will now include a warning any time you use it that way.

So for npm 4 the logic should be equivalent to your option 1, but for npm < 4 we should just use `prepublish` without checking for `prepare` (since npm 3 doesn't even know about `prepare`).  And I guess if `prepublish` is totally de-supported in npm 5 we should eliminate the fallback there entirely. 😬 

We might also want to include a warning if we use `prepublish` on npm 4, similar to what npm itself does.

Thanks for tackling ths @wizardzloy!

**Comment by wizardzloy** [comment]
@gigabo that sounds reasonable

**Comment by wizardzloy** [comment]
@gigabo 
> And I guess if prepublish is totally de-supported in npm 5 we should eliminate the fallback there entirely. 

Looks like they want to bring `prepublish` back in npm 5 and replace `prepublishOnly` with it, so I don't think we need to eliminate the fallback for npm@5

**Comment by cmroanirgo** [comment]
Adding 2c. I think @evocateur's is the way to go. 
That is, in this interim period then *both* `prepublish/prepare` as well as `prepublishOnly/prepublish` needs to be handled correctly according to the current npm installation, otherwise I envisage a large mess, and lots of strange errors (and the resulting support questions).

I for one ended up here because I'd used `prepublishOnly` in my packages (only to find out that lerna doesn't really support it properly yet!). Hence, I've changed my scripts to be `prepublish`, but I _don't_ want `prepare` equivalency.

**Comment by FezVrasta** [comment]
Are there updates on this? I'm using `prepare` to compile all my packages' sources but Lerna doesn't still seem to run the `prepare` script on `bootstrap`.

**Comment by evocateur** [comment]
Once I'm back from holiday, I plan on making a compatibility pass to support this and other npm 4+ capabilities.
