### ISSUE TITLE
Packages specified as file relative are not symlinked

### ISSUE THREAD

**Issue by dmfenton** [lerna/lerna#424]
if package `b` is linked to package `a` as `file:../a` it will not be symlinked to package `b`. To me, this is a bug.

**Comment by gigabo** [comment]
Interesting... I think I agree that it makes sense to link relative deps within the repo.  Lerna has generally followed a design guideline that packages in a Lerna repo should still work if they're taken _out_ of the Lerna repo.  Relative deps break from that and tie your project to the layout of your repo.  But I don't see any reason for Lerna to _prohibit_ that.  Maybe documentation could just include a word of caution.

I would call this an enhancement rather than a bug, since it hasn't ever been supported (yet) as far as I can tell.

@dmfenton Are you interested in taking this on?

**Comment by dmfenton** [comment]
Hi @gigabo I've already PR'd it here: https://github.com/lerna/lerna/pull/425
