### ISSUE TITLE
feature request: watching

### ISSUE THREAD

**Issue by jeffwhelpley** [lerna/lerna#449]
There are various watching tools like the one for TypeScript (i.e. `tsc -w`). This doesn't seem to work with `lerna run`. It would be awesome if you could essentially do `tsc -w` (or any other similar watching tool) on each package at the same time.

**Comment by gigabo** [comment]
I think https://github.com/lerna/lerna/issues/446 is the main thing standing in the way of this.

**Comment by trotzig** [comment]
I'm not sure #446 solved it completely. I have a repo with a few packages, all with a `build:watch` script. Most packages depend on the `core` package. When I run `lerna run --stream build:watch` I see output for the core package, but none of the others. This is likely because they are waiting for the `core` package to finish, which it never will in watch mode. 

EDIT: I just found the `--no-sort` option, which resolves the dependency lock that I ran into. Posting this here anyway in case others find it useful.

**Comment by evocateur** [comment]
@trotzig This could definitely use some README documentation, agreed.

**Comment by scottmas** [comment]
--no-sort doesn't seem to fix every case. For instance I have 5 packages in my repo that implement a `dev` script. Only 2 of them run with `--stream` only but only 4 of the 5 run even with `--stream --no-sort`. Not sure what else I should do. The command in the offending package executes just fine when I run it manually.

**Comment by gigabo** [comment]
@scottmas Lerna has a default concurrency of 4.  You can increase that with the `--concurrency` option.

**Comment by scottmas** [comment]
Okay that makes sense. It seems a bit sub-optimal that to get sane "watch" behavior in any fair sized mono repo we need to implement three flags: `--stream --no-sort --concurrency 9999`. Having to specify concurrency limits doesn't make sense in a `--watch` context since the concurrency will always have to be equal or greater to the number of scripts. 

Seems to me like it would be a good idea to roll all this behavior into a `--watch` flag or something of the like.

**Comment by scottmas** [comment]
Or make `--stream` set concurrency to number of threads and set `--no-sort`? Also an option.

**Comment by evocateur** [comment]
I like the idea of a synthetic `--watch` flag more than overloading `--stream`.

**Comment by reggi** [comment]
What's the current status with this issue? I want to watch multiple lerna packages at once to build each individually with each packages `npm run build:watch` script.

**Comment by evocateur** [comment]
`lerna run --parallel build:watch`

**Comment by Dombo** [comment]
I know this is a stale issue but I've been working with a team on some monorepo tooling and put together a quick proof of concept to demonstrate watching for changes across the relevant Leena dependencies & triggering a rebuild of only the affected artefacts.

https://github.com/Dombo/node-lerna-monorepo

Hopefully I save someone some time & thanks to the lerna maintainers for their awesome work in building such a tool.
