### ISSUE TITLE
Make the git remote configurable

### ISSUE THREAD

**Issue by thomasfr** [lerna/lerna#464]
At the moment when running lerna publish, lerna will do a `git push origin`. It would be nice if one could change / configure the git remote where to push.

The reason for this is our development workflow which is quote common i think. Every developer has a fork of the "origin" repo, a  local clone of this fork. This local clone is then the "origin" and in addition a "upstream" remote to the original/source repo.
The person who actually executes `lerna publish` usually also has this setup git setup and so lerna publish would push to the personal fork instead of the "upstream" repo.

**Comment by bryanspears** [comment]
I just ran into this since I have some fork PRs outstanding and realized the publish commits/tags weren't in the "upstream" repo (rather, they were in my "origin" fork).

Like @thomasfr suggested, being able to configure an "upstream repo" would be fantastic. Then the maintainers of a module don't need a second repo that points "origin" to the non-fork version of the modules repo.

**Comment by gigabo** [comment]
Yes, this would be awesome!  It's been [suggested before](https://github.com/lerna/lerna/issues/142), so let's merge this into https://github.com/lerna/lerna/issues/142.

Either of you interested in taking it on? 😁
