### ISSUE TITLE
Is lerna bootstrap supposed to install common dev dependencies into each project?

### ISSUE THREAD

**Issue by ryancole** [lerna/lerna#470]
It's my understanding that `lerna bootstrap` will install the dev dependencies defined in the outer most `package.json` into each child project. It's my understanding that this would be done via sym links to an outer `node_modules`.

I'm on Windows 10 and this does not appear to be happening with I run `lerna bootstrap`. Each project's own dependencies get installed but none of the dependencies from the parent `package.json` are installed.

Am I understanding this incorrectly? Thanks!

**Comment by cchamberlain** [comment]
I don't think this is the case. My understanding is this:

You may install common `devDependencies` to the lerna repo root but **not** CLI dependencies. This means that if one of your packages runs a babel command via its npm scripts, you must have `babel-cli` defined as a dev dependency of that project. The only reason that installing common `devDependencies` to the repo root works at all is because of node's built-in resolution of `node_modules` when being required from node code (it walks up the file system until it finds a `node_modules` directory with the package in it - in this case that could be the repo root).

The CLI references called from npm scripts don't resolve the same way, rather they will be able to hit anything in the current projects `node_modules/.bin` OR the global npm bin.

Would love to be corrected if I have anything off here.

**Comment by cif** [comment]
THANK YOU @cchamberlain. The fact that you have to install common devDependencies at the project root and not via `lerna boostrap` should be in the docs / README! 

I realize that this is a feature of node and not lerna but I've been using node since day one and walking up to resolve deps is news to me!

**Comment by hzoo** [comment]
Bootstrap just links the internal dependencies together. For example with babel-x packages a lot of them rely on own other but we want to be up to date when developing so it's linked together. All the other packages are npm installed.

I think our readme explains it well? https://github.com/lerna/lerna#bootstrap - tried to be pretty verbose.

You don't have to install common devDependencies in the root - it just makes sense to do so because it will work anyways due to the resolution. and we just added a --hoist option to do it for you https://github.com/lerna/lerna/releases/tag/v2.0.0-beta.35

If something is confusing in the readme feel free to note in this issue or make a pr

**Comment by cif** [comment]
Understood on how the bootstrap command works, just wasn't clear *how* common devDependencies https://github.com/lerna/lerna/blob/master/README.md#common-devdependencies were actually being resolved.  Turns out this is simply a node feature I wasn't aware of. My comment is that a short note explaining this in that particular section would be helpful.

**Comment by gpltaylor** [comment]
Where the hell did that little feature come from! I know this is a node thing, but I have been scratching my head wondering how to make sure all the packages are using the same version! I have been looking at webpack stats for years to work this out.

Node keeps looking up the tree for a node_modules, this is clever and a little scary.
Today is a school day 😄
