### ISSUE TITLE
Skip a package bump on lerna publish

### ISSUE THREAD

**Issue by danielo515** [lerna/lerna#472]
Hello,

Thank you for lerna, great tool.
I was guessing if there is any way of skipping one package version bump when you run `lerna publish`. We do work on a feature basis, and usually changes are made to just a couple of packages, so I would like to be able to only bump those. Note that I there will be situations where I may want to just bump some package versions without publishing.

So, if I have
 - Pkg A (changed)
 - Pkg B
 - Pkg C (changed)

I want to be able to bump version of A and C and just skip B. Could this be done in the interactive cli?

**Comment by garthk** [comment]
Have you tried `lerna publish --only-explicit-updates`?

**Comment by kospiotr** [comment]
@garthk this is no more a workaround for other than Babel projects:

`lerna publish --only-explicit-updates --force-publish=* --yes`

got:

`--only-explicit-updates has been removed. This flag was only ever added for Babel and we never should have exposed it to everyone.`

**Comment by danielo515** [comment]
Is good to see how features are removed without providing a valid substitution

**Comment by AnaRobynn** [comment]
I'm wondering if lerna is a good use-case now that I read this issue:
Imagine I have an b2b product, which consists of indepedent React apps: Login (A), B2B (B) and account management (C).
Let also say I have services module (D) and generic component library (E).

I understand that changing something on D or E, 100% has impact on A, B and C and I agree they should be version bumped. 
But let's say I added a bugfix for A and want to release that. I want to version bump A from x.x.0 to x.x.1, without touching the other modules, because it has no impact on them, since B, C, D and E don't depend on changes from A.

The main reason for switching to a monorepo is code-sharing of D and E with the stand-alone apps A, B and C. Do you think lerna is still a good fit for that?

**Comment by danielo515** [comment]
I think it is. The version bumping only happens when packages has dependants, and not the other way around

**Comment by AnaRobynn** [comment]
Hmmm, I feel I'm missing a key piece in order to understand this behaviour completely. Can you check out the last comment I made here? https://github.com/lerna/lerna/issues/1332#issuecomment-376089905

**Comment by mrkstwrt** [comment]
I'm having a similar issue. I've read in other issues that only packages with dependents that updated will updated, however I have a package in my monorepo with no dependents or dependencies and it still gets a minor bump every time any other package is updated.

**Comment by evocateur** [comment]
@mrkstwrt A minimal repro in a separate issue will help us figure that out, thanks.

**Comment by kirill-konshin** [comment]
In our repo we have actual packages and demo apps, we don't care about versions of demo apps, more over, they are private packages, so version there could always be 0.0.0 and nobody will ever care.

Also, in our workflow, we bump version numbers manually (or by calling `lerna version --no-git-tag-version --no-push`) and then when I run `lerna publish` I expect it to just use existing versions and not do any bumping (bc it runs on CI as well, w/o extra git tags).

**Comment by evocateur** [comment]
I'm going to close this because the thread has metamorphosed into a completely off-topic flytrap for grousing about #707.

To answer the _original_ question, if you packages A, B, and C have _no_ dependency relationship, publishing with changes present in only A & C will indeed ignore B, as has always been the case with lerna. However, if B has a dependency on A _or_ C, it will be bumped, as explained many, many, _many_ times across various issues.
