### ISSUE TITLE
[Docs] transpiled packages

### ISSUE THREAD

**Issue by rgbkrk** [lerna/lerna#487]
Are there repositories or recommendations for making lerna monorepos that have packages requiring transpiling?

Particular motivations:

* exporting React components as modules
* flow types across packages

**Comment by slorber** [comment]
Hi @rgbkrk I'm looking for the same but did not found yet anything

Check this issue as well:
https://github.com/zeit/next.js/issues/707


I think it would be great to have a Lerna boilerplate with some idiomatic setting. Sure we can take a look at projects like babel as inspiration but they are pretty complex projects with specific requirements, while most of us just want to develop a webapp :)

**Comment by ravicious** [comment]
I did [what was suggested in one of the issues @slorber linked to](https://github.com/zeit/next.js/issues/706#issuecomment-271395363): my shared packages are scoped under a common name. So I have a package `bar` that's in `packages/bar`, but its `package.json` has `"name": "@foo/bar"`.

At work, we use webpack and babel for transpiling, so to make it work I had to do the following:

1. [Set `resolve.symlinks` to `false`](https://github.com/webpack/webpack/issues/1866#issuecomment-284571531).
   * This is needed for the next step.
2. Add `/@foo/` regex to the `include` array of the rule that uses babel-loader.
   * Since we turned off symlinks resolving in the previous point, other packages from the monorepo are going to resolve to `node_modules/@foo/<package-name>`, not `../<package-name>`.
   * This was suggested in [next.js issue](https://github.com/zeit/next.js/issues/706#issuecomment-271395363), so I just went to see how they implemented it and did something similar.

So now exported React components/Flow types can be transpiled by babel!

One more thing I did was to add `flow-bin` to `devDependencies` of the monorepo's package.json, but idk if it's necessary.

**Comment by LukasBombach** [comment]
Dude @ravicious that worked! Thank you! For others following this, I had to not do the step with `path.resolve(__dirname, 'node_modules')`, I simply had to keep the normal `node_modules` string (in a `create-react-app`-app)

**Comment by LukasBombach** [comment]
Ok, it does not _quite_ work. I have to restart my webpack dev server any time I make changes to my imported packages.

**Comment by ravicious** [comment]
Yes, that was my problem as well. That happened after upgrading yarn to 1.0 I think. Unfortunately, I stopped working on the project that was using this stack, so I don’t have a solution for this issue.

**Comment by LukasBombach** [comment]
I see, thank you

**Comment by sibelius** [comment]
@ravicious do you have a repo example of this structure?

**Comment by ravicious** [comment]
@sibelius Unfortunately not, I don't own rights to that project.

**Comment by rgbkrk** [comment]
https://github.com/nteract/nteract uses both lerna and yarn workspaces, feel free to check it out. We have a common webpack config in `packages/webpack-configurator`, a `flowconfig` that resolves the right packages, and a `jest` config in our `package.json` that says how to map modules.

**Comment by sibelius** [comment]
for jest config check this https://github.com/entria/entria-fullstack/pull/13

you need to use require.resolve, instead of <rootDir> node_modules because you can't know whether workspace will hoist or not
