### ISSUE TITLE
Question: Why doesn't this lerna exec command work properly?

### ISSUE THREAD

**Issue by reggi** [lerna/lerna#500]
I have this `lerna exec` command that doesn't work as expected.

```
lerna exec -- PARENT=`pwd | grep -o '[^/]*$'` && echo $PARENT
```

Is it something about assigning vars?

```
lerna exec -- PARENT=`node -e 'console.log(path.basename(process.cwd()))'` && echo $PARENT
```

Logs the name of the lerna package, not the sub packages. Thoughts on why this happens?

**Comment by reggi** [comment]
This works. Just still curious why the above does not. Assuming it a unix thing tho.

```
lerna exec -- node -e 'console.log(path.basename(process.cwd()))'
```

**Comment by xaka** [comment]
That is because command substitution (whatever is between backticks) happens in current shell session before entire command gets executed. Same is for variable expansion. Try this (though node.js one-liner looks better):

```bash
lerna exec -- bash -c 'basename $PWD'
```

```bash
lerna exec -- node -e 'console.log(path.basename(process.cwd()))'
```

It's important to use single quotes so variable expansion doesn't happen in current shell session as well. Another thing to keep in mind is that `lerna exec` doesn't exec whatever you provide in shell and rather let you control, which is why `bash -c` is needed in first example.

**Comment by reggi** [comment]
Yep I think this makes sense:

lerna exec -- "PARENT=`pwd | grep -o '[^/]*$'` && echo $PARENT"

**Comment by doug-wade** [comment]
yo @reggi I noticed you cleaned up a buncha issues -- thanks!
