### ISSUE TITLE
Lerna bootstrap doesn't tolerate semver ranges?

### ISSUE THREAD

**Issue by emirotin** [lerna/lerna#509]
I have package A depend on package B.
Package B most recent version is 0.0.4. All 4 of its version are published to npm, but the local copy has some unpublished changes.
Package A depended on `^0.0.3` which should match `0.0.4` as well.
Yet `lerna bootstrap` installs the npm version of package B instead of symlinking the local copy.
Once I've updated package A dependency to read `^0.0.4` it worked as expected.

**Comment by dylang** [comment]
Hi @emirotin  -

When using semver `major.minor.patch`, if `major` is `0` then any version change can be a breaking change, so `^` won't upgrade from `0.0.3` to `0.0.4`.

https://docs.npmjs.com/misc/semver

Can you reproduce this problem with something like `^1.0.3` to see if it uses `1.0.3` from the registry instead of `1.0.4` from the local copy?

I think I'm seeing this problem as well, so knowing I'm not alone will be helpful.

**Comment by emirotin** [comment]
Hmm, I thought with major version 0 patch changes are considered compatible
when the minor version is unchanged?

Will try with the non-zero majors
