### ISSUE TITLE
lerna assumes it manages git root

### ISSUE THREAD

**Issue by joscha** [lerna/lerna#555]
When using lerna within a folder of a repository, e.g.
```
/ <-- here is the git root
/maven-project-a/ <-- calling `lerna init` here, this folder also has a `package.json`
```

it assumes that the `lerna.json` and `package.json` file will live in the root folder, e.g. creating a structure like this:
```
/lerna.json
/package.json (empty with only the lerna package)
/project-a/ (package.json here is unaltered)
```
if I move `lerna.json` into the `project-a` folder and add lerna to the dependencies of that `package.json` I get
```
lerna bootstrap
Lerna v2.0.0-beta.34
`package.json` does not exist, have you run `lerna init`?
```
when running `lerna bootstrap` from within `project-a`.

Would you accept a PR that teaches lerna to stop searching for a lerna config in the git root if it is invoked from a subdirectory which has a valid `package.json` (e.g. `"dependencies": {    "lerna": "2.0.0-beta.34" }`) and a valid `lerna.json`?

**Comment by doug-wade** [comment]
You can use the [`packages` option in lerna.json](https://github.com/lerna/lerna#lernajson) to configure `maven-project-a/packages/` to be where your lerna modules are located, which should allow you to structure your project however is most convenient for maven.  Does that cover your use case, or is there something more I'm missing?

**Comment by joscha** [comment]
Thanks for the answer @doug-wade, the packages location is actually not the problem, adapting that path works fine. The problem lies in lerna thinking its not been `lerna init`ed when the lerna managed package is not equal to the git root. I can create a gist to demonstrate the problem if that is easier?

**Comment by doug-wade** [comment]
@joscha I think in this case a repro repository would be best, since then I can clone it and use it locally -- unless there's some cool gist feature I don't know about, to use it locally would take a lot of copy-paste.

**Comment by joscha** [comment]
sure, repo is here: https://github.com/joscha/lerna-broken-nesting-example

**Comment by joscha** [comment]
@doug-wade were you able to verify the problem or is there anything else I can provide?

**Comment by evocateur** [comment]
@joscha I understand this problem, and I could've sworn there were a couple other issues recently with _basically_ the same problem. In any case...

Right now, we are indeed making the assumption that `lerna.json` lives in the repo root, which we obtain in the normal git plumbing fashion (`git rev-parse --show-toplevel`). It's robust because it doesn't care what your `CWD` is, and so on.

Alternatively, we could use a package like [find-up](https://github.com/sindresorhus/find-up) to locate `lerna.json`, which would largely enable your desired pattern (with the caveat that you'd always need to run lerna commands with `$CWD == /maven-project-a/`, in your example).

TODOs, as I see them:

- [ ] The `Repository` class needs to use `findUp("lerna.json")` to set its [`rootPath`](https://github.com/lerna/lerna/blob/master/src/Repository.js#L18) property.
- [ ] We need to resolve the "chicken vs egg" problem for [`lerna init`](https://github.com/lerna/lerna/blob/master/src/commands/InitCommand.js), namely that `lerna.json` won't exist (and thus all the `Repository` setup needs to be delayable or re-baseable?).
- [ ] `lerna init` should accept an optional argument specifying the root directory, otherwise defaulting to `process.cwd()`.

PRs welcome. :)

**Comment by joscha** [comment]
Thanks for the answer @evocateur - we had to abandon our plans to use lerna in the meantime, due to #377 and also a few comments here and there that suggested that lerna functionality might be picked up by yarn, so I won't be investing time in this issue for now. We can close the issue or leave it open (as I think other people might have similar issues and might be interested in following through the TODOs).

**Comment by evocateur** [comment]
I understand completely, @joscha. We'll leave this open so it's easier for others with the same issue to find.

**Comment by joscha** [comment]
:tada: thanks @evocateur
