### ISSUE TITLE
[Feature] Better exiting on publish

### ISSUE THREAD

**Issue by jamiebuilds** [lerna/lerna#56]
Right now if stuff starts erroring out or you cancel before everything is finished lerna doesn't completely roll back. It would be nice if it could handle this more gracefully.

**Comment by delcore92** [comment]
I'm finding the same issue. If for example you attempt to publish and git returns an error because there are changes that haven't been pulled, the packages that need to be updated will no longer be visible when you use the command 'lerna updated'. I'm assuming that lerna clears the updated flags on the packages regardless of errors.

Currently using v1.1.2

**Comment by boxxxie** [comment]
If i'm not allowed to publish to npm then i get dirty git state. i have a commit that i don't want, and i have a bunch of tags that i have to manually delete.
I have also run into the problem where i ended up with dist-tags on each of my packages that were causing me to not be able to publish, so my git tags would increment, and my npm publish wouldn't work.

there are a few steps that lerna does when we ask it to publish. i think that each step should be a command, each step should output a log of what it does, and for each command there should be a revert-command that does or does not use this log.

**Comment by gauntface** [comment]
I just hit this as well and fixing it doesn't seem to be easy. I wasn't logged in to NPM so the final step of publishing to NPM failed and lerna now believes everything is fine and published even though the last step failed.
