### ISSUE TITLE
Lerna stops working on packages when private: true

### ISSUE THREAD

**Issue by guigrpa** [lerna/lerna#570]
I'm on lerna 2.0.0-beta.36 and setting packages to `"private": true` disables Lerna for them altogether: no updates are detected, no bumping versions, nothing. A soon as I disable the `private` flag, Lerna works again.

I have tried to find this exact bug but didn't succeed. Sorry if it's a duplicate!

**Comment by gigabo** [comment]
Hi @guigrpa sorry you're running into trouble.  What Lerna command is failing for you?

Can you link to the repository where this is happening?

**Comment by guigrpa** [comment]
Unfortunately, I can't link to that repo since it's *private* ;) But I've prepared two simplified repros here (lerna v2.0.0-beta.36, npm v3.8.5, node v7.3.0). The repros have been generated on Windows, but the same problem appears on OS X:

**Example 1: private from the start** -- [guigrpa/test-lerna1](http://github.com/guigrpa/test-lerna1)

1. On a new repo:

  ```sh
  $ lerna init
  Lerna v2.0.0-beta.36
  Creating package.json.
  Updating lerna.json.
  Successfully created Lerna files
  ```

2. Create a couple of simple packages, `packages/a` and `packages/b`, initializing `package.json` with `npm init` and then setting `private` to `true`
3. Run `lerna bootstrap`
4. Commit -- **this is the version you can see in the first repo, [guigrpa/test-lerna1](http://github.com/guigrpa/test-lerna1)**
5. If you now run `lerna publish`, you would expect lerna to prompt you for a new version (as happens when the packages are not private). Instead:

```sh
$ lerna publish
D:\Prog\test\test-lerna1>lerna publish
Lerna v2.0.0-beta.36
Current version: 0.0.0
Checking for updated packages...
Errored while running PublishCommand.initialize
Error: No updated packages to publish.
    at PublishCommand.initialize (...\lerna\lib\commands\PublishCommand.js:98:18)
    at PublishCommand._attempt (...\lerna\lib\Command.js:198:21)
    at PublishCommand.runCommand (...\lerna\lib\Command.js:182:12)
    at PublishCommand.run (...\lerna\lib\Command.js:98:12)
    at Object.<anonymous> (...\lerna\bin\lerna.js:70:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Example 2: public, then private** -- [guigrpa/test-lerna2](http://github.com/guigrpa/test-lerna2)

1. On a new repo: `lerna init` (as above)
2. Create a couple of simple packages, `packages/a` and `packages/b`, initializing `package.json` with `npm init` (we leave `private` unspecified first)
3. Run `lerna bootstrap`
4. Commit
5. Running `lerna publish --skip-npm`, it prompts for a new version number. We choose minor and confirm. As expected, Lerna updates the `package.json` files, generates a new git tag and a new commit (which in Windows has an incorrect commit message, btw.: *$(echo v0.1.0)*)
6. We now make both packages private and commit
7. We also make modifications to both packages, e.g. creating new files in them, and commit again -- **this is the version you can see in the second repo, [guigrpa/test-lerna2](http://github.com/guigrpa/test-lerna2)**
8. If we run `lerna publish` now, Lerna throws (just as in the first example), despite the updates

**Comment by spudly** [comment]
Ran into the same issue this morning.

If you only change a private package before running publish, lerna will say there are no changes and refuse to do anything. I expected that it would at least update the version for the changed, private packages, but it just fails instead because there are "no updated packages to publish".

Likewise, if you change a private package and don't change any packages that depend on it, that private package will not have it's version updated, even if you have other changes in other packages that do get published.

In my case, some of my packages are marked private because they get published in a different way (they get zipped and uploaded, not published to NPM). For this reason, I need the version to be updated, even if it doesn't get published to NPM.

At this point, if I want it to rev the version for my private package without changing other packages, I have to make it public. 😢

**Comment by tomwayson** [comment]
Same problem as @spudly describes just happened to us. I'll just add that I expected `lerna publish --force-publish=my-private-package1,my-private-package2` to work, but it threw the same error. We were able to run `lerna publish --force-publish=*`, but that bumps every packages, even the public ones that didn't change. Since then we've just been making sure to make at least one change to one of the public packages that our private packages depend on.

**Comment by spudly** [comment]
Digging through the source code, it looks like the publish command expects the updates provided by `updatedPackagesCollector.getUpdates()` to include private packages (see [PublishCommand.js Line 38](https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L38)), but they are already filtered out (see [UpdatedPackagesCollector Line 63](https://github.com/lerna/lerna/blob/master/src/UpdatedPackagesCollector.js#L63)).

**Comment by spudly** [comment]
Digging some more, I was not strictly correct when I said that the `getUpdates` function does not return any private packages. It does filter out changed private packages, but then it adds all dependents of the changed public packages, which may or may not include some private packages.

So in order for a private package to get its version incremented, it must depend on a public package that changed. Whether the private package changed or not does not matter.

Thus, if all your changes are private, it will refuse to update anything.
Or, if you change a private package and a public package, but the private package doesn't depend on the public package, it will skip the private package and only publish the public package.

I can kind-of see why this might be intentional. You could say, for example, that there's no point in updating packages that are not public or are not depended upon by public packages.

Unfortunately this doesn't fit the following use cases:
* All private packages
* Some public, some private (but deployable). Private packages are private because they are entry Apps that get deployed, not published as a library. They still need to be versioned, but not published to npm. (this is my use case)

@gigabo, @thejameskyle, @hzoo, Would you guys accept a pull request in which all changed packages have their versions updated (but not necessarily published) regardless of whether they are private or not? It would only involve removing lines [63 - 65 of UpdatedPackagesCollector.js](https://github.com/lerna/lerna/blob/master/src/UpdatedPackagesCollector.js#L63). I've tried locally and it fixes the problem without breaking other tests.

**Comment by evocateur** [comment]
@spudly It may very well be an accident that PublishCommand filters out private packages redundantly. It's quite likely due to the fact that we're kind of overloading the concept of `"private": true` to mean "do stuff to this package but don't actually publish it" instead of the default "never publish this package".

The "all private packages" use-case seems kind of... "Why use `lerna` at all?" territory.

For the second use-case, to be honest, I'm not sure I agree that `lerna` should support it.

Indeed, PublishCommand _does_ appear to execute the [`prepublish` phase for _all_ updated packages](https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L352), regardless of privacy, thus giving you a hook for running webpack/rollup/etc. Presumably this private prepublish generates a tarball somewhere, which an external process then uploads into an artifact repository, and so on.

At this point, why is it `lerna`'s responsibility to choose the version number of this build artifact? The private package.json's `version` property is utterly irrelevant to the deployable artifact being created, as it cannot be consulted before the artifact is downloaded to determine its version (which is what the artifact's filename is for).

I would like to get @gigabo and @hzoo's input on what the intentions were behind `private: true` filtering.

**Comment by danielo515** [comment]
> Some public, some private (but deployable). Private packages are private because they are entry Apps that get deployed, not published as a library. They still need to be versioned, but not published to npm. (this is my use case)

This is exactly the usecase at my company. I don't see why lerna should not support it since it is a mono-repo and lerna is a tool for managing mono-repos

**Comment by evocateur** [comment]
That’s literally what happens now. Private packages versioned til the cows come home.
