### ISSUE TITLE
`lerna bootstrap` does not symlink with URLs

### ISSUE THREAD

**Issue by acarl005** [lerna/lerna#571]
This tool is awesome! We'd really like to be able to benefit from it, but...

Our local copies of the dependencies specified at GitHub URLs are not getting symlinked by `lerna bootstrap`.

```js
{
  "dependencies": {
    "bluebird": "3.4.7",
    "lodash": "4.17.4",
    // dependencies in URLs do not work. no symlinked
    "some-internal-package": "https://x-oauth-basic:<token>@github.com/stems/some-internal-package/archive/2.1.6.tar.gz"
  }
}
```

Would it be possible to support these as they are not published on NPM?

**Comment by foodforarabbit** [comment]
Hey I would love to see this too. We don't publish packages but pull them from a private gitlab instead e.g.

`"framework": "git+ssh://git@gitlab.host.com:frontend/framework.git"`

Currently, each of the packages is actually it's own git repo as submodules so that they can have their own ci/cd pipeline so I need the gitlab url. 

My current work around is when I need to work on multiple packages at the same time in lerna, I change the urls to version numbers (e.g. 0.0.1) and then run lerna bootstrap. After lerna has finished symlinking everything, I change the versions back (so I don't forget) and then everything kinda works. I would love to have this work automatically without having to switch numbers back and forth.

**Comment by evocateur** [comment]
[Hosted Dependencies](https://github.com/lerna/lerna#git-hosted-dependencies) have been supported for some time. They just need a "committish" hash (`#v1.0.0` or `#semver:^1.0.0`) that matches the monorepo sibling's version.

It doesn't cover the tarball case, however.

**Comment by foodforarabbit** [comment]
@evocateur I tried it out just now and I can't seem to get it to work. I tried it with both lerna version `2.11.0` and `3.0.0-beta.20`. 

The way I had it working before, I had a package "framework" set to version `0.0.9` in the package.json. In the package pulling in "framework", I would switch between `"framework": "0.0.9"` which would symlink it locally, and `"framework": "https://git@gitlab.company.com/repo/framework.git"` which would allow the package to be built without lerna (each package is a git submodule with gitlab ci and can be developed as a standalone codebase... I use lerna when making changes to "framework" at the same time). 

I tried adding the version as per the examples: `"framework": "https://git@gitlab.company.com/repo/framework.git#v0.0.9"` which errored at first, but worked after I created a `0.0.9` tag in gitlab for "framework". However, lerna does not symlink it (no symlink in node_modules of the package pulling in "framework", and changes made to the local code in "framework" are not reflected in the other package.) 

The gitlab repo is an internally hosted repo with "public" visibility if that makes a difference.

Can you see if I'm doing anything immediately wrong? Otherwise I can try to create a repo to replicate this issue...

**Comment by evocateur** [comment]
Using gitlab from a subdomain instead of gitlab.com might be confusing the underlying library, hosted-git-info.

**Comment by foodforarabbit** [comment]
You're right, changing gitlab.company.com to just gitlab.com makes the symlinking work. Thanks, I'll look into my own work arounds for this issue!
