### ISSUE TITLE
Document the packages option better

### ISSUE THREAD

**Issue by hzoo** [lerna/lerna#589]
Ref https://github.com/lerna/lerna/issues/11#issuecomment-278474277

Maybe add some more examples or usecases

common one is people wanting to use the root as a package so you would say `"."` in https://github.com/lerna/lerna#lernajson

**Comment by abellinii** [comment]
I would like to contribute. This is my first contribution so would anyone like to guide me through the process?

**Comment by evocateur** [comment]
@abellinii A good place to start would be ...ehh, kinda hard to find. Probably start with questions that _you_ have about the `packages` config, and then investigate current tests and fixtures for possible demonstrations of current behavior? It's a bit haphazard right now, but it _should_ be a bit more detailed than when this issue was first created.

**Comment by sainiajay** [comment]
Hi @evocateur, Not sure if this issue is resolved already. If not, I'd like start my contribution journey from this issue. Please help me to get started on this one.

**Comment by JamesHenry** [comment]
Hi Folks 👋

In light of its age, and in order to allow our small team to focus on what matters most to Lerna v6 users in late 2022, I'm going to close this one. If you have any requests that could enhance your usage of Lerna 6, then please do let us know by opening a new discussion (for a feature) or issue (for a bug report) with as much context as possible.

You can also check out our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

Many thanks 🙏
