### ISSUE TITLE
Init doesn't create a packages folder

### ISSUE THREAD

**Issue by xtuc** [lerna/lerna#591]
In the README, the getting started section says that the `lerna init` command:

> [...] will create a lerna.json configuration file as well as a packages folder.

Looking at the source code I think this behavior doesn't exists anymore, see [InitCommand](https://github.com/lerna/lerna/blob/master/src/commands/InitCommand.js#L16-L18)

Tested on `lerna@2.0.0-beta.37`

**Comment by gigabo** [comment]
Nice catch @xtuc.  That was removed from the documentation when https://github.com/lerna/lerna/pull/365 stopped creating the folder, but looks it was added back into the documentation in https://github.com/lerna/lerna/pull/517.  I guess the resolution there should have been to update the _website_ rather than the README.  Should be solved by building the website from the README, which I think is underway in https://github.com/lerna/website/pull/14.

**Comment by jwb** [comment]
I wonder: if the website generation isn't making progress, should we prune out the details and just link to the README, so we aren't providing bad info to users?
