### ISSUE TITLE
improve throughput of topologically-sorted tasks

### ISSUE THREAD

**Issue by seansfkelley** [lerna/lerna#612]
The current implementation is easy to grok, but because it only uses static information about the dependency tree, it can bottleneck hard if different tasks take wildly different times to execute. Imagine a case where several long-running tasks are batched serially by an accident of the dependency tree:

```
S = short-running task
L = long-running task

S
| \
S  L
| \  
S  L
```

Sad times! The current implementation will put each row into its own batch, and even though the long-running tasks don't actually depend on each other it will serialize them. Instead, Lerna should enqueue packages for execution as their dependencies actually finish executing to avoid this situation. As a downside, cycles can't be identified until they are encountered without a bunch of other preprocessing work, but this is probably fine since cycles are bad bad bad anyway.

Furthermore, fixing this arguably justifies the removal of the `--no-sort` flag, as there is no longer a penalty for toposorting (simpler UI!). In Yerna, changing the toposorting implementation alone reduced my build times by fully 25% (~20m -> ~15m). You can check [a reference implementation here](https://github.com/nomcopter/yerna/blob/27625be2601625402addd8766818f11dbe84dea4/lib/taskrunning.js#L167).

(This was a feature I added in [Yerna](https://github.com/palantir/yerna) that I found quite useful; I'm filing this issue for discussion purposes. Feel free to close if it's not a behavior you want in Lerna.)

**Comment by evocateur** [comment]
I'm interested in this, but I'm also hesitant because our current testing strategy would in all likelihood be insufficient validation. If I find myself with spare cycles, I'll play with this a bit.

Thanks @seansfkelley!

**Comment by JamesHenry** [comment]
Hi Folks 👋

In light of its age, and in order to allow our small team to focus on what matters most to Lerna v6 users in late 2022, I'm going to close this one. If you have any requests that could enhance your usage of Lerna 6, then please do let us know by opening a new discussion (for a feature) or issue (for a bug report) with as much context as possible.

You can also check out our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

Many thanks 🙏
