### ISSUE TITLE
Consider supporting examples.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [lerna/lerna#618]
Let's say I have a `lerna` repo for `react` components and I wanted to add some examples using `create-react-app`.  I can think of three ways to do that

1. Have the examples as packages.  But the examples don't get published and `react-scripts` from `create-react-app` will be installed when I bootstrap, so it's less than ideal.
2. Manage the examples outside of `lerna`, require components as dependencies.  This means that I can only use versions of the component that have been published, not what's actually in the repo.
3. Manage the examples outside of `lerna`, require components directly.  This is probably the best available solution, but
```
const myComponent = require('../../packages/my-component/dist');
```
is a bit more tedious and brittle than
```
const myComponent = require('my-component');
```

Could `lerna` provide a way for `examples` to reference `packages`?

**Comment by evocateur** [comment]
Would a second `packages` glob in `lerna.json` solve this? e.g.,

```
{
  "lerna": "2.0.0-beta.37",
  "packages": [
    "packages/*",
    "examples/*"
  ],
  "command": {
    "bootstrap": {
      "hoist": true
    },
    "publish": {
      "ignore": [
        "examples/*"
      ]
    }
  },
  "version": "$VERSION"
}
```

Of course, the problem here is that `command.publish.ignore` operates on package _names_, not file paths. That's awkward. Alternatively, ensure that all the `examples/*` packages have `"private": true` in their package.json.

With this setup, you'd get the best of both worlds: ease of requiring "live" (not published-only) dependencies without the hassle of bifurcated source repositories?

**Comment by ben-eb** [comment]
@wtgtybhertgeghgtwtg babel-plugin-module-resolver makes option 3 more viable. 😄 

https://github.com/tleunen/babel-plugin-module-resolver

**Comment by wtgtybhertgeghgtwtg** [comment]
@evocateur Wouldn't that still install the dependencies of packages in `examples` on `bootstrap`?
@ben-eb That is probably the best solution.  Thank you.

**Comment by evocateur** [comment]
Yes, it would, but if you're hoisting, they'll no doubt go a lot faster.
