### ISSUE TITLE
--hoist with yarn removes root packages

### ISSUE THREAD

**Issue by jquense** [lerna/lerna#630]
Running into an issue trying out the new `npmClient` option. From a clean repo (`lerna clean && rm -rf node_modules`) running `yarn install && lerna bootstrap --hoist` results in a broken configuration. From what I can tell, when the packages are hoisted to the root directory all the root dependencies are bulldozed over and removed. As a consequence binaries (like eslint) are missing/unavailable to packages. This seems to be yarn's install behavior

I'm not sure how to debug further but I'd be happy to do what I can with some direction

**Comment by evocateur** [comment]
This is one of the reasons I've never felt especially comfortable with `--hoist`'s behavior of installing the dependencies at the root of the repo (instead of the closest common directory, e.g. `./packages/node_modules` for the default `packages/*` location).

I'm assuming your `lerna.json` looks similar to this:
```json
{
  "lerna": "2.0.0-beta.38",
  "packages": [
    "packages/*"
  ],
  "npmClient": "yarn",
  "version": "0.0.0"
}
```

I've had good luck with a yarn root, `lerna --hoist` (_without_ the new `npmClient` option), **and** fully-specified `dependencies` and `devDependencies` of those hoisted sub-packages in the root. I don't have to use `--npm-client yarn` because `npm install` is never called during bootstrap (which I call from the `postinstall` lifecycle script, so `yarn` has already installed everything in the root).

My approach is obviously a laborious and error-prone process for projects with many (or conflicting) sub-package dependencies. I did it because of my dislike of `--hoist` just dumping stuff in the root regardless of what the root `package.json` specifies. I am in favor of changing the target of `--hoist` to the closest common directory, but also open to other solutions.

**Comment by gigabo** [comment]
>  binaries (like eslint) are missing/unavailable to packages.

Oh, they sure are! 🤦‍♂️ 

That's... unfortunate.

>  I am in favor of changing the target of --hoist to the closest common directory, but also open to other solutions.

What if the closest common directory is the root?

**Comment by gigabo** [comment]
Minimal repro of the problematic Yarn behavior:

```sh
$ cat package.json
{
  "dependencies": {
    "eslint": "^3.16.1"
  }
}
$ npm i rimraf
$ ls node_modules/.bin/
rimraf
$ yarn install
$ ls node_modules/.bin/
eslint
```

It doesn't remove `node_modules/rimraf/`.  It just removes the link in `node_modules/.bin`.

**Comment by evocateur** [comment]
> What if the closest common directory is the root?

That's a valid result, certainly, but then we have decisions to make. Disable `--hoist` when `--npm-client` is `yarn`? Add a `lerna hoist` subcommand that adds missing package dependencies to the root's `devDependencies`, thus avoiding the yarn nukage?

**Comment by jquense** [comment]
seems like the most straightforward (maybe not correct tho) solution is to combine the package.json in the hoist location with all the hoisted deps, so `installInDir works as intended? 

Honestly tho I can't see lerna supporting other npm clients without specific client adaptors that handle the api differences, yarn especially has fairly divergent behavior from `npm`

**Comment by gigabo** [comment]
Just put up https://github.com/lerna/lerna/pull/638 to address this.

It lets Yarn know about all of the dependencies we expect to wind up in any given location.
