### ISSUE TITLE
[Bug] README.md is not published to npm

### ISSUE THREAD

**Issue by Deadarius** [lerna/lerna#64]
When I try `lerna publish` - npm registry doesn't display readme, however when I use npm publish - it does.

**Comment by thejameskyle** [comment]
The README where? Individual packages should have their own README, the primary one at the root of the repo will not be published anywhere.

**Comment by gigabo** [comment]
We're actually seeing the same thing.  Assumed we were doing something wrong.  Hadn't considered that it may be related to deploying with `lerna`.

Here's our [package](https://github.com/redfin/react-server/tree/master/packages/react-server) and here's the corresponding [npm page](https://www.npmjs.com/package/react-server) with missing README.

**Comment by thejameskyle** [comment]
Weird... we're literally just [`cd`-ing into the directory and running `npm publish`](https://github.com/kittens/lerna/blob/91a22ecb5bca5fd605209960621173840ea30677/lib/commands/publish/npmPublishAsTemp.js#L42)

**Comment by gigabo** [comment]
Maybe something to do with the package not living at the repo root?

Seems more likely to be an `npm` bug than a `lerna` bug, honestly.

**Comment by Deadarius** [comment]
Yes, I do have readmes... When I was trying to find a problem I noticed that you just run existing npm... have no idea what can be a problem here. Only aware of this issue in outdated version of npm.

**Comment by Deadarius** [comment]
@gigabo But it works fine when I run ```npm publish``` directly...

**Comment by ianwremmel** [comment]
I seem to be running into the same issue. I definitely have a new README, but the changes aren't showing up on NPM.

**Comment by ianwremmel** [comment]
(by NPM, I mean https://www.npmjs.com/)

**Comment by ianwremmel** [comment]
I have a hypothesis that the way lerna messes with dist-tags isn't triggering npm's normal website refresh job. I've opened a support ticket with npm, inc to investigate and will report back here if I hear anything.

**Comment by Deadarius** [comment]
@ianwremmel thank you very much, I still suffer from this issue.

**Comment by thejameskyle** [comment]
This bug is hard to debug as I've had no problems with README's (https://www.npmjs.com/package/cf-component-modal)

**Comment by ianwremmel** [comment]
I heard back from npm. It is indeed a result of the dist-tags technique used by lerna. npm has an open issue: https://github.com/npm/newww/issues/389#issuecomment-188428605

**Comment by ianwremmel** [comment]
Ok, it's a hack, but a I got some help from npm and there's at least a way we can trick npm into rebuilding the readme.

First, add "-readmehack" to the end of the package version in package.json, then:

```bash
npm publish
npm dist-tag add ciscospark@0.6.3 latest
npm unpublish ciscospark@0.6.3-readmehack
```

**Comment by thejameskyle** [comment]
I don't really want to put a hack like that into lerna. The publishing process is already very complex and that adds a lot of complexity

**Comment by ianwremmel** [comment]
Agreed, I'm not suggesting that gets hacked in, but it at least helps those with the problem until npm fixes the bug.

**Comment by ianwremmel** [comment]
In my case, I only actually have one readme I need to update, so I can put that in my publish script pretty trivially.

**Comment by danigb** [comment]
I'm having the same issue...

**Comment by thejameskyle** [comment]
Locking this. I want an update just as much as everyone, but please just follow the actual issue on npm: https://github.com/npm/newww/issues/389

**Comment by hzoo** [comment]
### Alright!!! An update to this issue: it should be fixed (via npm side)!

So I just published 6.22.0 yesterday and was thinking about publishing to the `latest` tag first instead of first `lerna-temp` then moving to `latest` but forgot. Then I was checking the readme's and it looked like they were already updated magically!?

Turns out @bcoe had been working on fixing this issue, so it looks like it's all good for us on this one?

> it now renders the README directly from the package, rather than pulling it out at publish time.

---

We haven't published a new babel version in a month (>30 days)

Example with `babel-core`:

https://www.npmjs.com/package/babel-core

![screen shot 2017-01-20 at 3 35 33 pm](https://cloud.githubusercontent.com/assets/588473/22164638/19bcc63e-df26-11e6-97a9-d4c9cc93b5d6.png)

https://github.com/babel/babel/pull/5101/files (5 days ago)

![screen shot 2017-01-20 at 3 35 16 pm](https://cloud.githubusercontent.com/assets/588473/22164629/11f8667e-df26-11e6-98b4-7b7b99d78ced.png)

**Comment by gigabo** [comment]
Awesome!  Finally! 🎉

**Comment by ianwremmel** [comment]
Awesome! Thanks @bcoe! The emoji don't exist to express my excitement!

**Comment by bcoe** [comment]
Thanks! Giving credit where credit is due, the whole backend team at npm has been working on infrastructure this makes solving problems like this much easier (we've been rolling out a database that was @chrisdickinson's mad-science idea). I'm really excited to make the tag workflow elegant, for the community and for the benefit of my own OSS projects.

**Comment by tomwayson** [comment]
I'm confused. It sounds like @hzoo is saying that the npm website now picks up the README from whatever's on master in GitHub repository. I have not experienced this in my own projects, looking though issues for the npm website and registry for whatever changes were alluded to above, I see [comments like this]( https://github.com/npm/registry/issues/118#issuecomment-349713296).

@bcoe would you be able to shed light on the behavior we should expect, or point to any docs or at least the changes above?

Thanks!

**Comment by bcoe** [comment]
@tomwayson Hey 👋 

So, rather than always pointing to the last published README file, we now point to whatever README is pointed to by the `latest` tag of npm. _so,_ if you have a workflow in which you publish to a `beta` tag (as an example) and then use `npm dist-tag add` to switch this tag, you will see the appropriate README after the swap has taken place.
