### ISSUE TITLE
Feature request:  Optionally disable stdout prefix for "lerna run"

### ISSUE THREAD

**Issue by GordonSmith** [lerna/lerna#644]
Motivation - To allow vscode "tsc-watch" problem matcher to work correctly.

Currently it spots errors, but is unable to resolve the offending file due to the package prefix that lerna emits.

For example:
```
lerna run watch --stream --no-sort
```

Outputs:
```
...
@hpcc-js/comms: src/ECL/Result.ts(1,10): error TS2305: Module '"C:/Users/gordon/git/hpcc-js/packages/xml/lib/index"' has no exported member 'parseXSD'.
...
```

And VSCode gets confused due to the: ```@hpcc-js/comms: ``` prefix:
```
Unable to open 'Result.ts': File not found (c:\Users\gordon\git\hpcc-js\@hpcc-js\comms: src\ECL\Result.ts).
```

**Comment by GordonSmith** [comment]
Actually this is a bit more involved - lerna would need to emit "packages/pck-name/" as the prefix for this to work (and is very vscode specific).

While vsCode has a pretty flexible problemMatcher - I dont think there is anyway to regex the full relative path from the prefix and the error.

**Comment by evocateur** [comment]
I think the [prefix](https://github.com/lerna/lerna/blob/master/src/NpmUtilities.js#L114) is useful, especially when streaming. However, it should probably be changed to emit the relative path (`packages/foo-module`) instead of the package name, since the package name and directory name don't always coincide (e.g., when using a scoped package name but not a scope directory).

For your particular use-case, wouldn't it be sufficient to replace the scope prefix with `packages`? I'm not sure we want to customize log output for a single tool, given the capacity for filtering in the shell and whatnot.
