### ISSUE TITLE
Proposal: Use a graphic to explain what the project is

### ISSUE THREAD

**Issue by rodet** [lerna/lerna#651]
Hello,

I just have got in touch for the first time with this project today, and at first, while being on https://lernajs.io/, it took me some time to understand what the project was about. Reading more in detail, I started to think I have understood. Later on, looking on the GitHub project README, I found something similar to what I was looking for:

> There's actually very little to it. You have a file system that looks like this

That followed by a symbolic view of directories and files, which I found really useful.

So I started thinking about how to depict this easily with a graph on https://lernajs.io/ that would make very quickly clear to users what the project is about. I came up with the following ideas:

### Vertical
![vertical](https://cloud.githubusercontent.com/assets/343696/23662378/a47e3d64-034f-11e7-9189-c79ff6bc86de.png)

### Horizontal
![horizontal](https://cloud.githubusercontent.com/assets/343696/23662391/ae4c1a0a-034f-11e7-85f6-132dc4b1bf71.png)

Let me know if that is not accurate.

Would you consider using or creating such a graph? Do you think it would help users understand the project better?

**Comment by hzoo** [comment]
How did you find out about the project? What about the "About" section was confusing?

If people understand that `Package` = npm package, then yeah it's possible it could be helpful? Might need to make more to explain that it also means there are node_modules for each folder, including the top level repo. Is the picture providing that much more info that just writing it out in markdown? You can just point a user to the actual github repo which is more interactive as well.

At the same time using lerna a monorepo is a specific solution to a problem not everyone has. It's not worth just using for the sake of using just because some projects we see are using since it has it's own complexity/issues.

**Comment by rodet** [comment]
@hzoo Thanks for the quick answer! I found out about this project because I started working on a project that uses it. I understand this might not be for everyone - the project I am on actually have needs for it, as it is a collection of sub-projects that live together.
Should I replace "Package A" by "npm package A" etc? Markdown might do the job as well - I was hinting at a picture because it often says more than 1000 words if done right.
Here is a preview with the replacement:

![vertical2](https://cloud.githubusercontent.com/assets/343696/23698179/db0813e6-03ea-11e7-90af-66dddcc37e74.png)

Or

![horizontal2](https://cloud.githubusercontent.com/assets/343696/23698184/dfd424c8-03ea-11e7-8d77-5af091b089e2.png)

In the end, I just wanted to show one possibility that I think might make easier for potential users to understand quickly if and why they should use Lerna. You decide if you want to include such a graph or not, or take another action on that feedback :)

**Comment by JamesHenry** [comment]
Hi Folks 👋

In light of its age, and in order to allow our small team to focus on what matters most to Lerna v6 users in late 2022, I'm going to close this one. If you have any requests that could enhance your usage of Lerna 6, then please do let us know by opening a new discussion (for a feature) or issue (for a bug report) with as much context as possible.

You can also check out our published roadmap for Lerna v7 here: https://github.com/lerna/lerna/discussions/3410

Many thanks 🙏
