### ISSUE TITLE
Publishing independent lerna in CI

### ISSUE THREAD

**Issue by Moeriki** [lerna/lerna#653]
Dears,

I'm having some issues figuring out how to publish Lerna in independent mode through a CI.

I want to:

1. update NPM versions independently locally
2. have CI do NPM publish

I can do 1. with `lerna publish --skip-npm`. But how do I do 2. ?

I checked the source code of `publish` and it seems to me an option is missing. Something like `--current` to publish all tags attached to the last commit.

Or am I missing something. Your feedback would be greatly appreciated.

**Comment by noherczeg** [comment]
Have you considered using https://github.com/lerna/lerna#exec with manual git push on your CI?

**Comment by Moeriki** [comment]
I have tried some things and settled with this script.

_package.json_

```json
{
  "scripts": {
    "deploy": "node deploy.js"
  }
}
```

_deploy.js_

```js
const execSync = require('child_process').execSync;

const exec = (command) => execSync(command, { encoding: 'utf8' }).trim();
const LERNA_BIN = path.join(exec('npm bin'), 'lerna');
const lerna = (args) => exec(`${LERNA_BIN} ${args}`);

const isPkg = (tag) => tag.match(/[\w-]+@\d+\.\d+\.\d+(-[\w\d]+)?/);

const updatedPackages = exec('git tag --list --contain HEAD')
  .split('\n')
  .filter(isPkg)
  .map(split('@'))
  .reduce(zip, {})
;

for (const pkg of Object.keys(updatedPackages)) {
  const version = updatedPackages[pkg];
  lerna(`--scope ${pkg} exec -- npm publish`);
}
```

It's a bit surprising such a manual effort is needed to deploy independent packages through a CI. Any plans to make anything like the script above available as lerna command?

**Comment by evocateur** [comment]
I suppose I'm left wondering why you would want to split these decisions? If you're just trying to gate a release on tests passing, that should be a `prepublish` lifecycle (or other agreed-upon process).

We definitely want to support automated publishing in CI (something like [semantic-release](https://github.com/semantic-release/semantic-release)), but I don't think we can safely support this split-decision approach in our current codebase.

I can see an argument for improving `lerna updated` or `lerna ls` to support better filtering and perhaps even a `--since=<commit-ish>` flag that would make scripts like yours far easier.

**Comment by Moeriki** [comment]
No good reason. Just company policy 😖

**Comment by evocateur** [comment]
Oh, I sympathize! I'm probably going to be in a similar situation at work Real Soon Now™️, so it's not _completely_ hopeless.

However, we've got a (growing) complexity problem with the codebase, and I'm trying to keep the stuff that _can_ be an external script externalized for now. My dream is to make various parts of `lerna` pluggable, so we can simplify a bit of the core code and have cleaner integrations with special cases like yours.

**Comment by Moeriki** [comment]
No problem. I'm good as-is.

**Comment by joebowbeer** [comment]
Can step 2 be accomplished using the `--skip-git` flag, possibly in combination with `--force-publish`?

`lerna publish --skip-git`
