### ISSUE TITLE
Not all package peer/dev deps were updated during a publish

### ISSUE THREAD

**Issue by milesj** [lerna/lerna#660]
Project and packages here: https://github.com/milesj/aesthetic/tree/master/packages

I just ran `lerna publish --include-filtered-dependencies --force-publish=*` to update all packages major version to 1.0.0 (which tagged successfully). However, I noticed after the fact, that the `peerDependencies` and `devDependencies` for `aesthetic-adapter-css-modules` and `aesthetic-adapter-jss` did not update to the 1.0.0 version, while all the other packages did, but instead remained on the previous version of 0.5.2. I tried publishing a 1.0.1 version and the same exact thing happened.

I'm not entirely sure what the root cause is. Could it be that the source files are not directly in the packages folder (I build to them)? That wouldn't explain the inconsistency though.

**Comment by milesj** [comment]
Spent the last week moving the root src/test folders into each package. I then tagged a new version and all the `package.json` files were updated accordingly. Not sure if that's the actual issue, just giving an update.

**Comment by evocateur** [comment]
Has this issue re-occurred after you moved things into their expected place (`packages/*/{src,test}`)?

**Comment by milesj** [comment]
@evocateur I've not encountered it, but I haven't tagged much since.

**Comment by evocateur** [comment]
@milesj Thanks for checking. I'm going to close this for now, since we don't have anything actionable. If that changes, by all means re-open this.

**Comment by pshrmn** [comment]
I ran into what I believe is the same issue. I think that it is happening because `topologicallyBatchUpdates` does not take `peerDependencies` into consideration when it is ordering the packages. That means that if the peer dependency gets ordered after the other package, it will not be updated. I believe that a peer dependency should be placed ahead of the files that expect it to be installed.

I'll do a little bit more experimenting to confirm, but I'm not too familiar with Lerna's code base, so I'm just <kbd>Ctrl</kbd>+<kbd>f</kbd>ing my way through the files.

**Comment by pshrmn** [comment]
As an update, I was able to get my desired behavior, but part of the fix was that I had to disable the `semver` check because I was going from `0.X.X` to `1.0.0-beta.X`.

Basically, I changed this line https://github.com/lerna/lerna/blob/v2.0.0/src/PackageGraph.js#L36 to merge the `dependencies` and `peerDependencies` objects when in `depsOnly` mode. Then I removed the semver check from this line https://github.com/lerna/lerna/blob/v2.0.0/src/PackageGraph.js#L44 so that I could ensure that all of my dependencies get updated (if I didn't do this, then the ref count would be incorrect and the order would be wrong). 

The second part of my fix is definitely hacky, but I'm not sure if there is a built-in way to force dependency updates when bumping major versions. That isn't something that happens often, and perhaps I'm just using Lerna incorrectly, but it was something that I had hoped to be automated. I can understand why it wouldn't be, though.

**Comment by pshrmn** [comment]
Another addendum: I actually had an incomplete solution before. I also had to add `peerDependencies` to the `allDependencies` object. I'm actually a little bit confused now because in `PublishCommand.js`, the `peerDependencies` are definitely updated ([source](https://github.com/lerna/lerna/blob/v2.0.0/src/commands/PublishCommand.js#L452)), but they are never added to the `PackageGraphNode` for a package...
