### ISSUE TITLE
create-react-app: `lerna bootstrap` occasionally failing

### ISSUE THREAD

**Issue by darrenscerri** [lerna/lerna#716]
We are noticing that `lerna bootstrap` is occasionally failing on AppVeyor ([1](https://ci.appveyor.com/project/Facebook/create-react-app/build/1.0.399/job/leexhufu96s5oexg), [2](https://ci.appveyor.com/project/FeodorFitsner/create-react-app/build/1.0.24), [3](https://ci.appveyor.com/project/darrenscerri/create-react-app/build/1.0.23/job/0jiu3ql9k0kal9jm), [4](https://ci.appveyor.com/project/Facebook/create-react-app/build/1.0.102/job/fajf166mvjiqaqeo)).

Noticed some issues are already open here, but all seem to be mentioning yarn, as npm should handle concurrent installs just fine.

Having said this, it might also be a memory issue (https://github.com/lerna/lerna/issues/338).

**Comment by rayrutjes** [comment]
I've experienced random failures as well with Yarn as NPM client.
Even when not running in CI.
In general, lerna clean && learn bootstrap solves the issue.

**Comment by evocateur** [comment]
The yarn failures are likely due to issues discussed in #671.

I wonder if this is an issue specific to create-react-app, or merely exacerbated by the amount of installing going on in a project like it? My gut-feeling is the latter, and would be consistent with an underlying root-cause of memory problems.

I've got a few ideas to mitigate some of the memory issues (chiefly: use `child_process.spawn` instead of `child_process.exec`), but it'll likely be awhile before we're able to address them directly.
