### ISSUE TITLE
Provide safe way of reducing version spam

### ISSUE THREAD

**Issue by garthk** [lerna/lerna#718]
Further to #706 and #707, I'd like to safely reintroduce the lifestyle improvement of the-option-previously-known-as-only-explicit-updates but with a mechanism to prevent unwanted gun-foot interaction.

Out of scope: we can't possibly solve _all_ "that package wasn't ready to be published" problems.

If `A@1.0.0` depends on `B@^1.0.0` and `B` changes, I'd like to publish a new `B@1.0.1` without updating `A/package.json` at all.

If the user signals a breaking change for `B` by giving it version `B@2.0.0`, however, I'd like to prompt the user for a new version for A as well and update `A/package.json` to reflect its new version and the new semver range for its dependency on `B`. I trust we can provide the users with sufficient feedback to avoid some of the woe in #707.

This won't require any re-prompting if we follow the dependency graph from leaves to roots. Perhaps this is a solved problem, but it doesn't seem so in beta 38.

## Expected Behavior

Regardless of options:

* Do not prompt for a package until prompting for all its dependencies

If I provide `--bump-only-when-forced` then, for each unchanged A depending on changed B:

* If B's version is still in range for A's dependency on it, treat A as not having changed
* If B's version is no longer in range for A's dependency on it, warn the user and treat A as having changed

Result:

* Lerna will prompt for fewer version-only changes
* Lerna will still ensure all dependencies can be resolved as declared

## Current Behavior

* If you do not provide the-option-that-must-not-be-named, Lerna will publish "new" versions of packages with dependencies when nothing changed, confusing some users and developers 
* If you do provide the-option-that-must-not-be-named and specify a new version that breaks a dependency, [pain will ensue](http://dumpsterfi.re) as mentioned in #707 

## Possible Solution

Bump versions when you need to. Don't bump versions when you don't need to. A dependency no longer matching the version range in your `package.json` is a great reason to bump a version. A dependency changing but still matching the version range in your `package.json` might not be.

**Comment by garthk** [comment]
Turns out, I more or less asked already in #472.

**Comment by smrq** [comment]
This is more important now that `--only-explicit-updates` has been removed, which was previously a viable workaround when publishing patch changes.

**Comment by evocateur** [comment]
With increasing adoption of `yarn` and soon always-on shrinkwrapping in `npm` (apps should already always shrinkwrap their dependencies), how would you indicate they should upgrade dependent `A` to pick up a bugfix in transitive `B` if you don't bump `A`'s version? From the perspective of `npm outdated` when using a lockfile (`yarn.lock` or `npm-shrinkwrap.json`), _not_ bumping `A` means there is no awareness of the need to upgrade.

So I guess I'm pretty skeptical we can account for _all_ of the edge cases, and pretty confident it would be a never-ending bug farm. I consider the "cost" of new patch versions (registry bloat?) to be basically nil compared to their benefits (less footguns, more change awareness, simpler code paths, less bugs).

**Comment by smrq** [comment]
Using a lockfile means that you have less churn in versions of dependencies, which is a protection against the fact that developers are fallible and don't always signal breaking changes (no matter how small) with a corresponding major bump.  (If we got it right all the time then there would be no need for lockfiles.)

If dependent `A` gets a new version every time dependency `B` is updated (and repoints its dependency to require at least that version of `B`), then in order to pick up *real* changes to `A` you automatically must pick up all changes to `B` as well, whether you want them or not.  This means that the surface area for semver errors extends through the entire dependency graph of `A`, defeating the purpose of having a lockfile.

**Comment by garthk** [comment]
I can't strongly enough emphasise @smrq's comment above. Bumping a package's version whenever one of its dependencies changes has harmful side-effects many of us would like to avoid.

Yes, sometimes it's important to change your dependency from `^1.0.1` to `^1.0.2` to indicate that you _need_ that bug fix. When you do so, you must bump your own patch.

No, that one situation in which you should update your dependency doesn't mean you must always update your dependency.

**Comment by rcline** [comment]
I too am having problems adapting to the consistent updating of dependency minor and patch versions in package.json files.  And though I agree that "Versions are cheap", the fallout of not letting semver ranges pull in the correct version is non-trivial developer time spent keeping everything up-to-date.

Has anyone move past this in some way that has not been said in thread?

Thank you all!

**Comment by bertho-zero** [comment]
I think that when you have versions that are satisfied by the semver, we can only update the `package-lock.json` or the `yarn.lock`. Why not with an option?

As if we were doing `yarn upgrade package` instead of `yarn upgrade package@^1.0.1`.

**Comment by evocateur** [comment]
Yarn’s behavior when upgrading is irrelevant in this context.

**Comment by bertho-zero** [comment]
Why ? It updates the package in the semver's range without updating the package.json, which would avoid version spam while keeping the versions up to date, package-lock.json and yarn.lock too. It's a behavior like that we're looking for.

**Comment by evocateur** [comment]
There are several threads that already explain the reasoning in detail. #707 is one of the bigger ones.

**Comment by bertho-zero** [comment]
I have already read this thread and the reasons mentioned do not concern me in my case. This option is necessary and would not necessarily make my installation dirty.

By keeping the package-lock.json, yarn.lock and symbolic links up to date, I do not see any reason why my installation could be dirty.
The packages would all be up to date with dependencies that are also up to date, symbolic links updated as well, but not published versions just because one of these dependencies is updated with a patch version.

In addition package-lock.json, yarn.lock are ignored for dependencies, so in any case the last versions would be used if I just published a patch version of this dependency.

The only thing that could have concerned us in my company is the problem mentioned in the thread you just shared, which is: npm2 can have problems with deduping. But we do not use npm.

In my case, the only thing annoying is version spam, the choice could at least be left to the developers.

**Comment by bertho-zero** [comment]
```
Changes:
 - @openagenda/activities: 2.0.12 => 2.0.13
 - @openagenda/activity-apps: 1.0.23 => 1.0.24
 - @openagenda/agenda-locations: 1.0.31 => 1.0.32
 - @openagenda/agendas: 1.0.13 => 1.0.14
 - @openagenda/bs-templates: 2.0.52 => 2.0.53
 - @openagenda/event-search: 1.1.24 => 1.1.25
 - @openagenda/events: 1.1.16 => 1.1.17
 - @openagenda/flat-exports: 1.1.14 => 1.1.15
 - @openagenda/form-schemas: 1.1.11 => 1.1.12
 - @openagenda/inbox-apps: 1.0.54 => 1.0.55
 - @openagenda/inboxes: 1.0.36 => 1.0.37
 - @openagenda/labels: 2.0.54 => 2.0.55
 - @openagenda/member-apps: 1.0.26 => 1.0.27
 - @openagenda/surveys: 1.1.22 => 1.1.23
 - @openagenda/translators: 1.0.5 => 1.0.6
```

`lerna publish` create all these versions for only one small change in `@openagenda/labels` which actually only concerns one other repo, why would I be obliged to publish all these versions?

A publication of `@openagenda/labels` and an update of the differents `yarn.lock` is sufficient in this case (if the @openagenda/labels version satisfies the differents package.json requirment).

As said in these comments (https://github.com/lerna/lerna/issues/706#issuecomment-288232324 & https://github.com/lerna/lerna/issues/706#issuecomment-288234225):

- > we had lots of pkgs and lots of dependencies where all of them were already using ^ so there was no reason to update all packages.

- > We never make major version bumps.

**Comment by evocateur** [comment]
@bertho-zero Presumably because all of those packages have a dependency on `@openagenda/labels`. "One other repo" is irrelevant, as it constitutes a change for all of the dependents.

To summarize (yet again (and again (and again))), the failure modes of "rely on ^ ranges and don't bump transitive dependents" are insidious, almost impossible to predict, and difficult to recover from. Babel is a special case, and the maintainers themselves recognized the error of the previous option.

The "annoying version spam" isn't for the sake of the developer, it's for the consumers. If a breaking change is inadvertently released as a patch (it happens, we're only human), but only to a transitive dependency, how does anyone using a lockfile know that they should upgrade? When their code breaks? If you're not using a lockfile, you've already accepted the risk of non-deterministic breakage, and the "annoying version spam" is irrelevant.

**Comment by bertho-zero** [comment]
@evocateur In my case, there are only changes in `@openagenda/labels`, the next patch version will always be installed in the other packages with `^` in the package.json files and the lockfile upgraded, or the package linked.

If the package is in the package.json with a version that starts with `^` (`"@openagenda/labels": "^2.0.0"`) then the patch version, if it exists, will be installed anyway (`2.x.x -> 2.0.55`).
For the transitive dependencies the lockfiles is not used.
If the version is voluntarily maintained at 2.0.54 without `^` in a package.json it is a choice.

> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

_https://docs.npmjs.com/files/package-lock.json#description_

In a project, if the lockfile is not updated then the latest version will not be installed and if it is updated the repo should be tested.

If a bug comes we can fix the version to the previous one and debug.

It is possible that only `@openagenda/labels` is updated.
