### ISSUE TITLE
Lerna is checking tags in wrong registry (npmrc vs package.json#registry)

### ISSUE THREAD

**Issue by mAAdhaTTah** [lerna/lerna#722]
We have a private registry hosted on Artifactory, which is configured to also provide us a backup cache of packages (really helpful when npm goes down, like the DNS attack not long ago) as well as hosting private packages. Each package has, in package.json#registry, a "local" npm registry, and in npmrc, a "virtual" npm registry, which serves packages from both the local registry (for private packages) and a cache registry (for public packages).

When I went to publish today, the publish itself appears to have been successful, but got a bunch of errors at what I believe is a post-install tag check. The problem is Lerna is checking for those tags against the "virtual" registry (in the npmrc) rather than the "local" registry (in the package.json). The virtual registry does not support checking `dist-tags` for local packages; the check needs to be made against the "local" registry in package.json#registry.

Every package has its own package.json & .npmrc file pointing to the appropriate registries.

Let me know if you need more information, but I think that covers it. I cleared out most of the template after ensuring the above description covers everything.

## Your Environment
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-beta.38 |
| `npm --version`  | 4.1.2 |
| `node --version` | v7.7.4 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
You meant [`publishConfig.registry`](https://docs.npmjs.com/files/package.json#publishconfig) in package.json, correct? I'm not aware of a root-level `registry` property.

```json
  "publishConfig": {
    "registry": "http://my-awesome-registry.com"
  },
```

In any case, that's what npm uses when publishing, and only falling back to the `.npmrc` registry when publishConfig.registry doesn't exist. That's why the publish half-worked for you. As near as I can tell, the `.npmrc` value is the one that is propagated into the env var that we are passing through.

Are you using the `--registry` flag of `lerna publish`, by any chance?

**Comment by mAAdhaTTah** [comment]
@evocateur Yes, that's correct, my mistake.

No, I'm not using the `--registry` flag. It publishes to the correct registry, it fails at what appears to be a post-publish verification step.

**Comment by evocateur** [comment]
I don't suppose you can convince the Artifactory folks to fix their bug? A "virtual" registry that serves both public and private packages that _doesn't_ understand how to deal with dist-tags is pretty broken, imo.

Personal opinions aside, passing `--registry=<url>` explicitly to `lerna publish` (or via `lerna.json` config such as `command.publish.registry`) is one way to work around this. It will use that value instead of anything provided by `.npmrc` or `publishConfig.registry` for all `npm` commands.

```json
{
  "lerna": "2.0.0-beta.38",
  "command":
    "publish": {
      "registry": "<URL>"
    }
  },
  "version": "1.0.0"
}
```

Focusing the config to `publish` only allows using the `.npmrc`-based virtual registry when running `lerna bootstrap`, the only time we run `npm install`.

**Comment by mAAdhaTTah** [comment]
Yeah... It returns a 400 error and tells you to check the local registry :/ – but I doubt I can get them to fix their setup.

I'll add that to my `lerna.config` and close this if it resolves the issue.

**Comment by noherczeg** [comment]
@mAAdhaTTah We are having difficulties with Nexus3 and NPM as well. Sadly as days pass I'm getting more and more convinced that these tools are not complete yet.

**Comment by wizardzloy** [comment]
@noherczeg `--skip-temp-tag` flag does the trick

**Comment by mAAdhaTTah** [comment]
Adding the registry to the lerna.json worked without errors. Is there a way to make `--skip-temp-tag` the default? I'm not sure what the purpose of that is or why/if it's necessary.

**Comment by evocateur** [comment]
Yes, that should be the default, I agree. I believe @hzoo has already opened an issue to that effect.

**Comment by hzoo** [comment]
yeah https://github.com/lerna/lerna/issues/742

it was "necessary" because we didn't publish in topologicial order (although now we realize it didn't help for proxies/3rd party npm registries

**Comment by mAAdhaTTah** [comment]
Great, subbed to that issue. Closing this one, cuz the main issue here is resolved by adding the `command.publish.registry` to my `lerna.json`.
