### ISSUE TITLE
[new feature] examples directory similar to packages

### ISSUE THREAD

**Issue by veeramarni** [lerna/lerna#800]
If we want to write examples for the packages, would it be clean to have an `examples` directory? The idea is to use hoisted external dependencies that installed at repo root but uses the released packages from npm instead of symbolic link.

```
my-lerna-repo/
  package.json
  examples/
    example-1/
      package.json
    example-2/
      package.json
  packages/
    package-1/
      package.json
    package-2/
      package.json
```

**Comment by evocateur** [comment]
Why not just add another glob to the `packages` list in `lerna.json`? That's definitely supported, and gets you everything you want (with the added benefit of keeping version pins up-to-date in the examples (whose package.json files you would simply add `"private": true` to avoid publishing)).

Everything except "install released packages from npm instead of symbolic link", that is. Why is that important in this context?

```json
{
  "lerna": "2.0.0-rc.4",
  "packages": [
    "examples/*",
    "packages/*"
  ],
  "version": "1.0.0"
}
```

**Comment by veeramarni** [comment]
@evocateur thanks for the update, I will give it a try. Well, the reason having a released packages vs. symbolic link is the symbolic link will break the examples if the current packages are under active development. But that is not a big issue to us now but if it is supported in future would be great.

**Comment by azu** [comment]
https://github.com/almin/almin is actual case for this issue.
This monorepo use following config:

```json
{
  "lerna": "2.0.0-rc.4",
  "commands": {
    "publish": {
      "ignore": [
        "example-*",
        "perf-*",
        "*.md"
      ]
    }
  },
  "packages": [
    "packages/*",
    "examples/*",
    "perf/*"
  ],
  "npmClient": "yarn",
  "version": "independent"
}
```

**Comment by evocateur** [comment]
Aside from the extra packages location, which is quite common and totally supported, I don't see the other request for "released packages of sibling dependencies instead of symlinks" happening. If you want examples to use released packages, don't add the `examples` directory as a lerna-managed target, and things will "just work".
