### ISSUE TITLE
[feature] Local hoisting targets

### ISSUE THREAD

**Issue by bigtimebuddy** [lerna/lerna#804]
Not sure if other people would find a use for this, but in our project we bumped into the issue of needing to hoist to one of our local packages, instead of to the root-level. The real reason is that we're testing on embedded hardware where we need to periodically sync in order to test. For this reason we cannot hoist to the root-level and using no hoisting bloats our memory footprint. I understand that this might be an unusual edge-case. But humor me for a minute...

For instance, here are the packages:

* **packages/parent**
  * node_modules/child1 -> ../child1
  * node_modules/child2 -> ../child2
  * node_modules/child3 -> ../child3
* **packages/child1**
  * node_modules/lodash
* **packages/child2**
  * node_modules/lodash
* **packages/child3**
  * node_modules/lodash

In this case **parent** has linked dependencies of **child1**, **child2** and **child3**. And these child packages all share a common dependency, let's say **lodash**. So instead of 3 versions of **lodash**,  we'd get 1 in the **parent** package.

* **packages/parent**
  * node_modules/child1 -> ../child1
  * node_modules/child2 -> ../child2
  * node_modules/child3 -> ../child3
   * node_modules/lodash
* **packages/child1**
* **packages/child2**
* **packages/child3**

Instead of hoisting to the root-level, it would be nice to configure hoisting-like capability for a specified package or packages. `lerna bootstrap --hoist --hoist-targets=parent`

There's complexity in this approach and maybe the juice might not be worth the squeeze. But thought I'd throw it out there. Also, open to other suggestions! 

Thanks for creating a great tool.

**Comment by evocateur** [comment]
I am open to changing the hoist target to "closest common directory," which in your example (and indeed the default `packages` location) would be `packages/node_modules`. As @gigabo pointed out in earlier discussions, sometimes "closest common directory" _is_ the root, but at least there would be some wiggle room for cases like yours.

However, the `--hoist-targets` solution as proposed would actually break all the children who depend on lodash, since `node_modules` resolution is always done with fully-resolved paths, not the symlink paths (and thus, none of the children in this example would have access to `../parent/node_modules/lodash`).

**Comment by akosyakov** [comment]
@evocateur Could such simple solution work:
- hoist dependencies not to the root but a directory that does not participate in node module resolution for local packages;
- link all dependencies, including transitive, of local packages to this directory

Since node resolution follows symlinks and resolves from the linked location:
- everything should be properly resolved via `hoist/node_modules`
- at the same time, local packages **cannot** directly access all hoisted packages as now, but only declared in `package.json` and their transitive dependencies

E.g:
- project
  - lerna.json
  - hoist
    - node_modules
      - dep1
      - dep2
      - dep3 **the transitive dep of dep2**
    - yarn.loc
  - packages
    - foo
      - node_modules
        - dep1 -> ../../../lerna/node_modules/dep1
    - bar
      - node_modules
        - dep2 -> ../../../lerna/node_modules/dep2
        - dep3 -> ../../../lerna/node_modules/dep3 **transitive**
    - baz
      - node_modules
        - foo -> ../../foo
        - baz -> ../../baz
        - dep1 -> ../../../lerna/node_modules/dep1 **transitive**
        - dep2 -> ../../../lerna/node_modules/dep2 **transitive**
        - dep3 -> ../../../lerna/node_modules/dep3 **transitive**
