### ISSUE TITLE
[feature request] lerna bootstrap triggering root postinstall hook

### ISSUE THREAD

**Issue by Andarist** [lerna/lerna#866]
Im not sure if this makes sense, as the intention for having root `package.json` like this is unclear from the docs:
```js
lerna-repo/
  packages/
  package.json
  lerna.json
```
however its respected during the bootstraping so I think it makes sense to execute (after [this line](https://github.com/lerna/lerna/blob/4fe341fa65bec76d3d258ea4b8060e40be79f901/src/commands/BootstrapCommand.js#L96)?) `postinstall` script. 

If you think its the right thing to do, I can provide PR for it.

Also if you provide short explanation of how combination of per package `package.json`s and root `package.json` should work together it would be really helpful

**Comment by evocateur** [comment]
The root `package.json`, at the very least, is how you install `lerna` locally during a CI build. And, generally, where you place your testing and linting tools, which you run from the root instead of each package (slowly and repetitiously). The root can also hold all the "hoisted" packages, which speeds up bootstrapping when using the `--hoist` flag.

`postinstall` is a really odd lifecycle, considering it is [kinda-sorta deprecated](https://docs.npmjs.com/misc/scripts#best-practices) (its siblings `preinstall` and `install` are explicitly called out, anyway).

I don't think it's really appropriate for lerna to artificially call `npm run postinstall` on a `package.json` that it is not explicitly managing. You can always add the root as a managed location (in the `packages` array of `lerna.json`), which _would_ then run postinstall along with the others.

**Comment by Andarist** [comment]
Thanks for the answer!

> And, generally, where you place your testing and linting tools, which you run from the root instead of each package (slowly and repetitiously).

Yeah, scripts were obvious - I was more buffled by dependencies.

> The root package.json, at the very least, is how you install lerna locally during a CI build. 

hm, aint sure then how to configure this correctly - i mean if i just run `yarn` or `npm install` as my dependency task, it will install my root deps, including lerna, so i will basically need to run `lerna bootstrap` as some sort of the postinstall task

> The root can also hold all the "hoisted" packages, which speeds up bootstrapping when using the --hoist flag.

cool, dependency entries needs to be 'hoisted' manually, right?

**Comment by evocateur** [comment]
Yes, "manual" hoisting is currently the safest way to make `lerna bootstrap` super quick.

If you're hoisting, it's currently unsafe to put `lerna bootstrap` in the `postinstall` of the root package.json, as `lerna bootstrap --hoist` runs `npm install` in the root first, thus triggering an endless cycle.

However, you've presumably got other commands, like `npm test` and the like. You can either run an additional script in the root that calls `lerna bootstrap`, or call it from a "pre"-lifecycle hook, like "pretest" or "prebuild".

```json
{
  "name": "my-monorepo",
  "private": true,
  "devDependencies": {
    "eslint": "^3.19.0",
    "jest": "^20.0.4",
    "lerna": "^2.0.0-rc.5"
  },
  "scripts": {
    "bootstrap": "lerna bootstrap --hoist",
    "pretest": "npm run bootstrap && eslint packages",
    "test": "jest"
  }
}
```

With this root, `npm install && npm test` would be sufficient to ensure bootstrap is always run when needed.

**Comment by Andarist** [comment]
so basically it means that on CI there should be 2 dependency tasks, for CicleCI it could look like this
```yml
dependencies:
  override:
    - yarn
  post:
    - npm run bootstrap
```

**Comment by evocateur** [comment]
@Andarist Wonderful, thanks!

**Comment by rcchen** [comment]
> And, generally, where you place your testing and linting tools, which you run from the root instead of each package (slowly and repetitiously).

I've also experienced this in practice (10x difference between running from root vs. `lerna run test` and having it proxied out to packages) but don't fully understand why it is happening, would either of you guys be able to help me understand? :)

**Comment by wbern** [comment]
While it's not completely clear to me if this thread wants to address the issue of having to run 2 separate commands for a locally development-ready environment or not, I wanted to contribute with the below solution.

package.json
```
  ...
  "config": {
    "envs": "node_modules='$INIT_CWD/node_modules'"
  },
  "scripts": {
    "postinstall": "node ./scripts/bootstrap.js",
    "bootstrap": "cross-env $npm_package_config_envs lerna bootstrap --hoist",
    ...
```

./scripts/bootstrap.js
```
#!/usr/bin/env node

var cp = require('child_process');
var os = require('os');

var npmCmd = os.platform().startsWith('win') ? 'npm.cmd' : 'npm';

const runCommand = function(command, args, options = {}) {
    console.log(
        'EXECUTING COMMAND:',
        npmCmd,
        args.join(' '),
        '( path:',
        options.path || process.cwd(),
        ')'
    );
    const { error, statusCode } = cp.spawn(npmCmd, args, {
        env: process.env,
        cwd: options.path,
        stdio: [
            process.stdin,
            process.stdout,
            options.ignoreErrors ? 'ignore' : process.stderr,
        ],
    });

    if (statusCode !== 0 && options.ignoreErrors) {
        console.warn('Command had errors, but ignoring.');
        console.error(error);
    }
};

const alreadyExecuted = process.env['LERNA_EXECUTED'];

if(!alreadyExecuted) {
    process.env['LERNA_EXECUTED'] = true;
    runCommand(npmCmd, ['run', 'bootstrap'], { });
}
```

Any developer can do `npm install`, and the following will/should happen.

1. `npm install` runs as per usual process
2. `postinstall` hook triggers, executing bootstrap.js
3. `bootstrap.js` executes, which checks if `LERNA_EXECUTED` is set. If not set, does `npm run bootstrap`
4. `npm run bootstrap` will run lerna, which (with hoisting) implies another npm install being done.
5. Upon completion by lerna, _another_ `postinstall` hook triggers, which again executes `./scripts/bootstrap.js`
6. `bootstrap.js` will this time recognize that `LERNA_EXECUTED` is set to `true`, and will gracefully exit.
7. When script execution is finally over, `LERNA_EXECUTED` will again become empty (ie `echo $LERNA_EXECUTED` in the shell will return an empty string)

Tested with:
npm: 5.6.0 (package-lock.json-files enabled)
node: 8.11.3 (LTS by current writing)

This will ease transition to lerna for me and my colleagues.
Since I just discovered this, I will get back if we find any issues. The only real downside now is that you need to run a regular `npm install` before lerna does it again. On the other hand, we have listed `lerna` as a local dependency, so it would not be possible for lerna to execute without the initial installation.
