### ISSUE TITLE
Suggested development flow?

### ISSUE THREAD

**Issue by steezeburger** [lerna/lerna#878]
I'm developing packages in tandem that rely on each other, and I keep getting 404s when trying to install a dependency that is contained in my repo.

What is the suggested flow for working on these packages in tandem with other teammates?

imagine packages structure like:
/team-components
/team-app-generator

I ran `lerna bootstrap` then tried `npm install team-components` inside team-app-generator but keep getting 404s because it's trying to hit NPM. I made sure the version numbers match, so I don't think this is what's happening. I'm not sure if I'm doing something out of order or if there's an issue with Lerna.

Edit: so it looks like it does actually look to `team-components` when I do an import, but it's not in the package.json. For packages that will never be published to NPM and only used within this repo, do I not need to make sure they're in the package.json?

Edit2: removing the packages from the package.json caused issues. Now I'm a bit confused. After running lerna bootstrap, I can npm install some packages (it installs with an @security tag, is this how Lerna connects to my local package? or is this because these were accidentally published to NPM and then removed, so NPM installs with the security tag?), but am still getting a 404 for the team-components package, which was setup the same way as the other packages that are installing.

**Comment by evocateur** [comment]
If you're never going to publish a given package, make sure you set `"private": true` in its package.json. It will then be available to link during bootstrap, but in this case (for public packages), you really shouldn't be depending on a private package as that fundamentally breaks any consumer.

If you're not publishing _any_ of these packages, I would strongly advise against using lerna. Just use a single package.json and a reasonable directory structure.

When using lerna, you do not (generally) run `npm install` anywhere except the root of the repo (wherever `lerna.json` and the `package.json` sibling that holds the common `devDependencies` + test/lint scripts lives). `lerna bootstrap` is the way you install things in the managed packages. The association of "sibling" packages (subdirectories of `./packages`, by default) is matched by package name (_not_ strictly the directory name, but whatever is in the `name` property of `./packages/${package_name}/package.json`) _and_ `semver`-satisfying version range.

Given this structure:
```
.
├── lerna.json
├── package.json
└── packages
    ├── package-1
    │   └── package.json
    └── package-2
        └── package.json
```
With these `package.json`s under `packages`:

```json
{
  "name": "@my-scope/package-1",
  "version": "1.0.3",
  "dependencies": {
    "foo-bar-package-2": "^0.1.5"
  }
}
```

```json
{
  "name": "foo-bar-package-2",
  "version": "1.1.0",
  "dependencies": {
    "@my-scope/package-1": "^1.0.0"
  }
}
```

The following things should happen during `lerna bootstrap`:
1. `./packages/package-1` is symlinked into `./packages/package-2/node_modules/@my-scope/package-1`
2. `foo-bar-package-2@0.1.5` is _not_ symlinked into `./packages/package-1/node_modules/...`, but instead installed from npm (because the semver range does not satisfy the _current_ repo version of `@my-scope/package-1`, which is 1.0.3)

Does that make sense?

**Comment by Reinmar** [comment]
I tried to use Lerna with not-yet published packages and it didn't work. I get the same error with and without `"private": true`.

This is my package:

```json
{
  "name": "@ckeditor/ckeditor5-foo",
  "private": true,
  "version": "0.0.1"
}
```

And this is some other package requiring it:

```json
{
  "name": "ckeditor5",
  "version": "1.0.0-alpha.2",
  "dependencies": {
    ...
    "@ckeditor/ckeditor5-foo": "*",
  }
}
```

When I try to use `lerna bootstrap` I get:

```
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm install
lerna ERR! npm ERR! code E404
lerna ERR! npm ERR! 404 Not found : @ckeditor/ckeditor5-foo
lerna ERR! npm ERR! 404
lerna ERR! npm ERR! 404  '@ckeditor/ckeditor5-foo' is not in the npm registry.
lerna ERR! npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
lerna ERR! npm ERR! 404
lerna ERR! npm ERR! 404 Note that you can also install from a
lerna ERR! npm ERR! 404 tarball, folder, http url, or git url.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/p/.npm/_logs/2017-12-14T12_47_26_000Z-debug.log
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
(node:78434) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Command failed: npm install
npm ERR! code E404
npm ERR! 404 Not found : @ckeditor/ckeditor5-foo
npm ERR! 404
npm ERR! 404  '@ckeditor/ckeditor5-foo' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I need to be able to work with packages which are not yet published for instance when we're starting their development. Right now I need to publish their `0.0.1` version right after creating the package to satisfy Lerna. This is problematic because such a package isn't functional yet and might actually never be (if this is some research, fo instance).

**Comment by Reinmar** [comment]
I've checked that v2.5.1 gives the same result.

**Comment by evocateur** [comment]
The dependency range in the consumer cannot be `*`, it must match the private package. Also, a private local package should never be in `dependencies` of a published package, as that will break when anyone tries to install the published package.

**Comment by Reinmar** [comment]
Hi again!

I've stumbled upon this again. I tried to bootstrap a project which has this in the root `package.json`:

```json
  "dependencies": {
    "@ckeditor/ckeditor5-font": "0.0.1",
  }
```

And `@ckeditor/ckeditor5-font`'s `package.json` looks like this:

```json
{
  "name": "@ckeditor/ckeditor5-font",
  "version": "0.0.1",
  "private": true
}
```

`lerna bootstrap` logs this, unfortunately:

```
lerna info hoist Installing hoisted dependencies into root
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm install
lerna ERR! npm ERR! code E404
lerna ERR! npm ERR! 404 Not found : @ckeditor/ckeditor5-font
lerna ERR! npm ERR! 404
lerna ERR! npm ERR! 404  '@ckeditor/ckeditor5-font' is not in the npm registry.
lerna ERR! npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
lerna ERR! npm ERR! 404
lerna ERR! npm ERR! 404 Note that you can also install from a
lerna ERR! npm ERR! 404 tarball, folder, http url, or git url.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/p/.npm/_logs/2018-02-14T16_30_11_944Z-debug.log
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
{ Error: Command failed: npm install
npm ERR! code E404
npm ERR! 404 Not found : @ckeditor/ckeditor5-font
npm ERR! 404
npm ERR! 404  '@ckeditor/ckeditor5-font' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p/.npm/_logs/2018-02-14T16_30_11_944Z-debug.log

    at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'npm ERR! code E404\nnpm ERR! 404 Not found : @ckeditor/ckeditor5-font\nnpm ERR! 404 \nnpm ERR! 404  \'@ckeditor/ckeditor5-font\' is not in the npm registry.\nnpm ERR! 404 You should bug the author to publish it (or use the name yourself!)\nnpm ERR! 404 \nnpm ERR! 404 Note that you can also install from a\nnpm ERR! 404 tarball, folder, http url, or git url.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/p/.npm/_logs/2018-02-14T16_30_11_944Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm install',
  timedOut: false,
  exitCode: 1 }
```

How can I force Lerna to not try to look for this package on npm? For the development purposes only I need to somehow work with it locally, before publishing it on npm.

**Comment by evocateur** [comment]
Why does your root package have local dependencies? Is it _also_ published? (I don’t recommend publishing your root package, btw)

If it isn’t, just use a local file specifier (`file:packages/my-package-directory`) and npm5 will do the right thing.

**Comment by Reinmar** [comment]
> Why does your root package have local dependencies? Is it _also_ published? (I don’t recommend publishing your root package, btw)

This one isn't but some consumers may also be published. But, as I wrote, I need this for development purposes. It's a temporary state required when I'm bootstrapping such a package. And I don't publish a new version of the consumer (with added dependency) before publishing the dependency first.

> If it isn’t, just use a local file specifier (`file:packages/my-package-directory`) and npm5 will do the right thing.

Npm did, but Lerna didn't. It didn't symlink this package.

**Comment by Reinmar** [comment]
Our community stumbles upon these not-yet-completed packages and people are confused about them (see https://stackoverflow.com/questions/48943719/how-to-install-plugins-in-ckeditor-5). Is there something we could do? Would you be interested in accepting a PR if we changed this in Lerna? If yes, how should we approach this?

**Comment by evocateur** [comment]
A reproduction would go a long way toward diagnosing the actual issue.

**Comment by jodator** [comment]
Hi. I've created a simples Lerna repo that illustrates that issue: https://github.com/jodator/lerna-878. Basically it boilds down to the fact that main `package.json` requires sub-package and Lerna is doing `npm install` before hoisting packages from `./packages`. /cc @Reinmar .

**Comment by Reinmar** [comment]
Just to make sure, @jodator, what are the steps to reproduce this? And which of these packages are published? Also, does using `private: true` help?

**Comment by jodator** [comment]
Just do `lerna bootstrap` in main directory.

Adding `private: true` does not help.

**Comment by Reinmar** [comment]
I've just realised that this problem doesn't exist when there's a dependency between e.g. `packages/foo` and `packages/bar` (not published). That works fine (at least with lerna@2.11.0). What didn't work was when `.` package has depends on `packages/bar` (not published). I didn't check with lerna@3 yet, though.

**Comment by evocateur** [comment]
@Reinmar A "rooted leaf" (lerna.json `"packages": [".", ...]`) is generally not a good idea with lerna for a variety of reasons, this problem (`lerna bootstrap --hoist`) included.

**Comment by Reinmar** [comment]
Hm..., that's a pity, cause it's quite useful when the root has some dependencies too. This allows us to install or clean all at once (with a single `lerna bootstrap|clean` call) and of course, allows us to use those packages which we're developing as dependencies of the root project. For instance, we keep the documentation in the root project. The demos in the documentation import code from packages that we're developing in `packages/` using normal module names. That's a really clean setup and worked well over the last two years (except this issue discussed here, but it isn't a blocker).

Is the "root leaf" something that will definitely not be fully supported due to some problems that it brings? Or is it something doable?

**Comment by evocateur** [comment]
I would really like to remove support for it, to be quite frank. It's generally nothing but problems for _very_ little gain. If I get around to it, I won't remove it until the next major.

Use [relative `file:` specifiers](https://github.com/npm/cli/blob/latest/doc/spec/file-specifiers.md) (just like lerna itself does) and you can completely ignore `lerna bootstrap` and `lerna clean`. Run `lerna link convert` once, and a single `npm ci` in the root is all that is necessary.

**Comment by Reinmar** [comment]
Thanks, we'll check that.

**Comment by borekb** [comment]
Hi, I might be encountering the same challenges, also related seems #720.

I'm already using `file:` specifiers to inter-link local packages as suggested above. The simplest example of my setup is a monorepo with two packages, `app` and `lib`, where `app` depends on `lib`:

```
{
  "name": "app",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "lib": "file:../lib"
  }
}
```

This is also also the only way to make plain `yarn` work. If the dependency was `"lib": "^1.0.0"`, Yarn would fail as that package is not published.

So far so good but but running `lerna bootstrap` doesn't seem to symlink `lib` into app's `node_modules`. I also tried `lerna link`, with the same result. First I thought I encountered some bug in Lerna as it's still not apparent to me why `file:` dependencies would be treated differently but now I'm not sure.

I don't think we're doing anything too weird, `file:` specifiers are a natural way to link unpublished dependencies and I hope they could be supported by Lerna one day :)

**Comment by evocateur** [comment]
@borekb Your problem is using Yarn. Don't do that, imo. You can't use `file:` specifiers with Yarn; if you insist on Yarn, switch to workspaces instead of `lerna bootstrap`.

**Comment by borekb** [comment]
> You can't use `file:` specifiers with Yarn

You mean that Lerna doesn't support it or that Yarn doesn't support it?

I'd consider `npm` but Lerna doesn't work with that either: #1679.

**Comment by evocateur** [comment]
Yarn literally does not support `file:` specifiers. Trust me when I say npm handles this 100% fine, otherwise I wouldn't be able to publish new versions of Lerna itself.

**Comment by ErisDS** [comment]
I have, I think, a similar workflow problem - happy to raise a new issue if preferred?

 I am using `yarn`, I am not using a "rooted leaf".

Use case - I have an existing package `foo`, and I'm creating some new functionality that `foo` will depend on in `bar`. 

Problem - there doesn't seem to be a good workflow for adding inter-dependent packages without publishing them that doesn't result in a broken package.

How I'm reproducing:

- run `lerna init --independent`
- make a new package `foo` that console.logs "hello world"
- make a new package `bar` that has a function that returns "hello world" we want to use instead of the string
- you're not ready to publish just yet, you want to update `foo` to use` bar` first

What I expected to need to do:
- `lerna add bar foo` -> this results in a 404 because it wants to add from yarn

Alternative approach:
- require('bar') in foo without adding it to the package.json,
- use bar(), test it all works and it does :tada:
- then run `lerna publish` command works without failing
- `foo` package errors because the `bar` dependency is missing

Am I missing something?

**Comment by doug-wade** [comment]
@ErisDS it should work if you edit foo's package.json directly to reflect the dependency.

**Comment by ErisDS** [comment]
@doug-wade That comment feels very dismissive. I could also manually edit package.json files to manage the whole repository, but I don't, I use lerna.

The tagline for lerna is:

> Lerna is a tool that optimizes the workflow around managing multi-package repositories with git and npm.

I believe my workflow is fairly standard, editing the package.json file manually is not an optimized workflow.

Meanwhile in the docs for [lerna add](https://github.com/lerna/lerna/tree/master/commands/add#readme) it reads:

> Add local or remote package as dependency to packages in the current Lerna repo.

There is no mention of a restriction to packages that have already been published. 

Further still, lerna does help me to work with the new package - as I don't actively _have_ to add it to package.json. In that case lerna will publish a broken package, without any warning.

Either this is a bug, or an overlooked workflow or perhaps I'm missing something fundamental about what lerna is for.

**Comment by ErisDS** [comment]
Should I raise a new issue?

**Comment by ggascoigne** [comment]
I should say that using yarn I've never found that `lerna bootstrap` ever links anything, but that `lerna link --force-local` works reliably as a work around.

**Comment by evocateur** [comment]
If you're using Yarn you might as well use [workspaces](https://www.yarnpkg.com/blog/2017/08/02/introducing-workspaces/).

If `lerna add` isn't recognizing the local package, an isolated reproduction would be appreciated.

**Comment by revelt** [comment]
hi all, should we close this issue? It seems this issue became stale and all questions seems to be addressed...

**Comment by ErisDS** [comment]
I still have this problem every time I create a new module inside a mono-repo.

**Comment by revelt** [comment]
@ErisDS hm... when I create a new module, I manually add a new entry in the package(s) that will consume it, then I run an update on everything (https://www.npmjs.com/package/update-versions), wipe (`rm -rf node_modules && npx lerna clean -y`) and bootstrap (`npx lerna bootstrap --hoist --ignore-scripts`).

At first, I felt the same sentiment — adding packages manually into `package.json` seems wrong when being used to `npm i ...` but... a) it's quick to clone a row, request that new `newpackage: ^1.0.0`, b) update-wipe-bootstrap action that I perform often anyway patches things up. Boostrap `--ignore-scripts` part is paramount because otherwise git hooks kick in and 2 minute job becomes 30min with full laptop fan spin.

I don't know, manually adding package.json entries doesn't feel that bad to me now. It did at the beginning...

**Comment by ErisDS** [comment]
The problem is that you don't _have_ to add the line to package.json for lerna to work. Lerna magically figures everything out if you just run `lerna bootstrap`.

It's only when you go to publish that the problem occurs. You publish your first version of an existing package with a new dependency that simply doesn't exist, and lerna does nothing to prevent this happening despite being what allowed this situation to occur.

`lerna add` doesn't work in this situation. You have to publish a version of the new package first, which doesn't work in my use cases.

When you're working in an organisation with a team of people trying to slowly split out a set of huge monorepos into packages, you end up running into this problem every other week. It becomes a training problem - and that's quite literally the opposite of what automation tooling is for!

**Comment by ErisDS** [comment]
Feels like this issue has turned into a massive debate into whether automation tooling should automate things, and I don't really understand why that is.

It would be great if we could build consensus around there being a missing step in the workflow, so that we can talk about how to resolve it. I'm not trying to lump the problem over the fence, but we haven't even got past understanding the problem yet 😞

**Comment by revelt** [comment]
@ErisDS Thank you for being patient with me, I'm just trying to help :o)

Making `lerna add` work with local, unpublished packages has been raised or mentioned in quite few issues, https://github.com/lerna/lerna/issues/2011 for example... That ticket is still open.

Originally this ticket was raised about slightly different case (which to me seems to be answered); we might be writing here on a wrong ticket...

The `lerna add` using on local, unpublished-yet packages is a valid feature request but let's discuss it on https://github.com/lerna/lerna/issues/2011

**Comment by ErisDS** [comment]
I wrote here because the issue talks about workflow problems, which I wanted to get a better understanding of, rather than suggesting or jump on a ticket with a proposed solution in a project I don't fully understand yet. 

If changing `lerna add` is the accepted/preferred solution, then cool - I'll jump over there :)

**Comment by revelt** [comment]
If anybody feels this ticket should not be closed please post your challenges, we'll address them and close this ticket. 

Otherwise, let's close this ticket now and reduce the ticket queue.
