### ISSUE TITLE
lerna updated returns wrong packages

### ISSUE THREAD

**Issue by sebelga** [lerna/lerna#886]
## Expected Behavior
When running `lerna updated` only return 1 package that has been updated.
After I publish all my packages I make 1 change to a file and commit it. I then run `git describe --abbrev=0` that shows the correct latest tag (1 commit behind current head). I then run `lerna updated` and it should only list 1 package.

## Current Behavior
Return all the packages

## Steps to Reproduce (for bugs)

1. run `lerna publish` (publishes all packages (6))
2. modify a file in 1 package and commit
3. run `lerna updated`

<details><summary>lerna.json</summary><p>

```json
{
  "lerna": "2.0.0-rc.5",
  "packages": [
    "applications/opsys/src/main/*",
    "modules/*",
    "features/*"
  ],
  "version": "independent",
  "npmClient": "yarn"
}
```
</p></details>

## Context
I would need to be able to only tag the branch, bump version and publish packages that have been modified.

## Your Environment

| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0-rc.5 |
| `npm --version`  | 4.2.0 |
| `yarn --version` | 0.22.0 |
| `node --version` | 7.10.0 |

| OS | Version |
| --- | --- |
| Windows | 7 |

**Comment by angryobject** [comment]
Same here on macOS.

**Comment by StarpTech** [comment]
Same behaviour
![image](https://user-images.githubusercontent.com/1764424/27515115-bd5b7ba0-599c-11e7-8214-bc4326153895.png)

**Comment by patrickmarabeas** [comment]
`lerna updated` looks to return the packages with _changes_ AND _dependants/transitive dependants_, e.g:

Component list:
-button
-button-group (dependency on button)
-button-group-wrapper (dependency on button-group)
-input

Test cases:

A change in `button`, `lerna updated` returns:
-button
-button-group
-button-group-wrapper

A change in `button-group`, `lerna updated` returns:
-button-group
-button-group-wrapper

A change in `button-group-wrapper`, `lerna updated` returns:
-button-group-wrapper

A change in `input`, `lerna updated` returns:
-input

Seems like an odd thing to accident, so I'm going to assume it's intended. Great for bootstrapping or testing only the packages which might be affected, and is one way to enforce some sort of determinism on publish I guess if semver is shakey...

If you wish to only publish the packages which have in fact changed, I'm currently going down the path of:

Return the last commit SHA with message of "Publish".
> git log :/Publish --pretty=format:"%H" -1
> 51371bdd7bc6d9bfd52ed50557ecf18647e61bf9

Return the altered files since the last publish
> git diff --name-only 51371bdd7bc6d9bfd52ed50557ecf18647e61bf9
> /package/pkg1/index.js /packages/pkg1/src/thing.js /pckage/pkg2/src/util.js

Throw some regex at the array of files to determine packages
> pkg1 pkg1 pkg2

filter out duplicates
> pkg1 pkg2

Undocumented, but the scope flag works with publish
> lerna publish --scope={pkg1,pkg2}

I'll post the bash script I end up using if this is related to issues above.

**Comment by sebelga** [comment]
@patrickmarabeas great, thanks for the insight! ´Looking forward for you bash script, it seems like a good solution!

**Comment by angryobject** [comment]
Oh, i didn't realize it watches for dependencies either. Makes sense now. Thanks!

+1 for the script

**Comment by markbjerke** [comment]
But if the dependents SemVer range for the dependency that updated is not valid anymore you would need the existing behavior ? It seems like Lerna updates the dependents SemVer with the dependency ^version ? 

Every now and then you want the current behavior.  Also I guess you could manually filter just by inspection using the scope flag ? So if I didn't have your script I could just manually exclude dependents of the package I changed.

**Comment by patrickmarabeas** [comment]
Quick'n'dirty: https://gist.github.com/patrickmarabeas/68cb15303c2f427a3270136673253a07

- Assumes Yarn usage; alter `BIN_PATH` if not
- Assumes package names (bar scope) is the same as containing folder
- Assumes using default "Publish" commit message
- Assumes package location - update `packageRootMatch` and `packageNameCapture`
- Commented out scope prepending, re-add and set if required

as @markbjerke has said, you will run into semver issues if a major release is published which doesn't require an update to some other package - i.e. breaking change which only effects some optional API. This will cause issues for packages which are currently symlinked but no longer should have a dependency connection.

Seems like the easiest solution is to only work on ONE package at a time and then publish it - either via my script (rely on semver and tests to tell you what transitive packages need updating) OR with the default publish script if it's a major version increase.

- Restrict a feature branch to a single dependency tree
- Only publish on master / where all feature branches merge
- Publish after every single merge

**Comment by patrickmarabeas** [comment]
Fixed issue publishing single packages.

I've got a bunch of helper functions I'll look to make configurable and publish at some point.

**Comment by patrickmarabeas** [comment]
Look to have solved major version increases by doing publishing in two steps:
* publish all changed packages (using --scope)
* review the tags created to determine if a major version was published
* find all direct dependants of those packages and bump their dependencies to match those published
* publish these packages (using --scope and --cd-version=patch)

I'll hopefully package this up for general use shortly.

**Comment by evocateur** [comment]
We've been down this road [before](https://github.com/lerna/lerna/pull/707), and our stance hasn't changed. Versions are cheap, developer time is not, and we will always bump transitive dependents when their dependencies change.
