### ISSUE TITLE
[question] what are the best practices to manage internal dependencies?

### ISSUE THREAD

**Issue by zhenyulin** [lerna/lerna#949]
I'm relatively new to lerna, and just used it to set up the development of a UI library(https://github.com/finbourne/finchart). I'm still in the process of migrating the original `src` to `packages`.

A few packages are depending on each other, and during the process it seems to be a bit tricky to get the instant update without running `lerna publish`. Was wondering if there's a best practice to manage internal dependencies throughout the development process?

**Comment by evocateur** [comment]
If you mean shared `devDependencies` that you never intend to publish to a registry, just add `"private": true` to their package.json files and otherwise treat them like any other sibling dependency (a subdirectory of `packages/`, by default). They'll be versioned and everything, they just won't ever be published.
