### ISSUE TITLE
Lerna bootstrap installing ignored files

### ISSUE THREAD

**Issue by PaulBrunache** [lerna/lerna#971]
Lerna bootstrap is linking my packages with all files i asked it to ignore
## Expected Behavior

I assumed that with the ignore it would ignore the files matching the array, this is the output

lerna info version 2.0.0
lerna info ignore [ 'src', '.*', 'node_modules' ]
lerna info Bootstrapping 3 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna success Bootstrapped 3 packages

I expect my node_module after bootstrap to look like this

package-name
--lib 
--package.json

## Current Behavior
Am I not understanding how the ignore works ? Isn't it suppose to ignore the flag the src.. etc.. while linking with bootstrap ? 
My shared package is being added like so:

package-name
--node_module (with all the dependencies from the linked package)
--lib 
--src
--.npmingore
--.babelrc
--package-lock.json
--package.json

shouldn't it ignore these files or do i have to delete them manually ? 

## Steps to Reproduce (for bugs)

1. Run lerna Bootstrap
2. Go to node_modules in package you're linking too
3. Open package and all files will be in there

```json
{
  "lerna": "2.0.0",
  "packages": [
    "packages/*"
  ],
  "commands": {
      "bootstrap": {
        "ignore": ["src", ".*","node_modules"]
      },
    "version": "independent",
    "npmClient": "yarn"
  }
}
```
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.0.0 |
| `yarn --version` | 0.27.5 |
| `node --version` | v8.3.0 |

| OS | Version |
| --- | --- |
|  macOS Sierra | 10.12.3 |

**Comment by evocateur** [comment]
The `commands.bootstrap.ignore` section is a list of package name globs equivalent to the `--ignore` CLI option. It's not a file-based glob that does any filtering on what is installed.

Without seeing the package.json of the packages having this problem, I can't say for sure, but I would guess that it's not symlinking to the sibling package because of a version mismatch between the dependent's `pkg.dependencies[parent]` value and the parent dependency's `pkg.version`.
