### ISSUE TITLE
lerna publish --canary --cd-version major '--force-publish=*' publishes with "latest" tag

### ISSUE THREAD

**Issue by KyleAMathews** [lerna/lerna#987]
I was trying to publish canary versions for all Gatsby packages so used `lerna publish --canary --cd-version major '--force-publish=*'` to try to do that.

## Expected Behavior
All packages would be canary published to the next major version

## Current Behavior
Every package got published to the next major version with the "latest" tag.

**Comment by evocateur** [comment]
Yikes. Any reason you included `--force-publish=*`? `--canary` should be sufficient, and publish to a dist-tag of `canary` (customizable via `--npm-tag <name>`.

**Comment by evocateur** [comment]
(also, version of lerna/npm/node?)

**Comment by KyleAMathews** [comment]
>Any reason you included --force-publish=*

Yeah I tried that and it wasn't publishing all packages.

Lerna 2.1.0
NPM 4.6.1
Node 8.1.2

**Comment by evocateur** [comment]
Your current setup is losing a lot of the advantages of `lerna bootstrap --hoist` with version mismatches and a `postinstall` that includes `lerna bootstrap` in the root, which notably in the `--hoist` case can get called recursively because `--hoist` calls `npm install` in the root first.

`npx lerna bootstrap --loglevel=silly` can provide insight here, but it's ridiculously noisy.

Also, not sure if I should use yarn or npm5 because both lockfiles are in the `.gitignore`, yet `yarn.lock` is still versioned? One or the other should be versioned in the root, and ignored in all leaf nodes (`packages/*/package-lock.json`, since your npmClient is explicitly `npm`).

I think `--canary` is supposed to be partial? Anything that hasn't changed should be fine to stay on the previous version specifier, and only those that do need to have the `-alpha.<sha>` prerelease. Perhaps `--cd-version premajor` is more appropriate in the context of `--canary`? It's very complicated by the fact you're using `independent` versioning, which I really don't recommend for most cases.
