### ISSUE TITLE
Only the package.json file is updated on Github

### ISSUE THREAD

**Issue by ghost** [lerna/lerna#991]
When I run "lerna publish" only the file "package.json" is updated on Github. Do I have to upload all other files manually? Is there a way to upload all the files in the package automatically?

```json
{
  "lerna": "2.0.0",
  "version": "0.1.0",
  "packages": [
    "packages/*"
  ]
}
```

**Comment by evocateur** [comment]
`lerna publish` just runs `npm publish` in each package that has updated since your last `lerna publish` (identified by an annotated git tag). You can run `npm pack` in a package directory to see what npm bundles into the tarball.

The `files` key of [package.json](https://docs.npmjs.com/files/package.json#files) controls what is included in the published package.
